### ISSUE TITLE
vue.js2.0

### ISSUE THREAD

**Issue by 847721464** [ustbhuangyi/better-scroll#10]
Hello, is your better-scroll is not supported by vue.js2.0? I file a report on the wrong, can not find name

**Comment by ustbhuangyi** [comment]
of course support vue.js 2.0，make sure you get the real dom and pass it to the better-scroll constructor

**Comment by 847721464** [comment]
![9454c 5hhz vaw8yacq5u9f](https://cloud.githubusercontent.com/assets/20931278/21798391/16ce5e08-d74f-11e6-8e6d-30b7d49ca236.png)
当从另一个页面进入这个页面的时候，下面能超出底线，如果是在这个页面刷新就不会有这种效果？这是什么原因
