### ISSUE TITLE
这么好的滚动插件，希望可以支持鼠标的滑轮滚动

### ISSUE THREAD

**Issue by eric-ocz** [ustbhuangyi/better-scroll#100]
这样就可以开发非移动端应用了

**Comment by xing00** [comment]
有这个需求+1，或者能不能提供一下思路，自行扩展需要的功能，谢谢

**Comment by mqhe2007** [comment]
最近也有这个需求了，不知道老大有没有计划，可否预告一下。 @ustbhuangyi

**Comment by Lanseria** [comment]
希望有这个功能

**Comment by mikelrmb** [comment]
＋1

**Comment by JasonDung** [comment]
+1

**Comment by a5108** [comment]
+1

**Comment by weixinfei123** [comment]
+1

**Comment by fantasy525** [comment]
+1啊，我看文档说可以自动识别PC环境，但是鼠标滑轮滚动还是没有效果啊，原来根本没支持啊，希望支持一下

**Comment by ustbhuangyi** [comment]
@eric-ocz @xing00 @mqhe2007 @Lanseria @mikelrmb @JasonDung @a5108 @weixinfei123 @fantasy525 
1.8.0 版本已经支持此功能，欢迎试用，有问题随时反馈喔~
