### ISSUE TITLE
Android设备上 better-scroll的slide 组件内嵌video,导致video点击时，播放控件controls不显示，求解，betterscroll 的disableTouch设置true时，video点击，video的播放控件可以显示，但是banner不能跟随手指滚动了。

### ISSUE THREAD

**Issue by LiLustre** [ustbhuangyi/better-scroll#1000]
better-scroll的slide 组件内嵌video 是不是没有兼容video？怎么样让video点击时播放控件显示，

**Comment by dolymood** [comment]
https://better-scroll.github.io/docs/zh-CN/guide/base-scroll-options.html#preventdefaultexception
这里加入 video 试试
