### ISSUE TITLE
slide 内video全屏播放问题

### ISSUE THREAD

**Issue by LiLustre** [ustbhuangyi/better-scroll#1003]
Android webview 内 使用 slide 内的video的全屏播放按钮获取推出出全屏 ， Scroll会主动回调beforeScrollStart、slideWillChange、scrollEnd 然后 refresh 事件，导致video退出啊全屏后当前页不是播放video页，请问怎么解决？代码内并没有主动调用以上事件，已经设置了 preventDefaultException: {tagName: /^(INPUT|TEXTAREA|BUTTON|SELECT|AUDIO|VIDEO)$/},和preventDefault: false

**Comment by dolymood** [comment]
可以试试 observeDOM 为 false 试试

**Comment by LiLustre** [comment]
> 可以试试 observeDOM 为 false 试试

试了下，没有用 
伪代码如下：
import ObserveDom from '@better-scroll/observe-dom'
import BScroll from '@better-scroll/core'
import Slide from '@better-scroll/slide'
BScroll.use(ObserveDom)
BScroll.use(Slide);



this.slide = new BScroll((this.$refs.slide as any), {
            scrollX: true,
            scrollY: false,
            slide: {
                loop: this.isLoop,
                threshold: this.selThreshold,

            },
            observeDom:false,
            click: true,
            useTransition: true,
            momentum: false,
            bounce: !this.isLoop,
            stopPropagation: true,
            preventDefault: false,
            preventDefaultException: {tagName: /^(INPUT|TEXTAREA|BUTTON|SELECT|AUDIO|VIDEO)$/},
            probeType: 2
        });

**Comment by LiLustre** [comment]
在线求解，急

**Comment by dolymood** [comment]
来个简易复现demo吧

**Comment by LiLustre** [comment]
> 来个简易复现demo吧

deom已上传到 github 上 
https://github.com/LiLustre/slide-video-demo.git   
需要在Android 的WebView 上打开网页才会出现上述问题

**Comment by cuijing1031** [comment]
> > 来个简易复现demo吧
> 
> deom已上传到 github 上
> https://github.com/LiLustre/slide-video-demo.git
> 需要在Android 的WebView 上打开运行的网页才会出现上述问题

如果你的页面本身不考虑横屏/竖屏切换的话，可以加上
this.slide.scroller.hooks.off('resize')
临时禁用resize的监听

**Comment by LiLustre** [comment]
> > > 来个简易复现demo吧
> > 
> > 
> > deom已上传到 github 上
> > https://github.com/LiLustre/slide-video-demo.git
> > 需要在Android 的WebView 上打开运行的网页才会出现上述问题
> 
> 如果你的页面本身不考虑横屏/竖屏切换的话，可以加上
> this.slide.scroller.hooks.off('resize')
> 临时禁用resize的监听

目前禁用是好使的，但是考虑到横竖屏的问题，还不是最好的处理办法，还有其他办法么

**Comment by dolymood** [comment]
非hack的方式 正在修复中

**Comment by LiLustre** [comment]
> 非hack的方式 正在修复中

大概何时修复？项目要上线了，==

**Comment by cuijing1031** [comment]
> > > > 来个简易复现demo吧
> > > 
> > > 
> > > deom已上传到 github 上
> > > https://github.com/LiLustre/slide-video-demo.git
> > > 需要在Android 的WebView 上打开运行的网页才会出现上述问题
> > 
> > 
> > 如果你的页面本身不考虑横屏/竖屏切换的话，可以加上
> > this.slide.scroller.hooks.off('resize')
> > 临时禁用resize的监听
> 
> 目前禁用是好使的，但是考虑到横竖屏的问题，还不是最好的处理办法，还有其他办法么

请升级到 beta8 试试。
针对安卓需要在options中设置：resizePolling: 500  的延迟，保证resize的时候，对于slide的大小获取是正确的
