### ISSUE TITLE
vue项目下用betterScroll，如果通过v-show隐藏，后面显示无法滑动，需要点击一下才能滑动

### ISSUE THREAD

**Issue by keyuliang** [ustbhuangyi/better-scroll#1004]
### Version
1.15.0

### Reproduction link
[https://github.com/keyuliang/betterS.git](https://github.com/keyuliang/betterS.git)

### Steps to reproduce
点击切换按钮后蓝色背景的div无法滑动，需要点击才能滑动

### What is expected?
切换后可以滑动

### What is actually happening?
切换后不可以滑动

**Comment by liuwu1211** [comment]
我也遇到相同的问题

**Comment by liuwu1211** [comment]
但是并未解决

**Comment by keyuliang** [comment]
> 我也遇到相同的问题
在refresh()外面套一层setTimeout就行了，不知道为什么

**Comment by liuwu1211** [comment]
> > 我也
> > 遇到相同的问题在refresh（）外面套一层setTimeout就行了，不知道为什么

>> 可以了  非常感谢

**Comment by justforuse** [comment]
我遇到的场景是，隐藏时做初始化，导致对象属性有误，点击一下刷新属性后才能滚动。
所以要显示时才做初始化
