### ISSUE TITLE
html 引入 better scroll 做题 iPhone 做到三四十题的时候 页面就崩溃

### ISSUE THREAD

**Issue by michaelsky123** [ustbhuangyi/better-scroll#1005]
参考链接
http://mobile.chinaerei.com/kaoshizhongmtest.html?timestamp=1589705429309&subjectid=1&examid=268&timunum=0&juanzi=1

**Comment by michaelsky123** [comment]
麻烦大神看下 指导下 安卓没问题 iPhone 就会崩溃 重新加载

**Comment by dolymood** [comment]
这种大数据量的 需要做优化的，不能有多少数据就渲染多少 那肯定会有问题
例如 分为 左中右 三个 通过动态更新达到目的
