### ISSUE TITLE
[New Feature] 提供实例级别的插件注册

### ISSUE THREAD

**Issue by fjc0k** [ustbhuangyi/better-scroll#1006]
### What problem does this feature solve?
看了 v2 的文档，现在仅提供了全局级别的插件注册，对于具体业务开发而言，这没有任何问题。

但对于公共组件库的开发而言，全局并不是一件好事，比如我在多个组件里依赖了 mouse-wheel 插件：

- 如果我在全局 use 该插件，那么整个组件库就产生了副作用，也就无法利用 webpack 或者 rollup 提供的摇树优化剔除没有使用到的代码；
- 如果我在组件内 use 该插件，那么当多个组件同时被使用，use 该插件的代码也就会被调用多次，我暂无法确定这是否会导致错误。

因此，我觉得应该提供一种在实例级别注册插件的能力，api 可以和全局的保持一致，也叫 use，比如：

```js
  import BScroll from '@better-scroll/core'
  import MouseWheel from '@better-scroll/mouse-wheel'

  new BScroll('.bs-wrap', {
    //...
    use: [MouseWheel],
    mouseWheel: {
      speed: 20,
      invert: false,
      easeTime: 300
    }
  })
```

如果要求 TypeScript 友好，插件配置可以提到插件注册时进行：

```js
  import BScroll from '@better-scroll/core'
  import MouseWheel from '@better-scroll/mouse-wheel'

  new BScroll('.bs-wrap', {
    //...
    use: [MouseWheel.register({
      speed: 20,
      invert: false,
      easeTime: 300
    })],
  })
```

综上所述，实例级别的插件注册更有利于产生清晰的代码逻辑，对摇树优化的支持也是极好的。

### What does the proposed API look like?
如上。

**Comment by dolymood** [comment]
组件内调用use没什么问题，重复use 不会有新的问题
