### ISSUE TITLE
关于写聊天功能时，使用better-scroll实现下拉加载更多聊天历史记录，就是分页加载完数据后，如果不手动滚动，会一直停在最上面，如果使用scrollTo滚动到原来的位置，下次下拉加载时就会出现下面种情况！！！scroll 事件有时候返回的pos为NAN

### ISSUE THREAD

**Issue by programmer1000** [ustbhuangyi/better-scroll#101]
![4 ouj2 03p 8 d4 nv f3](https://user-images.githubusercontent.com/22095849/28653618-1a8c8c96-72c1-11e7-8a3b-1f253c1e9c0e.png)

**Comment by ustbhuangyi** [comment]
请看一下最新提 issue 的规范
