### ISSUE TITLE
pull-down 与 observe-dom 冲突

### ISSUE THREAD

**Issue by hanai** [ustbhuangyi/better-scroll#1010]
### Version
2.0.0-beta.8

### Reproduction link
[https://codesandbox.io/s/small-field-y51fj](https://codesandbox.io/s/small-field-y51fj)

### Steps to reproduce
断点发现 `mutation.target` 和 `this.scroll.scroller.content` 值总是不同的 https://github.com/ustbhuangyi/better-scroll/blob/dev/packages/observe-dom/src/index.ts#L63

### What is expected?
等待 5 秒后执行 finishPullDown，位置恢复。

### What is actually happening?
在 observe-dom 中触发了 refresh 

---
关联的 issue https://github.com/ustbhuangyi/better-scroll/issues/966

### Reproduction link
[https://codesandbox.io/s/small-field-y51fj](https://codesandbox.io/s/small-field-y51fj)

### Steps to reproduce
断点发现 `mutation.target` 和 `this.scroll.scroller.content` 值总是不同的 https://github.com/ustbhuangyi/better-scroll/blob/dev/packages/observe-dom/src/index.ts#L63

### What is expected?
等待 5 秒后执行 finishPullDown，位置恢复。

### What is actually happening?
在 observe-dom 中触发了 refresh 

---
关联的 issue https://github.com/ustbhuangyi/better-scroll/issues/966

**Comment by johanazhu** [comment]
同样遇到

**Comment by theniceangel** [comment]
> 同样遇到

将在下一个版本修复，应该是今明两天的样子

**Comment by theniceangel** [comment]
@hanai @johanazhu v2.0.0-beta.10 版本修复了
