### ISSUE TITLE
better-scroll配合vant-ui使用的时候，van-tabs无法横向手势滚动

### ISSUE THREAD

**Issue by wuhuisiyue** [ustbhuangyi/better-scroll#1011]
### Version
1.15.0

### Reproduction link
[https://codesandbox.io/s/withered-hill-fsjyx?file=/src/App.vue](https://codesandbox.io/s/withered-hill-fsjyx?file=/src/App.vue)

### Steps to reproduce
van-tabs在子项多余4个时可以手势左右滑动，但是better-scroll禁用了该事件，如果配置preventDefault: false，van-tabs可以左右滑动，但是内容向下滚动后，无法直接向上滚动到顶部，必须向下滚动后再向上滚动。配置preventDefaultException: {className: /(^|\s)van-tabs(\s|$)/},tagException: className:/(^|\s)van-tabs(\s|$)/ }，也是无效。

### What is expected?
van-tabs可以左右手势滚动

### What is actually happening?
van-tabs无法左右手势滚动

---
移动端演示地址：http://m.wkmblog.com/#/

**Comment by theniceangel** [comment]
根据 demo 地址，没复现

**Comment by fengzhongwen** [comment]
> ### Version
> 1.15.0
> 
> ### Reproduction link
> https://codesandbox.io/s/withered-hill-fsjyx?file=/src/App.vue
> 
> ### Steps to reproduce
> van-tabs在子项多余4个时可以手势左右滑动，但是better-scroll禁用了该事件，如果配置preventDefault: false，van-tabs可以左右滑动，但是内容向下滚动后，无法直接向上滚动到顶部，必须向下滚动后再向上滚动。配置preventDefaultException: {className: /(^|\s)van-tabs(\s|$)/},tagException: className:/(^|\s)van-tabs(\s|$)/ }，也是无效。
> 
> ### What is expected?
> van-tabs可以左右手势滚动
> 
> ### What is actually happening?
> van-tabs无法左右手势滚动
> 
> 移动端演示地址：http://m.wkmblog.com/#/

我也遇到这个问题啦，请问你是怎么解决的，方便讲一下吗
