### ISSUE TITLE
ios下快速滚动至底部会有明显的卡顿，滚动至底部卡一下然后自动滚动到底部。

### ISSUE THREAD

**Issue by xuan-zi** [ustbhuangyi/better-scroll#1012]
### Version
1.15.0

### Reproduction link
[http://119.23.255.181/#/index](http://119.23.255.181/#/index)

### Steps to reproduce
打开http://119.23.255.181/#/index，在首页快速滚动至底部。

### What is expected?
滚动至底部不要出现卡顿

### What is actually happening?
卡顿，2次滚动

**Comment by Fullsize** [comment]
> ### Version
> 1.15.0
> 
> ### Reproduction link
> http://119.23.255.181/#/index
> 
> ### Steps to reproduce
> 打开[http://119.23.255.181/#/index，在首页快速滚动至底部。](http://119.23.255.181/#/index%EF%BC%8C%E5%9C%A8%E9%A6%96%E9%A1%B5%E5%BF%AB%E9%80%9F%E6%BB%9A%E5%8A%A8%E8%87%B3%E5%BA%95%E9%83%A8%E3%80%82)
> 
> ### What is expected?
> 滚动至底部不要出现卡顿
> 
> ### What is actually happening?
> 卡顿，2次滚动

同样的问题

**Comment by dolymood** [comment]
As https://github.com/ustbhuangyi/better-scroll/issues/978
