### ISSUE TITLE
当在滑动时容器高度一直在变，导致最后一个品类无法置顶问题请教

### ISSUE THREAD

**Issue by margin-0** [ustbhuangyi/better-scroll#102]
#### 我用的是react 开发， 需求是滑动联动
<img src='https://user-images.githubusercontent.com/23308724/28661169-606ae614-72e8-11e7-9d55-9f8c01adf522.PNG' width='240'>

#### 当滑动的时候上面的banner 也一起向上，第一列到顶之后则不在动，我是在scroll中改变了容器的高度，结果最后一个就滑不到顶了

<img src='https://user-images.githubusercontent.com/23308724/28661199-7e6fe24a-72e8-11e7-91a1-c71320807b85.PNG' width='240'>
<img src='https://user-images.githubusercontent.com/23308724/28661187-74828b52-72e8-11e7-9fa4-a47e2c825c99.PNG' width='240'>

```js
// banner 距离判断
this.mainListScroll.on('scroll', pos => {
      if (!pos.y) {
        return
      }
      if (this.isScroll) {
        this.mypos = pos.y
        this.ListeningScroll(this.mypos)
      }
      if (pos.y <= 0) {
        this.scrollY = Math.abs(Math.round(pos.y))
      }
      const index = this.currentIndex()
      if (this.state.tagsIndex !== index) {
        this.setState({
          tagsIndex: index,
        })
      }
    })
  ListeningScroll(newVal) {
    const translateY = Math.max(this.minTranslateY, newVal)
    const height = Math.abs(translateY)
    this.mainWrap.style.transform = `translate3d(0,${ translateY }px, 0)` // 这个是banner加上列表的父元素
    this.indexMainWrap.style.height = `${ this.mainHeight + height }`// 这里是左右两个列表的父元素
  }
```

**Comment by ustbhuangyi** [comment]
参考一下这个的实现吧：https://github.com/ustbhuangyi/vue-sell
