### ISSUE TITLE
[New Feature] Additional handler, make ActionsHandler/ScrollerActions public

### ISSUE THREAD

**Issue by marcj** [ustbhuangyi/better-scroll#1022]
### What problem does this feature solve?
Hi there,

I'm using this library to make a scroll effect where an different element (aka handler) can control the scroll area.

Let's assume you have have a scrollarea. And on top (before) this scrollarea you have an top-area which slightly increases/decrease in size depending on your scroll position. You want now that this top-area when scrolled should proxy its event to the actual scroll area.

See this GIF as example where I implemented this functionality already, but very hacky.

![2020-06-16 03 00 52](https://user-images.githubusercontent.com/450980/84720425-4e24dc00-af7e-11ea-80f2-a4d88d47670b.gif)

Currently I work around this by using this code:

```typescript
const bs = new BScroll(this.scrollAnimation, {
  scrollbar: true,
  scrollY: true,
  wheel: true,
  probeType: 3 //3=Probe.realtime
});

if (this.scrollAnimationAdditionalHandler) {
  //note: this seems hacky, but is exactly what we want. We proxy events from an additional
  // HTMLElement to our scroll area.

  //we extract 2 classes that are actually private
  const ActionsHandler = bs.scroller.actionsHandler.constructor as Type<ActionsHandler>;
  const ScrollerActions = bs.scroller.actions.constructor as Type<ScrollerActions>;

  //we create an additional event listener (actionsHandler)
  const additionalActionsHandler = new ActionsHandler(this.scrollAnimationAdditionalHandler, bs.scroller.actionsHandler.options);
  //and assign it to the already existing animater of the scrollAnimation pane.
  // this essentially proxies all events from an additional handler to our actual scroll area.
  const actions = new ScrollerActions(
    bs.scroller.actions.scrollBehaviorX,
    bs.scroller.actions.scrollBehaviorY,
    additionalActionsHandler,
    bs.scroller.actions.animater,
    bs.scroller.actions.options,
  );
  //make sure already registered hooks are used as well
  actions.hooks = bs.scroller.actions.hooks;
}
```

This works, but is hacky as the classes ActionsHandler and ScrollerActions are not public. If they were I could easily implement it that way. Easier would be of course to support a new config option.

### What does the proposed API look like?
The new config option could look like this:

```typescript
const bs = new BScroll(this.scrollArea, {
    scrollbar: true,
    scrollY: true,
    wheel: true,
    additionalHandlers: [this.header] //all mouse/touch events from topArea will be proxies to `bs`.
});
```

**Comment by marcj** [comment]
I've found a lot less hacky solution:

```

          const bs2 = new BScroll(this.scrollAnimationAdditionalHandler, {
            // bindToWrapper: true,
            eventPassthrough: 'horizontal',
            scrollY: true,
            wheel: true,
            probeType: 3 //3=Probe.realtime
          });
          //just act as a proxy for our main BScroll
          bs2.scroller.actions.scrollBehaviorX = bs.scroller.actions.scrollBehaviorX;
          bs2.scroller.actions.scrollBehaviorY = bs.scroller.actions.scrollBehaviorY;
          bs2.scroller.actions.animater = bs.scroller.actions.animater;
          bs2.scroller.actions.hooks = bs.scroller.actions.hooks;
```

However, when the main `bs` was not yet triggered using touch events then `bs2` won't have any momentum. Only when I first used `bs` is `bs` having the full functionality.

**Comment by theniceangel** [comment]
Can you give me a repo of your GIF example？

**Comment by marcj** [comment]
Sure, I added it here: https://github.com/marcj/better-scroll-1022

**Comment by theniceangel** [comment]
@marcj Hi bro, the idea of your scroll animation is so cool, are you interested in making a PR for this, you can do this in Core Scroll by adding options or via a Plugin. 

Maybe like this:

```js
const bs = new BScroll(this.scrollArea, {
    controlledBy: [headerElement] //all mouse/touch events from topArea
    // or
    drivenBy: [headerElement]
});
```

**Comment by marcj** [comment]
I could try. Any hint where in the class structure this is best implemented? It seems to me I just have to connect additional scrollBehavior to actions/animater. But not familiar with the internals that much.

**Comment by theniceangel** [comment]
> I could try. Any hint where in the class structure this is best implemented? It seems to me I just have to connect additional scrollBehavior to actions/animater. But not familiar with the internals that much.

`Scroller.ts` and `ActionsHandler.ts`. The key point is that use another element's touch behavior to drive real `content` elment to scroll

**Comment by marcj** [comment]
I'm sorry, I'm no longer part of the team that needs this, so I'm no longer interested in developing it.
