### ISSUE TITLE
[New Feature] infinity 插件无法渲染组件或模版

### ISSUE THREAD

**Issue by Wulawa** [ustbhuangyi/better-scroll#1023]
### What problem does this feature solve?
目前是无法渲染组件或模版的，只能通过render函数返回HTMLElement

### What does the proposed API look like?
能不能在fetch中返回startindex\endindex,用来控制当前渲染数据，render中返回数据，让开发者自行渲染

**Comment by theniceangel** [comment]
可以参考 cube-ui 的 recycle-list 组件
