### ISSUE TITLE
Element still can scroll by mouse wheel in PC after calling disable() API

### ISSUE THREAD

**Issue by Gwokhov** [ustbhuangyi/better-scroll#1025]
### Version
2.0.0-@beta.10

### Reproduction link
[https://codesandbox.io/s/bscroll-mouse-wheel-issue-7mm45?file=/src/index.js:120-143](https://codesandbox.io/s/bscroll-mouse-wheel-issue-7mm45?file=/src/index.js:120-143)

### Steps to reproduce
1. Use mouse-wheel plugin.
2. Call the `disable()` API.
3. It works when using touch, but it's still scrollable by mouse wheel. 

### What is expected?
Can't scroll by mouse wheel.

### What is actually happening?
Scrollable by mouse wheel.

**Comment by theniceangel** [comment]
Thanks

**Comment by theniceangel** [comment]
fix in v2.0.0
