### ISSUE TITLE
使用wheel制作的picker组件在ios9.3有样式问题

### ISSUE THREAD

**Issue by qubitsky** [ustbhuangyi/better-scroll#1026]
### Version
2.0.0-beta.10

### Reproduction link
[https://ustbhuangyi.github.io/better-scroll/#/examples/picker/zh](https://ustbhuangyi.github.io/better-scroll/#/examples/picker/zh)

### Steps to reproduce
首先感谢你们的这个组件，为我们开发业务提供了方便
实际使用中我们碰到了如下样式兼容性问题
没有时间写demo，只能把问题描述下，抱歉 (。・＿・。)ﾉ

问题：使用@better-scroll/wheel 制作的 DatePicker 组件，含年、月两列，和 https://ustbhuangyi.github.io/better-scroll/#/examples/picker/zh 类似，滚动年份列时出现问题，年份区间设置从1990-2020。
机型：iphone 6s ios9.3
现象：当滚动年份列时，通常在滚动到最底部时（60%-80%几率）触发，最后一个年份的rotateX值不正确，表现为文字样式上下倒置。
![WechatIMG4](https://user-images.githubusercontent.com/12454892/85377350-8e322300-b56b-11ea-848e-c2a140c50a9e.jpeg)

### What is expected?
年份列大幅度滚动到底部时，最后一年份应当居中正常大小显示

### What is actually happening?
年份列大幅度滚动到底部时，最后一年份上下倒转显示，再稍微滑动下后即恢复正常

---
分析：在上面列出的机型上，经调试定位发现，滚动到最后一个年份时，在计算 rotateX 的方法中，对应的wheel-item 被计算出来的 rotateX 值为 -3.xxxxxe-13 deg，但是检查 wheel-item 被设置的style属性的transform值却大约是 rotateX(400deg)。
解决办法：尝试对 https://github.com/ustbhuangyi/better-scroll/blob/dev/packages/wheel/src/index.ts 中如下代码做修改

```ts
  private rotateX(y: number) {
    const { rotate = 25 } = this.options
    for (let i = 0; i < this.items.length; i  ) {
      let deg = rotate * (y / this.itemHeight   i);
      deg = deg.toFixed(3) // 添加的行，保留3位小数
      (this.items[i] as HTMLElement).style[
        style.transform as any
      ] = `rotateX(${deg}deg)`
    }
  }
```
之后便不再出现上述问题。
但是具体原因仍未查明，猜测是上述机型的浏览器在采用 -3.xxxxxe-13 这种过小的数值设置style属性时会有特殊处理？
建议是否可以对deg值做舍入处理，保留5位小数即可？

**Comment by theniceangel** [comment]
@qubitsky Thanks，fix it in next version
