### ISSUE TITLE
滚动的过程中 Touchstart 触发调用 scrollToElement 表现不和预期

### ISSUE THREAD

**Issue by BUPTlhuanyu** [ustbhuangyi/better-scroll#1027]
### Version
1.8.1

### Reproduction link
[https://github.com/BUPTlhuanyu/react-music-lhy/blob/hooks/src/app/components/listview/ListView.tsx](https://github.com/BUPTlhuanyu/react-music-lhy/blob/hooks/src/app/components/listview/ListView.tsx)

### Steps to reproduce
滚动的过程中 Touchstart 触发调用 scrollToElement 会导致后面 _end 事件处理函数中调用一次 _translate 以及 scrollTo。前一次 _translate 会滚动到指定位置，而后一次则直接滑动到边界处。

### What is expected?
滚动的过程中 Touchstart 触发调用 scrollToElement 滚动到指定的 dom 处

### What is actually happening?
滚动的过程中 Touchstart 触发调用 scrollToElement 滚动到了内容的边界处。

---
为了解决上述问题，只能在给 scrollToElement 延迟一定时间，等滑动完毕之后再触发。

<img width="616" alt="WechatIMG3" src="https://user-images.githubusercontent.com/27213108/85829540-676b2b00-b7bd-11ea-9574-623f8886b6ae.png">
![Xnip2020-06-26_15-00-57](https://user-images.githubusercontent.com/27213108/85829929-41925600-b7be-11ea-9f54-a28dc44f711e.jpg)
![Xnip2020-06-26_15-03-35](https://user-images.githubusercontent.com/27213108/85829933-43f4b000-b7be-11ea-83c0-861f571b70d8.jpg)

**Comment by BUPTlhuanyu** [comment]
<img width="616" alt="WechatIMG3" src="https://user-images.githubusercontent.com/27213108/85830063-8a4a0f00-b7be-11ea-86e6-b771db56c4f3.png">
![Xnip2020-06-26_15-00-57](https://user-images.githubusercontent.com/27213108/85830067-8c13d280-b7be-11ea-9002-c5e5d89deef5.jpg)
![Xnip2020-06-26_15-03-35](https://user-images.githubusercontent.com/27213108/85830070-8ddd9600-b7be-11ea-89be-abe7ae17a3e6.jpg)

**Comment by BUPTlhuanyu** [comment]
`    console.log('_end _translate', newX, this.x, newY, this.y)
    this._translate(newX, newY);

    this.endTime = getNow();
    var duration = this.endTime - this.startTime;
    var absDistX = Math.abs(newX - this.startX);
    var absDistY = Math.abs(newY - this.startY);

    // flick
    if (this._events.flick && duration < this.options.flickLimitTime && absDistX < this.options.flickLimitDistance && absDistY < this.options.flickLimitDistance) {
      this.trigger('flick');
      console.log('flick')
      return;
    }

    var time = 0;
    // start momentum animation if needed
    if (this.options.momentum && duration < this.options.momentumLimitTime && (absDistY > this.options.momentumLimitDistance || absDistX > this.options.momentumLimitDistance)) {
      var top = false;
      var bottom = false;
      var left = false;
      var right = false;
      var bounce = this.options.bounce;
      if (bounce !== false) {
        top = bounce.top === undefined ? true : bounce.top;
        bottom = bounce.bottom === undefined ? true : bounce.bottom;
        left = bounce.left === undefined ? true : bounce.left;
        right = bounce.right === undefined ? true : bounce.right;
      }
      var wrapperWidth = this.directionX === DIRECTION_RIGHT && left || this.directionX === DIRECTION_LEFT && right ? this.wrapperWidth : 0;
      var wrapperHeight = this.directionY === DIRECTION_DOWN && top || this.directionY === DIRECTION_UP && bottom ? this.wrapperHeight : 0;
      var momentumX = this.hasHorizontalScroll ? momentum(this.x, this.startX, duration, this.maxScrollX, this.minScrollX, wrapperWidth, this.options, this) : { destination: newX, duration: 0 };
      var momentumY = this.hasVerticalScroll ? momentum(this.y, this.startY, duration, this.maxScrollY, this.minScrollY, wrapperHeight, this.options, this) : { destination: newY, duration: 0 };
      newX = momentumX.destination;
      newY = momentumY.destination;
      time = Math.max(momentumX.duration, momentumY.duration);
      this.isInTransition = true;
    } else {
      if (this.options.wheel) {
        newY = this._findNearestValidWheel(newY).y;
        console.log('_end wheel', newX, this.x, newY, this.y)
        time = this.options.wheel.adjustTime || 400;
      }
    }

    var easing = ease.swipe;
    if (this.options.snap) {
      var snap = this._nearestSnap(newX, newY);
      this.currentPage = snap;
      time = this.options.snapSpeed || Math.max(Math.max(Math.min(Math.abs(newX - snap.x), 1000), Math.min(Math.abs(newY - snap.y), 1000)), 300);
      newX = snap.x;
      newY = snap.y;
      console.log('_end snap', newX, this.x, newY, this.y)
      this.directionX = 0;
      this.directionY = 0;
      easing = this.options.snap.easing || ease.bounce;
    }

    if (newX !== this.x || newY !== this.y) {
      // change easing function when scroller goes out of the boundaries
      if (newX > this.minScrollX || newX < this.maxScrollX || newY > this.minScrollY || newY < this.maxScrollY) {
        easing = ease.swipeBounce;
      }
      console.log('_end scrollTo', newX, this.x, newY, this.y)
      this.scrollTo(newX, newY, time, easing);
      return;
    }`

_end _translate 到 _end scrollTo 中间的 if 都没有执行，但是 this.y 从 -5980 变成了 -8756，导致后一次 scroll
To 执行，页面从 -5980 滑动到 -8756，scrollToElement 本来滑动到的位置就是 -5980。给  scrollToElement 延迟一定时间之后，也就是等上一次滑动结束之后再scrollToElement，则能达到预期，因为这样能使得 _end 事件触发完成之后，再滚动到指定位置。

**Comment by theniceangel** [comment]
什么场景是需要在 touchstart 的时候调用 scrollToElement

**Comment by BUPTlhuanyu** [comment]
@theniceangel 这个场景不是很常见吗？举个例子，移动端中，当你正在滑动列表查看内容的时候，想点击某个 btn 跳转到列表中的某一项。

**Comment by theniceangel** [comment]
> @theniceangel 这个场景不是很常见吗？举个例子，移动端中，当你正在滑动列表查看内容的时候，想点击某个 btn 跳转到列表中的某一项。

可以升级到 2.x 版本

**Comment by BUPTlhuanyu** [comment]
@theniceangel 行，我试试
