### ISSUE TITLE
position: sticky 替代方法

### ISSUE THREAD

**Issue by Dog-Egg** [ustbhuangyi/better-scroll#1030]
有一个需求，必需要在better-scroll内嵌套 sticky 定位的元素，请教一下有什么可行的替代方法吗？

**Comment by theniceangel** [comment]
可以用 absolute 替代，bs 滚动的时候会派发 y 方向滚动距离

**Comment by Dog-Egg** [comment]
> 可以用 absolute 替代，bs 滚动的时候会派发 y 方向滚动距离

谢谢提供思路，我尝试了下，当 sticky 元素上方的元素高度一定时，这个方法是可行的，但是当上方元素动态变化时，sticky元素距离视口top的距离就会动态变化

**Comment by Dog-Egg** [comment]
> > 可以用 absolute 替代，bs 滚动的时候会派发 y 方向滚动距离
> 
> @theniceangel 谢谢提供思路，我尝试了下，当 sticky 元素上方的元素高度一定时，这个方法是可行的，但是当上方元素动态变化时，sticky元素距离视口top的距离就会动态变化

我呆了😳 ，可以通过动态获取上方元素的高度可以判断距离，nice！！
