### ISSUE TITLE
[New Feature] 使用slide插件做轮播图时，移动端浏览器地址栏和底部工具栏会随着滚动而显示隐藏，导致会不断触发refresh事件

### ISSUE THREAD

**Issue by shcping** [ustbhuangyi/better-scroll#1037]
### What problem does this feature solve?
使用slide插件做轮播图时，移动端浏览器地址栏和底部工具栏会随着滚动而显示隐藏，导致会不断触发refresh事件

### What does the proposed API look like?
使用slide插件做轮播图时，移动端浏览器地址栏和底部工具栏会随着滚动而显示隐藏，导致会不断触发refresh事件

**Comment by theniceangel** [comment]
什么浏览器？能提供个gif么

**Comment by shcping** [comment]
> 什么浏览器？能提供个gif么

手机自带浏览器，google都是的，只要浏览器的地址栏或底部工具栏显示或隐藏，就会触发refresh事件，比如我轮播图切到第三张，然后滚动屏幕，底部工具条隐藏了，就会触发refresh事件，轮播图就会跳到初始轮播位置，如果做了懒加载，就会重新加载

**Comment by theniceangel** [comment]
@shcping fixed in v2.0.0
