### ISSUE TITLE
为什么实例话的BScorl渲染不了n+2个子元素

### ISSUE THREAD

**Issue by daydaylee1227** [ustbhuangyi/better-scroll#1038]

**Comment by daydaylee1227** [comment]
我最近在使用vue导入better-scroll中，遇到一个问题，我导入的是最新的包，但是出现了问题，就是不能无限滚动的效果。
我通过审查元素的方式，发现我传入5个数据，理论上应该会帮我生成7个子元素的，实际上还是5个数据。
但是可以通过手势的方式去滑动它，我把网上的方案都看了，我能够滑动，但是就是实现不了，轮播的效果，有大哥帮忙看看什么问题吗？

**Comment by theniceangel** [comment]
贴代码
