### ISSUE TITLE
[New Feature] v2版本的picker不支持某个属性的disabled了吗

### ISSUE THREAD

**Issue by freyach** [ustbhuangyi/better-scroll#1039]
### What problem does this feature solve?
v2 api中的高级选项selectedIndex设置为-1也没办法disabled picker中的某一个，希望有更详细的api

### What does the proposed API look like?
有详细的steps

**Comment by theniceangel** [comment]
> ### What problem does this feature solve?
> v2 api中的高级选项selectedIndex设置为-1也没办法disabled picker中的某一个，希望有更详细的api
> 
> ### What does the proposed API look like?
> 有详细的steps

只要某一个 item 的 className 含有 `wheel-disabled-item`，那么内部就会处理成 disabled。[可以参考这个demo](https://github.com/ustbhuangyi/better-scroll/blob/dev/packages/examples/vue/components/picker/one-column.vue)
