### ISSUE TITLE
better-scroll下的点击事件，在pc端触发两次，在chrome模拟移动端的情况下触发一次，input框无法获取焦点，且input框添加点击事件，input框上的点击事件无效

### ISSUE THREAD

**Issue by programmer1000** [ustbhuangyi/better-scroll#104]
在pc情况下，会触发两次，
![image](https://user-images.githubusercontent.com/22095849/28711224-72b7c00e-73b9-11e7-8fa2-1ea9d0bbba80.png)
在chrome模拟移动端的情况下，只触发一次。

input框，在pc条件下可以获取焦点，
在chrome模拟移动端的情况下，无法获取焦点

**Comment by Foreverofh** [comment]
@programmer1000  问题解决了没有！

**Comment by vincent-cong** [comment]
@programmer1000   有个判断PC端的  点击事件里面 event._constructed  判断下   if( !event._constructed ){ return }

**Comment by doublemin** [comment]
请问你解决了吗？我是无论什么模式下都触发两次。

**Comment by ustbhuangyi** [comment]
最新版本已经修复该问题
