### ISSUE TITLE
v1.x版本  能不能再出一个版本  解决   ios13.4+  二次回弹的 问题？

### ISSUE THREAD

**Issue by mircle** [ustbhuangyi/better-scroll#1044]
v1.x版本  能不能再出一个版本  解决   ios13.4+  大力滑动  二次回弹的 问题？
v2.x版本  解决了ios13.4+大力滑动   二次回弹的问题  但是  先前的下拉刷新  上拉加载 滑动的 功能 都出了问题 （我是 全量加载的   better-scroll 组件 ）

**Comment by theniceangel** [comment]
v2的下拉刷新、上拉加载、滑动都有了问题？具体的表现是？

**Comment by mircle** [comment]
嗯    原来 在 v1.x  下  都没有问题的功能  
换成 v2.x 之后    滑动的功能  就  无法滑动了       页面上的   按钮 点击事件 等 都无法 操作了

**Comment by mircle** [comment]
我使用组件的方式是：      全量引入

**Comment by theniceangel** [comment]
> 我使用组件的方式是： 全量引入

看下 node_modules 下面的版本号

**Comment by mircle** [comment]
![image](https://user-images.githubusercontent.com/5029239/89991180-0688ab00-dcb6-11ea-9f09-fcb363252cc8.png)
![image](https://user-images.githubusercontent.com/5029239/89991206-11434000-dcb6-11ea-94bc-d86088ae10c5.png)

**Comment by theniceangel** [comment]
@mircle 能提供一个复现 repo 么

**Comment by mircle** [comment]
index.vue?67f5:124 Uncaught TypeError: swiper.getCurrentPage is not a function

![image](https://user-images.githubusercontent.com/5029239/89994610-f58e6880-dcba-11ea-8ec4-f1fc20c7c361.png)
![image](https://user-images.githubusercontent.com/5029239/89994650-017a2a80-dcbb-11ea-93db-0aa9cbbc8be8.png)
![image](https://user-images.githubusercontent.com/5029239/89994725-18b91800-dcbb-11ea-9e3d-ab3f04b3f6f6.png)

下拉刷新  上拉加载       横向滑动       一起使用 的     1.x  没问题    2.x  会报上面的错误

**Comment by theniceangel** [comment]
我这边需要代码调试一下，如果使用 v1.x，可以使用 `useTransition: false` 来修复回弹的问题

**Comment by mircle** [comment]
嗯   这个属性  可以解决我的问题      感谢老大

**Comment by theniceangel** [comment]
> 嗯 这个属性 可以解决我的问题 感谢老大

在 2.0 的正式版本，我们会解决这个问题，并且给出对应的示例
