### ISSUE TITLE
手指向上快速滑动，页面卡在回弹前的状态，无法触发scrollEnd

### ISSUE THREAD

**Issue by wanzijinx** [ustbhuangyi/better-scroll#1045]
bug截图：
![image](https://user-images.githubusercontent.com/28819509/90091032-1a84e900-dd58-11ea-8449-b19a707adb78.png)
bug详细描述：
手指迅速上划，导致页面无法回弹，不断触发scroll事件，重新点击页面或者滑动页面触发touchEnd事件才可以回弹

**Comment by theniceangel** [comment]
提供版本号，以及代码

**Comment by wanzijinx** [comment]
> 提供版本号，以及代码

版本号：1.15.2
代码：
<template>
    <view id="{{wrapperId}}" class="wrapper"
          style="{{cstyle}}">
        <view>
            <view c-if="{{pullDown}}"
                  class="pullDown"
                  style="{{dragTipStyle}}"
            >
                <view class="clear" c-if="{{dragTip.showLoading}}">
                    <view>{{dragTip.text}}</view>
                </view>
            </view>
                <slot></slot>
        </view>
    </view>
</template>

<script>
import BScroll from 'better-scroll';
import cml from 'chameleon-api';
class Scroller implements ScrollerInterface {
    props = {
        dataList: {
            type: Array,
            default: []
        },
        pullUp: {
            type: Boolean,
            default: false
        },
        pullDown: {
            type: Boolean,
            default: false
        }, // 是否开启下拉刷新
        pullingDownFinish: {
            type: Boolean,
            default: false
        },
        wrapperId: {
            type: String,
            default: 'wrapper'
        },
        cstyle: {
            type: String,
            default: ''
        },
        bottomOffset: {
            // 距底部/右边多远时（单位px），触发 scrolltolower 事件
            type: Number,
            default: 0
        },
        scrollLeft: {
            type: Number,
            default: 0
        },
        scrollTop: {
            type: Number,
            default: 0
        }, // 滚动到纵向指定位置
        pullingDown: {
            type: Boolean,
            default: false
        },
        scrollWithAnimation: {
            type: Boolean,
            default: true
        },
        scrollIntoView: {
            type: String,
            default: ''
        }
    };

    data = {
        scroll: {},
        dragTip: {
            text: '下拉刷新',
            translate: -100,
            showLoading: false
        },
        isLoading: false,
        position: {
            x: 0,
            y: 0
        }
    };

    computed = {
        dragTipStyle () {
            return `margin-top:${this.dragTip.translate}cpx`;
        }
    };

    watch = {
        // 监听数据的变化，延时refreshDelay时间后调用refresh方法重新计算，保证滚动效果正常
        dataList (val) {
            if (val.length > 0) {
                setTimeout(() => {
                    this.refresh();
                }, 20);
            }
        },
        pullingDownFinish (val) {
            if (val) {
                this.scroll.finishPullUp();
                this.isLoading = false;
                this.isDone = false;
                this.dragTip = {
                    text: '下拉刷新',
                    translate: -100,
                    showLoading: false
                };
            }
        },
        scrollTop (val) {
            console.log(val);
            this.scroll.scrollTo(0, val, 100);
        },
        scrollIntoView (val) {
            this.scroll.scrollToElement(document.getElementById(val));
        }
    };

    mounted () {
        const vm = this;
        setTimeout(() => {
            vm.initScroll();
        }, 20);
    }

    methods = {
        initScroll () {
            let node = {};
            node = document.getElementById(this.wrapperId);
            if (!node) {
                return;
            }
            // better-scroll的初始化
            if (this.pullDown) {
                this.scroll = new BScroll(node, {
                    probeType: 1,
                    click: true,
                    scrollX: false,
                    pullDownRefresh: {
                        threshold: 50,
                        stop: 20
                    },
                    mouseWheel: true
                });
            } else {
                this.scroll = new BScroll(node, {
                    probeType: 1,
                    click: true,
                    scrollX: false,
                    mouseWheel: true
                });
            }
            this.scroll.on('scroll', (pos) => {
                console.log(pos);
                if (pos.y > 50 && this.dragTip.text !== '刷新中...') {
                    // 显示下拉刷新loding
                    console.log('释放刷新');
                    this.dragTip.showLoading = true;
                    this.dragTip.text = '释放刷新';
                }
                const detail = {
                    deltaX: cml.px2cpx(pos.x),
                    deltaY: cml.px2cpx(pos.y),
                    scrollHeight: 0,
                    scrollLeft: -cml.px2cpx(pos.x),
                    scrollTop: -cml.px2cpx(pos.y),
                    scrollWidth: 0
                };
                this.$cmlEmit('onScroll', detail);
                this.$cmlEmit('customscroll', detail);
            });
            this.scroll.on('scrollEnd', () => {
                console.log('scrollEnd');
                // 滚动到底部
                if (this.scroll.y <= (this.scroll.maxScrollY + 50)) {
                    console.log('scrolltobottom');
                    this.$cmlEmit('scrolltobottom');
                }
            });
            // 是否派发顶部下拉事件，用于下拉刷新
            if (this.pullDown) {
                this.scroll.on('touchEnd', (pos) => {
                    console.log('touchEnd');
                    if (pos.y > 50) {
                        console.log('刷新中');
                        this.dragTip.translate = 0;
                        this.dragTip.text = '刷新中...';
                        // 重新初始化
                        this.$cmlEmit('onPullDownRefresh');
                    }
                });
            }
        },
        refresh () {
            // 代理better-scroll的refresh方法
            this.scroll && this.scroll.refresh();
        },
        scrollTo (param) {
            // 代理better-scroll的scrollTo方法
            this.scroll && this.scroll.scrollTo.apply(this.scroll, param);
        },
        scrollToElement (param) {
            // 代理better-scroll的scrollToElement方法
            this.scroll && this.scroll.scrollToElement.apply(this.scroll, param);
        }
    };

    beforeCreate () {
    }

    created () {
    }

    beforeMount () {
    }

    beforeDestroy () {
    }

    destroyed () {
    }
}

export default new Scroller();
</script>
<style scoped lang="less" type="text/less">
    .wrapper{
        .pullDown{
            width:100%;
            height:50px;
            position:relative;
            .clear{
                padding:10px 0px;
                font-size:.28rem;
                position:absolute;
                left:50%;
                top:5px;
                transform:translate(-50%,0)
            }
        }
    }
</style>
<script cml-type="json" type="application/json">
{
    "base": {
        "usingComponents": {}
    }
}
</script>

**Comment by theniceangel** [comment]
> > 提供版本号，以及代码
> 
> 版本号：1.15.2
> 代码：
> https://codepen.io/wanzijinx-the-encoder/pen/WNwrLad

不好意思，最近忙着发2.0的版本，我看你代码里面为什么用了 pulldownRefresh，调用的是 finishPullUp？

另外建议切换到 2.x 版本，1.x 有很多问题，也不准备维护了。

**Comment by theniceangel** [comment]
2.0 已发版，可以尝试～
