### ISSUE TITLE
v2版本的pullUpLoad插件不能通过方法开启

### ISSUE THREAD

**Issue by php4world** [ustbhuangyi/better-scroll#1046]
### Version
1.15.0

### Reproduction link
[https://codesandbox.io/s/festive-sky-wyjyj](https://codesandbox.io/s/festive-sky-wyjyj)

### Steps to reproduce
使用pullingUp这类插件时，如果实例化的时候传入pullUpLoad: false，则实例不会加载此插件。导致openPullUp函数不能被加载。而实例化时传入pullUpLoad: true，则没有问题。

### What is expected?
BScroll.use(Pullup)后，设置pullUpLoad: false可以通过openPullUp(config: pullUpLoadOptions = true)方法开启上拉加载

### What is actually happening?
pullUpLoad不设置为true，BScroll.use(Pullup)后实际不会加载此插件

**Comment by theniceangel** [comment]
@php4world 如果要禁用插件，直接调用 close 方法关闭 pullup 能力
