### ISSUE TITLE
从bate10升级到2.0.1版本 translateZ 的值为什么从0变成了1

### ISSUE THREAD

**Issue by xupd** [ustbhuangyi/better-scroll#1050]
### Version
2.0.1

### Reproduction link
[https://qbql4.csb.app/](https://qbql4.csb.app/)

### Steps to reproduce
我根元素有配置transform-style: preserve-3d，导致滑动页面覆盖了父元素的同级元素了。

### What is expected?
无

### What is actually happening?
无

**Comment by xupd** [comment]
<img width="618" alt="WX20200828-151017@2x" src="https://user-images.githubusercontent.com/18721169/91532353-c9244e80-e940-11ea-962e-f131006a5e0b.png">

**Comment by theniceangel** [comment]
@xupd 增加这个 css 是为了解决滚动可能出现白屏的问题

**Comment by xupd** [comment]
好的，谢谢。我把原来的样式改改。
