### ISSUE TITLE
PullDown plugin has a problem

### ISSUE THREAD

**Issue by MingxiangFeng** [ustbhuangyi/better-scroll#1052]
问题描述：pullingDown 钩子无法触发

问题复现: 
从文档中拷贝的例子，略作改动，如下：

![image](https://user-images.githubusercontent.com/30710446/91590759-69ed2b00-e98e-11ea-8bc1-1f22c811d9de.png)

![image](https://user-images.githubusercontent.com/30710446/91590860-930dbb80-e98e-11ea-867a-0fdc431a16d8.png)

![image](https://user-images.githubusercontent.com/30710446/91590894-a1f46e00-e98e-11ea-9be1-e4fd3b344d36.png)

其他还是按照官网文档给出的来，运行后，发现 scroll 和scrollEnd钩子均能被触发，pullingDown不能被触发。

文件已附上。

[scroll.vue.zip](https://github.com/ustbhuangyi/better-scroll/files/5143132/scroll.vue.zip)

**Comment by MingxiangFeng** [comment]
依赖版本：
"vue": "^2.5.2",
"@better-scroll/core": "^2.0.1",
"@better-scroll/pull-down": "^2.0.1",

**Comment by theniceangel** [comment]
@MingxiangFeng 用你打包的文件替换了 pulldown/default.vue，测试了可以触发 pullingDown 钩子

**Comment by MingxiangFeng** [comment]
@theniceangel 
yes，indeed。但我发现需要添加样式, 否则还是无法触发。如下：

`css
html, body {
  width: 100%;
  height: 100%;
  margin: 0;
  overflow: hidden;
}

.app {
  width: 100%;
  position: relative;
  height: 100%;
  overflow: hidden;
}
`

在chrome模拟器上和真机都测试过，加上此样式后，可触发。

觉得可以在文档的“使用”中标注此条件。

thanks!
