### ISSUE TITLE
插件挺好好的，不过文档做的太差了

### ISSUE THREAD

**Issue by happyqian** [ustbhuangyi/better-scroll#1053]
可能，你是技术大牛，都不屑写太多的代码了，比如说banner slider, 只给出的效果，代码没有，配置项也没有。

**Comment by theniceangel** [comment]
@happyqian 有代码呀，可以点图标
![image](https://user-images.githubusercontent.com/25956811/91676997-0fadbf00-eb74-11ea-9707-86f3bdec3a4f.png)

**Comment by theniceangel** [comment]
@happyqian 如果有什么建议，可以提的哈～，我们花了这么多心血开源这个项目，自然希望文档也能写好

**Comment by happyqian** [comment]
@theniceangel 我是在2.xDemo 点进去的
![微信截图_20200831103735](https://user-images.githubusercontent.com/3366947/91677910-ba26e180-eb76-11ea-9ec4-57253c88adaa.png)
![微信截图_20200831103821](https://user-images.githubusercontent.com/3366947/91677917-bc893b80-eb76-11ea-84a1-b7166b04b501.png)

**Comment by theniceangel** [comment]
@happyqian 一般的了解一个库是从文档开始的，所以我们把代码同步到了文档当中

**Comment by chenyulun** [comment]
搞不清楚demo和文档的区别吗？
