### ISSUE TITLE
无论怎么样设置样式 好像都不能上拉完全 总有一部分内容在下面无法完全上拉起来显示

### ISSUE THREAD

**Issue by hongdundada** [ustbhuangyi/better-scroll#1054]

**Comment by hongdundada** [comment]
[bug.zip](https://github.com/ustbhuangyi/better-scroll/files/5146990/bug.zip)
使用的是1.13.2版本  views/login/cad.vue  写了200个数字li 不知道为什么下面就是有部分内容无法上拉 特别奇怪

**Comment by theniceangel** [comment]
@hongdundada 试了一下可以啊，你是不是从pc模式切到手机模式，没有刷新？
