### ISSUE TITLE
移动端，下拉刷新卡住

### ISSUE THREAD

**Issue by xupd** [ustbhuangyi/better-scroll#1055]
### Version
2.0.1

### Reproduction link
[https://better-scroll.github.io/examples/#/pulldown/](https://better-scroll.github.io/examples/#/pulldown/)

### Steps to reproduce
下拉刷新不松开，同时另一个手点击一下屏幕，两只手放开，下拉卡住了。要重新下划一下才行。

### What is expected?
无

### What is actually happening?
无

**Comment by theniceangel** [comment]
@xupd 谢谢反馈

**Comment by theniceangel** [comment]
fixed at v2.0.2
