### ISSUE TITLE
苹果机，快速滚动一段距离，然后手在屏幕顿一下（此时滚动会停止），把手拿开，滚动会重新出现

### ISSUE THREAD

**Issue by tfeng-use** [ustbhuangyi/better-scroll#1056]
### Version
2.0.1

### Reproduction link
[http://ustbhuangyi.com/music/#/recommend](http://ustbhuangyi.com/music/#/recommend)

### Steps to reproduce
注意：机型iphone8p，os13.6
1. 手移动到滚动区，快速移动；
2. 手停在屏幕上，顿一下；
3. 手拿开（此时滚动就会发生）

### What is expected?
当手停住的时候，由于跟随性，滚动会停止，当手拿开以后，滚动也不应该再出现

### What is actually happening?
试5次肯定就会出现

**Comment by theniceangel** [comment]
@tfeng-use reproduction link 的那个链接用的是 1.x 版本

**Comment by tfeng-use** [comment]
https://dev-repurchaseassemble.jjh9999.com/site/#/


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ustbhuangyi/better-scroll"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 中午1:45
收件人:&nbsp;"ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;;
抄送:&nbsp;"绯红的倩影、、、"<462787828@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ustbhuangyi/better-scroll] 苹果机，快速滚动一段距离，然后手在屏幕顿一下（此时滚动会停止），把手拿开，滚动会重新出现 (#1056)





 
@tfeng-use reproduction link 的那个链接用的是 1.x 版本

**Comment by tfeng-use** [comment]
https://dev-repurchaseassemble.jjh9999.com/site/#/
可以试一下这个连接


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ustbhuangyi/better-scroll"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 中午1:45
收件人:&nbsp;"ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;;
抄送:&nbsp;"绯红的倩影、、、"<462787828@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ustbhuangyi/better-scroll] 苹果机，快速滚动一段距离，然后手在屏幕顿一下（此时滚动会停止），把手拿开，滚动会重新出现 (#1056)





 
@tfeng-use reproduction link 的那个链接用的是 1.x 版本

**Comment by theniceangel** [comment]
@tfeng-use 试了很多次，未复线，你可以录个屏

**Comment by tfeng-use** [comment]
在第7s、16s、19s可以比较清楚的看见




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ustbhuangyi/better-scroll"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 下午5:29
收件人:&nbsp;"ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;;
抄送:&nbsp;"绯红的倩影、、、"<462787828@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ustbhuangyi/better-scroll] 苹果机，快速滚动一段距离，然后手在屏幕顿一下（此时滚动会停止），把手拿开，滚动会重新出现 (#1056)





 
@tfeng-use 试了很多次，未复线，你可以录个屏

**Comment by theniceangel** [comment]
@tfeng-use 可以录制一个视频，目前未复线

**Comment by tfeng-use** [comment]
附件里面是录制的视频，关注第4s、8s、10s。
说一下我的理解：有没有可能是判断初始触摸点和结尾触摸点的时候没有考虑到停顿的情况，把结尾时的停顿当成了普通的离开




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ustbhuangyi/better-scroll"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 晚上7:44
收件人:&nbsp;"ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;;
抄送:&nbsp;"绯红的倩影、、、"<462787828@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ustbhuangyi/better-scroll] 苹果机，快速滚动一段距离，然后手在屏幕顿一下（此时滚动会停止），把手拿开，滚动会重新出现 (#1056)





 
@tfeng-use 可以录制一个视频，目前未复线

**Comment by theniceangel** [comment]
@tfeng-use 没看到附件～～

**Comment by tfeng-use** [comment]
我在附件里面添加了，如果找不到附件，可以看下面的github地址，里面的betterscroll.mp4就是对应的mp4，下载下来就可以看
https://github.com/tfeng-use/files




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ustbhuangyi/better-scroll"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 晚上9:43
收件人:&nbsp;"ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;;
抄送:&nbsp;"绯红的倩影、、、"<462787828@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ustbhuangyi/better-scroll] 苹果机，快速滚动一段距离，然后手在屏幕顿一下（此时滚动会停止），把手拿开，滚动会重新出现 (#1056)





 
@tfeng-use 没看到附件～～

**Comment by theniceangel** [comment]
@tfeng-use 像是触发了 momentum 动量动画，你可以在 `@better-scroll/core/dist/core.esm.js` 下面的代码，看看是否进入了垂直方向的 momentum 动画。
![image](https://user-images.githubusercontent.com/25956811/91941396-bdaf9980-ed2b-11ea-8808-fd641209f6fd.png)

**Comment by tfeng-use** [comment]
确实进入了的，只要出现那个问题就会进入到向量动画里面。
（1）图片是我标记的地方；
（2）github地址（https://github.com/tfeng-use/files）下面的 检查是否进入了向量动画.gif是演示效果







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ustbhuangyi/better-scroll"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月2日(星期三) 下午2:51
收件人:&nbsp;"ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;;
抄送:&nbsp;"绯红的倩影、、、"<462787828@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ustbhuangyi/better-scroll] 苹果机，快速滚动一段距离，然后手在屏幕顿一下（此时滚动会停止），把手拿开，滚动会重新出现 (#1056)





 
@tfeng-use 像是触发了 momentum 动量动画，你可以在 @better-scroll/core/dist/core.esm.js 下面的代码，看看是否进入了垂直方向的 momentum 动画。

**Comment by theniceangel** [comment]
@tfeng-use 那就没问题了，可以 google 一下 momentum 算法，主要是模拟客户端的惯性滚动动画。

**Comment by tfeng-use** [comment]
如果滑动过程中顿了一下，然后拿开手，就不应该进入惯性动画，所以前面还要再判断一下这种情况才对


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ustbhuangyi/better-scroll"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月2日(星期三) 下午3:43
收件人:&nbsp;"ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;;
抄送:&nbsp;"绯红的倩影、、、"<462787828@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ustbhuangyi/better-scroll] 苹果机，快速滚动一段距离，然后手在屏幕顿一下（此时滚动会停止），把手拿开，滚动会重新出现 (#1056)





 
@tfeng-use 那就没问题了，可以 google 一下 momentum 算法，主要是模拟客户端的惯性滚动动画。
 
—发送

**Comment by theniceangel** [comment]
@tfeng-use 你的演示，是因为拿开手之后，又迅速滚动了一小段距离，触发了 momentum

**Comment by tfeng-use** [comment]
手拿开就是很正常的拿开，和在普通h5上面拿开是一样的，这个时候就应该停下来（普通H5滚动也是停下来的），至于迅速的滚动一小段距离不太明白什么意思，如果是手拿开的时候触发了滚动（但是很明显用户都会认为自己没有滚动），那么就需要代码里面去处理一下这种情况。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ustbhuangyi/better-scroll"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月2日(星期三) 下午3:59
收件人:&nbsp;"ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;;
抄送:&nbsp;"绯红的倩影、、、"<462787828@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ustbhuangyi/better-scroll] 苹果机，快速滚动一段距离，然后手在屏幕顿一下（此时滚动会停止），把手拿开，滚动会重新出现 (#1056)





 
@tfeng-use 你的演示，是因为拿开手之后，又迅速滚动了一小段距离，触发了 momentum

**Comment by theniceangel** [comment]
@tfeng-use 你仔细剖析下你的手指动作。你触发了一段滚动，然后手指再次放上去的时候，其实你的手指迅速的动了一下，造成了第二次 momentum 的计算。

**Comment by tfeng-use** [comment]
触发一段滚动后，手并没有移开，一直都在屏幕上面，放开手指后就触发了，后面再放上去是滚动停止后的事情了。所以迅速的动一下这个并没有，我建议你复现一下，一次用手划一下（不要手用力划一下），然后把手拿开，很容易就复现了。如果你那边没有复现，咋们可以接个视频，好好的演示一下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ustbhuangyi/better-scroll"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月2日(星期三) 下午5:04
收件人:&nbsp;"ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;;
抄送:&nbsp;"绯红的倩影、、、"<462787828@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ustbhuangyi/better-scroll] 苹果机，快速滚动一段距离，然后手在屏幕顿一下（此时滚动会停止），把手拿开，滚动会重新出现 (#1056)





 
@tfeng-use 你仔细剖析下你的手指动作。你触发了一段滚动，然后手指再次放上去的时候，其实你的手指迅速的动了一下，造成了第二次 momentum 的计算。

**Comment by tfeng-use** [comment]
问题没有解决啊，亲，怎么就关闭了呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ustbhuangyi/better-scroll"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月2日(星期三) 晚上6:07
收件人:&nbsp;"ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;;
抄送:&nbsp;"绯红的倩影、、、"<462787828@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ustbhuangyi/better-scroll] 苹果机，快速滚动一段距离，然后手在屏幕顿一下（此时滚动会停止），把手拿开，滚动会重新出现 (#1056)





 
Closed #1056.

**Comment by theniceangel** [comment]
@tfeng-use 建议从源码的角度去理清问题，而且你的描述也是有误的

**Comment by tfeng-use** [comment]
描述不知道有啥问题，效果就是这样的，视频也发给你了，问题就是滚动时出现的违和感，可以从源码的角度解释这个，并不代表这不是个问题，从使用角度上这是个很大的问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ustbhuangyi/better-scroll"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月3日(星期四) 上午9:33
收件人:&nbsp;"ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;;
抄送:&nbsp;"绯红的倩影、、、"<462787828@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ustbhuangyi/better-scroll] 苹果机，快速滚动一段距离，然后手在屏幕顿一下（此时滚动会停止），把手拿开，滚动会重新出现 (#1056)





 
@tfeng-use 建议从源码的角度去理清问题，而且你的描述也是有误的

**Comment by Tanbo123456** [comment]
> ### Version
> 2.0.1
> 
> ### Reproduction link
> http://ustbhuangyi.com/music/#/recommend
> 
> ### Steps to reproduce
> 注意：机型iphone8p，os13.6
> 
> 1. 手移动到滚动区，快速移动；
> 2. 手停在屏幕上，顿一下；
> 3. 手拿开（此时滚动就会发生）
> 
> ### What is expected?
> 当手停住的时候，由于跟随性，滚动会停止，当手拿开以后，滚动也不应该再出现
> 
> ### What is actually happening?
> 试5次肯定就会出现

复现
