### ISSUE TITLE
每次需要重新刷新页面 才能进行上拉 

### ISSUE THREAD

**Issue by hongdundada** [ustbhuangyi/better-scroll#1057]
项目运行以后 点击投资 来到cad页面无法进行上拉 明明已经mounted进行刷新了
但是仍旧需要 刷新整个页面

即使使用debounce better-scroll this.scroll.refresh(); 依旧无效
页面已经加载完毕 mounted里面 延迟2秒执行this.scroll.refresh(); 
依旧无法进行上拉
必须要整个页面进行刷新才可以
[bug.docx](https://github.com/ustbhuangyi/better-scroll/files/5156428/bug.docx)

![刷新后](https://user-images.githubusercontent.com/61041443/91855948-77f5c100-ec98-11ea-82d3-12ced2d56dc6.png)
ll.refresh(); 
![刷新前](https://user-images.githubusercontent.com/61041443/91855960-7af0b180-ec98-11ea-8b46-1c5fbb34e184.png)

依旧无法进行上拉
必须要整个页面进行刷新才可以

[滑动bug.zip](https://github.com/ustbhuangyi/better-scroll/files/5156374/bug.zip)

**Comment by theniceangel** [comment]
@hongdundada 你是怎么操作的？如果是从 pc 模式切换到手机模式，自然需要刷新页面

**Comment by hongdundada** [comment]
一开始就是手机模式进行操作
