### ISSUE TITLE
使用BetterScroll让vuetify的v-tab中的v-tab-item中的元素滚动起来，结果：pc端可以顺滑滚动，移动端不能顺滑滚动

### ISSUE THREAD

**Issue by CHENQIKUAI** [ustbhuangyi/better-scroll#1059]
### Version
2.0.2

### Reproduction link
[https://codepen.io/chenqikuai/pen/QWNqXmW](https://codepen.io/chenqikuai/pen/QWNqXmW)

### Steps to reproduce
https://codepen.io/chenqikuai/pen/QWNqXmW
在电脑端打开后，列表可以顺滑滚动的。
在移动端打开后，列表不可以顺滑滚动。

### What is expected?
期望v-tab-item中的元素，在移动端也可以通过BetterScroll实现顺滑滚动。

### What is actually happening?
v-tab-item中的元素，在移动端无法通过BetterScroll实现顺滑滚动。

**Comment by theniceangel** [comment]
@CHENQIKUAI bs 内部与 vuetify 冲突啦，vuetify 默认会在 touchend 事件里面阻止冒泡，只需要实例化 bs 增加以下配置就行。

```diff
{
+    bindToWrapper: true
}
```
