### ISSUE TITLE
快速滑动后，在滚动未停止之前反方向再次快速滑动，滑动结束后，点击input输入框无法获取焦点

### ISSUE THREAD

**Issue by haidaxian** [ustbhuangyi/better-scroll#1060]
### Version
2.0.2

### Reproduction link
[ https://codesandbox.io/s/nervous-driscoll-3b5it]( https://codesandbox.io/s/nervous-driscoll-3b5it)

### Steps to reproduce
1、快速滑动后，在滚动未停止之前反方向再次快速滑动
2、滑动结束后，点击input输入框无法获取焦点

### What is expected?
点击input输入框可以获取焦点

### What is actually happening?
点击input输入框无法获取焦点

**Comment by haidaxian** [comment]
同样情况下click点击事件也会不生效

**Comment by theniceangel** [comment]
@haidaxian repos 在 codesandbox 里面报错了

**Comment by haidaxian** [comment]
> @haidaxian repos在codeandbox里面报错了

https://codesandbox.io/s/quizzical-leftpad-46ocp

**Comment by haidaxian** [comment]
@theniceangel  https://codesandbox.io/s/quizzical-leftpad-46ocp

**Comment by haidaxian** [comment]
不好意思，请看这个链接吧&nbsp;https://codesandbox.io/s/quizzical-leftpad-46ocp
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ustbhuangyi/better-scroll"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 上午9:57
收件人:&nbsp;"ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;;
抄送:&nbsp;"867968023"<867968023@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ustbhuangyi/better-scroll] 快速滑动后，在滚动未停止之前反方向再次快速滑动，滑动结束后，点击input输入框无法获取焦点 (#1060)





 
@haidaxian repos 在 codesandbox 里面报错了

**Comment by theniceangel** [comment]
@haidaxian transition 模式有 bug，可以临时用 raf 解决一下。

```js
{
    useTransition: false
}
```

**Comment by haidaxian** [comment]
@theniceangel 好的，谢谢，期望尽快解决。

**Comment by theniceangel** [comment]
@haidaxian 今天上午发版

**Comment by theniceangel** [comment]
@haidaxian fix at v2.0.3

**Comment by haidaxian** [comment]
@theniceangel 更新后问题已解决，感谢
