### ISSUE TITLE
[New Feature] 初始化时开启了鼠标滚轮滚动(mouseWheel: true)，想要禁止默认的长按滚动

### ISSUE THREAD

**Issue by jhmei** [ustbhuangyi/better-scroll#1061]
### What problem does this feature solve?
PC端页面，当给页面元素加上draggable="true"开启拖动时，这会和better-scroll的默认长按滚动有点小冲突的(某种场景下会造成鼠标像是粘在滚动列表一样，移不开了，原本的拖动也难以触发了)

### What does the proposed API look like?
我觉得禁止默认长按滚动的属性应该已经有了吧，不过我还没找到

@ustbhuangyi

**Comment by theniceangel** [comment]
@jhmei preventDefault 设置为false

**Comment by theniceangel** [comment]
可以提供 repo

**Comment by jhmei** [comment]
> @jhmei preventDefault 设置为false
这属性不是干这个的，加上不管用，谢谢啦

PS:
preventDefault
类型：boolean
默认值：true
作用：当事件派发后是否阻止浏览器默认行为。这个值应该设为 true，除非你真的知道你在做什么，通常你可能用到的是 preventDefaultException。

**Comment by jhmei** [comment]
> 可以提供 repo

兄台  不好意思没搞懂您的意思是？

**Comment by theniceangel** [comment]
@jhmei 给出你的场景以及可复现的仓库代码

**Comment by jhmei** [comment]
> @jhmei 给出你的场景以及可复现的仓库代码

这样就麻烦了，其实不需要repo，很简单：就是想取消better-scroll默认长按滑动滚动（因为PC端已经开启mouseWheel: true鼠标滚轮滚动了）

**Comment by theniceangel** [comment]
@jhmei disableMouse 设置为 true

**Comment by jhmei** [comment]
> @jhmei disableMouse 设置为 true

真的好使了，谢谢大佬
