### ISSUE TITLE
使用betterScroll2.0滚动的时候，当滚动停止，无法触发点击事件，刷新后又可以

### ISSUE THREAD

**Issue by GreatHonour** [ustbhuangyi/better-scroll#1062]
这个链接打不开，只能在这里发布了
https://cube-ui.github.io/cube-issue-helper/?repo=ustbhuangyi/better-scroll

默认配置click已经为true，按需引入，测试浏览器 为 《谷歌浏览器Google Chrome 版本 85.0.4183.83（正式版本64 位）》
小米手机mix2微信浏览器，企业微信，自带浏览器，都出现这样的问题

![image](https://user-images.githubusercontent.com/25587991/92352637-22df0280-f111-11ea-9a76-22d8db777237.png)

![image](https://user-images.githubusercontent.com/25587991/92352700-430ec180-f111-11ea-862f-bad475bd0988.png)

![image](https://user-images.githubusercontent.com/25587991/92352902-b57fa180-f111-11ea-9658-6125067638ef.png)

**Comment by theniceangel** [comment]
@GreatHonour 有复线的 repo 么？

**Comment by theniceangel** [comment]
@GreatHonour 升级到 v2.0.3试试
