### ISSUE TITLE
better-scroll@2.0.2设置mouseWheel为true后ctrl+鼠标滚轮无法缩放网页

### ISSUE THREAD

**Issue by luoyi-syoyu** [ustbhuangyi/better-scroll#1063]
mouseWheel: true这个属性虽然可以使用鼠标滚轮进行滚动，但是在滚动区域中，ctrl+鼠标滚轮无法缩放网页，依然是滚动网页

**Comment by theniceangel** [comment]
@luoyi-syoyu 这种行为跟系统、浏览器有关系，有什么强烈的需求必须要遵从这种交互行为么？

**Comment by luoyi-syoyu** [comment]
某些用户习惯使用ctrl+鼠标滚轮来进行放大缩小网页，但是在滚动区域内该属性被禁止了，我不明白为什么要禁止ctrl+鼠标滚轮缩放网页的行为

**Comment by theniceangel** [comment]
@luoyi-syoyu 那你实例化 bs 的时候传入以下配置试试，
```diff
{
    preventDefault: false
}
```

**Comment by luoyi-syoyu** [comment]
这个配置昨天就试过了，如果设置为false那么移动端滑动就会出现其他问题，手机上无法向上滑动

**Comment by theniceangel** [comment]
@luoyi-syoyu bs 内部会调用 `e.preventDefault()` 来阻止默认行为，因此影响到 ctrl + 鼠标滚轮的放大缩小，你的页面如果要既支持 pc 又要支持手机，可以根据 ua 在实例化 bs 的时候进行 preventDefault 的配置
