### ISSUE TITLE
2.0之前所有的alpha、beta版更新到2.0正式版导致slide自动滚动

### ISSUE THREAD

**Issue by luckyhalley** [ustbhuangyi/better-scroll#1065]
### Version
2.0.0

### Steps to reproduce
2.0正式版之前所有的alpha、beta版更新至2.0正式版

### What is expected?
2.0正式版之前所有版本没有autoplay参数，slide插件默认不会自动滚动，如果2.0正式版添加新参数，不应改变之前版本的行为，应与之前版本保持一致的兼容性，且向下兼容，不应自动滚动

### What is actually happening?
2.0正式版添加了autoplay参数，且默认值为true，导致alpha、beta版更新到正式版slide插件自动滚动

```
    const defaultOptions: SlideConfig = {
      loop: true,
      threshold: 0.1,
      speed: 400,
      easing: ease.bounce,
      listenFlick: true,
      autoplay: true,
      interval: 3000,
    }
```

**Comment by theniceangel** [comment]
@luckyhalley 对于 2.0 正式版本来说，我们重新思考了一下交互，认为轮播图应该正如它的名字一样，所以把 autoplay 默认设为 true，如果不需要，需要手动关闭。

**Comment by luckyhalley** [comment]
> @luckyhalley 对于 2.0 正式版本来说，我们重新思考了一下交互，认为轮播图应该正如它的名字一样，所以把 autoplay 默认设为 true，如果不需要，需要手动关闭。

你们团队是否对slide的语意有误解，slide来源于iOS的滑动解锁，也是手机滑动滚屏的效果，轮播图的语意为画廊gallery，建议参考一下主流ui对slide的解析，如antd或是element

**Comment by luckyhalley** [comment]
> @luckyhalley 对于 2.0 正式版本来说，我们重新思考了一下交互，认为轮播图应该正如它的名字一样，所以把 autoplay 默认设为 true，如果不需要，需要手动关闭。

另外要说的一点是，直接在正式版发颠覆性的改动，并不是一个合适的做法，这样的改动没有经过任何一个alpha或beta版，并且直接推翻了之前的效果

**Comment by theniceangel** [comment]
@luckyhalley 嗯，正式版本肯定会发生一些 breaking change，只不过正如你所说，我们没有一个版本来过渡，有点欠妥
