### ISSUE TITLE
Better-Scroll的疑难杂症 增加浏览器默认手势冲突的解决方案

### ISSUE THREAD

**Issue by minikey** [ustbhuangyi/better-scroll#1067]
在国内很多的默认浏览器中都会有手势来快速的回退和前进，一旦有BS实现的水平滚动，在很多时候都会冲突。表现为卡顿或滚动不生效。一个比较通用的方案是通过css的touch-action，来解决，比如：
BS实现了水平方向的滚动，就可以指定 `touch-action: pan-y;` 这样水平方向的操作就不会触发浏览器的默认行为。

**Comment by theniceangel** [comment]
@minikey 如果自己在 wrapper 或者 content 元素上面设置这个样式呢？

**Comment by minikey** [comment]
> @minikey 如果自己在 wrapper 或者 content 元素上面设置这个样式呢？

对，需要开发者自己根据实际情况去设置

**Comment by theniceangel** [comment]
@minikey 欢迎 pr，加入到文档里面去

**Comment by miya-yang** [comment]
感谢大佬，完美解决卡顿。
