### ISSUE TITLE
mouse-wheel bug

### ISSUE THREAD

**Issue by TothingWay** [ustbhuangyi/better-scroll#1072]
### Version
2.0.3

### Reproduction link
[https://codesandbox.io/s/magical-hamilton-3t0z6?file=/src/main.js](https://codesandbox.io/s/magical-hamilton-3t0z6?file=/src/main.js)

### Steps to reproduce
在页面中同时使用2个better-scroll（不嵌套）并开启mouse-wheel，在其中一个better-scroll中使用鼠标滚轮快速滚动后马上移动到另一个better-scroll中，该better-scroll会继承之前better-scroll滚动的行为。

### What is expected?
使用滚轮滚动，两个better-scroll相互独立，不关联

### What is actually happening?
使用滚轮滚动后在一个better-scroll中滚动未结束前移动到另一个better-scroll中，会继承之前的滚动行为

---
开启mouse-wheel之后的回弹动画体验不是很好，为什么回弹动画如此缓慢？在调整了easeTime，discreteTime，throttleTime，dampingFactor，bounceTime等时间都无法达到移动端手指触摸的回弹体验。

**Comment by theniceangel** [comment]
我这边未复现，你那边可否录个屏，另外因为鼠标的交互特性，很难无法做到移动端的一模一样的回弹体验，只能去修改 dampingFactor 和 bounceTime 来迎合你的需求了。

**Comment by TothingWay** [comment]
系统：macOS 10.15.6

浏览器：Chrome 84.0.4147.105

使用滚轮滚动左边的列表，然后马上移动到右边列表，右边在不使用滚轮的情况下也会滚动
![录屏](http://101.132.76.13/images/issue.gif)

**Comment by theniceangel** [comment]
@TothingWay 我这边的系统与你一样，浏览器版本：Chrome 85.0.4183.102，未复现。你能否尝试升级一下版本，看下 bug 是否存在

**Comment by TothingWay** [comment]
@theniceangel 升级Chrome浏览器到最新版本，还是有这个情况，且我尝试在Safari中查看，也还有这个现象。

https://codesandbox.io/s/magical-hamilton-3t0z6?file=/src/main.js

**Comment by theniceangel** [comment]
@TothingWay 我试了几个同事的 mac，都没有复现问题

**Comment by TothingWay** [comment]
那我用我同事的电脑也去测试一下，看看有没有这个问题

**Comment by TothingWay** [comment]
@theniceangel 我在同事电脑测试对比之后，发现了问题的根源，我是用magic mouse蓝牙鼠标，用触摸板滚动这个现象不会发生，具体为什么用magic mouse会出现这个现象的原因不清楚

**Comment by theniceangel** [comment]
@TothingWay 可以在mouse-wheel的源码 debugger 一下，欢迎 pr

**Comment by zhuangxiaohui** [comment]
我也出现这个问题了。v1.15.0不会出现这个问题。
 v2.0.4 缩放浏览器就可以滚动了，不然无法滚动

**Comment by webfansplz** [comment]
+1
