### ISSUE TITLE
[New Feature] 添加配置项`translateRound` 以 支持 translate 偏移值 强制取整

### ISSUE THREAD

**Issue by solome** [ustbhuangyi/better-scroll#1077]
### What problem does this feature solve?
当诸如 `transform: translateX(0px) translateY(-617px) translateZ(1px);` 偏移值出现小数时，比如移动过程中会出现如下值`transform: translateX(0px) translateY(-617.434343px) translateZ(1px);` 时：

如果DOM 中有`<canvas>\<image>` 标签时 会出现1px 左右的偏差。如下截图所示，如果`translate`相关值均为整数则无此问题。

[偏移截图](https://vrlab-static.ljcdn.com/release/web/better-scroll-issues.adde6614.png)
<img width="600" src="https://vrlab-static.ljcdn.com/release/web/better-scroll-issues.adde6614.png"/>

可以访问页面：http://vrlab-static.ljcdn.com/release/web/better-scroll-Jitter.html 移动后，将 `translateY` 改成小数 则 会出现 1px 左右的缝隙。

Chrome\Safari 以及 iOS\Android 均能复现。

### What does the proposed API look like?
给 配置项添加个 `translateRound` 参数，在设置  `transform: translateX(0px) translateY(-617px) translateZ(1px);` 时取整。

**Comment by theniceangel** [comment]
看样子是 CSS 的问题，可能会有独特的 CSS 解决方案，bs 不会提供 translateRound 配置项，不过你可以通过钩子来解决这个问题。

```js
bs.scroller.translater.hooks.on('beforeTranslate', (transformStyle, point) => {
    transformStyle[1] = `translateY(${Math.round(point.y)}px)`
})
```

**Comment by solome** [comment]
@theniceangel 目前没找到 独特的 CSS 解决方案，不过您推荐的 钩子 方式也能解决我的问题。

谢谢~
