### ISSUE TITLE
Unable to know when the scrollbar ends scrolling

### ISSUE THREAD

**Issue by DIYgod** [ustbhuangyi/better-scroll#1080]
### Version
2.0.4

### Reproduction link
[https://codesandbox.io/s/thirsty-thunder-bew3w?file=/src/App.vue](https://codesandbox.io/s/thirsty-thunder-bew3w?file=/src/App.vue)

### Steps to reproduce
Dragging the progress bar.

### What is expected?
After mouseup, the scrollEnd event is triggered once, so I can know when the scrollbar ends scrolling.

### What is actually happening?
The scrollEnd event is triggered in mousemove for many times, I can't know which scrollEnd is the ture end.

---
Thanks

**Comment by theniceangel** [comment]
Can you describe your scenario requirements in more detail?

**Comment by jhmei** [comment]
I know what he means: He wants to know how to judge if the scroll is completely over (no more data). @theniceangel

**Comment by jhmei** [comment]
you can refer to [https://github.com/ustbhuangyi/better-scroll/issues/67](url) @DIYgod

**Comment by jhmei** [comment]
#67

**Comment by DIYgod** [comment]
> Can you describe your scenario requirements in more detail?

The scenario is that I want to exec some callbacks when the scrollbar ends scrolling, but I can't know when it is.

**Comment by theniceangel** [comment]
will fix it in next patch version

**Comment by theniceangel** [comment]
fixed at v2.2.0
