### ISSUE TITLE
已正确初始化，无滚动效果

### ISSUE THREAD

**Issue by StringKe** [ustbhuangyi/better-scroll#1081]
### Version
2.0.4

### Reproduction link
[https://codesandbox.io/s/peaceful-https-sucwh?file=/src/App.vue](https://codesandbox.io/s/peaceful-https-sucwh?file=/src/App.vue)

### Steps to reproduce
重现链接中已经提供，是包裹元素的问题么？

### What is expected?
正确工作

### What is actually happening?
无法滚动

**Comment by StringKe** [comment]
@ustbhuangyi

**Comment by chenyulun** [comment]
我的2.0.4加web component组件都成功了，这样的问题最好对比一下官方案例，自己研究

**Comment by ArvinHsieh** [comment]
拿掉 .full 樣式內的 height: 100%;

**Comment by theniceangel** [comment]
@StringKe .full 元素的高度并没有撑开。

![image](https://user-images.githubusercontent.com/25956811/95267287-786d1300-0867-11eb-811c-0570e6893cb0.png)

**Comment by swliu920322** [comment]
https://codesandbox.io/s/lucid-rhodes-2ybee?file=/src/App.vue

**Comment by swliu920322** [comment]
https://codesandbox.io/s/lucid-rhodes-2ybee?file=/src/App.vue,

**Comment by swliu920322** [comment]
https://codesandbox.io/s/lucid-rhodes-2ybee?file=/src/App.vue
一开始数据量不够，后来数据更新后，超出了范围后，就无法滚动了，
一开始够的话是可以滚动的，这个应该怎么解决
