### ISSUE TITLE
useTransform is not implemented?

### ISSUE THREAD

**Issue by whitecolor** [ustbhuangyi/better-scroll#1084]
In iScroll there was an option `useTransform` which made iScroll use `left`/`top` props instead of `transform/translate`. So it is not implemented, wonder why? It is really useful on desktop browsers for example on windows where chrome/firefox while css translating is blurring the content, and when `left/top` are used content is not blurred. Desktop performance usually is not suffering, but the visual effect is much better. 

I tried to implement it using `beforeTranslate` hook, but it allows only to affect `transform` style. And using hacky method like: 

```js
     hooks.on('beforeTranslate', (transformStyle, point) => {
         transformStyle.splice(0, Infinity)
         Promise.resolve().then(() => {
           const wrapper = elm.children[0] as HTMLElement
           wrapper.style.left = point.x + 'px'
           wrapper.style.top = point.y + 'px'
         })        
      })
```

doesn't seem to work well.

**Comment by whitecolor** [comment]
Normalizing coordinate to integer value solves the blurry effect issue mostly, though not completely comparing with using `left/top`.

**Comment by theniceangel** [comment]
The reason that drop `left / top` implementation in v2 is performance and users do not have to bear the burden of additional configuration, as you mentioned, you can use `beforeTranslate ` hook to normalize coordinate to integer value to solve your troubles

**Comment by whitecolor** [comment]
Ok, but still the effect on the desktop is a little bit different.

**Comment by wclr** [comment]
@theniceangel 

I would encourage you to reconsider this, and an option to transform position using left/top as `iscroll` does. Have to rollback to `iscroll`, because the visual effect of blurring in webkit based browsers on windows are barely acceptable. Normalizing coors doesn't save.
