### ISSUE TITLE
[New Feature] 如何讓 scrollTo 結束後，不要觸發 scrollEnd

### ISSUE THREAD

**Issue by ArvinHsieh** [ustbhuangyi/better-scroll#1085]
### What problem does this feature solve?
目前使用版本: 2.0.4

場景: 擴充卷軸自動置底功能

請問如何能讓當自行呼叫 scroll.scrollTo(0, scroll.maxScrollY, 0, undefined); 時，能夠不要觸發 scrollEnd 事件? 我的情況是手動移動卷軸置底時 scrollEnd 中會觸發取得資料行為，但在監測 doc 異動時，呼叫 scrollTo 移動置底的情況下不要觸發 scrollEnd 避免額外撈取資料。

在 2.0.0-beta.10 版本時，呼叫 scrollTo 時不會觸發 scrollEnd，但升級 2.0.4 版本後會觸發 scrollEnd，是否能夠在 scrollTo 增加參數控制是否要觸發 scrollEnd 事件。

謝謝

### What does the proposed API look like?
scrollTo(x, y, time, easing, extraTransform, triggerEnd)

**Comment by theniceangel** [comment]
在 scrollEnd 的事件内部，应该是你自己去实现对应的逻辑吧

**Comment by ArvinHsieh** [comment]
有使用以下方式判斷
scroll.on("scrollEnd", () => { if (flag) return; });
然後
flag=false;
scroll.scrollTo(...);
flag=true;

但請問這樣能保證 flag 更改 true 之前會先觸發 scrollEnd 嗎? 謝謝
