### ISSUE TITLE
移动设备多触点操作不回弹

### ISSUE THREAD

**Issue by jombLiu** [ustbhuangyi/better-scroll#1087]
1. 单手下拉一段距离后
2. 再用一只手指轻触屏幕
3. 两手同时离开屏幕，页面不回弹（顶部下拉/底部上拉都是此效果
4. 需要再次上拉或者下滑页面才能恢复正常

**Comment by jsmakshi** [comment]
感觉和我提的一样
目前我不停下拉刷新，点击事件失效
需要再次上拉或者下滑页面才能恢复正常

**Comment by theniceangel** [comment]
will fix at next version

**Comment by theniceangel** [comment]
除了 zoom 的场景支持多指，其他场景暂不考虑，否则底层都需要发生全面的改动，成本太高
