### ISSUE TITLE
Zoom插件双指缩放时有概率报错

### ISSUE THREAD

**Issue by anyuxuan** [ustbhuangyi/better-scroll#1090]
【版本】2.0.4

【问题】从我们内部的埋点监控系统上报的数据发现，有用户出现以下报错
- Uncaught TypeError: Cannot read property 'x' of undefined （e.zoom）
- Uncaught TypeError: Cannot read property 'baseScale' of undefined （e._zoomTo）

【期望】是否可以给Zoom Class中的origin属性默认设置为{}

**Comment by theniceangel** [comment]
有复现的repo么

**Comment by anyuxuan** [comment]
> 有复现的repo么

这个还真的没有复现的代码，同时这个zoom在浏览器里也没法模拟双指缩放，我们每天大概有5% ~ %10的用户有报这些错，普遍都是安卓手机（比如有机型PCEM00、vivo X21i A、V1832A、Huawei P10等）
