### ISSUE TITLE
pulldown插件，下拉刷新后，click事件失效

### ISSUE THREAD

**Issue by jsmakshi** [ustbhuangyi/better-scroll#1092]
### Version
2.0.5

### Reproduction link
[https://better-scroll.github.io/docs/zh-CN/plugins/pulldown.html#%E4%BB%8B%E7%BB%8D](https://better-scroll.github.io/docs/zh-CN/plugins/pulldown.html#%E4%BB%8B%E7%BB%8D)

### Steps to reproduce
1、官网案例代码
2、pulldown 下拉刷新（不停说刷几次），点击事件失效
3、要手动滚动一下页面才能点击，就感觉错位似的

### What is expected?
下拉刷新后点击事件正常

### What is actually happening?
目前点击事件失效

---
尽快修复，谢谢

**Comment by theniceangel** [comment]
@jsmakshi 测试了没问题啊，你能否给个 demo？

**Comment by jsmakshi** [comment]
1、官网代码：https://better-scroll.github.io/examples/#/pulldown/
2、给列表添加点击事件，
3、不停刷新10次（刷新中也继续下拉）
4、点击列表没有反应，滚动一下页面再点击就可以了

**Comment by theniceangel** [comment]
@jsmakshi 配置了 click 为 true 么

**Comment by bunnybunny3** [comment]
请问最后解决了么，我也遇到了。偶遇点击事件失效，要重新滚动下页面才可以点击
