### ISSUE TITLE
当滚动区域内部有内容需要原生滚动时, preventDefaultException属性无效

### ISSUE THREAD

**Issue by rabbitao** [ustbhuangyi/better-scroll#1093]
### Version
2.0.5

### Reproduction link
[https://codesandbox.io/s/awesome-northcutt-i8bp6?file=/index.html](https://codesandbox.io/s/awesome-northcutt-i8bp6?file=/index.html)

### Steps to reproduce
1. 外层使用bs来创建滚动
2. 每一个条目内部有较长内容需要使用原生滚动
3.给需要原生滚动的元素设置preventDefaultException指定的class

### What is expected?
使用移动端浏览.
每一个子元素内部的内容可以触发浏览器原生滚动

### What is actually happening?
内部元素无法触发原生滚动

**Comment by theniceangel** [comment]
@rabbitao preventDefault 设置为 false
