### ISSUE TITLE
[New Feature] slider插件增加禁用手势配置

### ISSUE THREAD

**Issue by minikey** [ustbhuangyi/better-scroll#1097]
### What problem does this feature solve?
在一些场景下，需要slider的自动滚动，但是禁用手势操作，当前的版本如果设置 disableTouch: true ，会导致click失效，使用起来不是特别的方便

### What does the proposed API look like?
noSwiping: boolean 禁用手势切换，但是不影响api调用切换

**Comment by theniceangel** [comment]
@minikey 调用 bs.disable()

**Comment by zjy2931** [comment]
> @minikey 调用 bs.disable()

这样api调用也不行了
