### ISSUE TITLE
[typescript] pluginAPI error

### ISSUE THREAD

**Issue by chenyulun** [ustbhuangyi/better-scroll#1099]
### Version
2.0.4

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll](https://github.com/ustbhuangyi/better-scroll)

### Steps to reproduce
在ts环境注入部分带api的插件，ts实例里面提示的api路径有问题
node_modules/@better-scroll/pull-down/dist/types/index.d.ts
```ts
interface CustomAPI {
pullUpLoad: PluginAPI
} 
```
应该改成
```ts
interface CustomAPI extends PluginAPI {}
```

### What is expected?
能够正确的提示插件的api方法

### What is actually happening?
比如finishPullUp方法，根据d.ts的提示是在`scroll.pullUpLoad.finishPullUp()`实际是在`scroll.finishPullUp()`

---
带api的声明文档
```ts
interface CustomAPI {
pullUpLoad: PluginAPI
} 
应该改成
```ts
interface CustomAPI extends PluginAPI {}
```
```

<!-- generated by cube-issue-helper. DO NOT REMOVE -->

**Comment by theniceangel** [comment]
![image](https://user-images.githubusercontent.com/25956811/98506743-2587e080-2297-11eb-9c6d-801fa2bb3726.png)

**Comment by chenyulun** [comment]
其实我只想收集他的类型文件名为`better-scroll-interface.d.ts`
内容如下
```ts
import BScroll, { Options, CustomOptions, CustomAPI } from '@better-scroll/core';

export * from '@better-scroll/pull-down';
export * from '@better-scroll/scroll-bar';
export * from '@better-scroll/slide';
export * from '@better-scroll/wheel';
export * from '@better-scroll/zoom';
export * from '@better-scroll/infinity';
export * from '@better-scroll/observe-dom';
export * from '@better-scroll/nested-scroll';
export * from '@better-scroll/movable';
export * from '@better-scroll/pull-up';

export { EaseItem, EventEmitter, EventRegister } from '@better-scroll/shared-utils';
export { TranslaterPoint } from '@better-scroll/core/dist/types/translater';

export type BscrollOptions = Options;

export type BScrollInterface = BScroll & CustomAPI;
```
js通过异步加载，我只要定义类型就行了，是吧？
![image](https://user-images.githubusercontent.com/15979948/98508907-46eacb80-229b-11eb-9fdd-4f54129f0070.png)
![image](https://user-images.githubusercontent.com/15979948/98509011-76013d00-229b-11eb-8af0-591505b7e2ff.png)

```ts
export type BScrollInterface = BScroll & CustomAPI;
```
如果我这里不写`& CustomAPI`插件里面的方法都不提示，
或者我应该怎么提供正确的声明？

**Comment by chenyulun** [comment]
![image](https://user-images.githubusercontent.com/15979948/98511046-202e9400-229f-11eb-93a6-267f180c659a.png)
![image](https://user-images.githubusercontent.com/15979948/98511108-3a687200-229f-11eb-8569-4384559ff330.png)

使用变量传入就没有提示了，有没有机会给bs定义自己收集的类型

**Comment by theniceangel** [comment]
不理解为啥需要异步加载bs，第二个变量传入你可以先把 `Options & PulldownRefreshOptions` 的类型去掉试试

**Comment by chenyulun** [comment]
![image](https://user-images.githubusercontent.com/15979948/98624568-12354d80-2349-11eb-85a9-a0bcf2c53fa5.png)

这样是可以提示了，但是入参报错

**Comment by chenyulun** [comment]
异步场景，应该还是有的吧，先改成这样先用着
```ts
import BScroll, { Options, CustomOptions, CustomAPI } from '@better-scroll/core';
import { DefOptions } from '@better-scroll/core/dist/types/Options';
import { UnionToIntersection } from '@better-scroll/core/dist/types/utils/typesHelper';

export * from '@better-scroll/pull-down';
export * from '@better-scroll/scroll-bar';
export * from '@better-scroll/slide';
export * from '@better-scroll/wheel';
export * from '@better-scroll/zoom';
export * from '@better-scroll/infinity';
export * from '@better-scroll/observe-dom';
export * from '@better-scroll/nested-scroll';
export * from '@better-scroll/movable';
export * from '@better-scroll/pull-up';

declare type ExtractAPI<O> = {
  [K in keyof O]: K extends string ? DefOptions[K] extends undefined ? CustomAPI[K] : never : never;
}[keyof O];

export { EaseItem, EventEmitter, EventRegister } from '@better-scroll/shared-utils';
export { TranslaterPoint } from '@better-scroll/core/dist/types/translater';
export type BscrollOptions = Options;

export type BScrollInterface = BScroll & UnionToIntersection<ExtractAPI<{pullDownRefresh: true, slide: true, wheel: true, zoom: true, movable: true, pullUpLoad: true}>>
```

**Comment by theniceangel** [comment]
@chenyulun 
![image](https://user-images.githubusercontent.com/25956811/98626481-d69c8280-234c-11eb-8de9-7420463f9380.png)

**Comment by theniceangel** [comment]
@chenyulun 异步场景也应该是 bs 这个库是跟随着你的路由组件打包到另外一个 chunk，而不是这个库做成一个 chunk
