### ISSUE TITLE
当从另一个页面进入这个页面的时候，下面能超出底线，如果是在这个页面刷新就不会有这种效果？这是什么原因

### ISSUE THREAD

**Issue by 847721464** [ustbhuangyi/better-scroll#11]
![9454c 5hhz vaw8yacq5u9f](https://cloud.githubusercontent.com/assets/20931278/21873221/2632189e-d8a8-11e6-9cdf-5dcf610d95b2.png)

**Comment by ustbhuangyi** [comment]
如果 dom 结构变了，需要重新调用 scroll.refresh() 方法重新计算
