### ISSUE TITLE
wheel有机会进入死循环

### ISSUE THREAD

**Issue by chenyulun** [ustbhuangyi/better-scroll#1100]
### Version
1.15.0

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll](https://github.com/ustbhuangyi/better-scroll)

### Steps to reproduce
很奇怪的是我之前用的1.12.6版本好像怎么搞都不会，
升级`1.15.0`后开始有是循环的现象，观察源码，希望共同分析一下原因，

### What is expected?
希望selectedIndex的计算提前到scrollEnd事件之前，这样在`.getSelectedIndex()`方法就不会获取到老的`selectedIndex`

### What is actually happening?
开启wheel的时候： 

1.监听
```js
wheel.on('scrollEnd', () => {
            console.log("_createWheel -> wheel.getSelectedIndex")
            this.$emit(EVENT_CHANGE, i, wheel.getSelectedIndex()) // 31
          })
```
2.获取到wheel.getSelectedIndex()重新设置到数据里面， 

3.由于内部的计算在selectedIndex计算在scrollEnd事件后面，这时候计算到的selectedIndex为37，
数据有变动又在非同步状态（`this.$nextTick`）下wheel.wheelTo(31); 

4.内部无动画执行了scrollTo方法，由于无动画，直接执行`scrollEnd`事件，这时候监听器获取到的`selectedIndex`变成37，内部在变化为31

5.开始进入是循环阶段

---
我期望内部的`selectedIndex`计算在`scrollEnd`事件之前计算，方便在事件回调里面执行`.getSelectedIndex()`获取正确的`selectedIndex`

如果2.0.5也存在风险，能不能看看具体情况修复一下，
1.x.x不维护了的话我只能在`scrollEnd`延迟一点事件获取`selectedIndex`
```js
wheel.on('scrollEnd', () => {
            console.log("_createWheel -> wheel.getSelectedIndex")
            // 内部设置selectedIndex在scrollEnd事件之后，有风险进去死循环，延迟一点时间获取getSelectedIndex
            setTimeout(() => {
              this.$emit(EVENT_CHANGE, i, wheel.getSelectedIndex())
            }, 0)
          })
```

**Comment by chenyulun** [comment]
看到有2个地方设置`selectedIndex`的值，
一个在`BScroll.prototype._end`里面顺序没有问题的；
```js
if (this.options.wheel) {
      this.selectedIndex = this._findNearestValidWheel(this.y).index;
    }

    this.trigger('scrollEnd', {
      x: this.x,
      y: this.y
    });
```
一个在`BScroll.prototype.scrollTo`方法里面
```js

    if (!time || this.options.useTransition) {
      this._transitionTimingFunction(easing.style);
      this._transitionTime(time);
      this._translate(x, y);

      if (time && this.options.probeType === PROBE_REALTIME) {
        this._startProbe();
      }
      if (!time && !isSilent) {
        // don't trigger resetPosition when zoom feature is open, fix #748
        if (this.options.zoom) return;
        this.trigger('scroll', {
          x: x,
          y: y
        });
        // force reflow to put everything in position
        this._reflow = document.body.offsetHeight;
        if (!this.resetPosition(this.options.bounceTime, ease.bounce)) {
          this.trigger('scrollEnd', {
            x: x,
            y: y
          });
        }
      }

      if (this.options.wheel) {
        this.selectedIndex = this._findNearestValidWheel(y).index;
      }
```
这里的计算在`scrollEnd`事件之后,可能就是这里引发的死循环问题吧

**Comment by theniceangel** [comment]
1.x 版本已经不维护了。

**Comment by chenyulun** [comment]
@theniceangel 我知道1.x不维护了，你确定你的2.x不会有这个问题就行了，
