### ISSUE TITLE
scrollEnd 事件触发多次

### ISSUE THREAD

**Issue by zhuping** [ustbhuangyi/better-scroll#1102]
### Version
2.0.5

### Reproduction link
[https://github.com/zhuping/better-scroll-bug-report](https://github.com/zhuping/better-scroll-bug-report)

### Steps to reproduce
联动选择增加到3列

1、省份选择河北省，市选择唐山市，此时 scrollEnd 事件都还只执行1次

2、省份选择北京市，此时 scrollEnd 事件触发了2次

### What is expected?
触发一次 scrollEnd 时间

### What is actually happening?
触发了两次

**Comment by theniceangel** [comment]
测试的时候并没有出现

**Comment by zhuping** [comment]
![iconfont](https://user-images.githubusercontent.com/1574767/99203906-f7525580-27ee-11eb-9d55-cdf4284ea47b.gif)

**Comment by theniceangel** [comment]
@zhuping 因为第二列也滚动了

**Comment by zhuping** [comment]
@theniceangel ok，了解了
