### ISSUE TITLE
wheel 插件首次渲染样式问题

### ISSUE THREAD

**Issue by zhuping** [ustbhuangyi/better-scroll#1103]
### Version
2.0.5

### Steps to reproduce
默认有 `rotate` 弯曲处理，但是首次渲染的时候，并没有作用上这个效果，导致我滑动了第一栏后，两列的样式不一致
![image](https://user-images.githubusercontent.com/1574767/99060204-a79b4080-25da-11eb-9771-edabecdbb8a4.png)

### What is expected?
首次渲染可作用弯曲效果

### What is actually happening?
没有效果

**Comment by theniceangel** [comment]
没太懂，截图的这个效果不是预期的么

**Comment by zhuping** [comment]
山西是有加了弯曲效果，唐山没有弯曲效果

**Comment by theniceangel** [comment]
2.1 版本会完善这个 feature

**Comment by theniceangel** [comment]
fixed at v2.1.0
