### ISSUE TITLE
关于什么时候才调用 refresh()

### ISSUE THREAD

**Issue by ZW-L** [ustbhuangyi/better-scroll#1105]
如题，我对 refresh() 的执行时机有比较大的疑问：
+ 在 `$nextTick()` 中调用是无效的：
```js
this.$nextTick(_ => {
  this.$refs.scroll.refresh()
})
```
+ 在 `setTimeout` 中调用收到 delay 的影响：
```js
setTimeout(() => {
  this.$refs.scroll.refresh()
}, 100)    // 有时候 100 不行，又要继续上调
```

再有的是，频繁地在父组件中调用 `refresh()`，会增加组件的耦合度，难道没有更好的解决方法吗？

**Comment by theniceangel** [comment]
确保 BetterScroll 的 wrapper DOM 以及它的子元素已经渲染
