### ISSUE TITLE
使用better-scroll在微信打开页面无法长截屏

### ISSUE THREAD

**Issue by Zhuxh129** [ustbhuangyi/better-scroll#1107]
![image](https://user-images.githubusercontent.com/74597362/99380545-13e0b180-2905-11eb-95b0-7d70acbc47ba.png)
中间内容被截取了
![image](https://user-images.githubusercontent.com/74597362/99380878-7c2f9300-2905-11eb-820f-b2ca262e7f6c.png)

**Comment by theniceangel** [comment]
这个跟 bs 没啥关系吧

**Comment by Zhuxh129** [comment]
是有影响的

**Comment by theniceangel** [comment]
> 是有影响的

是不是长截屏的底层原理是代码自动操纵滚动条，导致你被卷去的那一部分被滚动了？

**Comment by Zhuxh129** [comment]
长截屏不就是滚动截屏嘛，我觉得你说的也有道理，不知道怎么解决呢

**Comment by Cecilia-li** [comment]
后来解决了吗
