### ISSUE TITLE
[New Feature] 使用 zoom 组件的时候，能不能 content 水平居中

### ISSUE THREAD

**Issue by ideal123** [ustbhuangyi/better-scroll#1110]
### What problem does this feature solve?
在使用 zoom 的时候，如果 content 小于 wrapper，content 是贴在左上方的，能不能做到水平或者垂直居中？

### What does the proposed API look like?
通过配置项，做到像使用 movable 移动到中部的效果

**Comment by ideal123** [comment]
小的时候，直接水平位置居中，不能左右移动

**Comment by theniceangel** [comment]
这种情况应该是结合 zoom 和 movable 插件，movable 有两个例子，你可以先参考下

**Comment by ideal123** [comment]
的确 zoom 和 movable 一起使用，在 content 小于 wrap 宽度的时候，调用 putAt 让 content 水平居中了，但是它能左右拖动

目的是想要这个情况不能拖动，只能放大、缩小后能水平居中

我尝试改动过 movable 插件中的代码来达到上面要求，但是这个时候 content 中的元素的 click 事件失效了

```js
const computeBoundary = (boundary: Boundary, behavior: Behavior) => {
      if (boundary.maxScrollPos > 0) {
        // content is smaller than wrapper，在 content 小的时候居中
        boundary.minScrollPos = (behavior.wrapperSize + behavior.contentSize) / 2;
        boundary.maxScrollPos =  (behavior.wrapperSize - behavior.contentSize) / 2;
      }
    }
```

**Comment by theniceangel** [comment]
目前不支持，只能新增插件来实现
