### ISSUE TITLE
slide缺少pausePlay和startPlay方法

### ISSUE THREAD

**Issue by chenyulun** [ustbhuangyi/better-scroll#1111]
### Version
2.0.4

### Reproduction link
[https://better-scroll.github.io/examples/#/slide/banner](https://better-scroll.github.io/examples/#/slide/banner)

### Steps to reproduce
`this.slide.on("slideWillChange", (function(e) {
                    t.currentPageIndex = e.pageX
                }`
在`t.currentPageIndex`上面打断点
控制台输出
```js
t.slide.startPlay // undefined
t.slide.pausePlay //undefined
```

### What is expected?
希望正常使用这个2个方法

### What is actually happening?
slide插件未注入pausePlay和startPlay方法

**Comment by chenyulun** [comment]
构建处理的代码里面为
```js
var sourcePrefix = 'plugins.slide';
var propertiesMap = [
    {
        key: 'next',
        name: 'next'
    },
    {
        key: 'prev',
        name: 'prev'
    },
    {
        key: 'goToPage',
        name: 'goToPage'
    },
    {
        key: 'getCurrentPage',
        name: 'getCurrentPage'
    }
];
```
很明显缺少了
```js
    {
        key: 'startPlay',
        name: 'startPlay'
    },
    {
        key: 'pausePlay',
        name: 'pausePlay'
    },
```
主动补充了这2个方法代理后，发现第二个问题：
```js
swiper.on('slideWillChange', page => {
            console.log('🚀 ~ file: swiper.tsx ~ line 145 ~ Swiper ~ _initSwiper ~ slideWillChange', page);
            setTimeout(() => {
                swiper.pausePlay();
            }, 100);
            // currentPageIndex = page.pageX
        });
```

动画过程中不能暂停自动滚动，只能在动画停止后执行`swiper.pausePlay();`才有效

原因是因为下一次滚动绑定到了scrollEnd事件上了；执行停止后，滑动一屏，继续进入循环，next方法也会进入循环
我以为的停止自动循环是指随时可以停止（如有动画过程，执行完成，等于autoplay设置为false

这样的话只能手动修改`autoplay`为false才能阻止掉后续触发scrollEnd事件执行startPlay里面的next

**Comment by theniceangel** [comment]
@chenyulun pausePlay 只是针对于 autoplay，不会停止当前的动画，如果在动画过程中强制停止动画，这个是基于什么需求？如果要支持这种能力，我们内部还得做自动吸附的能力，因为可能当前的动画位置不是一个合理的 pageIndex

**Comment by theniceangel** [comment]
v2.0.6 代理了上述两个方法

**Comment by chenyulun** [comment]
> @chenyulun pausePlay 只是针对于 autoplay，不会停止当前的动画，如果在动画过程中强制停止动画，这个是基于什么需求？如果要支持这种能力，我们内部还得做自动吸附的能力，因为可能当前的动画位置不是一个合理的 pageIndex

暂时可能没这个场景，先不管了，谢谢了
