### ISSUE TITLE
[New Feature] Flexbox demo example

### ISSUE THREAD

**Issue by d9k** [ustbhuangyi/better-scroll#1114]
### What problem does this feature solve?
Please provide example of better-scroll usage with flexbox layout.

### What does the proposed API look like?
I was able to use better-scroll for flexbox layout with following code:

template:

```
<div class="wrapper">
  <div class="content">
    <span class="item"></span>
    <span class="item"></span>
    ...
  </ul>
</div>
```

styles:

```
.wrapper {
  display: block;
  overflow-x: hidden;
  width: 100%
}

.content {
  display: inline-flex;
  min-width: 100%;
}

.item {
  min-width: 200px; 
  flex-grow: 1;
  flex-shrink: 0;
}
```

js:

```
import BetterScroll from 'better-scroll'

let betterScroll = new BetterScroll('.wrapper', {
  scrollX: true,
  scrollY: false,
})
```

**Comment by theniceangel** [comment]
@d9k Can you provide a repo which failed to use BetterScroll. The code as above works well with BetterScroll.
