### ISSUE TITLE
代理事件的target希望兼容composedPath

### ISSUE THREAD

**Issue by chenyulun** [ustbhuangyi/better-scroll#1118]
### Version
2.0.6

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll](https://github.com/ustbhuangyi/better-scroll)

### Steps to reproduce
在web components标签中点击事件，不能正确模拟当前标签的事件
比如在滚动里面
```html
<my-comp><span>span点击区域</span></my-comp>
```
然后在body绑定事件
```js
document.body.addEventListener('click',(event) => {console.log(event); console.log(event.composedPath())})
```
点击span标签后，
event.target指向`<my-comp></my-comp>`，
而event.composedPath()列表是`[span, document-fragment, mp-comp, body, html.hydrated, document, Window]`
第一个sapn是正确的

### What is expected?
期望正确代理点击click和tap事件

### What is actually happening?
在滚动组件里面嵌套web components标签里面，标签里面的元素点击事件的e.target永远指向监听路径中第一个遇到的web components标签，
#[Event事件](https://developer.mozilla.org/zh-CN/docs/Web/API/Event/composedPath)事件里面有一个composedPath方法可以获取到正确的点击元素，但是现在e.target指向的web components,不能穿透

---
经过测试chrome高版本的event自己定义了一个path数组，其他浏览器没有，但是composedPath是标准属性，应该能正确表达点击的冒泡过程，是不是可以把
```js
e.target.dispatchEvent(ev);
```
改为
```js
((e.composedPath && e.composedPath()[0]) || e.target).dispatchEvent(ev);
```

**Comment by chenyulun** [comment]
还有2个问题顺便提一下，
1. `slide`开启的时候如果设置`observeDOM`为`true`会有死循环的现象，不知道你们有没有遇见过？，
2. 滚动元素能不能跳过`slot`标签，在`web components`里面开启`showdom`会保留`slot`标签，纯滚动的场景还好，可以忽略，但是在`slide`的案例，只能检查到一屏的`slot`,其实列表在`slot`的`children `里面，
```html
<div class="slide-banner">
    <div class="banner-wrapper">
      <div class="slide-banner-wrapper" ref="slide">
        <div class="slide-banner-content">
           <slot>
              <div v-for="num in nums" class="slide-page" :class="'page' + num" :key="num">page {{num}}</div>
           </slot>
        </div>
      </div>
    </div>
  </div>
```
希望better-scroll对web components支持更好，点赞，我是探索者...

**Comment by theniceangel** [comment]
1. 不能正确模拟当前标签的事件：希望提供一个 demo 我回归下
2. slide 开启设置 observeDOM 为 true 会有死循环的现象，我们没遇见过，你可以提供一个简单的 demo，提供下复现步骤
3. 提供下 demo

**Comment by chenyulun** [comment]
1.关于这个问题：可以看一下这里(https://zh.javascript.info/shadow-dom-events)，很详细的说明了target和冒泡的问题；
我们的better-scroll的代理事件，问题其实有2个：1.不是正确的target,2:click事件`composed`默认的是`true`,可以传统到shadowDOM,自定义事件的`composed`默认的是`false`,没办法冒泡出去shadowDOM;需要设置自定义事件的`composed: true`比如
```js
var ev =new CustomEvent('click',{bubbles: true, detail: 2, composed: true})
```
新属性的兼容性(https://caniuse.com/?search=CustomEvent)
但是我们的better-scroll使用的是已经废弃的老属性https://developer.mozilla.org/zh-CN/docs/Web/API/Event/initEvent,可能没办法配置` composed: true`
网站案例可能不能给您发送，给我截图你看一下
每一次点击都是在shadowDOM里面的元素，发出自定义事件的时候，丢失了路径
![image](https://user-images.githubusercontent.com/15979948/100706596-40f09200-33e4-11eb-9997-3207f434a979.png)

![image](https://user-images.githubusercontent.com/15979948/100707013-f3285980-33e4-11eb-8ad6-08b068b91ba2.png)
确实需要demo,给我你的邮箱

**Comment by theniceangel** [comment]
@chenyulun theniceangel@163.com

**Comment by chenyulun** [comment]
> @chenyulun [theniceangel@163.com](mailto:theniceangel@163.com)

已经发送了，可以看到shadowDOM里面的slot是会保留的，如果slider的时候列表是slot传进来的话，会导致识别到只有一屏的slot标签，不过我已经用其他方法避免了，使用了better-scroll的场景我没开shadow...

**Comment by chenyulun** [comment]
tap事件也做一下`CustomEvent`是否存在判断，如果存在，使用
```js
function tap(e, eventName) {
    // var ev = document.createEvent('Event');
    // ev.initEvent(eventName, true, true);
    var ev =new CustomEvent(eventName,{bubbles: true, cancelable: true, composed: true})
    ev.pageX = e.pageX;
    ev.pageY = e.pageY;
    // e.target.dispatchEvent(ev);
    ((e.composedPath && e.composedPath()[0]) || e.target).dispatchEvent(ev);
}
```

**Comment by theniceangel** [comment]
@chenyulun 我们内部讨论了一下，目前没有精力来支持 web-components，不过非常欢迎你提 pr，可以先加我的qq，471695625
