### ISSUE TITLE
嵌套滚动在iOS14失效

### ISSUE THREAD

**Issue by silhouettesia** [ustbhuangyi/better-scroll#1122]
### Version
2.0.6

### Reproduction link
[https://codesandbox.io/s/wonderful-water-426b9?file=/index.html&resolutionWidth=320&resolutionHeight=675](https://codesandbox.io/s/wonderful-water-426b9?file=/index.html&resolutionWidth=320&resolutionHeight=675)

### Steps to reproduce
两层嵌套，外层scrolly，内层scrollx，外层设置了eventPassthrough: 'horizontal'，在iOS14上，在**上下滚动后**，内层无法左右滚动（iOS14以下测试可以滚动）

### What is expected?
内层可横行滚动

### What is actually happening?
内层无法滚动

**Comment by bruceln** [comment]
同样的问题， 在IOS 14.x 上，  外层 滚动超过边缘范围(即 触发 bounce) ，内层 横向滚动 就失效。 触发点击事件后（如点击vconsole ）， 又恢复正常。

bounce: false,  momentum: false  会有好转， 但体验较差。

**Comment by theniceangel** [comment]
@bruceln @silhouettesia iOS 14的这种场景出现问题，是跟开启硬件加速的配置有关。

```diff
let bs = new BScroll(wrapper, {
    scrollY: true,
    eventPassthrough: "horizontal",
+   HWCompositing: false
});
```

**Comment by silhouettesia** [comment]
@theniceangel 
但我同时也设置了useTransition: false（#580 ），这样就又不行了

**Comment by theniceangel** [comment]
> @theniceangel
> 但我同时也设置了useTransition: false（#580 ），这样就又不行了

有什么特殊的原因要设置 useTransition 么

**Comment by bruceln** [comment]
@theniceangel  IOS 13.4 的 回弹问题吧.  14.0+ 不需要 设置 useTransition: false了吧？

**Comment by theniceangel** [comment]
> @theniceangel IOS 13.4 的 回弹问题吧. 14.0+ 不需要 设置 useTransition: false了吧？

iOS 14.x 不会有回弹问题

**Comment by theniceangel** [comment]
如果是嵌套滚动，可以尝试实例化多个bs，目前有一个插件 [nested-scroll](https://better-scroll.github.io/docs/zh-CN/plugins/nested-scroll.html)，如果使用了 eventPassthrough，你会发现你拖动 bs 的时候，页面有些时候也会被拖动

**Comment by silhouettesia** [comment]
> 如果是嵌套滚动，可以尝试实例化多个bs，目前有一个插件 [nested-scroll](https://better-scroll.github.io/docs/zh-CN/plugins/nested-scroll.html)，如果使用了 eventPassthrough，你会发现你拖动 bs 的时候，页面有些时候也会被拖动

ts下用nested-scroll报错😓

**Comment by silhouettesia** [comment]
而且即使去掉useTransition 在比较复杂的列表下还是比较卡顿 也不是每次横滑都能生效

**Comment by theniceangel** [comment]
@silhouettesia 报什么错误？ts 版本是多少？

**Comment by silhouettesia** [comment]
> @silhouettesia 报什么错误？ts 版本是多少？

TS2345: Argument of type 'typeof NestedScroll' is not assignable to parameter of type 'PluginCtor'.
  Types of parameters 'scroll' and 'scroll' are incompatible.

ts 3.9.7

**Comment by theniceangel** [comment]
![image](https://user-images.githubusercontent.com/25956811/104544357-7f73a080-5662-11eb-869d-c2d0c3281d99.png)

**Comment by theniceangel** [comment]
@silhouettesia 用最新版本的 bs，2.1.1，我这边 ts 并没有报错

**Comment by silhouettesia** [comment]
@theniceangel bs用的2.0.7，ts在3.7.5下也会报一样的错

**Comment by theniceangel** [comment]
@silhouettesia 试试最新版本

**Comment by silhouettesia** [comment]
https://codesandbox.io/s/happy-shirley-3pngn?file=/src/App.js
@theniceangel 请问我这个写的哪里有问题吗 横向完全滚不了

**Comment by theniceangel** [comment]
@silhouettesia 这个 issue 已经关了，有些时候看不到信息，有问题可以加我 qq，471695625

**Comment by theniceangel** [comment]
横向滚动不了的原因，是因为 bs 的 inner-wrapper 没有被撑开。

```diff
.bs-inner-body {
+  display: inline-flex;
-  display: flex;
  flex-wrap: nowrap;
  height: 200px;
  overflow: auto;
}
```

还有一个问题是你的 innerRef 应该使用不当，因为你多个 横向 bs 的实例都是挂在在 innerRef 上，所以我调试你的 demo 的时候，发现 innerRef 只代表了最后一个 bs-inner 元素（**实际上有多个**），由于从来没写过 react，所以具体原因我也不知道

**Comment by silhouettesia** [comment]
@theniceangel 感谢🙏 这次终于可以了
