### ISSUE TITLE
scroll-bar滚动条内容宽度或者高度计算错误

### ISSUE THREAD

**Issue by chenyulun** [ustbhuangyi/better-scroll#1124]
### Version
2.0.6

### Reproduction link
[https://better-scroll.github.io/examples/#/scrollbar/](https://better-scroll.github.io/examples/#/scrollbar/)

### Steps to reproduce
把滚动条长度设置为可视区域的一半（比可视区域小）

然后内部计算的滚动条会偏小

### What is expected?
正确计算滚动条比例

### What is actually happening?
`packages/scroll-bar/src/indicator.ts`
```ts
  private _refreshKeyValues(
    wrapperSize: number,
    scrollerSize: number,
    maxScroll: number
  ): KeyValues {
    let initialSize = Math.max(
      Math.round(
        (wrapperSize * wrapperSize) / (scrollerSize || wrapperSize || 1)
      ),
      INDICATOR_MIN_LEN
    )

    let maxPos = wrapperSize - initialSize
    // sizeRatio is negative
    let sizeRatio = maxPos / maxScroll

    return {
      initialSize,
      maxPos,
      sizeRatio,
    }
  }
```
假如是横向滚动条  

滚动条宽度 = 滚动条的宽度 * （滚动条的宽度 / 滚动总宽度）

这里计算有问题，需要改成：  

滚动条宽度 = 滚动条的宽度 * （滚动可视区域宽度 / 滚动总宽度）可以改成下面

---
`/Users/chenyulun390/github/better-scroll/packages/scroll-bar/src/indicator.ts`
```ts
  private _refreshKeyValues(
    wrapperSize: number,
    scrollerSize: number,
    maxScroll: number
  ): KeyValues {
    let initialSize = Math.max(
      Math.round(
        (wrapperSize * (scrollerSize + maxScroll)) / (scrollerSize || wrapperSize || 1)
      ),
      INDICATOR_MIN_LEN
    )

    let maxPos = wrapperSize - initialSize
    // sizeRatio is negative
    let sizeRatio = maxPos / maxScroll

    return {
      initialSize,
      maxPos,
      sizeRatio,
    }
  }
```

**Comment by chenyulun** [comment]
我有设置较短滚动条的需求，这是1.x的代码
我修改了源码重新运行的修复的结果
![image](https://user-images.githubusercontent.com/15979948/102995561-490f9d80-455c-11eb-8ce5-c32171d2e621.png)

**Comment by theniceangel** [comment]
这个没太明白，如果可以的话，可以加我，周末有空的时候可以聊一下

**Comment by chenyulun** [comment]
1. 定义说明  
滚动总长度区域：`scrollerSize`  
最大可滚动长度（负值）：`-maxScroll`  
滚动可视区域= 滚动总长度区域 + 最大可滚动长度： `scrollerSize + maxScroll`  
滚动条容器长度： `wrapperSize`
滚动可视与总长度比例= 滚动可视区域 / 滚动总长度区域:  `(scrollerSize + maxScroll)/scrollerSize` 
滚动条(`initialSize`)长度=滚动条容器长度 * 滚动可视与总长度比例 : `wrapperSize * (scrollerSize + maxScroll)/scrollerSize`
2. 问题点  
由于默认的滚动条容器长度（`wrapperSize`） = 滚动可视区域（ `scrollerSize + maxScroll`  ）
所以原来的计算滚动条长度变成: 
```ts
let initialSize = Math.max(
      Math.round(
        (wrapperSize * wrapperSize) / (scrollerSize || wrapperSize || 1)
      ),
      INDICATOR_MIN_LEN
    )
```
3. 错误场景，假如滚动条容器主动设置小于滚动可视区域
初始化设置样式
```style
.bscroll-horizontal-scrollbar {
    width: 36px;
    margin-left: -18px;
    left: 50% !important;
}
```
这个时候`wrapperSize`并不等于滚动可视区域长度，不能用`wrapperSize`代替滚动可视区域长度
还原原来的计算方式，应该是
```ts
let initialSize = Math.max(
      Math.round(
        wrapperSize * (scrollerSize + maxScroll) / (scrollerSize || wrapperSize || 1)
      ),
      INDICATOR_MIN_LEN
    )
```

**Comment by theniceangel** [comment]
refactor at v2.2.0
