### ISSUE TITLE
core里面计算的滚动可视区域包括了边框

### ISSUE THREAD

**Issue by chenyulun** [ustbhuangyi/better-scroll#1125]
### Version
2.0.6

### Reproduction link
[https://better-scroll.github.io/examples/#/scrollbar/](https://better-scroll.github.io/examples/#/scrollbar/)

### Steps to reproduce
案例里面打断点，全局保存一个bs
```js
var bs = this.bscroll
```
实际滚动区域高度是上边框1px,下边框1px滚动内容770px
实际计算
```js
bs.maxScrollY
-708
bs.scrollerHeight
1480
console.log('滚动容器上1px边框，内容770px,下1px边框，实际滚动条区域为770px,bs实际计算滚动可视高度：',bs.scrollerHeight   bs.maxScrollY, 'px')
VM2405:1 滚动容器上1px边框，内容770px,下1px边框，实际滚动条区域为770px,bs实际计算滚动可视高度： 772 px
```

### What is expected?
正确计算滚动可视区域的宽/高度

### What is actually happening?
应该是使用了
`packages/shared-utils/src/dom.ts`
文件里面的`getRect`方法
```js
export function getRect(el: HTMLElement): DOMRect {
  /* istanbul ignore if  */
  if (el instanceof (window as any).SVGElement) {
    let rect = el.getBoundingClientRect()
    return {
      top: rect.top,
      left: rect.left,
      width: rect.width,
      height: rect.height,
    }
  } else {
    return {
      top: el.offsetTop,
      left: el.offsetLeft,
      width: el.offsetWidth,
      height: el.offsetHeight,
    }
  }
}
```
里面获取宽度或者高度采用的是`offsetHeight`

---
如果样式使用了box-sizing: border-box;border: 10px solid;  
使用`clientHeight`能正确获取到内容高度  
使用`offsetHeight`获取到的包括了内容 边框  
能不能修正一下  
fix方法：  
现在我们的处理方式就是不在包裹容器里面设置边框；  
但是你们的案例里面都使用了边框，不然得多写一个DIV来设置边框

**Comment by chenyulun** [comment]
![image](https://user-images.githubusercontent.com/15979948/102995409-eb7b5100-455b-11eb-8a53-0f345b805eeb.png)
我的实际场景虽然原来我只设置了1px,为了体现没有滚动完全，夸张设置了10px;
这里可以看到我滚动到了最右边，还是有一部分隐藏掉了
![image](https://user-images.githubusercontent.com/15979948/102995561-490f9d80-455c-11eb-8ce5-c32171d2e621.png)

**Comment by chenyulun** [comment]
`packages/scroll-bar/src/indicator.ts`
里面获取的宽度或者高度都是采用`clientHeight`或者`clientWidth`
```ts
  _getKeysMap(): KeysMap {
    if (this.direction === Direction.Vertical) {
      return {
        hasScroll: 'hasVerticalScroll',
        size: 'height',
        wrapperSize: 'clientHeight',
        scrollerSize: 'scrollerHeight',
        maxScroll: 'maxScrollY',
        pos: 'y',
        pointPos: 'pageY',
        translate: 'translateY',
      }
    }
    return {
      hasScroll: 'hasHorizontalScroll',
      size: 'width',
      wrapperSize: 'clientWidth',
      scrollerSize: 'scrollerWidth',
      maxScroll: 'maxScrollX',
      pos: 'x',
      pointPos: 'pageX',
      translate: 'translateX',
    }
  }
```
是不是`@better-scroll/core`里面有特殊场景需要计算边框？

**Comment by theniceangel** [comment]
@chenyulun 这个是 1.x 当时解决一下问题遗留下来的代码，我在 2.1 版本会优化这里

**Comment by theniceangel** [comment]
fixed at v2.1.0
