### ISSUE TITLE
怎么没看到有提供滚动到底部时的钩子函数呢？

### ISSUE THREAD

**Issue by zengguangzhong** [ustbhuangyi/better-scroll#1132]
### What problem does this feature solve?
需求是这样的：在一个有两页的作品里，第一页里有个better-scroll列表，想在列表滚动到底部的时候，自动翻页到第二页去。

这里需要有两个支持：
1、用户滚动到底时的钩子函数
2、重置 new BetterScroll 里的配置 ：stopPropagation 修改为 false 。

### What does the proposed API look like?
期待提供两个api：
1、onScrollAtBtton
2、updateConfig

**Comment by theniceangel** [comment]
用 pullup 插件就可以实现你的第一个需求，第二个重置配置是什么场景
