### ISSUE TITLE
网络请求下，使用BScroll无法滚动，解决原因?

### ISSUE THREAD

**Issue by 3320957750** [ustbhuangyi/better-scroll#1133]
我有很多网络请求模块，Bscroll  无法获取准确的 content 的高度，那么 wrapper 就无法进行滚动，那么如何解决这个问题呢？

![Snipaste_2020-12-28_00-30-51](https://user-images.githubusercontent.com/62078865/103175400-b7c66100-48a4-11eb-9b22-03f884e52398.png)
![Snipaste_2020-12-28_00-36-03](https://user-images.githubusercontent.com/62078865/103175401-b7c66100-48a4-11eb-8c01-0f6db9598e98.png)

**Comment by 3320957750** [comment]
页面一加载 Bscroll就会获取到 页面的高度，而网络请求是延迟到达，所以导致网络请求的模块数据的高度无法加载到 Bscroll的滚动里面，导致页面无法正常加载 滚动，content 里面只有一开始就有的数据，获取不到网络请求的高度，请问如何解决此问题

**Comment by h723999742** [comment]
等图片加载完后调用refresh() 方法



---原始邮件---
发件人: "幕念"<notifications@github.com&gt;
发送时间: 2020年12月28日(周一) 凌晨0:41
收件人: "ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [ustbhuangyi/better-scroll] 网络请求下，使用BScroll无法滚动，解决原因? (#1133)




 
页面一加载 Bscroll就会获取到 页面的高度，而网络请求是延迟到达，所以导致网络请求的模块数据的高度无法加载到 Bscroll的滚动里面，导致页面无法正常加载 滚动，content 里面只有一开始就有的数据，获取不到网络请求的高度，请问如何解决此问题

**Comment by daoke0818** [comment]
如果页面有10个模块通过网络请求加载，那要在这10个模块每个加载完都要调用一次refresh吗？能不能再父组件中检测页面高度，发现变化就调用一次？谢谢！

**Comment by theniceangel** [comment]
@daoke0818 observeDOM 以及 observeImage 插件了解一下
