### ISSUE TITLE
文档笔误

### ISSUE THREAD

**Issue by 7HzJoseJ** [ustbhuangyi/better-scroll#1137]
>maxScrollY
>类型：number
>作用：bs 最大纵向滚动位置。
>备注：bs 纵向滚动的位置区间是 [minScrollY, maxScrollY]，并且 maxScrollY 是负值，maxScrollY 是正值。

https://better-scroll.github.io/docs/zh-CN/guide/base-scroll-api.html#maxscrolly

bs 纵向滚动的位置区间是 [minScrollY, maxScrollY]，并且 maxScrollY 是负值 minScrollY 是正值

**Comment by theniceangel** [comment]
Thanks
