### ISSUE TITLE
关于better-scroll的probeType属性的问题!!! 戳进来

### ISSUE THREAD

**Issue by ZLd150** [ustbhuangyi/better-scroll#1139]
如果配置了probeType属性, 如果再配置pullUpload属性的话, 此时就会一直实时监控页面滚动.....
这是怎么回事? 此时probeType: 0 1 2, 就不起作用了, 全都是3,实时监控了, 求解

**Comment by yyx-520** [comment]
同楼主的问题，求解!

**Comment by theniceangel** [comment]
问题的本质是我们需要在任何时候，包括手指操控或者调用 scrollTo，获取当前的 bs 位置是否满足可以触发 pullingUp 的条件。

**Comment by ZLd150** [comment]
> 问题的本质是我们需要在任何时候，包括手指对准或调用scrollTo，获取当前的bs位置是否满足可以触发pullUp的条件。
感谢大佬指点,我们在需要监听的滚动的时候, 传进来就是了

**Comment by ZLd150** [comment]
需要的时候, 从其他组件传一个值过来, 就可以监听了, 在组件中默认值是0,不做监听
