### ISSUE TITLE
添加自动轮播功能

### ISSUE THREAD

**Issue by jiamianmao** [ustbhuangyi/better-scroll#114]
这样初始化的时候不就直接可以控制了？现在这个package用的人挺多的，每个人都能节省代码量了

**Comment by ustbhuangyi** [comment]
参考最新的文档：https://ustbhuangyi.github.io/better-scroll/doc/options-advanced.html#snap
以及对应的 demo 写法：https://github.com/ustbhuangyi/better-scroll/blob/master/example/components/slide/slide.vue
