### ISSUE TITLE
touchcancel事件不触发scrollEnd事件

### ISSUE THREAD

**Issue by chenyulun** [ustbhuangyi/better-scroll#1145]
### Version
2.1.1

### Reproduction link
[https://github.com/chenyulun/better-scroll/blob/dev/packages/shared-utils/src/dom.ts](https://github.com/chenyulun/better-scroll/blob/dev/packages/shared-utils/src/dom.ts)

### Steps to reproduce
Android 设备滚动的时候，有机会不触发`hooks.on('end',hander)`事件
![WechatIMG61](https://user-images.githubusercontent.com/15979948/105365057-d2d48880-5c38-11eb-8c7c-22aa15c83c20.jpeg)

### What is expected?
希望touchcancel触发end流程

### What is actually happening?
Android 设备滚动的时候，，有机会触发touchstart->touchmove->touchcancel;
这种情况下绑定‘end’事件不触发；

---
其实项目中监听了`touchcancel`的事件执行end钩子函数，但是eventTypeMap里面没有配置`touchcancel`事件为触摸事件;
```ts
export const eventTypeMap: {
  [key: string]: number
  touchstart: number
  touchmove: number
  touchend: number
  mousedown: number
  mousemove: number
  mouseup: number
} = {
  touchstart: 1,
  touchmove: 1,
  touchend: 1,

  mousedown: 2,
  mousemove: 2,
  mouseup: 2,
}
```
添加`touchcancel: 1`事件即可

**Comment by theniceangel** [comment]
fixed at v2.1.3
