### ISSUE TITLE
默认手机尺寸下无法滑动 但是chrome下更换手机尺寸后则可以滑动

### ISSUE THREAD

**Issue by likerapkeyboard** [ustbhuangyi/better-scroll#1148]
<script>
import BScroll from '@better-scroll/core'`
export default {
  name: 'CityList',
  props: {
    hot: Array,
    cities: Object
  },
  mounted () {
    this.$nextTick(() => {
      this.scroll = new BScroll(this.$refs.wrapper, {})
    })
  }
}
</script>`

数据由父组件传递  请问应该如何修改

**Comment by theniceangel** [comment]
复现repo？确保 DOM 渲染后再实例化 bs

**Comment by likerapkeyboard** [comment]
> 
> 
> 复现repo？确保 DOM 渲染后再实例化 bs

你好 我觉得也是bs实例化时间的问题  但我刚刚接触vue和bs 不知道从何下手 请问代码应该怎么改 万分感谢

**Comment by theniceangel** [comment]
你得给出一个完整的 repo，根据你这些 code snippets 我也无法确定到底是哪个环节出问题

**Comment by theniceangel** [comment]
@likerapkeyboard 可以借助于 codepen 这样的工具

**Comment by likerapkeyboard** [comment]
父组件city.vue https://codepen.io/likerapkeyboard/pen/MWjdMEj
子组件list.vue https://codepen.io/likerapkeyboard/pen/bGwyPYb

**Comment by theniceangel** [comment]
@likerapkeyboard 你得确保 cities 数据有了再渲染 city-list 组件，可以加个 v-if 控制渲染

```html
<city-list :cities="cities" :hot="hotCities" v-if="cities.length"></city-list>
```

或者你可以在  city-list 内部 watch cities 发生变化了，执行 bs.refresh 方法

**Comment by likerapkeyboard** [comment]
> @likerapkeyboard 你得确保 cities 数据有了再渲染 city-list 组件，可以加个 v-if 控制渲染
> 
> ```
> <city-list :cities="cities" :hot="hotCities" v-if="cities.length"></city-list>
> ```
> 
> 或者你可以在 city-list 内部 watch cities 发生变化了，执行 bs.refresh 方法

你好  我尝试了你提到的方法
方法1是可以的
方法2经过我测试 直接watch cities变化再刷新无效
因为cities渲染到页面时 是在updated之后
我尝试将bs初始化或是bs刷新放在updated钩子中都是可以的

**Comment by theniceangel** [comment]
那是你写的有问题，你对vue的渲染机制不熟悉------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;likerapkeyboard&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月24日(星期天) 下午3:55
收件人:&nbsp;&quot;ustbhuangyi/better-scroll&quot;<better-scroll@noreply.github.com&gt;;
抄送:&nbsp;&quot;JiZhi&quot;<471695625@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ustbhuangyi/better-scroll] 默认手机尺寸下无法滑动 但是chrome下更换手机尺寸后则可以滑动 (#1148)

**Comment by likerapkeyboard** [comment]
> 那是你写的有问题，你对vue的渲染机制不熟悉------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;likerapkeyboard&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年1月24日(星期天) 下午3:55 收件人:&nbsp;&quot;ustbhuangyi/better-scroll&quot;<better-scroll@noreply.github.com&gt;; 抄送:&nbsp;&quot;JiZhi&quot;<471695625@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [ustbhuangyi/better-scroll] 默认手机尺寸下无法滑动 但是chrome下更换手机尺寸后则可以滑动 (#1148)

刚开始学  请问watch应该怎么写
