### ISSUE TITLE
使用 pullup 插件时触发 pullingUp 事件的时机存在问题

### ISSUE THREAD

**Issue by wjq990112** [ustbhuangyi/better-scroll#1149]
### Version
2.1.4

### Reproduction link
[https://codesandbox.io/s/intelligent-proskuriakova-kqb8q?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675](https://codesandbox.io/s/intelligent-proskuriakova-kqb8q?file=/src/App.vue&resolutionWidth=320&resolutionHeight=675)

### Steps to reproduce
在使用 pullup 插件后，`pullingUp` 事件的执行时间存在问题：

1. 官方文档中对于 pullup 插件的 `options` 的阈值 `threshold` 默认值标注不正确，在翻阅源码后发现 `threshold` 默认值为 `0`：

```js
private handleOptions(userOptions: PullUpLoadOptions = {}) {
  userOptions = (userOptions === true ? {} : userOptions) as Partial<
    PullUpLoadConfig
  >
  const defaultOptions: PullUpLoadConfig = {
    threshold: 0,  // 默认值
  }
  this.options = extend(defaultOptions, userOptions)

  this.scroll.options.probeType = Probe.Realtime
}
```

2. 源码中对于 `pullingUp` 事件的执行时间计算存在问题。按照插件的设计逻辑，我们应该将 maxScrollY 与 `threshold` 做减法运算，得出的结果与 `position.y` 比较才能实现当用户上拉超过 `threshold` 阈值时触发 `pullingUp` 事件，而源码中是将两者做了加法运算，导致用户上拉到距离底部 `threshold` 阈值时就已经触发了 `pullingUp` 事件：

```diff
private checkPullUp(pos: { x: number; y: number }) {
  const { threshold } = this.options

+ //! 问题代码
  if (
    this.scroll.movingDirectionY === Direction.Positive &&
-   pos.y <= this.scroll.maxScrollY + threshold
+   pos.y <= this.scroll.maxScrollY - threshold
  ) {
    this.pulling = true
    // must reset pulling after scrollEnd
    this.scroll.once(this.scroll.eventTypes.scrollEnd, () => {
      this.pulling = false
    })
    this.unwatch()
    this.scroll.trigger(PULL_UP_HOOKS_NAME)
  }
}
```

正确的逻辑是否应该是上面这样的？

### What is expected?
在正确的时机触发 pullingUp 事件，即用户上拉超过阈值时才触发。

### What is actually happening?
不能在正确的时机触发 pullingUp 事件，在用户上拉未达到阈值时就已经触发了。

**Comment by theniceangel** [comment]
@wjq990112 文档有问题，但是逻辑是没问题的，最开始的初衷是当你需要超过底部 30px 才触发 pullingUp 的时候，你的 threshold 应该传 -30，所以源码那里是加法，你的 pr 我合进来，谢谢修改文档

**Comment by wjq990112** [comment]
> @wjq990112 文档有问题，但是逻辑是没问题的，最开始的初衷是当你需要超过底部 30px 才触发 pullingUp 的时候，你的 threshold 应该传 -30，所以源码那里是加法，你的 pr 我合进来，谢谢修改文档

没事，不过这个如果是需要传入 -30 的话，用户可能存在理解偏差，所以我个人的建议还是使用正值比较好理解。这部分的文档可能也需要再修改一下~

**Comment by theniceangel** [comment]
@wjq990112 文档具体哪里需要改一下？因为 1.x 的方式就是这样，所以就沿袭下来了

**Comment by wjq990112** [comment]
> @wjq990112 文档具体哪里需要改一下？因为 1.x 的方式就是这样，所以就沿袭下来了

应该需要在文档中添加一个 tips，提示用户应该使用负值，不过现在这里改成减法了，应该就不用修改了~

**Comment by theniceangel** [comment]
@wjq990112 可以加一个 tips，但是加法的逻辑依然会保持的，要不然就 breaking change 了，有些人希望距离底部 n px就触发，有些人希望超过底部 n px再触发，根据不同的场景选择不同的参数

**Comment by wjq990112** [comment]
> @wjq990112 可以加一个 tips，但是加法的逻辑依然会保持的，要不然就 breaking change 了，有些人希望距离底部 n px就触发，有些人希望超过底部 n px再触发，根据不同的场景选择不同的参数

明白了，稍后提一个 PR。
同时，scrollbar options 的 ts 类型也存在一些问题，应该需要支持传入 `false`，不能只支持传入 `true | Partial<ScrollbarConfig> | undefined`，类型是否改成 `boolean | Partial<ScrollbarConfig> | undefined` 更好？

源码：
```diff
// @better-scroll/scroll-bar/dist/types/index.d.ts
import BScroll from '@better-scroll/core';
import Indicator from './indicator';
export declare const enum Direction {
    Horizontal = "horizontal",
    Vertical = "vertical"
}
- export declare type ScrollbarOptions = Partial<ScrollbarConfig> | true;
+ export declare type ScrollbarOptions = Partial<ScrollbarConfig> | boolean;
export interface ScrollbarConfig {
    fade: boolean;
    interactive: boolean;
}
declare module '@better-scroll/core' {
    interface CustomOptions {
        scrollbar?: ScrollbarOptions;
    }
}
export default class ScrollBar {
    static pluginName: string;
    indicators: Array<Indicator>;
    constructor(scroll: BScroll);
    private createIndicators;
    private createIndicatorElement;
    destroy(): void;
}
```

**Comment by theniceangel** [comment]
@wjq990112 之前内部有讨论，因为传 false，根本不会走到 Scrollbar 插件的实例化，所以写死 true 了，如果会报错，需要使用 `as const` 语法，强制把你传的 options 里面的 true 推导成 true，而不是 boolean。

```ts
let options = {
  scrollbar: true
}

let options2 = {
  scrollbar: true
} as const

let bs = new BScroll('.wrapper', options) // bad
let bs2 =  new BScroll('.wrapper', options2) // good
```

**Comment by wjq990112** [comment]
如果是 `true | Partial<ScrollbarConfig> | undefined` 类型，在 scrollbar options 如果为 boolean 类型就会出现报错的情况，需要手动做类型断言：

```js
  const bs = new BScroll(wrapperRef.current as HTMLDivElement, {
      scrollX: direction === 'horizontal',
      scrollY: direction === 'vertical',
      click,
      //! 未传入 onScroll 事件时不触发 scroll 事件
      probeType: onUserScroll ? PROBE_TYPE : PROBE_TYPE_DEFAULT,
      pullUpLoad: onUserDragUp && {
        threshold: THRESHOLD
      },
      pullDownRefresh: onUserDragDown && {
        threshold: THRESHOLD,
        stop: STOP
      },
      //! ScrollBar 插件类型声明 bug
      //! scrollBar {boolean} props 传入
      scrollbar: scrollBar as ScrollbarOptions
    });
```

**Comment by wjq990112** [comment]
> @wjq990112 之前内部有讨论，因为传 false，根本不会走到 Scrollbar 插件的实例化，所以写死 true 了，如果会报错，需要使用 `as const` 语法，强制把你传的 options 里面的 true 推导成 true，而不是 boolean。
> 
> ```ts
> let options = {
>   scrollbar: true
> }
> 
> let options2 = {
>   scrollbar: true
> } as const
> 
> let bs = new BScroll('.wrapper', options) // bad
> let bs2 =  new BScroll('.wrapper', options2) // good
> ```

收到，明白了~

感谢解答~

**Comment by theniceangel** [comment]
@wjq990112 至于你说的这个，我再考虑下吧，因为对一般的用户来说，比较难以理解这个，而且也不会造成 breaking change

**Comment by wjq990112** [comment]
@theniceangel 后续的一些工作可能会和这个库有比较多亲密接触，可能会提一些建议/意见，方便加一个联系方式吗？

**Comment by theniceangel** [comment]
@wjq990112 471695625 搜这个微信吧
