### ISSUE TITLE
ios微信浏览器第一次不能滑到底部

### ISSUE THREAD

**Issue by shaozongyao** [ustbhuangyi/better-scroll#1151]
### Version
2.0.5

### Reproduction link
[http://web.dy-travel.co/rental_h5﻿](http://web.dy-travel.co/rental_h5﻿)

### Steps to reproduce
ios微信浏览器底部加了前进和后退的横条，导致第一次进入页面的时候不能滑到底，被横条遮住了，刷新一下就正常了

### What is expected?
fix

### What is actually happening?
always

**Comment by theniceangel** [comment]
@shaozongyao 实例化 bs 的时候，做为使用方，要确保滚动容器，以及滚动内容的尺寸，它自己并不会感知宿主环境
