### ISSUE TITLE
在slide插件中，如何使用H5 拖放api

### ISSUE THREAD

**Issue by chris-zhu** [ustbhuangyi/better-scroll#1161]
### Version
2.2.1

### Reproduction link
[https://github.com/chris-zhu/bs-question.git](https://github.com/chris-zhu/bs-question.git)

### Steps to reproduce
当我扩展了BS slide功能后，我在slide-page容器中，我想使用H5拖放功能，即使我开启了标签的draggable属性，还是无法使用drag的api，甚至图片默认的拖放也无法响应。
相关配置 slide: { loop: false, autoplay: false }

### What is expected?
想要在slide的page中自由使用H5 拖放api，实现元素的拖放，且并不影响到 slide的自由切换

### What is actually happening?
鼠标按住拖放元素进行拖放，会进行silde容器中page页的切换。

**Comment by theniceangel** [comment]
preventDefault 设置为 false 呢？

**Comment by chris-zhu** [comment]
preventDefault  设置为 false  可以解决问题  但是滚动的效果不太理想，会萌生新的bug( 图片拖拽结束还是会进入slide page切换的状态，page页会伴随鼠标的移动跟着移动 ) 
尝试  preventDefaultException  属性 对dom元素的 classname 进行标记限制， 但结果无效
`{ preventDefault : true, 
   preventDefaultException: {
      className: /(^|\s)test(\s|$)/
   }
}`

**Comment by chris-zhu** [comment]
好的  谢谢   那我尝试不去依赖bs
