### ISSUE TITLE
如果监听滚动事件，滚动出现卡顿问题

### ISSUE THREAD

**Issue by linkscope** [ustbhuangyi/better-scroll#1162]
### Version
2.1.4, Vue3.0

### Reproduction link
[https://github.com/linkscope/vue-music-app.git](https://github.com/linkscope/vue-music-app.git)

### Steps to reproduce
```bash
# step 1
git clone
# step 2
yarn
# step 3
yarn serve
```

### What is expected?
即使监听事件时，也希望可以流畅滚动

### What is actually happening?
请注意看歌手列表页面，该页面使用了onScroll滚动监听能力，总共有100条数据(50条数据也依然卡顿，与数据条目无关)，当我监听滚动事件时，会出现滚动卡顿问题；当没有监听滚动事件时，滚动非常流畅(可以对比推荐页面，推荐与歌手格式相差无几，都是一百条，区别仅仅是有无监听事件，两者滚动体验天壤之别)

[线上体验地址](http://81.70.10.185:2000/)

/src/views/singer/index.tsx:159

```tsx
{/* listenScroll决定是否监听滚动事件 */}
<ScrollView
    ref={scrollInstance}
    listenScroll={false}
    class={classes.scrollView}
    data={singerList}
    onScroll={onScroll}
>
     <ul ref={singerListInstance}>
          {singerList.map((item) => (
              <SingerItem singer={item} onClick={(singer) => goDetail(singer)} />
          ))}
     </ul>
</ScrollView>
```

**Comment by theniceangel** [comment]
@linkscope 我用 chrome 的 performance 测了一下，你的使用姿势不当。下面这段代码会不断的触发 vue3 的 rerender，浏览器又在做动画，又在执行 js，所以会卡顿。注释掉下面的代码即可。


![image](https://user-images.githubusercontent.com/25956811/110339873-9bdcf980-8063-11eb-8c52-6d8bd9890b35.png)

顺便给你解释一下：你可以看到一个 touchmove 就执行了 40多毫秒，并且 PatchFragment 就已经占了基本所有的时间，那是因为你在 touchmove 的钩子里面，也就是 onScroll 不断的执行响应式变更。
![image](https://user-images.githubusercontent.com/25956811/110340936-c5e2eb80-8064-11eb-975b-af79a11af4e5.png)

**Comment by linkscope** [comment]
> @linkscope 我用 chrome 的 performance 测了一下，你的使用姿势不当。下面这段代码会不断的触发 vue3 的 rerender，浏览器又在做动画，又在执行 js，所以会卡顿。注释掉下面的代码即可。
> 
> ![image](https://user-images.githubusercontent.com/25956811/110339873-9bdcf980-8063-11eb-8c52-6d8bd9890b35.png)
> 
> 顺便给你解释一下：你可以看到一个 touchmove 就执行了 40多毫秒，并且 PatchFragment 就已经占了基本所有的时间，那是因为你在 touchmove 的钩子里面，也就是 onScroll 不断的执行响应式变更。
> ![image](https://user-images.githubusercontent.com/25956811/110340936-c5e2eb80-8064-11eb-975b-af79a11af4e5.png)

听了您的解答，我在setup钩子内打了输出，发现并没有出现整个页面rerender的情况，如果我在监听事件内无法执行js是否也没有必要继续进行监听？希望能够解决该问题，目前没有找到什么有效的解决方法

**Comment by theniceangel** [comment]
@linkscope 建议了解一下 vue3 的源码， setup 函数只会执行一次，触发 reRender 并不会执行 setup，你的视图依赖了 `scrollYRef.value > 0`，但是在 scroll 的时候又不断的触发了响应式的 setter，这样又造成组件的 reRender，另外 reRender 是执行你 setup 里面返回的箭头函数，并不是 setup

**Comment by linkscope** [comment]
> @linkscope 建议了解一下 vue3 的源码， setup 函数只会执行一次，触发 reRender 并不会执行 setup，你的视图依赖了 `scrollYRef.value > 0`，但是在 scroll 的时候又不断的触发了响应式的 setter，这样又造成组件的 reRender，另外 reRender 是执行你 setup 里面返回的箭头函数，并不是 setup

大概明白了你的意思，就是滚动时会渲染一次，判断时又会渲染一次，的确我去掉了判断之后不会出现卡顿问题，但这是否意味着只要使用了滚动就不能使用条件渲染？

**Comment by theniceangel** [comment]
@linkscope 跟条件渲染无关，这是 vue 响应式的机制，这个跟 bs 无关，你只要保证触发 rerender 的频率不高即可，详情可以参考 cube-ui 的 index-list 组件，原理是一模一样的。
