### ISSUE TITLE
新版本 slide 使用 loop 滑动卡顿问题

### ISSUE THREAD

**Issue by FanKaiqiang** [ustbhuangyi/better-scroll#1168]
### Version
2.2.1

### Reproduction link
[https://better-scroll.github.io/examples/#/slide/dynamic](https://better-scroll.github.io/examples/#/slide/dynamic)

### Steps to reproduce
[![6h7XLQ.gif](https://z3.ax1x.com/2021/03/20/6h7XLQ.gif)](https://imgtu.com/i/6h7XLQ)

此前我业务场景使用的是2.0.3版本的 better-scroll，发现版本有更新就试着升级了。升级到 2.2.1 ，在没有更改其他配置的情况下，发现原本使用了 loop 的轮播图在从第一页划到最后一页的时候，如果有可能会出现卡顿的情况，但是旧版本（2.0.3）是没有问题的。

后来我试了一下文档中的 demo 也有相同的问题，如上 gif 所示（gif 由于被压缩可能不太流畅），全程我的手势都是往右滑动的，但是从 page 1 划到 page 3 时会卡顿，再试着滑动则会回到 page 1，体验比较奇怪。我的设备是 HUAWEI P30Pro，使用微信浏览器打开的。

### What is expected?
新版本的 loop 的 slide 滑动效果也正常

### What is actually happening?
新版本的 loop 的 slide 滑动效果与旧版本不一致，从第一页划到最后一页的时候可能会卡顿

---
不知道是否是从 2.0.3 升级到高版本有哪些不兼容旧版本的地方，或者我需要怎么配置才能使得交互变得正常呢？感谢您的解答

**Comment by theniceangel** [comment]
操作是否含有高频率的向左滑动？比如从1-2-3的过程中，还没有等到2停止，又开始手指向左滑了？

**Comment by FanKaiqiang** [comment]
> 操作是否含有高频率的向左滑动？比如从1-2-3的过程中，还没有等到2停止，又开始手指向左滑了？

并没有，我这里都是向右滑动，1-3-2 这样，频率是较快的，没有等到 3 完全停下。如果从 1 到 3 滑动等到 3 完全停下，再继续往右，倒是没有问题的。这里确实是往右较快滑动造成的问题，这个时候页面会卡在 3 处。

**Comment by theniceangel** [comment]
大概知道什么问题了，我找个时间修复下

**Comment by FanKaiqiang** [comment]
> 大概知道什么问题了，我找个时间修复下

顺带再请教一下，版本更新过后，「高频率地向左滑动」即 1-2-3 这样划，还没有等到2停止，又开始手指向左滑，感觉也没有旧版本（2.0.3）流畅了，这个和 loop 的卡顿是同一个问题嘛？

**Comment by theniceangel** [comment]
> > 大概知道什么问题了，我找个时间修复下
> 
> 顺带再请教一下，版本更新过后，「高频率地向左滑动」即 1-2-3 这样划，还没有等到2停止，又开始手指向左滑，感觉也没有旧版本（2.0.3）流畅了，这个和 loop 的卡顿是同一个问题嘛？

应该是一个问题，2.0.3 的实现是有一些 bug 的。

**Comment by theniceangel** [comment]
fixed at v2.3.0
