### ISSUE TITLE
v2.2.1版本的pullingUp在第一次执行下拉的时候，事件执行了两次，后面几次的下拉又正常了，我换到1.x的版本后就正常了

### ISSUE THREAD

**Issue by RayseaLee** [ustbhuangyi/better-scroll#1169]

**Comment by a798032825** [comment]
我也遇到了这个问题，使用请求加载数据后，下拉第一次会执行两次事件

**Comment by a798032825** [comment]
> _No description provided._

咋解决的呀

**Comment by RayseaLee** [comment]
> > _No description provided._
> 
> 咋解决的呀

我记得当时是因为引入了两次

**Comment by RayseaLee** [comment]
> > > _No description provided._
> > 
> > 
> > 咋解决的呀
> 
> 我记得当时是因为引入了两次

core库和标准库都引用了就出现这种情况
