### ISSUE TITLE
[Question] Why should I must give better-scroll a accurate height?

### ISSUE THREAD

**Issue by linkscope** [ustbhuangyi/better-scroll#1170]
Hello, When I give it a probably height like 100%, 70%. It can't scroll to the bottom!!!
I must give it a precisely like calc(100% - 74px), is there any better way?

**Comment by theniceangel** [comment]
Please ensure your `wrapper` DOM has stable height, you can inspect it in Chrome devtools, or give a repo to reproduce it.

**Comment by linkscope** [comment]
Well, it's really a wrapper controlled by v-show. So use v-show will affect its caclulation height and must give it a accurare height?
