### ISSUE TITLE
滚动div容器中会添加style="transform: translateX(0px)"等属性导致position: fixed失效，有什么好的解决方案

### ISSUE THREAD

**Issue by laijunlinfz** [ustbhuangyi/better-scroll#1171]

**Comment by theniceangel** [comment]
并没有，如果祖先元素有 transform，内部的元素设置 fixed 以后会失效，这是 css 决定的

**Comment by theniceangel** [comment]
> _No description provided._

如果是用 bs 1.x 的版本，设置 `useTransform` 为 false，就不存在这样的顾虑

**Comment by laijunlinfz** [comment]
> > _No description provided._
> 
> 如果是用 bs 1.x 的版本，设置 `useTransform` 为 false，就不存在这样的顾虑

好的，谢谢
