### ISSUE TITLE
PullDown 怎么限制最大下拉高度？

### ISSUE THREAD

**Issue by hzl123456** [ustbhuangyi/better-scroll#1173]
![image](https://user-images.githubusercontent.com/11958961/114019509-15554b00-98a1-11eb-9e0a-076f528b950e.png)
目前 PullDown 没有办法设置一个最大的下拉高度，如何才能限制一个最大的下拉高度呢？
如图中，我想实现下拉到红线位置就无法继续再下拉

**Comment by theniceangel** [comment]
目前无法实现，按照原生客户端的交互，并不需要限制一个最大的下拉高度
