### ISSUE TITLE
上拉消失滚动条，下拉展示滚动条

### ISSUE THREAD

**Issue by RichardSpace369** [ustbhuangyi/better-scroll#1174]
请教一下，浏览器是默认有上拉消失滚动条，下拉展示滚动条这个效果得，按照bs得滚动原理，是不会出现这个效果得。这种问题怎么解决了？

**Comment by theniceangel** [comment]
按照手机浏览器的交互，当你滑动页面的时候（不管上拉还是下拉），滚动条显示，过了一段时间，又隐藏，并不是你上面的这种现象
