### ISSUE TITLE
[New Feature] 为 slide 提供一个初始位置

### ISSUE THREAD

**Issue by FanKaiqiang** [ustbhuangyi/better-scroll#1175]
### What problem does this feature solve?
图片全屏轮播场景常常不是从第一张图片开始播放，如果要实现从中间的某张图开始播放，就比较麻烦了。若可以提供一个类似startX的配置项，可以设置slide的初始pageIndex，将会方便很多

### What does the proposed API look like?
``` ts
const slide = new BScroll(this.$refs.slide, {
    scrollX: true,
    scrollY: false,
    slide: {
        loop: true,
        autoplay: false,
        startIndex: 5,
    },
    momentum: false,
    bounce: false
})；
```

**Comment by theniceangel** [comment]
麻烦倒是不麻烦，直接在实例化 bs 之后，调用 `goToPage` 方法即可，不过内置参数比较好

**Comment by FanKaiqiang** [comment]
> 麻烦倒是不麻烦，直接在实例化 bs 之后，调用 `goToPage` 方法即可，不过内置参数比较好

之前我以为实例化 bs 之后调用直接`goToPage`会有在首屏时是在第一页，然后再切换成`startIndex`的效果，所以也没有试过。

刚才试了好像确实可以，如果有内置参数的话就更好了，现在用这种方式有点出乎意料的感觉。多谢了。

**Comment by theniceangel** [comment]
fixed at v2.3.0
