### ISSUE TITLE
[New Feature] 当我用better-scroll的实例去调用stop方法时，scrollEnd不会触发，好像没有相应的监听函数。

### ISSUE THREAD

**Issue by edison-hm** [ustbhuangyi/better-scroll#1176]
### What problem does this feature solve?
可以监听手动触发的stop

### What does the proposed API look like?
on('scrollStop', () => {} )

**Comment by theniceangel** [comment]
是在动画的过程中调用 stop 么

**Comment by edison-hm** [comment]
> 是在动画的过程中调用 stop 么

是的，场景是在picker组件里使用better-scroll，然后在滚动过程中点击Picker的确定按钮，希望立即停止动画并且拿到相应的值。

**Comment by theniceangel** [comment]
最新的版本么

**Comment by edison-hm** [comment]
> 最新的版本么

不好意思，之前不是最新版本，升级到2.2.1后就没问题了。
