### ISSUE TITLE
better-scroll重复打包

### ISSUE THREAD

**Issue by fjj19951017** [ustbhuangyi/better-scroll#1177]
vue/cli3下使用better-scroll，better-scroll无法打包进入公共依赖vendor，而是每个使用了better-scroll的页面都打进去了一个better-scroll依赖，重复打包造成包体积变大。

版本：2.0.5

重现步骤：1. 封装一个vue组件
2. 该组件通过 import BScroll from 'better-scroll' 引入better-scroll
3. 在若干个页面使用这个vue组件

**Comment by theniceangel** [comment]
复现 repo？

**Comment by fjj19951017** [comment]
是项目webpack配置的问题，与better-scroll无关
