### ISSUE TITLE
[New Feature] It is expected that the content can still be scrolled when the height of the content does not exceed the container

### ISSUE THREAD

**Issue by maskTAQ** [ustbhuangyi/better-scroll#1178]
When the height of the list does not exceed the container, I still want to use the pulldown, but it will not be triggered at this time

**Comment by theniceangel** [comment]
It is supported by the latest version of BetterScroll

**Comment by maskTAQ** [comment]
> It is supported by the latest version of BetterScroll

v2.2.1？

**Comment by theniceangel** [comment]
> > It is supported by the latest version of BetterScroll
> 
> v2.2.1？

yes, or you should use CSS when use BetterScroll 1.x, such as `min-height: 101%`, `min-height: calc(100% + 1px)` and so on.

**Comment by maskTAQ** [comment]
> > > It is supported by the latest version of BetterScroll
> > 
> > 
> > v2.2.1？
> 
> yes, or you should use CSS when use BetterScroll 1.x, such as `min-height: 101%`, `min-height: calc(100% + 1px)` and so on.

谢谢
