### ISSUE TITLE
t.wrapper.append is not a function

### ISSUE THREAD

**Issue by daqi** [ustbhuangyi/better-scroll#1185]
### Version
2.3.0

### Reproduction link
[https://better-scroll.github.io/examples/#/](https://better-scroll.github.io/examples/#/)

### Steps to reproduce
Open with vivo Y66 MicroMessenger

### What is expected?
Init success.

### What is actually happening?
Error: t.wrapper.append is not a function

---
UserAgent:
Mozilla/5.0 (Linux; Android 6.0.1; vivo Y66 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.81 Mobile Safari/537.36 MMWEBID/451 MicroMessenger/8.0.2.1860(0x28000234) Process/appbrand0 WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32 miniProgram

Chrome Mobile 51 not support Element.append()

**Comment by theniceangel** [comment]
fixed at v2.3.1
