### ISSUE TITLE
瀑布流布局除了onload图片加载完成，还有其他方法吗？

### ISSUE THREAD

**Issue by hmzgit** [ustbhuangyi/better-scroll#1188]
目前没找到其他方法，图片不确定高度只能等onload方法

**Comment by theniceangel** [comment]
如果是最新版本的 bs，使用 observe-image，可以自动探测图片加载完成并且完成刷新，否则只能等图片加载完成

**Comment by hmzgit** [comment]
> 如果是最新版本的bs，使用observe-image，可以自动探测图片加载完成和完成刷新，否则只能等图片加载完成

这个问题解决了 引出了一个新bug ObserveImage这个好像和LazyLoad这个库冲突了

上拉加载下页数据的时候 下一页列表数据的图片一大部分显示不出来了...

第一页的页面截图：
[
![153bf8a44a8cb6269d65b9645e8aed6](https://user-images.githubusercontent.com/45254733/117532720-7cd6f580-b01b-11eb-9b1b-598b7409c250.png)
](url)

第二页的页面截图：
[
![519629f77f54b022bca51767134bfa9](https://user-images.githubusercontent.com/45254733/117532732-937d4c80-b01b-11eb-80fe-a9e9c2caa11f.png)
](url)

第二页数据 就前几条显示了图片 后面的全部都是LazyLoad的占位图

代码子组件截图：
[
![0d25acf9b351535126a725ab05de6d5](https://user-images.githubusercontent.com/45254733/117532849-2ae29f80-b01c-11eb-9809-b4ceb2240070.png)
](url)

代码截图：
[
![826716b36798d8e92594538c9055126](https://user-images.githubusercontent.com/45254733/117532860-36ce6180-b01c-11eb-840f-255d76f16e1b.png)
](url)

啥原因啊
