### ISSUE TITLE
【BUG】 页面滑动到一半，卡住不动了

### ISSUE THREAD

**Issue by robbiemie** [ustbhuangyi/better-scroll#1191]
### Version
2.3.1

### Reproduction link
[https://better-scroll.github.io/examples/#/slide/fullpage](https://better-scroll.github.io/examples/#/slide/fullpage)

### Steps to reproduce
官方demo: https://better-scroll.github.io/examples/#/slide/fullpage

1. 将页面单手滑动到屏幕的一半
2. 然后再用另一个手指，点击屏幕
3. 双指离屏，可以看到页面卡住不动了

### What is expected?
双指离屏后，页面能正常恢复到原位置

### What is actually happening?
每次点击屏幕，都会触发 handleStart 事件，会将当前 transition 停止。双指触发时，就会导致页面卡在中间

---
下面两处需要处理双指操作：
第一处：https://github.com/ustbhuangyi/better-scroll/blob/aef6dab91a3527bb0781abf43cca0f6d9dc3c75d/packages/core/src/base/ActionsHandler.ts#L224
```
if(e.touches.length > 1) return
```
第二处：https://github.com/ustbhuangyi/better-scroll/blob/aef6dab91a/packages/core/src/scroller/Actions.ts#L149
```

```

**Comment by theniceangel** [comment]
除了 zoom 以外，都不考虑双至操作。
