### ISSUE TITLE
IOS 设备手势滑动，页面出现卡帧、抖动现象

### ISSUE THREAD

**Issue by robbiemie** [ustbhuangyi/better-scroll#1192]
### Version
2.3.1

### Reproduction link
[https://better-scroll.github.io/examples/#/slide/fullpage](https://better-scroll.github.io/examples/#/slide/fullpage)

### Steps to reproduce
iphone X、11、12 机型都能重现上述问题。
复现步骤：
在 slide 页面中，手指拖动单个页面左右滑，发现文字出现卡帧现象。

### What is expected?
Iphone 11 设备，拖动页面，文字可以平滑显示出来。

### What is actually happening?
拖动页面发现文字会出现卡帧现象，文字抖动

---
定位到问题的原因是监听的 touchmove 事件频繁绘制，导致掉帧问题。
解决方案：

为 touchmove 事件提供一个节流函数，可以解决此类问题。

```js

function throttle(fn,delay) {
  var timer = null
  return function (args)  {
    if(timer) return
    timer = setTimeout(() => {
      fn.call(this, args)
      timer = null
    }, delay)
  }
}
let throttleMoveFn = throttle(this.move, 1)
```

https://github.com/ustbhuangyi/better-scroll/blob/dev/packages/core/src/base/ActionsHandler.ts#L75

**Comment by robbiemie** [comment]
之前有试过设置 useTransition: false ，发现该问题还是存在。
最终原因还是 touchmove 事件触发，导致页面频繁重绘，使得 CPU 在当前帧，无法及时处理完当前帧任务。造成卡帧现象。

**Comment by theniceangel** [comment]
如果把[这段代码](https://github.com/ustbhuangyi/better-scroll/blob/aef6dab91a3527bb0781abf43cca0f6d9dc3c75d/packages/core/src/base/ActionsHandler.ts#L200)删除试试呢，touchmove 的时候不断的探测是否手指划出了边界

**Comment by robbiemie** [comment]
> 如果把[这段代码](https://github.com/ustbhuangyi/better-scroll/blob/aef6dab91a3527bb0781abf43cca0f6d9dc3c75d/packages/core/src/base/ActionsHandler.ts#L200)删除试试呢，touchmove 的时候不断的探测是否手指划出了边界

试了一下，删除上述超出边界对应的逻辑代码，并没有解决该问题。同时，删除之后，还会出现滑动导致连续翻页的现象。即滑动一小段距离，页面被连续翻过好几页。

**Comment by theniceangel** [comment]
你这里描述的文字抖动是什么意思？有gif图么

**Comment by robbiemie** [comment]
> 你这里描述的文字抖动是什么意思？有gif图么
录制的gif 可能是由于被压制的原因，抖动的效果不明显。但是在真机上测试，文字还是会上下抖动。而且缓慢滑动，还有闪屏的现象出现。

[gif 录屏](https://github.com/robbiemie/upload-files-repo/blob/master/Kapture%202021-05-24%20at%2012.03.31.gif)

**Comment by theniceangel** [comment]
在 iOS 会有此类问题，有没有试过用安卓测试一下？

**Comment by theniceangel** [comment]
这种情况的话，只能提供一个配置项，对 touchmove 实现 throttle 效果

**Comment by robbiemie** [comment]
> 在 iOS 会有此类问题，有没有试过用安卓测试一下？

安卓没有此类问题。嗯是可以加一个配置项，针对改问题去做处理。

**Comment by robbiemie** [comment]
本地打日志看过，安卓机型 FPS 基本在 90以上，IOS 的 FPS 在 60 左右。

**Comment by theniceangel** [comment]
这种优化还是不可取
