### ISSUE TITLE
better-scroll封装成组件scroll后，同一个页面只能用一个，无法实现左右两边同时都有并列scroll组件

### ISSUE THREAD

**Issue by clareliu458** [ustbhuangyi/better-scroll#1193]
### Version
2.3.1

### Reproduction link
[https://github.com/clareliu458/scroll-both-left-and-right.git](https://github.com/clareliu458/scroll-both-left-and-right.git)

### Steps to reproduce
1. 第一次commit：同一个页面左右两边并列使用同一个由better-scroll封装的Scroll组件，无法实现两边都滚动，右边的总是不能滚动。
2. 第二次commit：如果要实现同一个页面左右两边都同时可以滚动，需要再创建一个Scroll组件，并且里面初始化的时候class类名不能相同。亲测可行。

### What is expected?
N/A

### What is actually happening?
N/A

---
vue移动版项目中，把better-scroll封装成组件后，如果一个页面内左边要用这个scroll组件，右边也要用，无法实现左右两边同时都有并列scroll组件。只能是封装两个scroll组件，并且初始化时那个类名不能相同。版本是@2.3.1

**Comment by theniceangel** [comment]
实例化 bs 的时候第一个参数如果是传递一个 string，内部会尝试使用 `document.querySelector` 来获取对应的 DOM，当页面有相同的 classname 的时候，获取的永远是相同的一个。左右联动必须实例化两个 bs，并且保证传进去的 DOM 对象是相互独立的
