### ISSUE TITLE
当设置 better-scroll 的options  click: true 。在scroller 使用checkbox 不能触发默认的选中或者取消事件

### ISSUE THREAD

**Issue by weiRongLady** [ustbhuangyi/better-scroll#12]
当设置 better-scroll 的options  click: true 。在scroller 使用checkbox 不能触发默认的选中或者取消事件。demo:
[http://47.90.55.218:8081/demo/index.html](url)
浏览器 chrome v: 54.0.2840.59

**Comment by ustbhuangyi** [comment]
这个测试服务器应该是挂了，可以考虑把测试页面发布到 codepen, jsfiddle 或者 github page 上

**Comment by zppwt** [comment]
您好，我想请问 better-scroll  直接使用src引入 是怎么获取better-scroll.js ？非常感谢！

**Comment by neurotoxinvx** [comment]
@zppwt 使用 build里的 bscroll.min.js

**Comment by weiRongLady** [comment]
@ustbhuangyi 这个连接应该是可以使用的，但是需要复制一下再浏览器里面就能打开，github里面确实404.源码：https://github.com/weiRongLady/BScroll.git

**Comment by weiRongLady** [comment]
@ustbhuangyi  codepen: http://codepen.io/weiRongLady/pen/dNXRPK

**Comment by zppwtzjy** [comment]
@neurotoxinvx 谢谢啊，非常感谢！

**Comment by ustbhuangyi** [comment]
fixed，use  v0.1.11
