### ISSUE TITLE
[New Feature] Where to find type definition for @better-scroll/core ?

### ISSUE THREAD

**Issue by dingfanATyykj** [ustbhuangyi/better-scroll#1200]
### What problem does this feature solve?
I want to use it in TypeScript

There is only "Type definitions for better-scroll 1.12" in https://github.com/DefinitelyTyped/DefinitelyTyped/search?q=better-scroll

### What does the proposed API look like?
Add types to DefinitelyTyped so I can `yarn add @types/@better-scroll/core`

**Comment by theniceangel** [comment]
better-scroll 2.x is written by typescript
