### ISSUE TITLE
Scrolling distance may be constrainted to the height of item, cause inconsistency on scrolling distance.

### ISSUE THREAD

**Issue by xiyu23** [ustbhuangyi/better-scroll#1202]
### Version
`2.3.1`

### Reproduction link
⚠️ **Not Available**
[https://cgje0.csb.app/](https://cgje0.csb.app/)

please check [this](https://github.com/ustbhuangyi/better-scroll/blob/dev/packages/examples/vue/components/mouse-wheel/vertical-scroll.vue) out.

**it acrosses 5 lines once mousewheel is scrolled , but I would like to scroll slowly. How could I do that?**

### Steps to reproduce
1. make items in the container have different height
2. scroll vertically, you will see that the **scrollbar moves in a different distance every time you trigger the mouseWheel**.

### What is expected?
Same scrolling distance, no matter how the height of items are different from each other.

Sometimes we have different height for each item, but we dont wan't distance the scrollbar moves relys on the height of someone item's height. 

Since this behaviour may cause the item with larger height cannot be seen while you scrolling the vertical scrollbar.

**Do we have configs like this?** Its not easy to get that IMO.

### What is actually happening?
the scrollbar moves in a different distance every time you trigger the mouseWheel

**Comment by theniceangel** [comment]
You can look up the mousewheel events, it is different from touch or mouse event, maybe you scroll mousewheel a little, but result in large scroll distance
