### ISSUE TITLE
触屏pc端用better-scroll滚动失效。

### ISSUE THREAD

**Issue by blackgooes** [ustbhuangyi/better-scroll#1219]
### Version
2.4.1

### Reproduction link
[https://better-scroll.github.io/docs/zh-CN/guide/base-scroll.html#%E4%B8%8A%E6%89%8B](https://better-scroll.github.io/docs/zh-CN/guide/base-scroll.html#%E4%B8%8A%E6%89%8B)

### Steps to reproduce
1、打开chrome
2、在触屏的pc端环境下（可以用 多点触控模拟器MultiTouchVista 来模拟）。
3、官网的任意例子上下滑动都无法滚动。

### What is expected?
希望在触屏模式下可以滚动页面

### What is actually happening?
官网的任意例子在开启
多点触控模拟器MultiTouchVista
时都无法滚动

---
pc在chrome上使用鼠标或开启移动端调试模式，都可以滑动。但启用touch模式时不行。
之后参照官网的“平板电脑需要支持 touch 事件，平板电脑接入鼠标又得支持 mouse 事件”并进行配置
disableMouse: false,
disableTouch: false。
后还是无效。源码断点里 'ontouchstart' in window 为false

**Comment by theniceangel** [comment]
只是在模拟器下面无法滚动，还是在真实的环境中无法滚动？模拟器和真实环境可能有出入
