### ISSUE TITLE
better-scroll问题如果左侧列表里z的数据过少滚动出现问题

### ISSUE THREAD

**Issue by larryenjoy** [ustbhuangyi/better-scroll#122]
如果左侧数据过少better-scroll是滚动不上去的，如果点击右侧上面的tips会发生改变但是列表是不进行滚动的。请问这个怎么样解决。我用别的数据已经产生这个问题。
例如Z的数据只有四条左右，只能滚动到X的内容在往下就滚动不了了。右侧点击字母Z头部的TIPS也是会改变的。

**Comment by ustbhuangyi** [comment]
不符合 issue 规范
