### ISSUE TITLE
求开发一个吸顶功能，类似这里：https://www.zhangxinxu.com/wordpress/2018/12/css-position-sticky/

### ISSUE THREAD

**Issue by hongrunhui** [ustbhuangyi/better-scroll#1220]
### Reproduction link
[https://www.zhangxinxu.com/wordpress/2018/12/css-position-sticky/](https://www.zhangxinxu.com/wordpress/2018/12/css-position-sticky/)

### Steps to reproduce
求开发一个吸顶功能，类似这里：https://www.zhangxinxu.com/wordpress/2018/12/css-position-sticky/

### What is expected?
求开发一个吸顶功能，类似这里：https://www.zhangxinxu.com/wordpress/2018/12/css-position-sticky/

### What is actually happening?
不能吸顶

**Comment by theniceangel** [comment]
https://didi.github.io/cube-ui/#/zh-CN/docs/index-list

bs 滚动的时候会派发 scroll 事件能拿到当前的位置，根据位置编程即可
