### ISSUE TITLE
使用slide，怎么禁止上一页或下一页

### ISSUE THREAD

**Issue by hb2013** [ustbhuangyi/better-scroll#1225]
### Version
2.4.1

### Reproduction link
[https://jsfiddle.net/4owk0vqr/](https://jsfiddle.net/4owk0vqr/)

### Steps to reproduce
想在某页时，锁定页面，不让往上滑动或往下滑动，或不让滑动。没找到对应方法，尝试直接禁用滑动，页面中CLICK单击也不能点。
比如让Class包括no-slide的，不让滑动，或者用JS怎么控制不让滑动

### What is expected?
想在某页时，锁定页面，不让往上滑动或往下滑动，或不让滑动。没找到对应方法，尝试直接禁用滑动，页面中CLICK单击也不能点。
比如让Class包括no-slide的，不让滑动，或者用JS怎么控制不让滑动

### What is actually happening?
想在某页时，锁定页面，不让往上滑动或往下滑动，或不让滑动。没找到对应方法，尝试直接禁用滑动，页面中CLICK单击也不能点。
比如让Class包括no-slide的，不让滑动，或者用JS怎么控制不让滑动

**Comment by theniceangel** [comment]
bs.disable()

**Comment by hb2013** [comment]
> bs.disable()

试过了，这样点击也会失效
