### ISSUE TITLE
一开始数据量不大，没有超出容器，后来多了，超出容器后，但是无法滚动

### ISSUE THREAD

**Issue by swliu920322** [ustbhuangyi/better-scroll#1226]
https://codesandbox.io/s/lucid-rhodes-2ybee?file=/src/App.vue

**Comment by swliu920322** [comment]
拖动浏览器大小变化之后，就可以滚动，应该是触发重排了，但是怎么解决这个问题

**Comment by swliu920322** [comment]
可以暴露方法，通过refresh修改，怎么才能在指令里面解决呢，

**Comment by theniceangel** [comment]
组件 rerender 之后，指令有对应的钩子，参考vue官网
