### ISSUE TITLE
[New Feature] Allow for horizontal scrolling via touchpad with mouse-wheel-plugin

### ISSUE THREAD

**Issue by peterschmidler** [ustbhuangyi/better-scroll#1227]
### What problem does this feature solve?
Horizontally scrollable pages cannot be scrolled via my mbp's touchpad, since the mouse-wheel-plugin only captures vertical and no vertical wheel events.

### What does the proposed API look like?
A horizontal:bool paramater could decide weather horizontal deltaX values should be considered.

**Comment by peterschmidler** [comment]
This is possibly also a bug, since I can see lots of `wheelDeltaY` in the code, but with no effect.

**Comment by peterschmidler** [comment]
Horizontal scrolling is indeed possible, but only via up/down scrolling and not via left/right scrolling on touchpads.

**Comment by peterschmidler** [comment]
I think there's no parameter needed and the issue could easily be solves as in my pull request.

**Comment by theniceangel** [comment]
fixed at v2.4.2
