### ISSUE TITLE
老师，问一下，better-scroll的几个内部函数里都没有提供判断滚动方向的api哈？

### ISSUE THREAD

**Issue by h5chaipeng** [ustbhuangyi/better-scroll#123]
在用better-scroll做下拉刷新组件时，为了控制的更加精细，需要用到判断滑动方向，翻了一下文档，没看到scroll,touchend之类的提供这个api

**Comment by ustbhuangyi** [comment]
可以基于 touchend 事件做，判断 this.y >0 即可。
