### ISSUE TITLE
BetterScroll 2.0 中文文档的起步部分存在错误叙述

### ISSUE THREAD

**Issue by Zhao-Bocheng** [ustbhuangyi/better-scroll#1232]
### Version
2.4.1

### Reproduction link
[https://better-scroll.github.io/docs/zh-CN/guide/#%E8%B5%B7%E6%AD%A5](https://better-scroll.github.io/docs/zh-CN/guide/#%E8%B5%B7%E6%AD%A5)

### Steps to reproduce
起步部分的“注意”部分中的“上拉刷新、下拉加载”，实际上应该是“上拉加载、下拉刷新”
![image](https://user-images.githubusercontent.com/63044289/126903345-43bf94a2-3623-4332-86bd-852dd03735ea.png)

### What is expected?
起步部分的“注意”部分中的“上拉刷新、下拉加载”，实际上应该是“上拉加载、下拉刷新”

### What is actually happening?
起步部分的“注意”部分中为“上拉刷新、下拉加载”

**Comment by theniceangel** [comment]
thanks
