### ISSUE TITLE
nested-scroll 内部的点击事件会触发两次

### ISSUE THREAD

**Issue by GOGOGOSIR** [ustbhuangyi/better-scroll#1235]
### Version
2.4.2

### Reproduction link
[https://codesandbox.io/s/better-scroll-qian-tao-gun-dong-v0i6j](https://codesandbox.io/s/better-scroll-qian-tao-gun-dong-v0i6j)

### Steps to reproduce
点击嵌套的滚动区域，click事件会触发两次，如果内层设置了 stopPropagation: true, 则可以实现点击事件触发一次，但是手指在内层滚动区域上下滚动时，最外层滚动区域无法滚动

### What is expected?
只触发一次

### What is actually happening?
触发了2次

**Comment by txw2018** [comment]
![image](https://user-images.githubusercontent.com/37097875/130715271-66693b5d-e0cb-445a-874b-449ab994127e.png)
文档写了
