### ISSUE TITLE
pulldown支持水平方向的下拉刷新吗

### ISSUE THREAD

**Issue by jackYouth** [ustbhuangyi/better-scroll#1237]
看源码好像是不支持的 ==

`PullDown.prototype.checkPullDown = function () {
          var _a = this.options, threshold = _a.threshold, stop = _a.stop;
          // check if a real pull down action
          if (this.scroll.y < threshold) {
              return false;
          }
          if (this.pulling === 1 /* MOVING */) {
              this.modifyBehaviorYBoundary(stop);
              this.setPulling(2 /* FETCHING */);
              this.scroll.trigger(PULLING_DOWN_EVENT);
          }
          this.scroll.scrollTo(this.scroll.x, stop, this.scroll.options.bounceTime, ease.bounce);
          return this.isFetchingStatus();
      };`

**Comment by theniceangel** [comment]
不支持
