### ISSUE TITLE
better-scroll滚动问题，左侧Z条目下内容过少滚动出现问题

### ISSUE THREAD

**Issue by larryenjoy** [ustbhuangyi/better-scroll#124]
1.外网地址无
2.左侧最后一个LI下如果数据内容少于四条滚动出现问题。点击右侧字母上面TIPS会更改但左侧滚动不上去。
![59957e8500017c8803760511](https://user-images.githubusercontent.com/23193082/29448870-1d332740-842b-11e7-824f-5e4eabed3614.jpg)

**Comment by ustbhuangyi** [comment]
这个问题去 vue-music 项目的 issue 里提，不要在 better-scroll 下面 提，不属于 better-scroll 的 bug。
