### ISSUE TITLE
react example not work

### ISSUE THREAD

**Issue by fangaofeng** [ustbhuangyi/better-scroll#1243]
### Version
2.4.2

### Reproduction link
[http://no link.](http://no link.)

### Steps to reproduce
git clone https://github.com/ustbhuangyi/better-scroll.git
cd better-scroll
yarn
yarn react:dev

### What is expected?
example working

### What is actually happening?
PS E:\workspace\better-scroll-dev> yarn react:dev
yarn run v1.22.11
$ lerna run --stream --scope react-examples dev
lerna notice cli v3.22.1
lerna notice filter including "react-examples"
lerna info filter [ 'react-examples' ]
lerna info Executing command in 1 package: "yarn run dev"
react-examples: $ react-app-rewired start
react-examples: i ｢wds｣: Project is running at http://10.11.3.21/
react-examples: i ｢wds｣: webpack output is served from 
react-examples: i ｢wds｣: Content not from webpack is served from E:\workspace\better-scroll-dev\packages\react-examples\public
react-examples: i ｢wds｣: 404s will fallback to /
react-examples: Starting the development server...
react-examples: Failed to compile.
react-examples: ./src/pages/compose/components/pullup-pulldown.js
react-examples: Module not found: Can't resolve '@better-scroll/core' in 'E:\workspace\better-scroll-dev\packages\react-examples\src\pages\compose\components'
react-examples: Compiling...
react-examples: Failed to compile.
react-examples: ./src/pages/compose/components/pullup-pulldown.js
react-examples: Module not found: Can't resolve '@better-scroll/core' in 'E:\workspace\better-scroll-dev\packages\react-examples\src\pages\compose\components'

---
nodemodule in better-scroll-dev directory aleady install.

**Comment by theniceangel** [comment]
执行下 packages:build 构建包

**Comment by Spencer17x** [comment]
So did I!
This is a react demo that I documented, and it doesn't work.
docs: https://better-scroll.github.io/docs/zh-CN/plugins/pullup.html#%E4%BB%8B%E7%BB%8D
code: https://stackblitz.com/edit/react-ts-sosryk?file=App.tsx,style.scss
