### ISSUE TITLE
not able to pass position to child element

### ISSUE THREAD

**Issue by FHSWar** [ustbhuangyi/better-scroll#1245]
### Version
2.4.2

### Reproduction link
[https://github.com/FHSWar/scroll-dumb-fhs](https://github.com/FHSWar/scroll-dumb-fhs)

### Steps to reproduce
- yarn install
- yarn serve

### What is expected?
能把 position 传给滚动容器内的元素

### What is actually happening?
通过 v-bind 传的话下拉滚动就失效了

---
https://github.com/FHSWar/scroll-dumb-fhs 这个是 demo

**Comment by theniceangel** [comment]
跟 bs 没关系，因为 this.pos 是响应式数据，你不断的修改它，导致一直触发 updated 声明周期函数，不断的走 bs 的 refresh。

**Comment by FHSWar** [comment]
谢谢 @theniceangel 的解答，我想了下，直接通过 $refs 把 y 值写进 bubble 里面， 现在能用了，芜湖。
