### ISSUE TITLE
[New Feature] 希望出一个 React版本的@better-scroll/infinity demo

### ISSUE THREAD

**Issue by Qingzii** [ustbhuangyi/better-scroll#1247]
### What problem does this feature solve?
希望出一个 React版本的@better-scroll/infinity demo

### What does the proposed API look like?
希望出一个 React版本的@better-scroll/infinity demo

**Comment by ustbhuangyi** [comment]
https://github.com/ustbhuangyi/better-scroll/tree/dev/packages/react-examples/src/pages/infinity
