### ISSUE TITLE
使用preventDefaultException无效

### ISSUE THREAD

**Issue by muyichenran** [ustbhuangyi/better-scroll#125]
1.外网访问链接为 http://mq.helpyoulove.com/prodetail?Id=5
2.使用的版本是"better-scroll": "^0.2.4"。
3.调用的代码如下：

this.scroll = new BScroll(this.$refs.wrapper, {
          probeType: this.probeType,
          click: this.click,
          scrollX: this.scrollX,
          preventDefault:this.preventDefault,
          preventDefaultException:{ 
            tagName: /^(INPUT|TEXTAREA|BUTTON|SELECT)$/,
            className:/(^|\s)cancopy(\s|$)/
          }
 })
代码中使用了className:/(^|\s)canpay(\s|$)/ ，但在className 为cancopy 的div包裹区域还是无法实现最基本的长按复制功能

4.环境为微信自带浏览器，以及在电脑端也没办法点击复制

**Comment by ustbhuangyi** [comment]
1. 用最新版本的 better-scroll
2. 你需要把 className 用在 p 标签上而不是 article 标签上。因为 e.target 是 p 标签。
