### ISSUE TITLE
[New Feature] 在插件wheel中， setSelectedIndex没实现吗？

### ISSUE THREAD

**Issue by qianlongdoit** [ustbhuangyi/better-scroll#1257]
### What problem does this feature solve?
我看见[源码](https://github.com/ustbhuangyi/better-scroll/blob/dev/packages/wheel/src/index.ts#L258-L266)是有相关部分的，为什么这个api没有开放出来呢？
```js
  setSelectedIndex(index: number, contentChanged: boolean = false) {
    const prevSelectedIndex = this.selectedIndex
    this.selectedIndex = index

    // if content DOM changed, should not trigger event
    if (prevSelectedIndex !== index && !contentChanged) {
      this.scroll.trigger(WHEEL_INDEX_CHANGED_EVENT_NAME, index)
    }
  }
```

### What does the proposed API look like?
setSelectedIndex

**Comment by theniceangel** [comment]
初始化的时候可以指定选中项，实例化之后也可以通过 wheelTo 滚动过去，selectedIndex 只是内部维护的一个状态
