### ISSUE TITLE
ios 15.1微信8.0.16 banner slide闪屏

### ISSUE THREAD

**Issue by chenyulun** [ustbhuangyi/better-scroll#1260]
### Version
2.4.2

### Reproduction link
[https://better-scroll.github.io/examples/#/slide/banner](https://better-scroll.github.io/examples/#/slide/banner)

### Steps to reproduce
复现场景：
手机： iPhone 13 Pro
系统： ios 15.1
浏览器环境： 微信8.0.16和chrome92(safari不会闪屏)
打开：https://better-scroll.github.io/examples/#/slide/banner
可复现，录屏已发送到您微信

### What is expected?
希望支持ios15.1的系统微信和chrome流畅进行轮播

### What is actually happening?
ios 15.0.1和15.1里面better-scroll的banner闪屏

---
我们使用better-scroll 1.x的用户反馈iphone11的ios 15.0.1的微信上better-scroll的banner会闪屏,
然后我那现在的官方2.x案例在iPhone 13 Pro的最新版本微信里面也会闪屏

**Comment by baokuanze** [comment]
![image](https://user-images.githubusercontent.com/14322761/144774949-056280b3-8f70-4c9d-8585-f8a9aac4cec3.png)
