### ISSUE TITLE
mouseWheel & pulldown 官网示例无法正常触发

### ISSUE THREAD

**Issue by RickieWoo** [ustbhuangyi/better-scroll#1277]
### Version
2.4.2

### Reproduction link
[https://better-scroll.github.io/docs/zh-CN/plugins/mouse-wheel.html#%E8%BF%9B%E9%98%B6%E4%BD%BF%E7%94%A8](https://better-scroll.github.io/docs/zh-CN/plugins/mouse-wheel.html#%E8%BF%9B%E9%98%B6%E4%BD%BF%E7%94%A8)

### Steps to reproduce
鼠标下滑动有很大几率不会load数据，在官方demo中就不行

### What is expected?
鼠标下滑动会load数据

### What is actually happening?
鼠标下滑动有很大几率不会load数据

---
实际项目中也有相同问题

**Comment by jianatrm** [comment]
这个最后怎么解决的啊
