### ISSUE TITLE
MouseWheel（鼠标滚轮）和pull-down（下拉刷新）和pull-up（上拉加载）能组合使用吗，能否提供一个demo

### ISSUE THREAD

**Issue by hyz94** [ustbhuangyi/better-scroll#1281]

**Comment by theniceangel** [comment]
https://better-scroll.github.io/examples/#/compose/pullup-pulldown

**Comment by hyz94** [comment]
> https://better-scroll.github.io/examples/#/compose/pullup-pulldown

这个demo只是pullup、pulldown组合，mousewheel不能促发列表滚动
