### ISSUE TITLE
Better-Scroll breaks when window scrolls to elements that have tab index

### ISSUE THREAD

**Issue by LeeRob97** [ustbhuangyi/better-scroll#1282]
### Version
2.4.2

### Reproduction link
[https://codepen.io/LeeRob97/pen/JjOvXgO](https://codepen.io/LeeRob97/pen/JjOvXgO)

### Steps to reproduce
1. Select the first list element
2. keep pressing tab until the wrapper is forced to scroll
3. try to scroll back to the top with your mouse, notice you cannot

### What is expected?
I assumed since the scroller is binded to the document, that it would catch the scroll event triggered by the browser and would update the better-scroll scroller position.

### What is actually happening?
When the browser scrollers to the element, the better scroll position is not updating, hence breaking the scroller experience.

---
If I set all elements to have a tabindex of -1, then of course the issue won't occur, but due to accessibility I do not want to have to do that.

**Comment by theniceangel** [comment]
If we take this scene into consideration, the logic is too heavy, we should catch all scroll events

**Comment by cdiem** [comment]
@LeeRob97 have you found a way around this (except for making items inside the scroller untabbable)?

@theniceangel the issue was marked as "completed", but I can't find any commit linked, was this fixed somehow?
