### ISSUE TITLE
功能诉求

### ISSUE THREAD

**Issue by wuwhzen** [ustbhuangyi/better-scroll#1283]
在双向滚动的配置下，如何实现滑动时只能在一个方向，现在斜着滑动时，横竖都会滑动，能不能根据滑动角度判断滑动方向，然后只在对应方向上滑动

**Comment by theniceangel** [comment]
不通过 freeScroll 配置，明确的通过以下两个参数配置双向滚动。

```js
{
    scrollX: true,
    scrollY: true
}
```

**Comment by wuwhzen** [comment]
> 不通过 freeScroll 配置，明确的通过以下两个参数配置双向滚动。
> 
> ```js
> {
>     scrollX: true,
>     scrollY: true
> }
> ```

这样是能双向滚动，但是斜着拖动时，整个页面也是斜着动的，希望是：斜着拖动时，只会在一个方向滚动，而不是两个方向都在滚动
