### ISSUE TITLE
function disable() don't work when invoke scrollTo()

### ISSUE THREAD

**Issue by zhylmzr** [ustbhuangyi/better-scroll#129]
Thank your library. But i have a litter problem. 
The official docs show
>disable()
作用：禁用 better-scroll，事件回调函数不再响应。

But invoke the function don't disable better-scroll. The scrollTo() have effect and the callback of 'scroll' event is triggered, too.

e.g.https://codepen.io/zhyl/pen/yovZge
version: 1.2.0

**Comment by ustbhuangyi** [comment]
disable only stop DOM event such as touchstart、touchmove、touchend，it won't stop the scrollTo function. Ok, I will modify the wiki to avoid ambiguity.
