### ISSUE TITLE
官方demo在微信内打开，不指定内部item的高度，content区域下面会有一部分空白区域

### ISSUE THREAD

**Issue by coreyGh** [ustbhuangyi/better-scroll#1295]
2.4.2版本，你们的官方demo在微信内打开，不指定内部item的高度，将页面滑动到最底部，content区域下面会有一部分空白区域，区域高度跟item的个数正相关，item越多，空白高度越大，外部浏览器和钉钉内打开没有此问题，微信版本号8.0.20，手机iphone12

**Comment by yellowflyhub** [comment]
我在PC端也出现这个问题了，我非常快速地向上滑动的时候，content下面就会有很大一截空白
