### ISSUE TITLE
How Can I load better-scroll-core.min.js and better-scroll-pull-up.min.js with Script?

### ISSUE THREAD

**Issue by chunxiao01** [ustbhuangyi/better-scroll#1299]
**I try to do this**:
```html
<script src="asset/js/better-scroll-core.min.js"></script>
<script src="asset/js/pull-up.min.js"></script>
<script src="asset/js/pull-down.min.js"></script> 
```
```javascript
this.BS = new BScroll("#container", {
  probeType: 3,
  pullUpLoad: true,
  pullDownRefresh: true,
  click: true,
   scrollbar: true
})
```

**But it does not work , something is wrong:**
```shell
[BScroll warn]: EventEmitter has used unknown event type: "pullingUp", should be oneof ["refresh","contentChanged","enable","disable","beforeScrollStart","scrollStart","scroll","scrollEnd","scrollCancel","touchEnd","flick","destroy"]
```
How do it ? not use `important` or  `better-scroll.min.js`

### If I want to use the  `better-scroll-core.min.js `and `better-scroll-pull-up.min.js` with script, how can I do it ?

ps: I can not find the better-scroll-pull-up.min.js in the CDN or the website, I build from the better-scroll/pull-up source.

Thank you !

**Comment by dolymood** [comment]
Need to use:

BScroll.use(PullUp)
BScroll.use(PullDown)

Then

new BScroll()
