### ISSUE TITLE
不放在第一个tab时滚动失效Bug

### ISSUE THREAD

**Issue by feifanyajun** [ustbhuangyi/better-scroll#13]
![image](https://cloud.githubusercontent.com/assets/19487214/22055391/e11910a8-dd95-11e6-8b30-5c3d5f787c80.png)
通过这个tab控件加载插件分类组件，分类组件没有滚动效果，如果直接加载这个界面或者跳转到这个界面就 可以滚动
这个该如何设置啊？
mint-ui+vue2.0

![image](https://cloud.githubusercontent.com/assets/19487214/22055468/48980f7c-dd96-11e6-963e-423d700431b7.png)

**Comment by neurotoxinvx** [comment]
Console 有没有报错呢 ？目测来看可能是因为第一个之外的 TAB 获取不到外层容器宽高导致报错了哦
