### ISSUE TITLE
click event don't trigger when DOM is scrolling

### ISSUE THREAD

**Issue by zhylmzr** [ustbhuangyi/better-scroll#131]
I find the click event seem don't throw when DOM is scrolling or scrolled. like the gif

![demo](http://i.imgur.com/bTYLWMG.gif)

The demo: https://codepen.io/zhyl/pen/EvQMNe

**Comment by ustbhuangyi** [comment]
that is what expected, isn't it?

**Comment by zhylmzr** [comment]
I want to make user can click when scrolling. Have a solution?

**Comment by ustbhuangyi** [comment]
actually, scrolling won't stop trigger the 'click' event, because you listen on the 'li' tag, but click target is 'span' tag. so, you may listen on the 'span' tag or just remove span tag.

**Comment by zhylmzr** [comment]
Isn't 'span' click event bubbled to 'li' tag? 
And i remove the 'span' tag as same status.

**Comment by ustbhuangyi** [comment]
I have seen your demo carefully.  better-scroll won't stop trigger click while scrolling unless the scroll is out of boundaries. 
you can set your wrapper hight to a big value. and have a flick（do not let it scroll out of boundaries）, this time click is triggered as expected.

**Comment by zhylmzr** [comment]
Thanks, but i change the code of better-scroll to suit of my demand. I am silly comment out the dispatchEvent click event of custom and filter the 'touchstart', 'touchend' events has being preventDefault to use the native click event.

**Comment by ustbhuangyi** [comment]
Change source code is not recommend, as your demand,  you can configure BScroll by setting preventDefault to false and set click to false.  See the wiki: https://ustbhuangyi.github.io/better-scroll/doc/options.html#preventdefault.  And also, the code `if(!e._constructed) return` can be removed

**Comment by zhylmzr** [comment]
maybe, but the code show that will prevent native event.
```javascript
case 'click':
  if (this.enabled && !e._constructed) {
    e.preventDefault()
    e.stopPropagation()
  }
  break
```
The `if(!e._constructed) return` only use custom click event, can't use the native.

**Comment by ustbhuangyi** [comment]
you can listen and prevent touchmove outside of the box, to prevent page refresh

**Comment by zhylmzr** [comment]
Good idea, Thank you the guidance and the direction.
