### ISSUE TITLE
[New Feature] 为什么文档没有指导如何引入TS类型的？

### ISSUE THREAD

**Issue by suzhenghui-sky** [ustbhuangyi/better-scroll#1339]
### What problem does this feature solve?
为什么文档没有指导如何引入TS类型的？

### What does the proposed API look like?
为什么文档没有指导如何引入TS类型的？

**Comment by suzhenghui-sky** [comment]
看来作者并没有他说的那么的空闲。

**Comment by miaoyuqiang** [comment]
。。。。ts写的脑子疼，就是没文档，看来作者已经躺下了
