### ISSUE TITLE
音乐app，首页scroll刷新后发现计算下拉高度多余了接近1000px多的高度？

### ISSUE THREAD

**Issue by sunsunwong** [ustbhuangyi/better-scroll#135]
<!--recommend
--!>
<template>
  <div class="recommend">
    <scroll ref="scroll" class="recommend-content" :data="songLists">
      <div>
        <div v-if="recommends.length" class="slider-wrapper">
          <slider>
            <div v-for="item in recommends">
              <a :href="item.linkUrl">
                <img @load="loadImage" :src="item.picUrl">
              </a>
            </div>
          </slider>
        </div>
        <div class="recommend-list">
          <h1 class="list-title">热门歌单推荐</h1>
          <ul>
            <li v-for="item in radioLists" class="item">
              <div class="icon">
                  <img width="60" height="60" :src="item.picUrl">
              </div>
              <div class="text">
                  <h2 class="name" v-html="item.Ftitle"></h2>
                  <p class="desc" v-html="item.songListAuthor"></p>
              </div>  
            </li>
            <li v-for="item in songLists" class="item">
                <div class="icon">
                  <img width="60" height="60" :src="item.picUrl">
                </div>
                <div class="text">
                  <h2 class="name" v-html="item.songListDesc"></h2>
                  <p class="desc" v-html="item.songListAuthor"></p>
                </div>  
            </li>
          </ul>
        </div>
      </div>
    </scroll>
  </div>
</template>

<script type="text/ecmascript-6">
  import Scroll from '../../base/scroll/scroll.vue'
  import Slider from '../../base/slider/slider'
  import {getRecommend} from '../../api/recommend'
  import {ERR_OK} from '../../api/config'

  export default {
    data() {
      return {
        recommends: [],
        radioLists: [],
        songLists: []
      }
    },
    created() {
         this._getRecommend()
    },
    methods: {
      _getRecommend() {
        getRecommend().then((res) => {
          if(res.code === ERR_OK) {
            this.recommends = res.data.slider
            this.songLists = res.data.songList
            this.radioLists = res.data.radioList
          }
        })
      },
      loadImage() {
        if(!this.checkLoaded){
          this.checkLoaded = true
          this.$refs.scroll.refresh()
        }
      }
    },
    components: {
      Slider,
      Scroll
    }
  }
</script>

<style scoped lang="stylus" rel="stylesheet/stylus">
 @import "../../common/stylus/variable"

  .recommend
    position: fixed
    width: 100%
    top: 88px
    bottom: 0
    .recommend-content
      height: 100%
      overflow: hidden
      .slider-wrapper
        position: relative
        width: 100%
        overflow: hidden
      .recommend-list
        .list-title
          height: 65px
          line-height: 65px
          text-align: center
          font-size: $font-size-medium
          color: $color-theme
        .item
          display: flex
          box-sizing: border-box
          align-items: center
          padding: 0 20px 20px 20px
          .icon
            flex: 0 0 60px
            width: 60px
            padding-right: 20px
          .text
            display: flex
            flex-direction: column
            justify-content: center
            flex: 1
            line-height: 20px
            overflow: hidden
            font-size: $font-size-medium
            .name
              margin-bottom: 10px
              color: $color-text
            .desc
              color: $color-text-d
      .loading-container
        position: absolute
        width: 100%
        top: 50%
        transform: translateY(-50%)
</style>

<!--scroll
--!>
<template>
  <div ref="wrapper">
    <slot></slot>
  </div>
</template>

<script type="text/ecmascript-6">
  import BScroll from 'better-scroll'

  export default {
    props: {
      probeType: {
        type: Number,
        default: 1
      },
      click: {
        type: Boolean,
        default: true
      },
      data: {
        type: Array,
        default: null
      }
    },
    mounted() {
      setTimeout(() => {
        this._initScroll()
      },20)
    },
    methods: {
      _initScroll() {
        if(!this.$refs.wrapper) {
          return
        }
        this.scroll = new BScroll(this.$refs.wrapper,{
          probeType: this.probeType,
          click: this.click
        })
      },
      enable() {
        this.scroll && this.scroll.enable()
      },
      disable() {
        this.scroll && this.scroll.disable()
      },
      refresh() {
        this.scroll && this.scroll.refresh()
      }
    },
    watch: {
      data() {
        setTimeout(() => {
          this.refresh()
        },20)
      }
    }
  }
</script>

<style scoped lang="stylus" rel="stylesheet/stylus">
</style>

**Comment by ustbhuangyi** [comment]
不符合 issue 规范，不是本项目的问题不要在这里提 issue
