### ISSUE TITLE
scrollEnd事件似乎是没有参数的

### ISSUE THREAD

**Issue by xty1992a** [ustbhuangyi/better-scroll#136]
看了下源码,共有4处scrollEnd,3处为` this.trigger('scrollEnd');`
对比scroll事件是`                this.trigger('scroll', {
                  x: this.x,
                  y: this.y
                });`
望回复,谢谢!

**Comment by ustbhuangyi** [comment]
你看的什么版本的代码，scrollEnd 事件是有参数的

**Comment by xty1992a** [comment]
额,0.1.15,我的锅
