### ISSUE TITLE
script方式引入1.0.1 版本，滚动不生效

### ISSUE THREAD

**Issue by hanxin272623823** [ustbhuangyi/better-scroll#139]
1.测试地址 https://jsfiddle.net/gLf19xxb/  
2.详细的复现步骤：script方式引入滚动也不生效；
3.调用 BScroll 的代码 
   let scroll = new BScroll('.wrapper',{
      scrollY: true,
      click: true
  })
及 BScroll 版本（1.0.1）；
4.出现问题的机型（联想310S）、操作系统（Windows）、宿主环境、浏览器信息（谷歌浏览器）。

**Comment by ustbhuangyi** [comment]
如果是想要横向滚动的，应该设置 scrollX:true
