### ISSUE TITLE
加个设置bounceTop: true/false

### ISSUE THREAD

**Issue by admin00001** [ustbhuangyi/better-scroll#14]
bounceTop:false//代表不开启顶部弹力，就是拉到顶部时候没有弹力，scrollY只能为0

**Comment by ustbhuangyi** [comment]
需求是用手指拖动的时候超过边界也不开启弹力么？

**Comment by ustbhuangyi** [comment]
use bounce false in v0.1.12

**Comment by admin00001** [comment]
是的，这样可以满足判断没弹力这端x/y为0或者为最大值,好做下一步逻辑
