### ISSUE TITLE
better-scroll点击卡顿

### ISSUE THREAD

**Issue by spiritzx** [ustbhuangyi/better-scroll#145]
1. better-scroll版本为0.1.15和 1.2.1
2. 浏览器版本chrome59.0.3071.109（正式版本） （64 位）
3. 出现情况，当页面小幅度滚动完成之后，点击不生效，需要过段时间才能点击
4. better-scroll版本为0.1.8没出现这种情况

**Comment by ustbhuangyi** [comment]
还缺一个演示的地址

**Comment by liuhuanhui** [comment]
缺少有这个问题

**Comment by liuhuanhui** [comment]
你好 你解决没~
