### ISSUE TITLE
iOS8无法正常使用

### ISSUE THREAD

**Issue by koromon** [ustbhuangyi/better-scroll#148]
官方DEMO:
iOS8 系统无法下拉查看其它组件DEMO，进入普通组件查看 DEMO，布局错乱，并且 DEMO 无法滚动。

项目：
版本号："better-scroll": "^1.2.1"
```
new BScroll(this.$refs.productWrapper, {
          click: true,
          probeType: 3,
          pullUpLoad: true
        })
```
无法实现滚动，如果 click 设置为 true，一接触屏幕（即使是touchmove）也立刻触发点击事件（用 _constructed 判断过也是一样）。如果 click 为 false，依然无法实现滚动。

所以，请问是升级后不支持 iOS8 了么？之前用 0.4 版本是正常的

**Comment by ustbhuangyi** [comment]
已经解决，是没有为 ios8 加上 flex 的兼容写法，感谢反馈

**Comment by fxjs** [comment]
1.2.2还是有这个问题啊 黄老师
