### ISSUE TITLE
初始化完成后下面总是有大片留白

### ISSUE THREAD

**Issue by ripeBoy** [ustbhuangyi/better-scroll#149]
以下是页面代码
===========================================
  export default {
    components: {
      XHeader,
      Search,
      LoadMore
    },
    data() {
      return {
        menus: {},
        topShow: false,
        bottomShow: false,
        goodsScroll: ''
      };
    },
    methods: {
      scrollEvent: function () {
        if (!this.goodsScroll) {
          let _this = this;
          this.goodsScroll = new BScroll(this.$refs.listWrapper, {
            pullDownRefresh: true,
            click: true
          });
          this.goodsScroll.on("pullingDown", function () {
            _this.topShow = true;
            console.log('刷新了');
            setTimeout(function () {
              _this.topShow = false;
              _this.goodsScroll.finishPullDown();
            }, 500);
          });
          this.goodsScroll.on("scrollEnd", function () {
            if (_this.goodsScroll.y <= _this.goodsScroll.maxScrollY + 50) {
              _this.bottomShow = true;
              console.log('下拉加载');
              setTimeout(function () {
                _this.bottomShow = false;
              }, 500);
            }
          });
        } else {
          this.goodsScroll.refresh();
        }
      }
    },
    mounted() {
      this.$nextTick(() => {
        `this.scrollEvent();`
      });
    },
    created() {
    }
  };
![image](https://user-images.githubusercontent.com/24478225/29611745-589937a2-8831-11e7-8775-dd6b92b64a75.png)

**Comment by ustbhuangyi** [comment]
不符合 issue 规范，高度不对大多是因为 DOM 变化的时候没有 refresh 重新计算

**Comment by ripeBoy** [comment]
那麻烦问一下，在vue中初始化Scroll的事件放在哪个方法里比较好呢
