### ISSUE TITLE
raf.js 中 setTimeout 100 / 60  问题？网上资料都是 16.7 = 1000 / 60, 即每秒60帧，IScroll 也是这样。

### ISSUE THREAD

**Issue by jxZhangLi** [ustbhuangyi/better-scroll#153]
const DEFAULT_INTERVAL = 100 / 60

export const requestAnimationFrame = (() => {
  return window.requestAnimationFrame ||
    window.webkitRequestAnimationFrame ||
    window.mozRequestAnimationFrame ||
    window.oRequestAnimationFrame ||
    // if all else fails, use setTimeout
    function (callback) {
      return window.setTimeout(callback, (callback.interval || DEFAULT_INTERVAL) / 2) // make interval as precise as possible.
    }
})()

**Comment by ustbhuangyi** [comment]
其实并没有影响，即使你写 setTimeout(0)，也会至少在一个 Tick（约为 17ms）后才会执行回调
