### ISSUE TITLE
通过监听scroll事件可以得到滚动实时坐标，监听scrollEnd事件却不可以？

### ISSUE THREAD

**Issue by Aantabile** [ustbhuangyi/better-scroll#154]
您好，我在项目中使用better-scroll，发现在通过监听scroll事件可以得到此时滚动的实时坐标，而我认为监听滚动结束的时刻获取实时坐标更具有价值，因此监听了scrollEnd事件，但发现此时得到的数据为undefined？

**Comment by ustbhuangyi** [comment]
scrollEnd 只有在滚动结束的时候才会派发，如果滚动过程中获取坐标需要监听 scroll 事件
