### ISSUE TITLE
v1.2.2 scroll内部的input:text以外类型的input失效

### ISSUE THREAD

**Issue by CheerForMe** [ustbhuangyi/better-scroll#156]
使用的macbook + chrome + vue
BScroll：v1.2.2
```html
<scroll>
  <div>
    <!-- 代码...其中有input -->
  </div>
</scroll>
```
scroll内`<input type='checkbox'>`、`<input type='file'>`，点击完全没反应，亲测放到scroll外就好使了，并且在配置中添加
`preventDefaultException: {tagName: /^(INPUT|TEXTAREA|BUTTON|SELECT)$/}`仍然无效

在根元素绑定点击事件来打印`event.target`，其他区域都能打印出点击范围所属html，但是点击到input:file上没有任何反应

**Comment by CheerForMe** [comment]
使用preventDefaultException添加className的方式，还是不行

**Comment by ustbhuangyi** [comment]
需要提供可以运行的 demo 地址
