### ISSUE TITLE
不兼容 iOS8 么?

### ISSUE THREAD

**Issue by koromon** [ustbhuangyi/better-scroll#159]
最简单的 demo，代码如下，在线预览：https://jsfiddle.net/asrkz3qr/2/
```
<div class="outside" style="height: 200px;background:red;">
  <div class="container">
    <div class="inside" style="height: 400px;width:50%;background:green">inside</div>
  </div>
</div>
```
```
var target = document.querySelectorAll('.outside')[0];
var scroll = new BScroll(target)
```
在 iOS8 环境：
BScroll 版本 v0.4.0，可以正常实现上下滚动效果

BScroll 版本 v1.2.2，无法实现上下滚动效果。同时访问官方 demo 中的 `Slide` 组件，无法实现左右滑动，但是滑动的时候会立即触发点击事件。

所以现在项目目前还是使用旧版本的，如果作者能修复一下新版本的话就更好了，非常感谢~！

**Comment by fxjs** [comment]
我的ios8也不能左右滑动

**Comment by ustbhuangyi** [comment]
1.2.3 版本已经修复此问题

**Comment by fxjs** [comment]
1.2.3可以了 谢谢黄老师
