### ISSUE TITLE
better scroll里的元素无法触发原生的click事件

### ISSUE THREAD

**Issue by njleonzhang** [ustbhuangyi/better-scroll#161]
* 重现链接:
https://codepen.io/leonz/pen/OjoWrG

* 复现步骤；
1. 点击`test`区域，会弹出alert框
```
document.querySelector('.test').addEventListener('click', _ => {alert(123)})
```
2. 用手机打开页面，或者用chrome调试环境模拟一个手机环境(别忘记刷新下页面)
此时点击`test`区域，click事件不会触发，alert也就无法弹出。touchstart, touchend依然能触发。

3. 不初始化Better scroll则没有问题
```
    this.$scroll = new BScroll(this.el)
```

* BScroll:
`1.2.2`

* 出现问题的机型、操作系统、宿主环境、浏览器信息。
所有手机环境都有问题

* 问题分析
BScroll.prototype._start和BScroll.prototype.__end在默认情况下都会有走进`e.preventDefault()`的逻辑。touchstart和touchend的默认浏览器行为都被禁止了。在手机上click时间就是通过这2个事件来模拟的，default行为禁止了，就导致手机上的`click`事件无法被触发。`scroll-wrapper`内部的元素被touch后， touchstart和touchend的event都会冒泡到`scroll-wrapper`，然后都被禁用了默认行为,  @所以better-scroll里的所有元素（除了preventDefaultException以外）在手机上都无法触发`click`事件

```
  BScroll.prototype._start = function (e) {
    if (this.options.preventDefault && !preventDefaultException(e.target, this.options.preventDefaultException)) {
      e.preventDefault();
    }
  }
```
* workaround
把BScroll.prototype._start和BScroll.prototype.__end这2个函数里的`preventDefault`删除，问题就解决了。我没有细看其他代码了，所以不敢乱改。

**Comment by koromon** [comment]
这个配置 click 为 `true` 即可解决吧。可以看文档

**Comment by ustbhuangyi** [comment]
楼上正解

**Comment by njleonzhang** [comment]
……我知道可以解决，但是这不是问题么。

**Comment by ustbhuangyi** [comment]
很明显这不是问题

**Comment by njleonzhang** [comment]
```
click

类型：Boolean
默认值：false
作用：当设置为 true，better-scroll 会阻止浏览器的原生 click 事件，并自己派发一个 click 事件。为了区分和原生 click 事件，我们会给派发的 event 参数加一个私有属性 _constructed，值为 true。
```

不是问题么?! 文档里说`click`设置为true的时候，`better-scroll`会阻止浏览器原生的`click`事件。那么`click`是false的时候应该不会阻止原生事件。现在真实情况是`click`不管什么值，都是阻止原生事件, 必须设置`click`是true，否则`click`事件就没了。这**很明显**是一个问题，而且很严重，让人很费解。如果你确认现在的行为是正确的，那么请修改文档写清楚。

**Comment by ustbhuangyi** [comment]
@njleonzhang ，之前确实是文档没有描述清楚，已经修改

**Comment by ningsy1017** [comment]
```
 <li v-for="index in pages" :class="{'active':currentIndex === (index - 1)}" :key="index" 
         @click="clickNave(index)">
       <a href="javascript:void(0);" >{{index}}</a>
</li>
```

![image](https://user-images.githubusercontent.com/20644193/44335424-f95dca80-a4a6-11e8-96cb-c274931a3cdf.png)
我的这个事件在thinkpad的某个机型下就触发不了 试过加.native也不行 求解释咋回事

**Comment by xiaodaodizhen** [comment]
楼上这个问题是怎么解决的，求解

**Comment by ouyang5551555** [comment]
我遇到一个问题, 我的页面 app { overflow: scroll ;} 失效

**Comment by ouyang5551555** [comment]
比如我手机端 中间有一截 是better-scroll 的x轴滚动区域  如果这个区域y轴高度 超过了屏幕高度 这个时候我想上下滚动  发现 跟容器的 overflow: scroll; 在better-scroll区域没起作用,

**Comment by ouyang5551555** [comment]
仔细阅读了一下文档 设置 eventPassthrough 为 'vertical' 解决了我的问题
