### ISSUE TITLE
在better-scroll中使用swiper.js轮播插件后swiper.js无效，也不报错

### ISSUE THREAD

**Issue by xwpongithub** [ustbhuangyi/better-scroll#17]
我把自己的轮播初始化这部分的代码去掉以后，滚动区域又正常了，这可不可以算是better-scroll与其他第三方轮播插件间的冲突呢？如果有冲突，那要在scroll里使用轮播的话最好用啥插件和better-scroll配合？

**Comment by ustbhuangyi** [comment]
可能会有冲突， better-scroll 本身就可以做轮播，过阵子我们做一个轮播的 demo 出来

**Comment by xwpongithub** [comment]
哦哦哦。好滴好滴，黄老师就是黄老师~

**Comment by ustbhuangyi** [comment]
可以参考 demo 中 slider 的实现:https://ustbhuangyi.github.io/better-scroll/
