### ISSUE TITLE
在安卓的UC浏览器下touchend无效

### ISSUE THREAD

**Issue by dzjwan521** [ustbhuangyi/better-scroll#171]
外网地址  https://tb2b.yadea.com.cn/czpt.html
版本v1.2.3
代码不方便给出  
使用 scroll.on('touchEnd', touchEnd);
仅仅在安卓的UC浏览器下touchEnd事件不会触发

**Comment by dzjwan521** [comment]
版本1.2.3

**Comment by ustbhuangyi** [comment]
那就写一个最简单的 demo 示例放到 codepen 上吧

**Comment by dzjwan521** [comment]
经与UC的开发讨论，得出如下结果~~
    1.UC在内核不响应touchend事件的时候会补发一个touchcancel事件，开发者需要同时监听end和cancel事件，专门为UC做一下优化
    2.在UC的move事件并不是连续触发多次，而是只触发一次。根据x,y的值可以来判断改变距离。


这是uc论坛客服的回答 ,我看下better-scroll的api没有cancel事件 ,不清楚你的源码里有没有,我的代码会抽空补上,谢谢

**Comment by dzjwan521** [comment]
scroll = new BScroll(_this.$refs.list, {
                probeType: 1,
                click: true,
                scrollbar: {
                    type: null,
                    default: true
                }
            });
scroll.on('scroll', function(position) {

                if (position.y > 30) {
                     dosomething();
                }
            });
scroll.on('touchEnd', function(position){
           dosomething()
});

我大概的代码就是这样  在某些安卓自带浏览器   UC浏览器  touchend无法触发   这套代码微信端网页已经在生产环境了

**Comment by ustbhuangyi** [comment]
提供一下有问题的具体的 android 手机型号

**Comment by dzjwan521** [comment]
华为荣耀8   android7.0     在UC上有问题    红米4   Miui8.5  也是uc有问题   还有一款是客户的 没有记住品牌型号   自带浏览器和uc都存在这个问题

**Comment by dzjwan521** [comment]
魅族

**Comment by AmyFoxFN** [comment]
源码有同时监听touchcancel事件，而且我这边华为荣耀7 android5上的UC上试是没问题的，1.2.3和1.3.0版本都触发了touchEnd。要不是你试试最新版本的BetterScroll吧。

**Comment by Leosfen** [comment]
我的小米4（MIUI8.0以上，Android6.0）UC也有这样的问题，不过小米四默认的浏览器没有这样的问题，Android自带webview没有问题，我用的版本是（"better-scroll": "^1.2.0"）

**Comment by dzjwan521** [comment]
我现在用的jroll插件解决的,上面的朋友可以去试试  api差不多

**Comment by AmyFoxFN** [comment]
@Leosfen @dzjwan521 升级到BetterScrol最新版1.3.0就可以了
