### ISSUE TITLE
1.2.3版本的click事件无法兼容在pc端与移动端都触发

### ISSUE THREAD

**Issue by Jhin7782** [ustbhuangyi/better-scroll#173]
1. 设置click: true时，开启移动端点击事件，但pc端的点击事件会失效；
2. 不设置click选项，默认为click: false，此时pc端有点击事件，但移动端没有；

————————————————

有办法能兼容吗？不管是pc端还是移动端都能监听到点击事件

**Comment by ustbhuangyi** [comment]
不符合 issue 规范，需要提供演示地址

**Comment by w611363303798** [comment]
+1
