### ISSUE TITLE
官方例子太乱了根本学不了

### ISSUE THREAD

**Issue by EY5740** [ustbhuangyi/better-scroll#179]
如果没看过视频，根本不知道怎么用这个插件，弄了好久才会使用滚动。但想做picker，根本没法看。
文档里说去看例子，结果..
一个注释都没有。

**Comment by muzishuiji** [comment]
我也是你说的这种情况,你有解决吗?求助

**Comment by EY5740** [comment]
没救了。他的意思就是得把他的教程全看一遍。还不如去学其他框架。还不如去看原版的框架学习成本更低

**Comment by muzishuiji** [comment]
我就是觉得很难上手,就算读了源码我还是不晓得怎么做?一般的插件不应该就是一个css,一个js,一段示例代码,教怎么使用的吗?他现在都改成了vue的,我还没把vue学好,不晓得咋个弄啊.忧伤.你说的视频在哪里?原版的框架是指?

**Comment by EY5740** [comment]
原本是iscroll，picker.都有

**Comment by muzishuiji** [comment]
iscroll好上手吗?你最后的解决方案是?

**Comment by EY5740** [comment]
😓 最后只用了滚动功能。 scroll 使用时被注入的标签下面需要一个空白的子标签包裹内容。并且被注入的标签必须是有固定高度。而且动态渲染的内容不能自动撑开滚动距离，还要刷新一下。反正一系列蛋疼的问题。

**Comment by muzishuiji** [comment]
picker 的原生实现可以参考 https://github.com/ustbhuangyi/picker
作者回复给我一个上面的链接,你可以试试看,但是这个是不能联动的,这就很坑了,要是做时间选择肯定要联动的才行.如果使用这个需要在源码的基础上修改,我在看怎么改呢

**Comment by ustbhuangyi** [comment]
不要恶意揣测，我并没有在任何地方让你去学习我的视频教程。现在做开源真是难，把文档写详细，把demo写完整，做了中英文翻译，还是有人来喷。善意的讨论问题，我是非常欢迎的，如果是无脑喷或者伸手，请换一家。觉得不好用可以不用。

**Comment by muzishuiji** [comment]
没有恶意揣测啊？作者你是不是误会了，你没有让我们去学习教程啊！不过我倒是想知道学习教程在哪？想去学一学。没有任何否认和诽谤之意，我是觉得你很厉害的。我水平太低了，所以不能灵活使用你的插件，不过你推荐给我那个原生的还是可以用了，就是我需要自己改成联动的。我能理解你，你是觉得写那么明白了，你们还不能用，真是菜的很，可是我就是太笨。你很厉害而且乐于分享和帮助，很棒，我很佩服你。就是我太小白了，也不是伸手党就是太笨了不能灵活运用，你做的已经很好了，我只有自己去钻研提升自己。你不要生气，误会了哈。我不会用怪我

**Comment by muzishuiji** [comment]
我是再和他讨论小白该怎么办的问题，如果有言语不合适伤害到了你，我觉得很抱歉，但是我们绝对没有恶意揣测之意，我们对你只有敬意和崇拜。

**Comment by ustbhuangyi** [comment]
哦，我不是说你，是说另外那位。我不否认，通过我的教程，很多人知道了这个库。也是正因为很多人都用了，我是想好好做这个开源项目的，你可以看一下这个项目最近的提交记录。picker原生js版本也支持了联动选择，但是有些小问题，你可以对比看一下这里demo的代码。为什么用Vue写demo，因为确实Vue确实很适合移动端场景，但如果你能把demo看明白，用其他mvvm框架，甚至是原生js都能够实现。未来我们还会开源Vue移动端组件库，都是为了方便使用。至于课程，如果你感兴趣，可以去慕课网搜一下，有2门基于Vue的实战课程，不谦虚的说对Vue入门提高都很有帮助，但是是收费的。

**Comment by muzishuiji** [comment]
嗯嗯，好的，谢谢啦！我下来认真看一下。

**Comment by EY5740** [comment]
我没有揣测你让我们去看你的视频，但是看视频的一定是比较弱的一些人。让这些人去看demo确实有点太高估了。我跟着教程打完了项目，但运用到自己的项目时却发现各种问题各种行不通，文档不详细，demo太复杂。
不知道这个插件定位是给谁用的，高水平一些的自己会写，低水平的看不懂。

**Comment by ustbhuangyi** [comment]
@EY5740 
“看视频的一定是比较弱的一些人” ；不知道你是怎么得出这个结论的，如果你说你自己，那 ok。
“不知道这个插件定位是给谁用的”，这个库的定位就是来解决移动端一些基于用户滚动操作的场景的。
“高水平一些的自己会写”；据我所知，除了我们滴滴在用这个库，百度、携程等很多大公司也有在用这个库了，还有人改成 react 版本的。
BTW，如果你是一种吐槽的心态来讨论问题，我这里不欢迎，这也是我最后一次在这个 issue 回复你。你也不用回复了，我不想把 github 变成一个撕逼的地方。

**Comment by EY5740** [comment]
自己看看记录，谁在解决问题，谁在撕逼。
我遇到问题你直接关掉就算了，别人遇到问题我给出了解决方案你冒出来撕逼。

**Comment by ustbhuangyi** [comment]
你有看 issue 规范，你这种 issue 我不直接关？
已拉黑，真是浪费时间。

**Comment by Murrayee** [comment]
react版本的在哪 大神 ， 好想用你这个库~~。

**Comment by qiguoqianglovehtml** [comment]
看了一下这个组件库，一脸懵逼啊，这玩意儿没有新手入门案例，直挑重点参数说，组件库难道不是案例效果与代码共存吗？官网写参数作用，代码放在git上一大推，根本找不到两者之间的联系，直接用不了

**Comment by clevergod** [comment]
> 看了一下这个组件库，一脸懵逼啊，这玩意儿没有新手入门案例，直挑重点参数说，组件库难道不是案例效果与代码共存吗？官网写参数作用，代码放在git上一大推，根本找不到两者之间的联系，直接用不了

用不了不用，你牛逼你自己写
