### ISSUE TITLE
黄老师，关于饿了么app使用better-scroll后，切换回pc页面后，使用better-scroll部分的元素点击事件失效。一次事件都不触发

### ISSUE THREAD

**Issue by JaneFeng** [ustbhuangyi/better-scroll#183]
麻烦老师看到后，能回复一下我。我自己找bug已经很久了，但是还是不知道怎么解决

**Comment by JaneFeng** [comment]
黄老师，我刚刚终于解决了，感觉是版本的问题啊。。。我之前用的1.2.1 。。。卸载后安装最新版1.2.3就没问题了。。（热泪盈眶，好激动~~）

**Comment by wangxuedongOvO** [comment]
我这边使用也是1.2.3，单切回pc端，click事件还是失效的，一次也不触发。求教。

**Comment by JaneFeng** [comment]
你切到pc端的时候要刷新一次。或者就是重新npm install better-scroll。这个问题我也不太懂，当时我就是这样做的。出来的效果感觉和其他人的差不多。就暂时没管了。
如果你解决了，麻烦告诉我解决办法。
