### ISSUE TITLE
上拉onPullingUp多次触发

### ISSUE THREAD

**Issue by cqgsm** [ustbhuangyi/better-scroll#187]
`onPullingUp() {
            console.log(1);
            let start = this.start + this.limit;
            // 更新数据
            wxaqueryDoctor({
                start: start,
                limit: this.limit,
                keyword: this.searchTxt ? this.searchTxt : null,
            }).then((res) => {
                if (res.success) {
                    if (res.list.length > 0) {
                        this.doctorList = this.doctorList.concat(res.list);
                        // 有数据,页数加上
                        this.start = start;
                    } else {
                        // 没有数据了
                        setTimeout(() => {
                            this.$refs.scroll.forceUpdate();
                        }, 1000);
                    }
                } else {
                    return this.$vux.toast.text(res.message, 'center');
                }
                // 解锁数据
            });
        },`
这是我的 上拉加载事件， 该数据请求会触发很多次，表现在上拉，loading没有消失但是请求结束了，调用了this.$refs.scroll.forceUpdate(); 然后上拉事件会继续不停的触发。 setTimeout 1s后，请求速度很快也会出现这个问题。 下拉目前没有发现这种情况， 能否加上请求数据的时候 锁定接口的api。

问题2：
期望能能加timeout api。
当网络出现问题或者请求错误的时候，这个scroll组件，还能继续拉动

**Comment by ustbhuangyi** [comment]
不符合 issue 规范
