### ISSUE TITLE
如果手机键盘唤起，窗口resize，感觉滚动区域的大小不对，有解决办法吗？

### ISSUE THREAD

**Issue by gregzhang616** [ustbhuangyi/better-scroll#188]

**Comment by ustbhuangyi** [comment]
不符合 issue 规范

**Comment by langlong149** [comment]
![gif](https://user-images.githubusercontent.com/19711638/40034660-7bf7fa24-5830-11e8-92f2-12e2f11a2d0b.gif)
我也碰到这个问题。
编辑区域使用的是quill编辑器。键盘弹出后，滚动区域大小不对，具体可以看gif。

尝试过在键盘弹出后，调用refresh，并没有什么效果。resizePolling这个属性应该做了这件事。
`                setTimeout(() => {
                    ZmUtil.pageLog("quill scroller refresh");
                    this.quillScroller.refresh();
                },2000);`


@gregzhang616 你的解决了吗？

**Comment by iyangying** [comment]
我也遇到这种问题了， 只要在滚动区域唤起手机输入的键盘。。。滚动区域就不对了。。。 @ustbhuangyi @gregzhang616 @langlong149  你们解决了吗？？？

**Comment by langlong149** [comment]
我是给它加了一个padding-bottom暂时解决的。

发送自 Windows 10 版邮件应用

发件人: 炸米线
发送时间: 2018年5月30日 14:49
收件人: ustbhuangyi/better-scroll
抄送: langlang149; Mention
主题: Re: [ustbhuangyi/better-scroll]=?UTF-8?Q?_=E5=A6=82=E6=9E=9C=E6=89=8B=E6=9C=BA=E9=94=AE=E7=9B=98=E5=94=A4=E8=B5=B7=EF=BC=8C=E7=AA=97=E5=8F=A3resize=EF=BC=8C=E6=84=9F=E8=A7=89=E6=BB=9A=E5=8A=A8=E5=8C=BA=E5=9F=9F=E7=9A=84=E5=A4=A7=E5=B0=8F=E4=B8=8D=E5=AF=B9=EF=BC=8C=E6=9C=89=E8=A7=A3=E5=86=B3=E5=8A=9E=E6=B3=95=E5=90=97=EF=BC=9F?==?UTF-8?Q?_=28#188=29?=

我也遇到这种问题了， 只要在滚动区域唤起手机输入的键盘。。。滚动区域就不对了。。。 @ustbhuangyi @gregzhang616 @langlong149 你们解决了吗？？？
