### ISSUE TITLE
官网的上拉加载，当上拉加载后，往上滑动列表立马又触发了上拉加载，官网的例子看的很明显。

### ISSUE THREAD

**Issue by cqgsm** [ustbhuangyi/better-scroll#189]

**Comment by ustbhuangyi** [comment]
试试看最新版的 better-scroll 和 demo

**Comment by Xzillion** [comment]
感谢作者，1.25版本之前上拉加载之后滑动列表会重复触发pullingUp事件，
1.25版本上拉加载请求数据成功时，pullingUp事件不会重复触发
但如果请求失败，pullingUp事件还是会重复触发

**Comment by ustbhuangyi** [comment]
@Xzillion ,  今天又做了一些优化，可以用 1.2.6 版本的试试，并参考一下 demo 的实现
