### ISSUE TITLE
当惯性滚动到顶部或底部时，回弹有些生硬，不如原生的过渡平滑

### ISSUE THREAD

**Issue by yanglz1991** [ustbhuangyi/better-scroll#192]
当惯性滚动到顶部或底部时，回弹有些生硬，不如原生的过渡平滑
能不能修改一下参数，感觉惯性后的回弹有些过长，速度衰减的不平顺

**Comment by ustbhuangyi** [comment]
建议看文档尝试配置动画参数，如果仍然不满意可以修改源码尝试

**Comment by ouzhou** [comment]
是真的难受的一匹，别用css做回弹了，还是用js计算减速吧
这一点真比不上iscroll的感觉
@ustbhuangyi
