### ISSUE TITLE
label内的元素事件分发问题 

### ISSUE THREAD

**Issue by njleonzhang** [ustbhuangyi/better-scroll#193]
1.外网可访问的测试地址（可以调试的源码，借助 codepen 或者 JSFiddle）;
https://codepen.io/leonz/pen/jLRrMM

2.详细的复现步骤；
* 点击`test`
* input 会得到focus
我已经对事件进行了e.preventDefault()。所以正常的行为input就不应该被选中了
删除Bscroll的初始化，问题不会出现

```
    this.$scroll = new BScroll(this.el, {click: true, probeType: 1})

```

3.调用 BScroll 的代码及 BScroll 版本；
https://unpkg.com/better-scroll@1.2.2/dist/bscroll.js

4.出现问题的机型、操作系统、宿主环境、浏览器信息。
android /ios/mac chome

**Comment by ustbhuangyi** [comment]
初始化设置 click 为 false，监听 tap 事件模拟点击

**Comment by njleonzhang** [comment]
放弃使用click么  这只是workaround哎   还是希望能修复这个问题吧   我现在把div改成button元素来规避这个问题

**Comment by ustbhuangyi** [comment]
你能描述一下你的原始需求是什么吗？

**Comment by njleonzhang** [comment]
@ustbhuangyi 问题我能够通过替代方案解决，现在的行为你觉得没问题的话，那就不是问题。tnx
