### ISSUE TITLE
按demo写法无法实现下拉刷新后文字改变再回弹的动画效果

### ISSUE THREAD

**Issue by snakeninja110** [ustbhuangyi/better-scroll#197]
按demo方式写了scroll组件，下拉刷新后数据先回弹然后pullDown-wrapper盖在数据上 状态变成“刷新成功”之后消失，并不是像demo中那样有上滑动画。
上拉加载后当没有更多数据时，父组件上该在什么时间调用forceUpdate(),现在我的处理方式是没有更多时设置pullUpLoad为false  此时如果再下拉刷新(已把pullUpLoad重新设置为true) 就无法再进行上拉加载了。

**Comment by ustbhuangyi** [comment]
数据请求成功或者失败后，调用 forceUpdate，其它就仔细看 demo 的代码吧

**Comment by snakeninja110** [comment]
先调用了父组件的forceUpdate，然后在scroll组件里因为data的改变又调了一次forceUpdate(true)

**Comment by ustbhuangyi** [comment]
只有数据没有变化的时候才需要调用一次 forceUpdate

**Comment by snakeninja110** [comment]
再问一下  下拉刷新后的那个动画是写在哪个模块里的？我去源码里看下实现方式
