### ISSUE TITLE
最新的1.2.6版本对文件上传不友好

### ISSUE THREAD

**Issue by bring2014** [ustbhuangyi/better-scroll#204]
你好，今天我更新到了最新版本，发现input type=file都点击无响应；不初始化better scroll点击才有响应（弹出文件选择窗口）。
测试环境为pc端手机开发模式下。
我原来使用的是0.3.4版本，是没问题的。

**Comment by ustbhuangyi** [comment]
需要提供可以访问的 demo 外网链接

**Comment by bring2014** [comment]
调试发现handleEvent函数的case 'click'中少了“!/(SELECT|INPUT|TEXTAREA)/i.test(e.target.tagName)”的判断导致上述情况。不知道作者为啥去掉。
使用1.2.x版本调试demo如下：
<!DOCTYPE HTML>
<html lang="zh_CN">
<head>
    <meta name="viewport"
          content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
<title>test scroll</title>
<style type="text/css">
	.wrapper{
		position:fixed;
		top:0;
		left:0;
		bottom:0;
		width:100%;
		overflow:hidden;
	}
	.file-wrapper{
		position:relative;
		top:30px;
		left:16px;
		height:80px;
		width:180px;
		background-color:blue;
		font-size:14px;
		color:white;
	}
	.uploader_input{
		position:relative;
		height:100%;
		width:100%;
	}
	.content {
		position:relative;
		top:30px;
		margin:20px 0 20px 16px;
		width:80px;
		height:280px;
		background-color:green;
	}

</style>
</head>
<body>
<div class="wrapper">
	<div>
		<div class="file-wrapper">
			<input name="logo" class="uploader_input" type="file" accept="image/gif,image/jpeg,image/jpg,image/png"
                 multiple="multiple"/>
		</div>
		<div class="content"></div>
		<div class="content"></div>
		<div class="content"></div>
	</div>
</div>
<script type="text/javascript" src="bscroll.js"></script>
<script type="text/javascript">
	let scroll = new BScroll('.wrapper',{
		click: true
	})
	console.log(scroll)
</script>
</body>
</html>

**Comment by ustbhuangyi** [comment]
click 请设置为 false
