### ISSUE TITLE
  我做下拉刷新时,在基础组件scroll 中内部接收不到下拉的动作, 不知道啥原因,这段代码取自您的 example 中的 scroll

### ISSUE THREAD

**Issue by Ruanyang2015** [ustbhuangyi/better-scroll#205]
在基础组件scroll 中内部接收不到下拉的动作

this.scroll.on('pullingDown', () => {
// 接收不到下拉的动作
          this.beforePullDown = false
          this.isPullingDown = true
          this.pulling = true
          this.$emit('pullingDown')
        })

**Comment by ustbhuangyi** [comment]
需要配置 pullDownRefresh 为 true
