### ISSUE TITLE
使用rem导致非整数itemHeight带来的误差

### ISSUE THREAD

**Issue by TotooriaHyperion** [ustbhuangyi/better-scroll#206]
https://codepen.io/torihyper/pen/wqbYZN

移动端用户大多使用rem来设置高度，经常产生非整数的itemHeight，
应该根据scrollerHeight和items.length采用先乘后除的方式来消除误差。

https://codepen.io/torihyper/pen/vJodEO

这个是iscroll就一直有的bug，由于绝大多数场景使用的是transition，所以一般不会遇到。
开始一个新的animation之前，要清除旧的animation，否则如果旧animation的结束时间早于新animation则会导致最终定位为旧animation，并且画面闪动。
比如，在index-list的demo中，如果强制关闭transition（useTransition: false）那么在动画结束之前，点击右侧index的操作将被动画效果覆盖。

关联pr：https://github.com/ustbhuangyi/better-scroll/pull/184

**Comment by ustbhuangyi** [comment]
animation 这个确实可以先清除一下

**Comment by TotooriaHyperion** [comment]
虽然渲染到页面上的都是整数像素，但是他们并不是一致的，
在snap里，这种情况其实是得到了处理的：
比如10.25px的item，会生成
10px 10px 10px 11px 10px 10px 10px 11px的page，正因如此，snap并不会出现误差问题。
而在wheel中，这种情况并没有得到处理，所以才会出现误差。
至于demo的情况，在item非常多的时候，是会有很大误差的：
![image](https://user-images.githubusercontent.com/16434801/30255803-b6363e5e-96d8-11e7-96c8-71e16f7aaf1a.png)

**Comment by TotooriaHyperion** [comment]
如上图，在90的时候，已经错了整整1个itemHeight
在下图中，错位约半个itemHeight，截断了上面的
![image](https://user-images.githubusercontent.com/16434801/30255869-1fce8556-96d9-11e7-84dc-bf9831a881b1.png)

**Comment by TotooriaHyperion** [comment]
![image](https://user-images.githubusercontent.com/16434801/30256063-89a8db2e-96da-11e7-8c8f-daa2fe68699a.png)
如图， 实际的clientHeight是不同的，取item[0].clientHeight显然是不合理的。
这里要么使用nearestSnap来获得wheel对应的正确index，要么使用先乘后除的方式来消除误差。

**Comment by 1657413883** [comment]
@TotooriaHyperion  是的我也遇到这样问题,rem适配,item越多,误差越大

**Comment by TotooriaHyperion** [comment]
@1657413883 你可以先参照我上面先乘后除的方法临时处理一下。
对于这个问题，我还是觉得，pages不应该是snap独享，应该拿出来给大家使用。
而flick不应该修改原本行为，应该由用户来处理。并且应该作为单独的事件存在，不应该和momentum的判断标准混淆在一起。

**Comment by ustbhuangyi** [comment]
恩，rem 布局看来确实有问题
