### ISSUE TITLE
flick的判定或许不是很合理

### ISSUE THREAD

**Issue by TotooriaHyperion** [ustbhuangyi/better-scroll#208]
经常有用户在滑动中决定停在某一位置的情况，
此时如果采用最后一次move到end的时间来判定flick，会导致将用户整个滑动操作视为一个flick，
导致用户决定在+n位置停下的时候，并没有snap到+n位置，而是到了+1位置。这里会有明显的不合理跳动。
因此flick判定应该以滑动总时长为准。

关联codepen：https://codepen.io/torihyper/pen/brymLm
关联pr：https://github.com/ustbhuangyi/better-scroll/pull/207

**Comment by ustbhuangyi** [comment]
源码中是根据 duration = this.endTime - this.startTime 来算的间隔，并不是最后一次 move 到 end 的时间。 this.startTime 表示开始开始滑动的时间，这个时间会在慢速移动的过程中更新，所以考虑到这种 case，用户一开始慢速滑动，然后突然 flick 一下，如果按照你的逻辑，flick 是不会触发的。

**Comment by TotooriaHyperion** [comment]
https://github.com/ustbhuangyi/better-scroll/blob/master/src/scroll/core.js#L147
显然这个是根据momentumLimitTime来更新的。实际测试中300ms的momentumLimitTime会比较频繁地触发这种情况。测试用机：iPhone 5s，iPhone 6s，小米5s plus。
可能在不同设备上情况并不一样。
我所描述的case是，用户开始滑动比较快，接近目标之后逐渐降低速度然后松开手指的情况。这种情况确实较大概率会触发flick（略高于50%的几率）。看起来就像弹簧一样。明明从n拖动到了n+5然后减速放开，却又跳回了n+1。
虽然通过增加momentumLimitTIme可以缓解这一情况，但是同样也会导致momentum性能的下降。
并且，
1.flick操作和momentum的判断，在逻辑上也不应该属于同一分支，因此即使为flick更新startTime，也应该区别于momentum的startTime。
2.在snap中，flick的操作是n+1或n-1，而用户无论如何是不会为一个+1或-1的操作花费很长的整体时间的，因此我认为，flick操作应该是一个独立的操作，无需在_move中更新时间。
3.如果要实现用户慢速滑动后依然支持flick操作，那么应该在慢速滑动中动态改变当前的currentPage，或取flick操作触发时的nearestSnap，以确保用户的flick操作是针对减速时的最近目标。如果不需要支持这一case，那么，直接使用总滑动时长来判断，就可以完全杜绝误触发flick的情况。（实际上我认为这种情况是几乎不可能的，因为用户减速必然意味着要定位到目前减速位置，那么使用默认流程的snap是可以实现这一效果的，根本没有必要通过flick来实现，snap自身的flick只需要专注于明确的n+1、n-1操作。）

基于这种情况，我认为两种解决方式是合理的：
1.让flick只专注于纯粹的flick操作，即使用整体时长来判断。（就是我的pr）
2.让snap注册的flick只专注于明确的n+1、n-1操作。（修改snap注册的flick事件，在snap的flick中，snap到当前的nearestSnap + 1、nearestSnap - 1，而不是currentPage + 1或currentPage - 1。在开启snap的情况下载move里更新currentPage显然是影响性能的操作。）

**Comment by ustbhuangyi** [comment]
大概了解你的意思了，但这并不是 flick 的 bug。
flick 表示一次“轻拂”操作，默认的配置是一次滑动操作在 200ms 内移动小于 100 px。你这个 case 之所以有问题，是因为你的每个 snap 的高度都很小，用户在 move 的过程中其实已经改变了 currentPage，然后最后快速滑动触发了一次 flick，而这个时候 snap 里监听到 flick 的 currentPage 还是之前的，导致了 bug。

**Comment by TotooriaHyperion** [comment]
是这样的，所以对于这里的flick，我觉得要么认为这种触发在用户体验上是不合理的，要么这里的flick应该先获取nearestSnap。而更进一步的，我认为，默认事件不应该有改变原来的滑动行为的特征。或者至少这些行为应该是用户无感知的。
然后就是，最后触发flick并不是快速滑动，而是慢速滑动，只不过之前的滑动是快速的，所以在用户减慢速度的时候，触发了flick。
而你也说
默认的配置是一次滑动操作在 200ms 内移动小于 100 px
显然我这个case的“一次滑动”并不是指滑动结束时停止的操作，而应该是整个的滑动动作。从用户体验的角度，我认为这样的操作不应该被认为是flick。因为better-scroll是一个触屏滚动的工具，不是一个弹球小游戏=。=
滑动一段之后停下来定位，怎么想我也不觉得这应该被视为一次“轻拂”。
我刚刚试了ipadpro和小米5s plus的时间、日历设置，它们甚至根本不会触发flick事件。而却确保了在任意touchend时定位到最近元素的功能。我认为这样才是更合理的。

我看到你在文档中说，snap是实现类似轮播图或全屏滚动效果的。对于这种情况，显然这个flick没有问题，但是其它需要定位的情况呢？我认为snap的定位功能和flick功能应该是互相独立互不影响的。

虽然这个问题可以通过设置flickLimitTime = 0来解决，但这也意味着用户不能使用flick事件了。

**Comment by ustbhuangyi** [comment]
这个问题我觉得应该去修改 snap 的逻辑呀，flick 本质上没有啥问题，举个例子用户慢慢的滑动屏幕，停到了某个位置，没有抬手，这个时候再来一次快速滑动，触发 flick，也是合情合理。

**Comment by TotooriaHyperion** [comment]
你的意思是修改snap的默认flick，到触发flick时候的nearestSnap吗？
这确实是一种解决办法。
但是从代码结构，功能抽象，手势定义的角度，这都不是很合理。

**Comment by ustbhuangyi** [comment]
不过修改 _nearestSnap 也不是很好，因为至少轮播图这个 case，我应该每次只让他滚一屏，如果用 _nearestSnap，可能会出现一次滚 2 屏的 case。
你的原始需求是想用 snap 做 picker ？感觉你这种场景的 snap 或许压根就不监听 flick 会更好。

**Comment by ustbhuangyi** [comment]
打算给 snap 属性加一个 listenFlick 的字段，默认值为 true，如果设置为 false，则不会监听 flick 事件做额外的处理了，因为你这种场景和普通的轮播 snap 场景确实很不一样。
