### ISSUE TITLE
wheel 参数启用bug

### ISSUE THREAD

**Issue by shenxiang11** [ustbhuangyi/better-scroll#21]
如下两张图，加了wheel:true后，不仅无效，界面上出现元素被加上rotateX属性
<img width="314" alt="true" src="https://cloud.githubusercontent.com/assets/17292115/22820662/bf276768-efb2-11e6-89ce-579914684055.png">

<img width="314" alt="false" src="https://cloud.githubusercontent.com/assets/17292115/22820629/977cef4e-efb2-11e6-8c65-5af8cae0b099.png">

**Comment by ustbhuangyi** [comment]
wheel:true 这个是给 picker 组件使用的，普通的列表滚动不要使用这个属性

**Comment by shenxiang11** [comment]
@ustbhuangyi 老师 那鼠标滚轮就没法用了？PC端用，又不想要原生的滚动条，有什么好的解决方法吗？

**Comment by ustbhuangyi** [comment]
鼠标滚动可以用的，这个属性的含义之前文档写错了，我已经修复
