### ISSUE TITLE
关于preventDefault选项的作用

### ISSUE THREAD

**Issue by storkyeh** [ustbhuangyi/better-scroll#210]
文档中对于preventDefault选项作用的描述为`是否阻止原生的滚动`, 而其实际的作用应该为`是否阻止默认事件`, 查看better-scroll以前的[历史](https://github.com/ustbhuangyi/better-scroll/tree/next), 也是如此.
感觉`是否阻止默认事件`的描述更准确些.

**Comment by ustbhuangyi** [comment]
感谢反馈，已经修正。
