### ISSUE TITLE
click选项设置为true 之后 子元素的radio 等input元素点击事件被阻止

### ISSUE THREAD

**Issue by ranchoopenwrt** [ustbhuangyi/better-scroll#211]
1.外网可访问的测试地址（可以调试的源码，借助 codepen 或者 JSFiddle）;
演示环境
http://runjs.cn/detail/14bguesq
源码
http://runjs.cn/code/14bguesq
2.详细的复现步骤；
直接配置 better scroll
var scroll = new BScroll('.wraper', {
				probeType: 1,
          		click: true,
         		scrollX: false,
          		eventPassthrough: 'horizontal',
	            scrollbar: {
	             fade: true
	            }
			})

发现 子元素中的 checked 无法点击 
 把click设置为false 之后 就可以checked点击了
官方文档的 click解释为
`类型：Boolean
默认值：false
作用：better-scroll 默认会阻止浏览器的原生 click 事件。当设置为 true，better-scroll 会派发一个 click 事件，我们会给派发的 event 参数加一个私有属性 _constructed，值为 true。`
首先十分感谢黄老师提供这个好用的库 但是这个解释缺乏具体的demo 有点看不懂

总上所述  click设为true之后 check 不能点击 但是官方文档 对于input 的 checkbox radio的 是否能点击
只在preventDefaultException 提交了
3.调用 BScroll 的代码及 BScroll 版本；
版本v1.2.6
代码配置
var scroll = new BScroll('.wraper', {
				probeType: 1,
          		click: true,
         		scrollX: false,
          		eventPassthrough: 'horizontal',
	            scrollbar: {
	             fade: true
	            }
			})
4.出现问题的机型、操作系统、宿主环境、浏览器信息。
win10系统 谷歌浏览器

**Comment by ustbhuangyi** [comment]
如果设置 click 为 true，确实不能点击 checkbox 了，因为它会把默认的 click 行为阻止了。这个时候如果仍然想监听点击，可以用 tap 事件替代，文档这块我会再补充一些。

**Comment by ranchoopenwrt** [comment]
thx
