### ISSUE TITLE
首页只加载2条数据时，样式显示错误

### ISSUE THREAD

**Issue by SAOSO** [ustbhuangyi/better-scroll#213]
将example中的demo  vertical-scroll 中的items改为2个即可

重现步骤：
1，使用demo中的scroll组件，首页加载不满一屏幕的数据（只有两条数据的时候）。
2，下拉的bubble会一直存在。
3，会显示“加载更多”

![a](https://user-images.githubusercontent.com/29364780/30303759-95bccaca-979c-11e7-89ce-a071c52f9be1.png)

**Comment by SAOSO** [comment]
当数据不满一页的时候，无法开启下拉刷新

**Comment by ustbhuangyi** [comment]
这个可以考虑支持一下

**Comment by ustbhuangyi** [comment]
已经在 demo 组件中支持了数据少的情况，仍然可以上拉和下拉
