### ISSUE TITLE
在1.3.0版本下设置轮播loop属性为TRUE，不会克隆添加节点

### ISSUE THREAD

**Issue by linsywu** [ustbhuangyi/better-scroll#217]
版本：1.3.0
系统：mac ox 10.12.6

学习慕课网音乐webapp中安装的最新版本的better-scroll,但是在跟着编写slider插件的时候，dom结构里面怎么也没有多添加两个dom节点，各种检查排除编码错误后，更换了better-scroll版本到0.4.0版本，bug消失，slider子元素成功克隆并追加了两个dom。

[MySlider.txt](https://github.com/ustbhuangyi/better-scroll/files/1298559/MySlider.txt)

**Comment by ustbhuangyi** [comment]
1.3.0 版本的 API 已经发生了变化，请看文档。
https://ustbhuangyi.github.io/better-scroll/doc/options-advanced.html#snap
