### ISSUE TITLE
关于垂直滚动容器点击事件的问题求教

### ISSUE THREAD

**Issue by Richard-Choooou** [ustbhuangyi/better-scroll#221]
codepen 代码地址 https://codepen.io/Richard-Choooou/pen/NaPvbo/?editors=1111

在线预览地址 http://sgmuitest.duapp.com/components/schedule.html （需打开控制台后点击日程，查看console打印结果，建议使用这个站点在手机调试模式下预览）

是这样的， 容器初始化后点击日程，事件会执行两次，滚动容器后，事件只执行一次，之前尝试过 使用_constructed 这个属性，但是滚动前点击的 _constructed 两次都为ture ，不知道是我的代码问题还是库的bug，求解，谢谢

**Comment by ustbhuangyi** [comment]
看来 codepen 里的代码，你的 initDom 反复调用，导致点击事件也多次监听。同时 better-scroll 也 new 了多次，虽然你会调用 ```this.bScroll = null```，但这并没有清空之前监听的事件。在你这个 case 下，你应该调用的是 ```this.bScroll.destroy()```

**Comment by Richard-Choooou** [comment]
谢谢指点 :)
