### ISSUE TITLE
better-scroll 在vue+nuxt.js 中无法使用

### ISSUE THREAD

**Issue by guojs** [ustbhuangyi/better-scroll#222]
我安装nuxt.js 的插件引入方法，加载better-scroll 后，报错，提示document is not defined
不知如何解决，后者通过什么方法可以引用？

**Comment by ustbhuangyi** [comment]
better-scroll 是和 DOM 强相关的，所以不应该把初始化逻辑放到后端去跑，需要在节点渲染出来后再初始化

**Comment by guojs** [comment]
那better-scroll 是不是在我现有的框架中无法使用了？

**Comment by ustbhuangyi** [comment]
可以啊，初始化逻辑放到 mounted 钩子里不就好了

**Comment by Gemini-90s** [comment]
我目前使用这种方式是可以正常使用的
在plugins中新建better-scroll.js
```
let BScroll
if (process.browser) {
  BScroll = require('better-scroll').default
}
export default BScroll
```
使用的时候
import BScroll from '~/plugins/better-scroll'
在nuxt.config.js中build.vendor 下插入 '~/plugins/better-scroll.js' or better-scroll

**Comment by chengen12** [comment]
我的话，什么都没改，也能运行的。数据从 asyncData获取，渲染，mounted钩子里初始化BScroll，反正asyncData一定在 mounted之前的
