### ISSUE TITLE
refresh计算可滚动区域的bug

### ISSUE THREAD

**Issue by chemandy** [ustbhuangyi/better-scroll#223]
better-scroll计算可滚动区域宽高的代码是这样的：
parseInt(this.scroll.scroller.style.width) || this.scroll.scroller.clientWidth
当style中设置宽度不是px，例如：rem，此时宽度或高度计算就会出错。导致无法滚动。

**Comment by ustbhuangyi** [comment]
最新的代码已经修复了这个问题了
