### ISSUE TITLE
点击滚动列表里面的元素，发现点击子元素存在偶然无法点击的情况

### ISSUE THREAD

**Issue by Eric1991** [ustbhuangyi/better-scroll#224]
在一个ul>li的列表中，当滚动列表把底面的li滚动出来后，然后会有偶然无法点击的情况（同样再次滚动到顶部后，点击li也会经常出现），出现此情况后连续点击多次会成功，已排除原生事件的问题。 
        这么好的滚动插件，希望能解决一下此问题。

**Comment by ustbhuangyi** [comment]
不符合 issue 规范
