### ISSUE TITLE
制作下拉刷新的时候，在ios8.x系统上面无法滚动，但是低版本的bscroll可以实现

### ISSUE THREAD

**Issue by PhoenixAve** [ustbhuangyi/better-scroll#225]
1. 实现网址：https://github.com/chuanzaizai/scroll-demo 网址是别人的案例，我仿照他的写的
2. 我调用的版本 `1.2.2` ， 上面案例使用的版本 `0.1.12`
低版本是touchend事件不是toucheEnd事件
3. 出现的机型：ios8.x系统的iphone手机

**Comment by githubmann** [comment]
没有代码，无法定位问题。另；toucheEnd ->touchEnd

**Comment by AmyFoxFN** [comment]
1.2.2版本在ios8上存在一个bug。建议升级到最新版本。

**Comment by PhoenixAve** [comment]
@AmyFoxFN 1.3.0版本也是一样不能滚动

**Comment by PhoenixAve** [comment]
@githubmann 上面的github网址就可以看到代码啊

**Comment by xiejunping** [comment]
我的项目，ios8 上滚动就报一大堆错误

**Comment by AmyFoxFN** [comment]
@PhoenixAve 
首先较新的版本，已经不派发touchend，而是派发touchEnd。
另外新版本，已经内核支持下拉刷新和上拉加载，应该监听pullingDown，pullingUp事件，来做刷新。
建议看一下官方文档https://ustbhuangyi.github.io/better-scroll/doc/events.html#pullingdown，或这篇博文https://juejin.im/post/59b777015188257e764c716f。
