### ISSUE TITLE
希望提供一个vue可以直接使用的版本

### ISSUE THREAD

**Issue by tkggusraqk** [ustbhuangyi/better-scroll#226]

**Comment by ustbhuangyi** [comment]
未来我们会开源一套基于 Vue 的移动端组件库，底层依赖 better-scroll

**Comment by tangdw** [comment]
期待

**Comment by xiaolongyuan** [comment]
+1

**Comment by Abounce** [comment]
+1

**Comment by liudg** [comment]
您好，我遇到这样一个问题，我在nuxt里面使用这个滚动插件，当滚动列表是a标签的时候，点击会触发跳转两次。首先是router无刷新跳转，然后是a链接刷新跳转，代码如下
`<div class="slide" ref="slide">
        <div class="slide-group" ref="slideGroup">
          <div v-for="item in banners" class="slide-item">
            <nuxt-link :to="'/game/' + item.url">
              <img :src="item.src" :alt="item.title"/>
            </nuxt-link>
          </div>
        </div>
      </div>`
================初始化=================
`this.slide = new window.BScroll(this.$refs.slide, {
          scrollX: true,
          momentum: false,
          snap: {
            loop: this.loop,
            threshold: 0.3,
            speed: 400
          },
          click: this.click
        })`

**Comment by Aaronwkk** [comment]
+1

**Comment by kaimZhou** [comment]
+1

**Comment by 13189449986** [comment]
同vue,现在用的0.15,新版的3.15循环轮播用不了

**Comment by jianjian-web** [comment]
+1

**Comment by liuwenxiang** [comment]
+1

**Comment by jxZhangLi** [comment]
@ustbhuangyi 若在本地环境编写vue (非node环境下) 怎么调用（使用）better-scroll vue 的滑动插件呢

**Comment by wcldyx** [comment]
+1

**Comment by ustbhuangyi** [comment]
https://github.com/didi/cube-ui/
出门右转 cube-ui 开源~

**Comment by yangqihua** [comment]
我根据作者的文章也封装了一个better-scroll的vue用法
https://github.com/yangqihua/vue-scroll-mobile-demo

**Comment by bestime** [comment]
`finishPullDown` 为什么没有提供回调函数。我怎么得到准确的回到顶部的时机。`scroll` 不能监听通过`finishPullDown`的回退动画中，滚动过程的 `x` 和 `y`

**Comment by kjs-zjl** [comment]
请问这个插件在电脑端是不支持鼠标滚轴滚动吗，我用鼠标滚轮滚动没有反应

**Comment by kjs-zjl** [comment]
+10086

**Comment by hedgehog10086** [comment]
"better-scroll": "^2.2.1",
中怎么使用tap事件啊，我设置ltap:true没反应
