### ISSUE TITLE
老师你好，我在Vue@1.0中使用better-scroll滑动无效

### ISSUE THREAD

**Issue by TrustTheBoy** [ustbhuangyi/better-scroll#23]
vue.js@1.0
better-scroll@0.1.12
![filehelper_1486832611539_29](https://cloud.githubusercontent.com/assets/20201085/22855731/b40ee9b0-f0bf-11e6-8ff1-c38c73470094.png)
![filehelper_1486832611632_41](https://cloud.githubusercontent.com/assets/20201085/22855733/ba48ccec-f0bf-11e6-83cd-3c4ecc0c6cf0.png)
![filehelper_1486832611695_58](https://cloud.githubusercontent.com/assets/20201085/22855735/c5648832-f0bf-11e6-9f74-5d003f312841.png)
![filehelper_1486832611757_43](https://cloud.githubusercontent.com/assets/20201085/22855737/ce19c6fe-f0bf-11e6-9c65-e91f7bc01edd.png)

**Comment by TrustTheBoy** [comment]
这里是演示地址：[](http://api.biaoxintong.com:8080/landing-craft/craftFiles/schoolbus/index.html#!/index/1/%E6%9B%B2%E6%B1%9F%E6%A0%A1%E5%8C%BA%E2%80%94%E6%9C%AC%E9%83%A8%E6%9B%B2%E6%B1%9F%E6%A0%A1%E5%8C%BA%E2%80%94%E6%9C%AC%E9%83%A8%E6%9B%B2/123)

**Comment by neurotoxinvx** [comment]
@TrustTheBoy  根据代码截图来看， BetterScroll 实例化的时机不对，init 的时候当前页的滚动区域内容高度并不需要 scroll ,BetterScroll 便没有创建 Scroll ，切换到途径站点的时候虽然 content 内容变增加，但是你没有手动刷新 BetterScroll ，于是不会重新计算，也不会滚动。

**Comment by TrustTheBoy** [comment]
@neurotoxinvx 谢谢，已解决
