### ISSUE TITLE
在数据小于页面高度的时候无法产生滚动效果，这时下拉刷新也无法使用

### ISSUE THREAD

**Issue by snakeninja110** [ustbhuangyi/better-scroll#234]
1.在数据小于页面高度的时候无法产生滚动效果，这时下拉刷新也无法使用
2.数据小于页面高度的时候pulldown这div会显示在数据下方，只有拉一下页面才会到初始位置去（这一点我先做了透明度的隐藏然后在beforePullDown的时候把透明度改掉）

**Comment by ustbhuangyi** [comment]
需要对列表的 CSS 部分做一些修改，代码参考：https://github.com/ustbhuangyi/better-scroll/blob/master/example/components/scroll/scroll.vue

**Comment by snakeninja110** [comment]
第一条有办法解么？数据不满容器的时候无法下拉刷新？

**Comment by ustbhuangyi** [comment]
建议你把项目 clone 下来，把 demo 里的数据改少一些看看效果

**Comment by Bravo123** [comment]
> 第一条有办法解么？数据不满容器的时候无法下拉刷新？

请问您解决了这个问题了吗
