### ISSUE TITLE
scroll组件内的文字在浏览器中无法选中复制。

### ISSUE THREAD

**Issue by Zacccccc** [ustbhuangyi/better-scroll#235]
您好，
vue2 + better-scroll0.2.4，scroll组件中p标签内的文字，无法再pc浏览器复制、无法在手机长按选取及复制。
请问是否有办法解决这个问题呢？
scroll组件外的文字，在页面中可以复制。
css添加user-select:text/all; 也没有效果

**Comment by ustbhuangyi** [comment]
请移步最新版的 better-scroll，并参考文档：https://ustbhuangyi.github.io/better-scroll/doc/options.html#preventdefaultexception

**Comment by duanxb** [comment]
> 请移步最新版的 better-scroll，并参考文档：https://ustbhuangyi.github.io/better-scroll/doc/options.html#preventdefaultexception

你好，添加上这个属性preventdefaultexception后，可以复制了，但是当 scroll 刷新重新计算refresh()的时候，则又无法长按复制了。

**Comment by qinouz** [comment]
> > 请移步最新版的 better-scroll，并参考文档：https://ustbhuangyi.github.io/better-scroll/doc/options.html#preventdefaultexception
> 
> 你好，添加上这个属性preventdefaultexception后，可以复制了，但是当 scroll 刷新重新计算refresh()的时候，则又无法长按复制了。

请问解决了么 我现在页遇到这个问题了

**Comment by Haiwar** [comment]
解决方法：

```
const classIgnore = '需要被选择的class类名'
const tagException = {
  className:new RegExp(classIgnore,"i")
}
new BScroll(".wrapper",{
  tagException:tagException
})
```
