### ISSUE TITLE
在用slider组件时，第一次进入时就自动切换到了第二张图片（不算复制的2张），这样就形成了错位，但是刷新页面后就正常了，slider 组件用代码时老师vue-music里的那个

### ISSUE THREAD

**Issue by Leyoz** [ustbhuangyi/better-scroll#236]

**Comment by ustbhuangyi** [comment]
better-scroll 有升级，参考 better-scroll example 里的代码：https://github.com/ustbhuangyi/better-scroll/blob/master/example/components/slide/slide.vue
