### ISSUE TITLE
a链接点击调用两次

### ISSUE THREAD

**Issue by liudg** [ustbhuangyi/better-scroll#239]
您好，我遇到这样一个问题，我在nuxt里面使用这个滚动插件，当滚动列表是a标签的时候，点击会触发跳转两次。首先是router无刷新跳转，然后是a链接刷新跳转，代码如下
`<div class="slide" ref="slide">
        <div class="slide-group" ref="slideGroup">
          <div v-for="item in banners" class="slide-item">
            <img :src="item.src" :alt="item.title" @click="toLink(item.url)"/>
          </div>
        </div></div>`
================初始化=================
`this.slide = new window.BScroll(this.$refs.slide, {
          scrollX: true,
          momentum: false,
          snap: {
            loop: this.loop,
            threshold: 0.3,
            speed: 400
          },
          click: this.click })`

**Comment by ustbhuangyi** [comment]
不符合 issue 规范
