### ISSUE TITLE
使用better-scroll的时候，内层ul不能滚动到底

### ISSUE THREAD

**Issue by js-learn-ing** [ustbhuangyi/better-scroll#24]
￼
￼
![image](https://cloud.githubusercontent.com/assets/24387553/23060766/1b39492c-f53a-11e6-9d4b-f1214e42eeb9.png)

**Comment by ygtzz** [comment]
这个问题解决了吗？

**Comment by js-learn-ing** [comment]
后来没用这个插件了


发自网易邮箱大师
在2017年03月10日 14:55，mengwei 写道:

这个问题解决了吗？

**Comment by ygtzz** [comment]
不用插件，滚动如何做的，能分享一下吗，多谢

**Comment by js-learn-ing** [comment]
那个，我用了
-webkit-overflow-scrolling : touch;


发自网易邮箱大师
在2017年03月15日 13:41，mengwei 写道:

不用插件，滚动如何做的，能分享一下吗，多谢
