### ISSUE TITLE
卸载和初始化事件

### ISSUE THREAD

**Issue by ivanberry** [ustbhuangyi/better-scroll#242]
对比了下iscroll和better-scroll，在尝试过程中，因功能问题，有这么个操作：
```javascript
scroll._initEvent(true); 
scroll._initEvent(); 
```
我看了下better-scroll的源码，有个类似的函数，故尝试如下
```javascript
scroll._handleDOMEvents(addEvent);
scroll._handleDOMEvents(removeEvent);
```
其中`addEvent`和`removeEvent`是从源码中翻出来，与iscroll对应的函数，不过好像没有暴露，不知道怎么饮用。请指点一二，另项目文档是不是不太健全，没用过iscroll的人，根本不知道从哪儿开始

**Comment by ustbhuangyi** [comment]
这些是 better-scroll 内部初始化用的，并不需要暴露，也不需要用户主动调用。
另外是有详细的文档提供的，仔细看 readme 吧。
