### ISSUE TITLE
scroll滚动停止时，迅速点击click事件，事件无效

### ISSUE THREAD

**Issue by Chryseis** [ustbhuangyi/better-scroll#243]
当我下拉滚动条时，迅速点击click事件，事件并没有触发，而是滚动条container的transiform还在不停的计算，有什么办法可以把这个延迟处理掉？
![123](https://user-images.githubusercontent.com/13757352/30770422-3d7bd3f4-a063-11e7-9c2d-962c70dfe906.gif)
代码地址:https://github.com/Chryseis/elemDemo4React

**Comment by ustbhuangyi** [comment]
目前的设计就是当滚动的位置超过最大边界的时候，自定义的点击是无效的。

**Comment by Chryseis** [comment]
好的 谢谢

**Comment by Chryseis** [comment]
好的 谢谢

**Comment by ustbhuangyi** [comment]
不过这个 feature 我会评估一下是否合理，如果合理的话，也可以考虑做的

**Comment by jujingyi0618** [comment]
这个问题是很难受 - -

**Comment by HzLinWeiRan** [comment]
一般用户不知道为什么click失效

**Comment by BabyCY** [comment]
同遇到此问题

**Comment by ustbhuangyi** [comment]
结合 #295 ， 考虑了一下，和微信列表交互一致，当列表在滚动的过程中，包括滚动超出边界的时候，不允许点击。关于点击失效与否，可以用按压态表示，参考：https://ustbhuangyi.github.io/better-scroll/#/examples/index-view/en。

**Comment by gaoshijun1993** [comment]
@ustbhuangyi 最近在使用better-scroll的过程中也遇到了这个问题，具体表现就是列表在肉眼可见已经停止滚动后进行点击无效，需要等待一段时间后才能点击。在官方的demo中也有这种情况存在，但是不是很严重，大概跟页面性能可能也有关系。我猜测应该是在肉眼可见停止滚动后，滚动事件还没有完全完成，所以会造成这样点击迟钝的现象。期望能够修复~

**Comment by ustbhuangyi** [comment]
这个问题已经解决了

**Comment by nkbui** [comment]
@ustbhuangyi 的确有点影响强迫症体验，用户感官上觉得滚动快要停止了（滚动非常慢了），这时候手痒去click很正常的，但是click事件就触发不了，要等个大概不到一秒钟才能触发，期间用户手速快点的能点击2-3次没反应的click
