### ISSUE TITLE
有沒有非vue的原生可直接用版本

### ISSUE THREAD

**Issue by muzishuiji** [ustbhuangyi/better-scroll#244]
有沒有非vue的原生可直接用版本呢?你的demo里是一套体系,我只想用picker可是我没办法分离,
有没有只有pinker的demo,包含它的标签,用到的css和js 呢?我这个小白不知道该怎么上手改你的
源码以适应我的需求,请求帮助.

**Comment by ustbhuangyi** [comment]
better-scroll 本身就是原生 JS 开发的，picker 的原生实现可以参考 https://github.com/ustbhuangyi/picker，但是那个仓库我并不打算维护，你也可以看看 vue demo，理解后转成原生实现。
