### ISSUE TITLE
vue 中 checkbox 点击无效 该怎么处理

### ISSUE THREAD

**Issue by jjj694746002** [ustbhuangyi/better-scroll#246]
click和tap都为true，但是checkbox还是无法点击
<input type="checkbox" v-model="order[i].check" :value="ord.c_id" @click="checkone(i,n)" />

**Comment by ustbhuangyi** [comment]
click 不要设置为 true，用 v-model 取值就好。

**Comment by jjj694746002** [comment]
<input type="checkbox" v-model="order[i].check" :value="ord.c_id" @click="checkone(i,n)" />
我这里的input 不仅仅绑定了v-model 还绑定了click 事件的，click为false的话，checkone函数就无法执行了。
