### ISSUE TITLE
黄老师，能否给我详细解释下这个momentum方法是干啥的，尤其是里面这些算法为得出最后的结果起到了啥作用~

### ISSUE THREAD

**Issue by xwpongithub** [ustbhuangyi/better-scroll#25]
function momentum(current, start, time, lowerMargin, wrapperSize, options) {
	let distance = current - start;
	let speed = Math.abs(distance) / time;

	let {deceleration, itemHeight, swipeBounceTime, bounceTime} = options;
	let duration = options.swipeTime;
	let rate = options.wheel ? 4 : 15;

	let destination = current + speed / deceleration * (distance < 0 ? -1 : 1);

	if (options.wheel && itemHeight) {
		destination = Math.round(destination / itemHeight) * itemHeight;
	}

	if (destination < lowerMargin) {
		destination = wrapperSize ? lowerMargin - (wrapperSize / rate * speed) : lowerMargin;
		duration = swipeBounceTime - bounceTime;
	} else if (destination > 0) {
		destination = wrapperSize ? wrapperSize / rate * speed : 0;
		duration = swipeBounceTime - bounceTime;
	}

	return {
		destination: Math.round(destination),
		duration
	};
};

**Comment by ustbhuangyi** [comment]
为了 swipe 快速滑动的时候根据手指滑动的距离和时间计算最终滚动的位置和滚动的时间，再配合缓动函数就生成滑动的动画了。

**Comment by xwpongithub** [comment]
原来如此~~~~谢谢黄老师~
