### ISSUE TITLE
When i set the property of pullUpLoad false, there were some problems

### ISSUE THREAD

**Issue by chenyihao2621023** [ustbhuangyi/better-scroll#250]
In the demo `Normal Scroll List`[ https://ustbhuangyi.github.io/better-scroll/#/examples/en](url)

When i set the property of pullUpLoad false 
`
let options = {
        pullUpLoad: false
      }
`

this.scroll.on('scroll') dosen't work in the function `_initPullDownRefresh`

`
_initPullDownRefresh() {
this.scroll.on('scroll', (pos) => {
  console.log(pos)
})
}
`

And i have some problems in `pullDownRefresh`  because of that

**Comment by ustbhuangyi** [comment]
ok, it's a bug, need to fix
