### ISSUE TITLE
微信端的问题

### ISSUE THREAD

**Issue by Astaca** [ustbhuangyi/better-scroll#251]
1.在微信端将preventDefault 设为false,滚动会带动微信浏览器的滚动，出现不友好的体验。（pc浏览器正常）
2.this.scroll = new BScroll(this.$refs.wrapper, {
	                	scrollbar:true,
	                	click:false,
	                	bounce:false,
	                	preventDefault:false,
	                })
3.版本最新
4.ios

**Comment by ustbhuangyi** [comment]
preventDefault:false 不会阻止浏览器默认滚动行为，为何要设置这个属性？
