### ISSUE TITLE
列表筛选完成后，如何实现主动触发下拉刷新效果？

### ISSUE THREAD

**Issue by itHulk** [ustbhuangyi/better-scroll#252]
您好，刚刚接触better-scroll,请教您一个问题，目前下拉刷新只能通过手势去实现，但是实际场景中，有列表筛选这种，如何主动触发下拉刷新？  我调用了demo里的onPullingDown方法，但是这样就不带动画效果了。

**Comment by ustbhuangyi** [comment]
能配合图文描述一下你的具体需求？

**Comment by itHulk** [comment]
您好，感谢您的回复，项目结构如下
![qq 20170927152221](https://user-images.githubusercontent.com/22711051/30900776-c67e0b40-a397-11e7-8b67-83e6e155464a.png)

我想在每次列表页面进入的时候，自动触发一次下拉刷新的效果，头部条件筛选，添加筛选条件之后，触发一次下拉刷新的效果。如下图demo中的下拉刷新，但是目前只能手动触发下拉刷新。请指教
![qq 20170927152229](https://user-images.githubusercontent.com/22711051/30900772-c0d6c2ea-a397-11e7-9682-f6ea7301b34a.png)

**Comment by itHulk** [comment]
就是我想去主动下触发拉刷新的效果，如何实现呢，现在根据demo，只能通过手势滑动，实现下拉刷新

**Comment by ustbhuangyi** [comment]
我认为你这个需求，应该去直接请求更新数据，“手动触发下拉刷新” 是一个多余的动作。
