### ISSUE TITLE
表单元素的bug

### ISSUE THREAD

**Issue by iiicon** [ustbhuangyi/better-scroll#253]
页面中有表单元素的时候   表单元素和其父元素无法监听到blur  click 这些原生事件， 想问问有解决办法吗？

**Comment by ustbhuangyi** [comment]
需要配置 click 为 false

**Comment by iiicon** [comment]
那click怎么办

**Comment by iiicon** [comment]
禁掉原生的click  blur还是没有效果  tap也不起作用  是我姿势不对吗？

**Comment by Astaca** [comment]
同样的问题，请问解决了吗

**Comment by ustbhuangyi** [comment]
这个问题稍后会提供解决的 demo

**Comment by ustbhuangyi** [comment]
参考最新的 demo:https://ustbhuangyi.github.io/better-scroll/#/examples/form-list/zh
以及源码：https://github.com/ustbhuangyi/better-scroll/blob/master/example/pages/form-list/index.vue
