### ISSUE TITLE
bs picker在app下滑动过快会消失

### ISSUE THREAD

**Issue by ZhengXiaowei** [ustbhuangyi/better-scroll#256]
![image](https://user-images.githubusercontent.com/15809841/30899679-74b0e444-a393-11e7-8546-c13dfee76522.png)
1.picker在ios app下 滑动过快会(慢慢滑动不会出现这个情况)出现item 消失的情况 然后如果手指再触碰上去或者再慢慢滑动就会显示
2.测试环境ios app(iPhone7 IOS11),安卓app下无此情况,chrome手机模式下也无此情况,ios Safari暂没测试 未知
3.bs版本是最新的

**Comment by ZhengXiaowei** [comment]
![1](https://user-images.githubusercontent.com/15809841/30899824-1e16619e-a394-11e7-843f-c27279e26bf8.gif)
啊 上传的gif变静态图了 我重新上传个

**Comment by ustbhuangyi** [comment]
微信测试并未出现此问题

**Comment by ZhengXiaowei** [comment]
那是我打包成app的原因吗.. 我刚试了下在iphone Safari下和微信下 也无此问题

**Comment by ustbhuangyi** [comment]
是不是你们 app 里的 webview 有什么 bug，你试试慢慢拖动，当手指移出屏幕外，列表能否能回来。

**Comment by ZhengXiaowei** [comment]
app是通过cordova 打包而成的 
只要慢慢拖动 就不会有什么问题 一切都是正常 只有快速滑动的时候才会出现此问题

**Comment by ustbhuangyi** [comment]
啊，那应该就不是 better-scroll 的问题了。
