### ISSUE TITLE
惯性滚动的回弹距离能配置吗？

### ISSUE THREAD

**Issue by PhoonLee** [ustbhuangyi/better-scroll#257]
better-scroll版本：v1.3.0
没找到配置回弹距离的参数，感觉快速滑动到顶部，回弹距离太大了。

**Comment by ustbhuangyi** [comment]
可以配置 deceleration，https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#deceleration
deceleration 的值越大，滚动的距离就越近。
其实目前的配置看来，在移动端体验还 ok。

**Comment by PhoonLee** [comment]
@ustbhuangyi 
我再调调看，一开始我也是设置过这个参数数值，但一直没拿捏好。值大了，回弹距离是小了些，但惯性滚动体验就差了。
