### ISSUE TITLE
关于事件冒泡的问题

### ISSUE THREAD

**Issue by Astaca** [ustbhuangyi/better-scroll#259]
当click为true时，click.stop、click.stop.prevent就失效了，请问又该怎么取消事件冒泡呢？

**Comment by ustbhuangyi** [comment]
并不会呀，建议像 issue 模板那样提供一个外网可以访问的测试地址，方便定位问题

**Comment by Astaca** [comment]
<template>
	<div>
		<section id="scroll-wrapper" class="wrapper" ref="wrapper">
	        <div id="scroll-container" class="content">
				<ul class="production-list-container">
					<li v-for="(pro,index) in pros">
		                <router-link :to="{path:'detail',query:{pid:pro.id}}">
		                    <h5 class="text-ellipsis-2" @click.stop.prevent="alert">{{index}}</h5>
		                </router-link>
		            </li>
	            </ul>
		    </div>
		</section>
	</div>
</template>
<script>
import api from '../api/api';
import BScroll from 'better-scroll';
export	default{
	name:'demo',
	data(){
		return{
			pros:[

			],
			page:1,
			homeUrl:global.home_url,
		}
	},
	created(){
		this.GetIndexLove(this.page);
	},
	methods:{
		GetIndexLove: function(page){
	        api.ajax('GetIndexLove',{device: "3", channel_id:1, pageIndex:page}).then(res => {
	            // console.log(this.page)
	            if(res.data.length == 0){
	                this.more = '我也是有底线的';
	            }
	            this.pros = this.pros.concat(res.data);
	            this.$nextTick(() => {
	              if (!this.scroll) {
	                this.scroll = new BScroll(this.$refs.wrapper, {
	                	click:true,
	                	bounce:false,
	                })
	                this.scroll.on('touchEnd', (pos) => {
	                  // 加载更多
	                  if (pos.y <= (this.scroll.maxScrollY + 50)) {
	                      this.GetIndexLove(++this.page);
	                  }
	                  this.scroll.refresh()
	                })
	              } else {
	                this.scroll.refresh()
	              }
	            })
	        }).catch(error => {
	            console.log(error)
	        });
	    },
	    alert(){
	    	console.log(123)
	    }
	}
}
</script>
<style scoped>
/*@import '/static/css/order.css';*/
ul{padding: 0; margin:0;}
li{display: inline-block;
    vertical-align: top;
    width: 3.7rem;
    height: 5.2rem;
    margin: 0 0 0.1rem 0;
    background-color: #f4f4f4;
}
li a{
	width: 3.7rem;
    height: 5.2rem;
    display: inline-block;
}
li:nth-child(2n){
	background-color: #ccc;
}
</style>

这样可以不可以，写了一个简单的demo，数据请求这块换一下（没有申请CodePen 或者 JSFiddle）

**Comment by ustbhuangyi** [comment]
建议去注册一个，方便调试

**Comment by Astaca** [comment]
<template>
	<div>
		<section id="scroll-wrapper" class="wrapper" ref="wrapper">
	        <div id="scroll-container" class="content">
				<ul class="production-list-container">
					<li v-for="(pro,index) in pros">
		                <router-link :to="{path:'detail',query:{pid:pro.id}}">
		                    <h5 class="text-ellipsis-2" @click.stop.prevent="alert">{{index}}</h5>
		                </router-link>
		            </li>
	            </ul>
		    </div>
		</section>
	</div>
</template>
字数原因我成三段了

**Comment by Astaca** [comment]
<section id="scroll-wrapper" class="wrapper" ref="wrapper">
	        <div id="scroll-container" class="content">
				<ul class="production-list-container">
					<li v-for="(pro,index) in pros">
		                <router-link :to="{path:'detail',query:{pid:pro.id}}">
		                    <h5 class="text-ellipsis-2" @click.stop.prevent="alert">{{index}}</h5>
		                </router-link>
		            </li>
	            </ul>
		    </div>
		</section>
这是template里面的

**Comment by Astaca** [comment]
<script type= text/html>
	<template>
		<div>
			<section id="scroll-wrapper" class="wrapper" ref="wrapper">
		        <div id="scroll-container" class="content">
					<ul class="production-list-container">
						<li v-for="(pro,index) in pros">
			                <router-link :to="{path:'detail',query:{pid:pro.id}}">
			                    <h5 class="text-ellipsis-2" @click.stop.prevent="alert">{{index}}</h5>
			                </router-link>
			            </li>
		            </ul>
			    </div>
			</section>
		</div>
	</template>
</script>
这个是html的代码

**Comment by Astaca** [comment]
刚刚注册了jsrun，但是还不怎么熟悉怎么操作，我的demo就是router-link 里面包含了一个click事件， click加上click.stop.prevent属性，没有引入bs的时候，不会进行页面跳转，引入以后会

**Comment by ustbhuangyi** [comment]
你不能提供可访问的 demo 我也没法帮你调试，因为我在自己的 demo 里尝试写是 ok 的，所以还是需要可以运行的代码地址，如果自己搞不定可以寻求身边的小伙伴帮忙。

**Comment by Astaca** [comment]
我尝试的换了一种写法 将router-link 换成 a标签加上click事件 click里面用this.$router.push 去进行页面跳转，就能取消页面的跳转，如果是router-link就无法取消，demo的话，我等会尝试的去弄弄
