### ISSUE TITLE
在mac上面 better-scroll无法滚动

### ISSUE THREAD

**Issue by liuxingzhijian1320** [ustbhuangyi/better-scroll#263]
mac上面的无法滚动的，win上面和手机上面是滚动的正常的

**Comment by ustbhuangyi** [comment]
不符合 issue 规范，并且我们测过 mac 上也是一切正常的，很可能是你滚动的姿势不对。

**Comment by adouwt** [comment]
mac 上 谷歌浏览器，无法滚动，通过手机访问，可以滚动

**Comment by Aprilday** [comment]
准确说应该是在mac的chrome上没法滚动，chrome版本号  65.0.3325.181
