### ISSUE TITLE
关于手机端用better scroll实现屏幕滑动

### ISSUE THREAD

**Issue by AwakenedSomeone** [ustbhuangyi/better-scroll#266]
我在电脑上用chrome模拟手机端时滑动没有问题，但是在用自己的安卓手机测试时，按住屏幕滑动会出现内容闪烁的问题，感觉DOM更新没有及时一样，搜索了相关信息，没有找到解决方法，请问是什么原因呢？

**Comment by ustbhuangyi** [comment]
请按 issue 规范提问题。
