### ISSUE TITLE
为什么我配置了scrollbar: true，没有滚动条

### ISSUE THREAD

**Issue by bestime** [ustbhuangyi/better-scroll#267]
> 按照文档配置了 scrollBar: true  确并没有出现滚动条，是还需其他操作吗？

**Comment by ustbhuangyi** [comment]
`scrollbar: true` 而不是 `scrollBar`

**Comment by bestime** [comment]
@ustbhuangyi 习惯了。。我代码确实是写的 scrollbar。其他一切正常，就是没有滚动条
