### ISSUE TITLE
用了最新的1.3.1 snapLoop根本无法轮滑 改成0.1.5才好 希望快点解决

### ISSUE THREAD

**Issue by wangyu1997** [ustbhuangyi/better-scroll#268]

**Comment by 13189449986** [comment]
今天碰到同样的问题,确实是1.3.1版本无法循环轮播

**Comment by ustbhuangyi** [comment]
提 issue 前能否看一下文档？
https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options-advanced.html#snap
