### ISSUE TITLE
IOS 11.0.2上，better-scroll的列表最后的动画会出现抖动的情况

### ISSUE THREAD

**Issue by CodeLittlePrince** [ustbhuangyi/better-scroll#270]
复现的话，可以iPhone上直接访问better-scroll的demo地址，比如：
[https://ustbhuangyi.github.io/better-scroll/#/examples/picker/en](url)

手机系统：IOS 11.0.2
better-scroll版本: v1.3.1

**Comment by ustbhuangyi** [comment]
今天升级到了 IOS 11.0.3，运行 demo 还是很流畅的 ，iphone6s

**Comment by CodeLittlePrince** [comment]
恩，更新到了11.0.3，好了，之前发现11.0.2，所有的遮罩层都会闪烁。更新后也都好了。
苹果这个大坑，唉~~
