### ISSUE TITLE
When the network is poor, it will be abnormal

### ISSUE THREAD

**Issue by kaimZhou** [ustbhuangyi/better-scroll#271]
So, when i change refreshDelay to 1000(or more big), it's work.
```
watch: {
      data() {
        setTimeout(() => {
          this.refresh()
        }, this.refreshDelay)
      }
    }
````

**Comment by ustbhuangyi** [comment]
it's not reasonable,  refresh after data change，if you there is no transition, 20ms is enough. It's unrelated to network.
