### ISSUE TITLE
【BUG】在数据较少的情况下，关闭Pull Up Load会导致Pull Down Refresh失效

### ISSUE THREAD

**Issue by SAOSO** [ustbhuangyi/better-scroll#272]
使用的是最新的版本。

1，将官网demo中  example/page/vertical-scroll  中，加载的数据由20条，改为2条
2，关闭Pull Up Load
3，这个时候，Pull Down Refresh也不能用了。。

**Comment by ustbhuangyi** [comment]
fixed
