### ISSUE TITLE
slide 组件里自动播放，滚动播放时出现闪屏

### ISSUE THREAD

**Issue by codeXian** [ustbhuangyi/better-scroll#276]
版本:最新版本的better-scroll
![2](https://user-images.githubusercontent.com/25171865/31488973-f59bc5de-af04-11e7-88af-ff75a1fab906.png)
![1](https://user-images.githubusercontent.com/25171865/31489017-1539bae0-af05-11e7-9226-f136e833d25c.png)

slider组件滚动到最后一张图片translate属性的数值有-2472px变为-412px.希望黄老师注意一下

**Comment by ustbhuangyi** [comment]
http://ustbhuangyi.com/music/ 这就是用的最新版的 better-scroll，没有闪屏问题。

**Comment by codeXian** [comment]
chrome浏览器有闪屏问题 
61.0.3163.100（正式版本） （64 位）

**Comment by codeXian** [comment]
火狐没有
