### ISSUE TITLE
scroll 监听无效

### ISSUE THREAD

**Issue by yuanzhhh** [ustbhuangyi/better-scroll#278]
版本 1.3.1
我监听scrollStart、scrollEnd都正常，但scroll事件则无法监听，函数没有得到调用。
on('scroll', object => {
        console.log('out');
});

**Comment by yuanzhhh** [comment]
sorry，怪我
我重新又看了下文档，需要配置probeType才能对应得到触发

**Comment by dida-1894** [comment]
怎么配置probeype？我遇到和你一样的问题

**Comment by dida-1894** [comment]
好吧，我知道，重看了一下文档。
