### ISSUE TITLE
是不是可以用 MutationObserver 监听文档变化自动 refresh 呢

### ISSUE THREAD

**Issue by wcldyx** [ustbhuangyi/better-scroll#279]
每次手动调用 refresh 方法感觉太麻烦了， 能不能用 MutationObserver  监听scroll-content 内文档变化然后自动调用 refresh

**Comment by ustbhuangyi** [comment]
可以考虑，不过这样就相当于放弃了 Android 4.4 以下的浏览器，对 PC 的支持也不够友好。
目前做法是配合 MVVM 框架，比如 Vue，封装了 scroll 组件。因为是数据驱动视图的，所以可以监听数据的变化去调用 refresh 方法。

**Comment by acccco** [comment]
虽然是数据驱动视图的，但是也有调用refresh困难的情况。
当数据填充完配合动画显示效果时，一般的动画是没问题的，只有动态改变了元素的高度的动画会有这样的问题。
比如展开一个列表，实际的效果是这样的
```
enter: function (el, done) {
            var delay = el.dataset.index * 150
            setTimeout(function () {
                Velocity(
                    el,
                    {opacity: 1, height: el.dataset.height + 'px'},
                    {complete: function () {
                        done()
                        this.enterEnd && this.enterEnd()
                    }}
                )
            }, delay)
        },
```
这段是vue官网上有的，我多加了这一句`this.enterEnd && this.enterEnd()`。因为虽然数据已经都过来了，但是由于动画是有延迟的，所以导致调用refresh时机不对（由于内容的高度变了）。所以被迫加了这一段，这个方法我是写在mixins里的，所以每个使用这个mixins的地方，都得加上这一段
```
methods:{
  // ...
  enterEnd(){this.$refs.scroll.refresh()}
  // ...
}
```
用于监听动画结束

所以如果可以自动refresh就太好了，希望能支持

**Comment by ustbhuangyi** [comment]
试试新版的 better-scroll 吧，支持了自动 refresh。
