### ISSUE TITLE
元素在better-scroll容器内，position:fixed失效

### ISSUE THREAD

**Issue by wz51239925** [ustbhuangyi/better-scroll#285]
您好，有办法让元素在better-scroll容器内，让position:fixed有效吗？设置什么参数可以吗？

**Comment by ustbhuangyi** [comment]
请提供一个具体的 demo

**Comment by cnflyne** [comment]
http://www.cnblogs.com/xinpureZhu/p/5329699.html

**Comment by cnflyne** [comment]
@wz51239925 @ustbhuangyi 

> 这个问题是因为父元素存在 transform 属性导致的
> 因为 bscroll / iscroll 是基于 transform 属性实现滚动的, 所以 iscroll 会通过实时修改元素的 transform 属性以达到滚动的效果

参考：http://www.cnblogs.com/xinpureZhu/p/5329699.html
