### ISSUE TITLE
文中获取当前页面信息用的是getCurrentPage()方法，打印实例后的better-scroll并没这个方法而是currentPage

### ISSUE THREAD

**Issue by hiteamLiuLiXue** [ustbhuangyi/better-scroll#289]
版本号1.3.1；

文中获取当前页面信息用的是getCurrentPage()方法，打印实例后的better-scroll并没这个方法而是currentPage方法

**Comment by liujunzhang-8** [comment]
版本号2.4.2；
获取当前页面信息时报错getCurrentPage is not a function，是版本号太高了吗
