### ISSUE TITLE
实例化后无法滚动

### ISSUE THREAD

**Issue by webkong** [ustbhuangyi/better-scroll#29]
`this.$nextTick(() => {
            if (!this.cScroll) {
              this.cScroll = new BetterScroll(this.$refs.content, {
                click: true
              });
            } else {
              this.cScroll.refresh();
            }
          });`

在目标dom有
`style="transition-timing-function: cubic-bezier(0.165, 0.84, 0.44, 1); transition-duration: 0ms; transform: translate(0px, 0px) translateZ(0px);"`

但是无法滚动，不知道什么原因。

**Comment by ustbhuangyi** [comment]
你看一下你的子容器的高度是不是超过父容器的高度，只有这种情况才会滚动。

**Comment by webkong** [comment]
黄老师您好， 子容器的高度是超过父元素的， 有3个滚动的地方， 只有一个地方是OK的， 其他两个地方都不能滚动，代码check好多次都是一样的。所以，是否有对与父容器的一些要求呢。

**Comment by lemontree2000** [comment]
@ustbhuangyi  请问一定要给高度吗？ 我的高度是内容撑开的， 一旦给了高度。 在手机适配后可能会出现问题？  有什么解决方案吗

**Comment by neurotoxinvx** [comment]
@webkong 父容器高度需要固定

**Comment by neurotoxinvx** [comment]
@lemontree2000 Y轴滚动内层容器不需要给出指定高度。但是在 BScroll 计算容器高度时请确保你的内层容器高度大于外层

**Comment by mingmo13** [comment]
我也遇见了同样的问题，实例化后 内层ul被加上了style但是无法滚动

**Comment by lemontree2000** [comment]
@mingmo13 容器高度要小于内容

**Comment by hxxiaolong** [comment]
小于了也不行。。。无法滚动
