### ISSUE TITLE
picker的体验怪怪的

### ISSUE THREAD

**Issue by seekwe** [ustbhuangyi/better-scroll#290]
demo : https://ustbhuangyi.github.io/better-scroll/#/examples/picker/zh

首先向下拉 最低是这样 (没毛病)

![](http://ww1.sinaimg.cn/mw690/63a61209gy1fkmi9ag5g7j20cd09pq31.jpg)

但是 向上

![](http://ww1.sinaimg.cn/mw690/63a61209gy1fkmi9afajbj20e0098mx9.jpg)

然后动画也是有点看起来干着急的,过渡很慢,导致scrollEnd触发一延长了很多,

以上纯碎个人体验

**Comment by ustbhuangyi** [comment]
如果觉得体验不好，欢迎提 pr
