### ISSUE TITLE
使用better-scroll在移动端无法再有效使用css:active伪类实现效果

### ISSUE THREAD

**Issue by 2507483326** [ustbhuangyi/better-scroll#292]
使用better-scroll后，渲染的列表中按钮本身的:active效果在移动端Android浏览器下以及chrome iphone调试下没有效果，只有PC端才能触发伪类效果。不知道有没有相关API或者实现方式

**Comment by LeeYoung-s** [comment]
你好，请问你这个问题解决了吗？

**Comment by 2507483326** [comment]
> 还有一个类似的问题，移动端better-scroll里面文本无法复制，加上user-select:auto 依然无效

![image](https://user-images.githubusercontent.com/10804157/46240579-54ef7200-c3dc-11e8-9d27-e11989cbfdd2.png)
当初解决好像是这个属性

**Comment by 2692618231** [comment]
你好，请问你这个问题解决了吗？
