### ISSUE TITLE
请问支持 Recycle DOM 无限滚动吗？

### ISSUE THREAD

**Issue by Hellowor1d** [ustbhuangyi/better-scroll#294]
在 iScroll 中看到有这种支持的[demo](http://lab.cubiq.org/iscroll5/demos/infinite/),请问下better-scroll 可以实现这种固定数量的DOM节点，用以展示超量数据列表的效果吗？

**Comment by ustbhuangyi** [comment]
似乎上拉加载的效果可以满足需求？
