### ISSUE TITLE
关于better-scroll包的类型定义文件

### ISSUE THREAD

**Issue by linxiaowu66** [ustbhuangyi/better-scroll#300]
Hi ， @ustbhuangyi 
  非常感谢你的better-scroll，我们已经将其用于内部测试中。因为我们使用的typescript语法，在[DefinitelyTypes](https://github.com/DefinitelyTyped/DefinitelyTyped)官网上没有找到这个库的类型定义，所以我根据你写的代码和接口参数做了这么一个接口定义，相关PR在： https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21023

麻烦有时间看一下具体的类型定义是否正确，多谢了

**Comment by ustbhuangyi** [comment]
@linxiaowu66 ok

**Comment by ustbhuangyi** [comment]
@linxiaowu66 类型定义没有问题，如果 better-scroll 后续有接口参数升级，也请关注一下

**Comment by linxiaowu66** [comment]
ok
