### ISSUE TITLE
better-scroll里面的refresh功能该如何使用

### ISSUE THREAD

**Issue by joyjoe** [ustbhuangyi/better-scroll#31]
老师，我看了您的饿了么视频。视频里面您在初始化生成一个bs实例后，通过实例是否存在，而选择执行bs.refresh()方法。但是实际上并没有什么效果。但是看你的这个readme文档，上面说的是refresh是一个事件。那应该如何才能执行呢？

**Comment by neurotoxinvx** [comment]
var scroller = new BScroll();
scroller.refresh()

**Comment by joyjoe** [comment]
可是没有效果啊

**Comment by ustbhuangyi** [comment]
refresh 是方法，作用是重新获取容器的宽度和高度，然后执行一些初始化逻辑，同时会派发一个 refresh 事件，我们会完善文档
