### ISSUE TITLE
关于ios版本兼容问题

### ISSUE THREAD

**Issue by evanyangg** [ustbhuangyi/better-scroll#310]
注意：
1. 外网可访问的测试地址（可以调试的源码，借助 CodePen 或者 JSFiddle）;
工作时间可以提供地址, 09:00 - 18:30
2. 详细的复现步骤；
首次进入页面
3. 调用 BScroll 的代码及 BScroll 版本；
v1.4.0
4. 出现问题的机型、操作系统、宿主环境、浏览器信息。
IOS 7.1.2 出现
![image](https://user-images.githubusercontent.com/22952321/32369155-31f3752e-c056-11e7-805c-056b48597817.png)
IOS 10.3.3 出现
![image](https://user-images.githubusercontent.com/22952321/32369185-4ffd68ea-c056-11e7-8065-ead4147cb354.png)
我还在继续调试,请指教.

**Comment by evanyangg** [comment]
都是在微信浏览器下

**Comment by evanyangg** [comment]
@ustbhuangyi 你好,我想知道您那边有测试环境么? 我是通过您抽离出来的scroll组件来实现的, 然后出现上述两种bug场景

**Comment by ustbhuangyi** [comment]
你这个问题和 better-scroll 无关吧

**Comment by evanyangg** [comment]
@ustbhuangyi 你好, 是我的问题
![image](https://user-images.githubusercontent.com/22952321/32479402-47893e18-c34f-11e7-95c5-1cc0d047079f.png)
本来我想引用源码包里面的dom.js, 结果就出现上面提的issue, 后来单独引入本地dom.js就ok了,
谢谢啦!
