### ISSUE TITLE
click事件表单元素和普通元素不能同时触发

### ISSUE THREAD

**Issue by 327326724** [ustbhuangyi/better-scroll#311]
demo中的scroll组件，click设置为true不能触发表单元素的click事件，设置为false又不能出发普通元素的click事件。

**Comment by ustbhuangyi** [comment]
参考 https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#preventdefaultexception

**Comment by 327326724** [comment]
文档没看完啊，不好意思。。。
