### ISSUE TITLE
下拉刷新期间再次下拉不能回弹

### ISSUE THREAD

**Issue by baiyunshenghaishang** [ustbhuangyi/better-scroll#312]

**Comment by ustbhuangyi** [comment]
请描述一下具体复现步骤，我测试 demo 并无此问题

**Comment by baiyunshenghaishang** [comment]
demo normal scroll list,我把下拉刷新的timeout改成了10s，1s太短看不出来。下拉释放刷新后，处于loading阶段，此时再次下拉，下拉的列表释放后不会往回滑动。（正常情况会回弹到顶部吧）

**Comment by ustbhuangyi** [comment]
这个可以优化一下

**Comment by ustbhuangyi** [comment]
最新 demo 已经修复此问题。

**Comment by qiheng** [comment]
下拉释放刷新的监听事件处理函数，在通过接口获取下拉数据时，代码也要写在setTimeout里面并且设置2000ms吗？不然的话下拉刷新时偶尔下拉刷新的提示语会覆盖在数据列表上（也就是列表回弹比快，提示语没有跟着一起回弹）
