### ISSUE TITLE
关于图文列表滑动动画回闪问题

### ISSUE THREAD

**Issue by yangqihua** [ustbhuangyi/better-scroll#316]
- 1.  滑动区域为图文列表，列表为正在滑动状态时立即touch列表使滑动状态停止，列表动画并没有立即停止，而是执行完动画后再回退到touch的位置，此问题在加载多页数据后回闪会非常明显。

- 2. 将配置项 useTransition 改为 false 之后，可解决回闪问题，但画面滑动会变得非常卡顿，且浏览器浏览器控制台报错（报错内容：Uncaught TypeError: Cannot read property 'x' of undefined ）。查看源码得知：最新版本项目文件：/src/scroll/core.js 中的第 452、453 行的 this 应该改为 me 。

- 3. 针对此回闪问题是否优化：当列表滑动过程中，立即 touch 时，目前动画会继续执行完毕，只是将执行时间设为0。这样会导致回闪问题，建议优化一下，谢谢。

**Comment by ustbhuangyi** [comment]
感谢反馈代码中的 bug，你这个问题是否有可以访问的 demo 地址？

**Comment by Yeung2017** [comment]
我也遇到了这个问题,在手机上,当momentum动画正在执行的时候,这时手指放上去(触发touch事件),会感觉列表明显的闪动,并且越靠近momentum动画结束时刻被打断,这种闪动就越明显.
bscroll版本是v1.4.2

**Comment by yangqihua** [comment]
demo 访问地址：http://118.31.20.214/scroll-demo/#/better-scroll
代码 ：https://github.com/yangqihua/vue-scroll-mobile-demo

**Comment by azumia** [comment]
我也遇到这个问题了，多图文滑动的时候总是会有回弹

**Comment by ustbhuangyi** [comment]
@yangqihua ，你说的意思是在动画过程中触屏屏幕停止的时候，会稍微有一些后退吧？

**Comment by yangqihua** [comment]
是的，且数据越多，后退的会越明显，低端安卓机甚至会造成卡顿，闪屏。

**Comment by ustbhuangyi** [comment]
@yangqihua 低端安卓机设置 useTransition 为 false 应该会好一些

**Comment by stephenzhao** [comment]
请问这个case 解决方案是什么？ 我也遇到回闪的问题，Android和iOS都有
