### ISSUE TITLE
关于黄老师用bscroll做联系人列表的每一项滚动到顶部后列表组标题切换固定的问题

### ISSUE THREAD

**Issue by xwpongithub** [ustbhuangyi/better-scroll#32]
我看黄老师你做的效果是写了一个绝对定位的fixed-title ，其余每个列表项滚动的时候与fixed-title的底边接触时就开始改变fixed-title的translateY值。那么我的问题就在这里了~在bscroll里判断每个列表组标题与fixed-title是否接壤并开始改变fixed-title的判断条件的具体思路是啥~

**Comment by neurotoxinvx** [comment]
在创建 BScroll 的时候你可以计算每个列表组标题距离 BScroll 顶部的距离是多少 ，在 on('scroll') 的时候 BScroll 会派发给你当前已滚动的 y 值，如果 y 值 >= 每个列表组标题距离 BScroll 顶部的距离，即为已滚到了这个列表组 title ，你可以开始进行 fixed-tilte 的操作。具体实现的时候由于 fixed-title 本身也具有 height ，所以判断是否接壤的时候要减去 fixed-title 的高度哦。另外需要注意的地方是，由于 fixed-title 会根据滚动的距离进行一个位置的上移动画，实例化 BScroll 的时候一定要选择 probeType: 3 实时派发滚动事件。
