### ISSUE TITLE
关于返回顶部

### ISSUE THREAD

**Issue by donxbei** [ustbhuangyi/better-scroll#321]
大神，您好！用better-scroll时，没法有效的实现返回顶部的功能，因为没法获取window.pageYOffset的值：
    // 判断滚动区域大于多少的时候显示返回顶部的按钮
      currentPageYOffset () {
        window.pageYOffset > this.pageY ? this.showBackStatus = true : this.showBackStatus = false
        console.log(window.pageYOffset)
       },
      // 返回顶部
      showbackTop() {
        scrollIt(0, 1500, this.transitionName, this.currentPageYOffset)
        console.log(this.transitionName)
        console.log(this.currentPageYOffset)
        console.log(window.pageYOffset)
      },
我这里 console.log(window.pageYOffset)出来，发现window.pageYOffset一直是0。
用其他方法实现滚动的时候，就能获取window.pageYOffset的值，这是因为better-scroll要父元素设置为overflow:hidden的影响吗？

**Comment by ustbhuangyi** [comment]
建议看一下文档，你应该监听 scroll 事件，通过 scroll 的位置能知道滚动的距离。

**Comment by xxwangkaimin** [comment]
关于返回顶部提供了一个插件 better-scroll2-backtop
可以查看npm文档：https://www.npmjs.com/package/better-scroll2-backtop
