### ISSUE TITLE
can not scroll in WeChat develop tool

### ISSUE THREAD

**Issue by mobilesite** [ustbhuangyi/better-scroll#324]
It’s really a cool realization. I’m afraid there is something wrong in WeChat develop tool,  I just can’t scroll when I open the example(https://ustbhuangyi.github.io/better-scroll/#/examples/index-view/en) in the WeChat develop tool (version 1.01 on Mac OS).

**Comment by ustbhuangyi** [comment]
what about wechat webview?

**Comment by mobilesite** [comment]
It's ok

**Comment by ustbhuangyi** [comment]
maybe it's develop tool's bug
