### ISSUE TITLE
preventDefaultException默认支持表单元素原生click事件，没生效。

### ISSUE THREAD

**Issue by 327326724** [ustbhuangyi/better-scroll#327]
[https://github.com/ustbhuangyi/better-scroll/issues/311](url)，经查看文档，发现preventDefaultException默认值是不阻止表单元素click事件，但是实际并未生效，经调试发现是better-scroll里面的`e.stopPropagation();`导致的。请问这句代码是否可以移到判断内?
```js
case 'click':
        if (this.enabled && !e._constructed) {
          if (!preventDefaultException(e.target, this.options.preventDefaultException)) {
            e.preventDefault();
          }
          e.stopPropagation();
        }
        break;
```

**Comment by ustbhuangyi** [comment]
请按 issue 规范提供一个可访问的 demo 地址

**Comment by 327326724** [comment]
不好意思，我试了下`http://jsrun.net`这个网站，不知道怎么引入scroll组件，我把click换成了touch事件就可以了
