### ISSUE TITLE
动态计算html文字大小，使用rem为单位的时候，better-scroll表现异常

### ISSUE THREAD

**Issue by qinqin772** [ustbhuangyi/better-scroll#328]
使用了better-scroll的容器，在上拉时，如果开启了scrollbar:true时，wrapper和content 2者底部之间可以拉出很大的一段空白，（弹不回去），wrapper使用的单位是 rem
`       var load=window.onload||function(){};
	window.onload=function(event){
		load(event);
		var objHtml=$("html"),htmlFontSz=parseFloat(objHtml.css("fontSize")),
		ratio=$(window).width()/750;
		objHtml.css("fontSize",ratio*100+"px");
	};`
scrollbar设置为false的时候，wrapper和content的底部距离变现正常，弹性动画也正常

**Comment by ustbhuangyi** [comment]
请按 issue 规范提
