### ISSUE TITLE
使用better-scroll做react版的picker组件，在click时使用wheelTo滚动到指定位置无动画效果

### ISSUE THREAD

**Issue by zwsf** [ustbhuangyi/better-scroll#329]
您好，我使用better-scroll做底层库封装做react版本的picker组件，在处理点击事件滚动到点击的目标元素时，是直接切换到目标元素，没有像滑动那样的动画效果，但是我看您原生实现的picker库时有动画效果，不知这个是需要什么额外的参数还是怎么处理，感谢～

**Comment by ustbhuangyi** [comment]
可以看看这个 pr，https://github.com/ustbhuangyi/better-scroll/pull/331
应该是 class 的问题，也是可以优化的

**Comment by zwsf** [comment]
非常感谢！确实是class的问题，因为我使用了css modules，所以必须给列表项li加上wheel-item这个classname
