### ISSUE TITLE
better-scroll在IE浏览器中无法滚动问题

### ISSUE THREAD

**Issue by wangpu097511** [ustbhuangyi/better-scroll#330]
一个基于vue的项目，better-scroll在谷歌浏览器中可以滚动，但是在IE中无法滚动，到底是为什么？？
   
       this.meanScroll = new BScroll(this.$refs.menuWrapper,{
	       click:true
	});
	this.goodsBscroll = new BScroll(this.$refs.foodWrapper, {
               probeType: 3,
               click: true
       });
       this.goodsBscroll.on("scroll",(pos) => {
		this.scrollY = Math.abs(Math.round(pos.y));
        })

	哪位大神有解？？

**Comment by ustbhuangyi** [comment]
请按 issue 规范提供具体的 demo 地址
