### ISSUE TITLE
跪求作者帮我解读！！！

### ISSUE THREAD

**Issue by yzw2017** [ustbhuangyi/better-scroll#332]
@ustbhuangyi 
我看了看Demo的slide组件，发现有些属性和配置，手册上并没有，
比如
      this.slider = new BScroll(this.$refs.slider, {
          scrollX: true,
          momentum: false,
          snap: {
            loop: this.loop,
            threshold: 0.3,
            speed: 400
          },
          click: true
      })
这里的threshold: 0.3, 不知道是什么意思？？ 也查不到
还有
     this.slider.on('scrollEnd', () => {
        let pageIndex = this.slider.getCurrentPage().pageX;
        if (this.loop) {
          pageIndex -= 1;
        }
        this.currentPageIndex = pageIndex;

        if(this.autoPlay) {
          clearTimeout(this.timer);
          this._play();
        }
      })

    },
    _play() {
      let pageIndex = this.currentPageIndex + 1;
      if(this.loop) {
        pageIndex += 1
      }
      this.timer = setTimeout(() => {
        this.slider.goToPage(pageIndex, 0, 400)
      }, this.interval)
    }
这里的逻辑代码中当滚动一次，BScroll就会派发一个滚动结束的事件，然后有些不明白为什么pageIndex-=1和开始轮播pageIndex += 1 麻烦大神可以帮我解读一下，本人前端小白，谢谢！

在这我反复看了看您的课程，你说因为在循环模式下，BScroll会在第一个轮播图中复制一个副本在最前面，但是我理解是 ~~~~ 在BScroll初始化的时候会在轮播图开头和末尾都添加了一个副本，这个做法是为了无缝轮播，和swiper插件原理一样，但是既然这样为什么pageIndex只减一而不是二，这一点我搞不懂，我非常希望能入手BScroll，觉得是一个不可多得的插件，求大神帮我解读！！！！

**Comment by ximoThorn** [comment]
@yzw2017    如果开启loop，获取到的是首尾追加dom后的index值； 开头只添加了一个， 为什么要减2呢？

**Comment by yzw2017** [comment]
@ximoThorn 兄弟，我没看过源码，假设原本我有5个img，初始化BScroll并且打开loop，此时是不是前后都添加了1个img，也就是此时有7个img。对吧？

**Comment by ximoThorn** [comment]
@yzw2017   是7个啊，前面和后面各添加了一个！

**Comment by yzw2017** [comment]
@ximoThorn 兄弟，那这样本来img为5个的 开启loop，现在7个了，本来img.length = 5的 现在为7了哦。
那为什么pageIndex减1呢？谢谢大神的回复

**Comment by ximoThorn** [comment]
@yzw2017     0.0！！！！     **是前后各一个**      原来的index为0的变成了1， 1变成了2以此类推， 最后又多了7。为什么回想不明白呢

**Comment by yzw2017** [comment]
@ximoThorn 大兄弟！！！你这样一说 我秒懂了，万分感谢！能交个朋友吗？大家都对better-scroll和vue都感兴趣
