### ISSUE TITLE
es6 default

### ISSUE THREAD

**Issue by taoqf** [ustbhuangyi/better-scroll#338]
使用webpack打包，配置babel-loader，babelrc配置如下
```json
{
	"presets": [
		"env"
	],
	"plugins": [
		"transform-runtime"
	]
}
```
打包后的文件中使用bscroll的地方提示：`Uncaught (in promise) TypeError: BScroll is not a constructor`。
调试跟踪到代码
```js
var _betterScroll = __webpack_require__(277);

var BScroll = _interopRequireWildcard(_betterScroll);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```
处发现`_betterScroll`没有`__esModule`属性，所以`BScroll`实际上变成了`{default:BScroll}`。导致下面无法实际化
因为其它引用库的原因，我是没有办法使用 `module:false`的babel配置的。
我尝试了各种办法，但在不修改源码的基础上始终没有一个圆满的结果。
这是在我用
```ts
import * as BScroll from 'better-scroll';
```
的情况。而如果我换成
```ts
import BScroll from 'better-scroll';
```
写法的话，typescript会转换为amd格式的js代码
```js
const better_scroll_1 = require("better-scroll");
const myscroll = new better_scroll_1.default();
```
引用的话，`webpack`打包是没有问题，但问题在于我开发的时候用的是`amd`方式加载的`bscroll`，在这种情况下使用就有问题了。
所以我做了[一点修改](https://github.com/ustbhuangyi/better-scroll/pull/337)，如果 @ustbhuangyi 认为有更好的办法，请指点。

**Comment by taoqf** [comment]
呼叫 @ustbhuangyi

**Comment by taoqf** [comment]
到底怎么办呀，我空等2天了

**Comment by ustbhuangyi** [comment]
v1.4.2 支持了 esm

**Comment by taoqf** [comment]
老板是在国外上班的呀，时差这么多。。。
我不太明白esm是什么东西
> 你现在默认引入的应该是 bscroll.esm.js

你的意思是不是我引入这个就是可以的？

**Comment by ustbhuangyi** [comment]
正常import就可以

**Comment by taoqf** [comment]
我试试先

**Comment by taoqf** [comment]
我大概看了下`bscroll.esm.js`，似乎意思是说我用webpack的时候用它，但amd还用`bscroll.js`对吧?

**Comment by taoqf** [comment]
OK了，多谢

**Comment by taoqf** [comment]
我之前错了。并没有OK，问题依旧

**Comment by taoqf** [comment]
我不知道老板有没有认真看我的问题，我的问题其实简单来说是amd和webpack打包时用的方式其实是不一样的。

**Comment by taoqf** [comment]
事实上,`bscroll.esm.js`和`bscroll.js`在使用webpack打包的情况下，结果是一样的。

**Comment by taoqf** [comment]
@ustbhuangyi 再次呼叫老板。这个问题困扰我好多天了

**Comment by taoqf** [comment]
`bscroll.esm.js`在
```
var _betterScroll = __webpack_require__(277);

var BScroll = _interopRequireWildcard(_betterScroll);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```
处`_betterScroll`为
```js
{
    __esModule: true,
    default: BScroll
}
```
所以得到的`BScroll`是
```js
{
    default: {
        __esModule: true,
        default: BScroll
    }
}
```

**Comment by taoqf** [comment]
如果作者希望得到更详细的信息，我再提供，我觉得可能足够说明问题了。

**Comment by taoqf** [comment]
@ustbhuangyi 老板老板老板，急啊。

**Comment by taoqf** [comment]
.

**Comment by ustbhuangyi** [comment]
你的 webpack 什么版本，我们所有项目都是用 webpack 构建的，为啥没有你这个问题？

**Comment by taoqf** [comment]
老板终于在了，你们的.babelrc里有module:false的配置呀

**Comment by ustbhuangyi** [comment]
没有这个配置

**Comment by ustbhuangyi** [comment]
webpack 2+ 版本都没有这个问题

**Comment by taoqf** [comment]
还有一个原因可能是我用ts的原因，你看我问题的描述有没有不清楚的

**Comment by taoqf** [comment]
我一直用最新版本的webpack，不会是版本的问题

**Comment by taoqf** [comment]
我感觉确实是咱们的模块用rollup打包的问题

**Comment by ustbhuangyi** [comment]
我的构建方式和 Vue 是一样的，生成的代码结构也是一样，并不是 Rollup 的问题

**Comment by taoqf** [comment]
我可不可以小心地反问一下，我用其它的模块都没有问题的，只有咱们这个模块
要么amd方式不行，要么es和commonjs方式不行，只能选其一

**Comment by taoqf** [comment]
所以才有了那次我的提交的pr

**Comment by taoqf** [comment]
而我的ts代码是一份，只是在开发的时候编译为umd的，使用amd加载器加载，部署的时候使用webpack+babel-loader打包

**Comment by taoqf** [comment]
其实还有一个问题，我还没有得到验证：就是做轮播图的时候如果宽度是小数rem，计算getCurrentPage也会在最后一张图的时候计算出错。

**Comment by taoqf** [comment]
老板？？？真的是有问题呀，并且这个事非常急，我暂时都是通过手动修改打包后的代码解决的。

**Comment by ustbhuangyi** [comment]
开发阶段为啥要编译成 umd？
我刚才看了一下一个依赖 webpack 的项目编译后的代码，也并没有你说的问题。

**Comment by ustbhuangyi** [comment]
或者你建一个项目依赖一下 Vue，看看有没有类似的问题

**Comment by taoqf** [comment]
<开发阶段为啥要编译成 umd？�
我刚才看了一下一个依赖 webpack 的项目编译后的代码，也并没有你说的问题。

方便并且快。

**Comment by taoqf** [comment]
> 或者你建一个项目依赖一下 Vue，看看有没有类似的问题
我确定是跟vue没关系的。就是rollup和ts的问题，上次发过这个问题讨论的链接了。
能不能合并一下我上次提交的pr呢，它是解决这个问题一个比较另类的方法了，如果老板没有更好办法的话。

**Comment by taoqf** [comment]
副使用也不很大，就是在 `BScroll` 上加一个 `default` 属性而已。

**Comment by taoqf** [comment]
https://github.com/ustbhuangyi/better-scroll/pull/337 这个

**Comment by ustbhuangyi** [comment]
如果你不用 TS，还有这个问题吗？

**Comment by taoqf** [comment]
我对比过ts生成的umd和rollup生成的umd格式，就是差这个
```js
Object.defineProperty(exports, "__esModule", { value: true });
```
而babel会根据这个判断
```js
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```
转换代码

**Comment by ustbhuangyi** [comment]
你先按我说的，项目中引入一下 Vue，试试能不能正常引用，因为 Vue 也是对 TS 做了支持，也是 Rollup 打包，输出的也是 esm。

**Comment by taoqf** [comment]
试了，不行

**Comment by taoqf** [comment]
意思是老板不愿意解决这问题了，那我明白了。

**Comment by linxiaowu66** [comment]
@taoqf 你有试过这种写法吗？

```
import Bscroll = require('better-scroll')
```

我也是用的TS，这种写法在我这边没有问题

**Comment by taoqf** [comment]
多谢，刚看到这些回复。
最近没搞这一块了，暂时我那里能用了，并且我还修复过其它bug，TypeScript2.7已经对这问题有了改进，应该已经不存在了。

**Comment by channg** [comment]
同样遇到这样的问题
