### ISSUE TITLE
indexList 点击最后一个list时的currentIndex是没有落到lastIndex？

### ISSUE THREAD

**Issue by liangxiaoxin** [ustbhuangyi/better-scroll#339]
indexList中，当最后一个list的高度少于屏幕的高度时，点击最后一个list时的currentIndex是没有落到lastIndex的，希望这个可否作出优化的处理？

**Comment by ustbhuangyi** [comment]
这个是上层 demo，只是为了演示 better-scroll 的能力。不过 cube-ui 依赖了 better-scroll，并且提供了 IndexList 的组件，https://github.com/didi/cube-ui，或许这个 issue 提到那边更合适？
