### ISSUE TITLE
怎么开启横向滚动？

### ISSUE THREAD

**Issue by admin00001** [ustbhuangyi/better-scroll#34]
我写了一个div下面是ul li
<div>
<ul><li></li><li></li><li></li><li></li><li></li></ul>
</div>
li是横向排列的 div宽度100%，怎么当li标签过多时超出div的宽度可以横向滚动？而不是往下掉

**Comment by csdudu** [comment]
我也想知道，试验了scrollX: true, scrollY: false都不行。

**Comment by ustbhuangyi** [comment]
scrollX 设置为 true，同时要保证子元素的宽度要超出外层的容器，才会有滚动效果。
