### ISSUE TITLE
下拉刷新 pullingdown后，一直派发scroll事件

### ISSUE THREAD

**Issue by wangxiangyao** [ustbhuangyi/better-scroll#340]
![image](https://user-images.githubusercontent.com/23569474/32888405-1ed92b76-cb02-11e7-97c8-0e0d6f41305c.png)

不知道为啥一直派发scroll事件，以前项目模仿demo里边写的，是可以用的。后来直接拿到现在这个项目，普通滚动没事，一旦下拉，就成这样了。

**Comment by wangxiangyao** [comment]
下拉时候：
如果没有达到下拉距离，也没事，
一旦达到下拉距离，没有回弹动画，页面直接闪回去，之后的流程还是正常的，请求数据，状态改变为刷新完成。但就是一直派发滚动事件。（图上是，我再scroll监听函数里打印了pos.y）

**Comment by ustbhuangyi** [comment]
测试本地的 demo 没发现这个情况，你能否提供一个 demo 地址和详细的复现步骤？

**Comment by linxiaowu66** [comment]
@wangxiangyao 
 你是不是在触发pullDown事件后更新完数据没有再调用demo中的forceUpdate函数。只有调用这个函数才会出现回弹的
