### ISSUE TITLE
弹窗内滚动高度不足，少部分内容被隐藏

### ISSUE THREAD

**Issue by UWcan** [ustbhuangyi/better-scroll#341]
源码地址：https://coding.net/u/U_can/p/mytest/git/blob/master/src/components/demo/dialog.vue
问题：https://coding.net/u/U_can/p/mytest/git/blob/master/static/issues/dialog.gif

**Comment by littleyan-xu** [comment]
最新版本我也遇到这个问题，同求解决

**Comment by ustbhuangyi** [comment]
能否提供一个可访问的 demo 页面？

**Comment by UWcan** [comment]
demo地址：http://u_can.coding.me/mytest/dist/#/demo/dialog
感谢大神指导^_^

**Comment by ustbhuangyi** [comment]
你试试最新版的 better-scroll 呢
