### ISSUE TITLE
关于index-list.vue中的一个问题

### ISSUE THREAD

**Issue by ximoThorn** [ustbhuangyi/better-scroll#342]
@ustbhuangyi 
![1510904499 1](https://user-images.githubusercontent.com/32925631/32936804-bc8e329a-cbb0-11e7-9e37-b0e52d86bc17.jpg)

第三步, 感觉有点多余， 第二步完全可以循环到length-1这里

我的理解是-newY大于最后一个元素的上限，难道不就是大于listHeight中倒数第二个值吗， 而且这个时候感觉-newY是不可能大于最后一个值得（我的理解是你上拉的距离不可能大于初始化dom的height的）

还是我理解错了？

**Comment by yzw2017** [comment]
@ximoThorn 不是多余，老师都帮你写好注释了，在中间部分滚动是不包括最后一个的，你想想在计算左边高度的时候数组是多一个的，而且防止最后一个元素高度低的时候 -newY超出的情况，

**Comment by ximoThorn** [comment]
@yzw2017  我知道左边的数组多一个！  像你说的最后一个元素高度低的时候， 这时-newY就更不可能超出了， 千万不能以滚动到顶部的情况去想滚动到底部的情况，这是不一样的，  我问题已经说得很明白了

**Comment by yzw2017** [comment]
@ximoThorn 兄弟，可能我和你理解有些偏差，当最后一个元素高度低的时候，你快速在屏幕上滑动一段距离的时候，BScroll会有momentum和bounce的过程，滚动到顶部newY>0也是因为这个啊，不然怎么会有回弹的效果呢？
