### ISSUE TITLE
better-scroll 微信开发者工具中无法滚动

### ISSUE THREAD

**Issue by gmonking** [ustbhuangyi/better-scroll#343]
复现步骤

复制链接 http://ustbhuangyi.com/music/#/recommend

打开微信开发者工具 打开链接 测试页面上下滚动 ~

微信开发者工具版本 1.01.171019

各位老铁瞅瞅是不是我设置的不对~还是开发者工具禁用的触摸事件

> 我这里也有这个问题, 这个兼容问题确实应该做的啊, 不要 close 了,  确实是 better-scroll 的问题, 作者你把 Pointer 事件支持上应该就可以了

**Comment by ustbhuangyi** [comment]
试了一下，确实不可以，但是加了 Poniter 也会有问题，当页面高度超过一屏的时候，滚动没有办法阻止浏览器的默认滚动，目前也没有什么好办法。或者你有什么好办法欢迎提 pr

**Comment by gmonking** [comment]
其实我是因为在微信开发者工具里开发不方便才关注这个问题， iscroll 是没有这个 bug 的，之所以还想用 better-scroll 是因为你实现了 下拉刷新 上拉加载 ....   而我看了下 ， 我给 iscroll 加上下拉刷新和上拉加载要更简单些 ...  所以， 以后有时间会考虑 pr 。 
还有，之前发现下拉刷新有问题，到达设置的阀值之后，就不能在滚动了，我认为是因为 _checkPullDown
 里没有 else 分支，你可以加上 else 分支，顺便加上 cancelPullingDown 事件,  然后在 transitionend 的回调里判断 this.pulling 决定当前的 y 值。

```
/* cancelPullingDown */
if(this.y > threshold) {
    if(!this.pulling) {
        this.pulling = true;
        this.trigger('pullingDown');
    }
    this.scrollTo(this.x, top, this.options.bounceTime, this.options.bounceEasing);
}else {
    this.pulling = false
    this.trigger('cancelPullingDown')
}

/*transitionend*/
if (this.pulling) {
    y = pullDownRefresh.top
}
```

**Comment by ustbhuangyi** [comment]
我尝试加了，但是效果有问题，因为我的 scroll demo 页面屏幕超过了一屏，在给列表的滚动的同时也触发了浏览器原生的滚动，导致滚动有问题。e.preventDefault 似乎在 pointerEvent 的情况下无效。

**Comment by ustbhuangyi** [comment]
see #361
