### ISSUE TITLE
在使用Picker滑动滚动过程中，快速点击出现bug，无法自动归位

### ISSUE THREAD

**Issue by shenjingxin** [ustbhuangyi/better-scroll#344]
![image](https://user-images.githubusercontent.com/19813014/32988853-adcd7548-cd47-11e7-8d62-bca5999e5973.png)

在滚动动画进行中，快速的点击，就会出现如图所示的bug，无法自动归位，需要再次滑动在可归位

**Comment by ustbhuangyi** [comment]
我并没有复现此问题，请给出复现问题的机型，或者可以录一段视频

**Comment by linxiaowu66** [comment]
@shenjingxin 
这个问题你可以参考这个PR [331](https://github.com/ustbhuangyi/better-scroll/pull/331)

原因应该是你的wrapper类名没有和源码中指定的一样，我出现过这种问题，后来修改源码。请下载最新版本，并配置一下。

**Comment by savokiss** [comment]
原来是这个问题。。。文档上现在没有更新这两个 class 配置呢

**Comment by linxiaowu66** [comment]
@ustbhuangyi 文档没有同步更新？

**Comment by ustbhuangyi** [comment]
@linxiaowu66 ，我应该是忘了构建了，我弄一下
