### ISSUE TITLE
vue单页应用window事件监听问题

### ISSUE THREAD

**Issue by liudg** [ustbhuangyi/better-scroll#348]
1、测试地址：https://ustbhuangyi.github.io/better-scroll/#/examples/zh

2、问题：单页应用，添加了better-scroll的页面实例destory后，better-scroll添加的window事件resize，mousemove等没有取消监听，不刷新应用的情况下再次导航回添加了better-scroll的页面，在google调试控制台打印getEventListeners(window)，相同的监听被添加了多次。不知道这样对应用的性能或者其他方面会不会有影响。

3、复现步骤：打开上面的测试地址，点击slide组件，然后按导航键返回，重复多次，在控制台打印getEventListeners(window)可一看到问题

**Comment by ustbhuangyi** [comment]
这个毕竟只是一个应用层的 demo，和核心实现无关，slide 的正确书写姿势可以参考 cube-ui 的 slide 组件，会移除事件的。https://github.com/didi/cube-ui

**Comment by liudg** [comment]
@ustbhuangyi 好的，谢谢。
