### ISSUE TITLE
升级1.4.2后，nuxt服务端渲染使用问题

### ISSUE THREAD

**Issue by liudg** [ustbhuangyi/better-scroll#349]
外测网址：http://m.hnshuguo.com/

问题：升级1.4.2后，nuxt服务端渲染提示BScroll不是一个构造函数。回退到原来正常使用的1.4.1依然报错。
`
Uncaught TypeError: BScroll is not a constructor
    at VueComponent._initSlide (slide.vue:130)
    at VueComponent.boundFn [as _initSlide] (vue.runtime.esm.js:180)
    at slide.vue:58`

使用方法：
```
mounted () {
    const BScroll = require('better-scroll')
    this.slide = new BScroll(this.$refs.slide, {
          scrollX: true,
          momentum: false,
          snap: {
            loop: this.loop,
            threshold: 0.3,
            speed: 400
          },
          click: this.click
    })
}
```

**Comment by maxming2333** [comment]
+1

升级到 `1.4.2` 后，需要用  `require('better-scroll').default`

**Comment by liudg** [comment]
@maxming2333 谢谢，按你的方法弄好了

**Comment by ustbhuangyi** [comment]
你是用 webpack 构建的项目吗?

**Comment by liudg** [comment]
@ustbhuangyi 是的

**Comment by zhoujingang** [comment]
> 外测网址：http://m.hnshuguo.com/
> 
> 问题：升级1.4.2后，nuxt服务端渲染提示BScroll不是一个构造函数。回退到原来正常使用的1.4.1依然报错。
> ` Uncaught TypeError: BScroll is not a constructor at VueComponent._initSlide (slide.vue:130) at VueComponent.boundFn [as _initSlide] (vue.runtime.esm.js:180) at slide.vue:58`
> 
> 使用方法：
> 
> ```
> mounted () {
>     const BScroll = require('better-scroll')
>     this.slide = new BScroll(this.$refs.slide, {
>           scrollX: true,
>           momentum: false,
>           snap: {
>             loop: this.loop,
>             threshold: 0.3,
>             speed: 400
>           },
>           click: this.click
>     })
> }
> ```

为什么我需要点击一次才能滚动呢？
