### ISSUE TITLE
横向滚动问题

### ISSUE THREAD

**Issue by skyline-123** [ustbhuangyi/better-scroll#35]
首先非常感谢老师的better-scroll库,它的表现非常棒!

最近测试了下,发现需要横向滚动的话,option的设置必须为scrollY: false而且scrollX: true.缺一不可.文档中没有明确说明,可能会导致不必要的调试困难.希望这里能给大家提个醒.

**Comment by skyline-123** [comment]
因为横向滚动的时候,不能写死ul的width,所以只能用js动态写入.当用js动态的设置width的时候,由于width设置在行间样式,也会导致横向滚动失效.不知道这个问题怎么解决?

**Comment by skyline-123** [comment]
因为横向滚动的时候,不能写死ul的width,所以只能用js动态写入.当用js动态的设置width的时候,由于width设置在行间样式,也会导致横向滚动失效.不知道这个问题怎么解决?

**Comment by zhujunel** [comment]
就是说现在横向滚动有问题是么？

**Comment by ustbhuangyi** [comment]
@zhujunel ，没有问题，只不过需要通过 js 计算子元素的宽度并设置。

**Comment by xiongc** [comment]
也可以不用JS计算，设置CSS
`.scroll-content {
        width:auto;
        display:inline-block;
        white-space: nowrap;
        span {
          display: inline-block;
        }
 }
`

**Comment by Xutaotaotao** [comment]
横向滚动需要对内容的宽度进行实时调整

```
<div class="content" :style="{width: myWidth}"></div>
```
