### ISSUE TITLE
你好大神，纵向轮播的问题

### ISSUE THREAD

**Issue by c690554125** [ustbhuangyi/better-scroll#350]
最近有个需求，纵向轮播，新闻列表类的。发现用bs滚动到纵向最后一个就不在滚动。稍微看了下源码，定位在1389行，这里只对横向轮播滚动做了处理，纵向好像没处理啊。稍微改了下代码。
`      
if (snap.loop && scrollX && !scrollY) {
        if (_this.currentPage.pageX === 0) {
          _this.goToPage(_this.pages.length - 2, _this.currentPage.pageY, 0);
        }
        if (_this.currentPage.pageX === _this.pages.length - 1) {
          _this.goToPage(1, _this.currentPage.pageY, 0);
        }
      }else if(snap.loop && scrollY && !scrollX){
        if (_this.currentPage.pageY === 0) {
          _this.goToPage(_this.currentPage.pageX, _this.pages.length - 2, 0);
        }
        if (_this.currentPage.pageY === _this.pages.length - 1) {
          _this.goToPage(_this.currentPage.pageX, 1, 0);
        }
      }
`
还是不行，发现_this.pages.length值永远都是1，无奈将_this.pages.length换成了this.scroller.children.length，然后轮播就可以了。1296行的_this.pages的增加实在没看懂。 
请问黄老师，有没有正统一点的解决方法能提示一下？总感觉我这改的有点别扭。

**Comment by ustbhuangyi** [comment]
能提供一个可访问的 demo 地址吗

**Comment by ustbhuangyi** [comment]
纵向轮播确实没有实现循环，因为之前还还没这样的需求。

**Comment by c690554125** [comment]
刚写了个DEMO。http://runjs.cn/code/kgcvazw4   恩。看了下源码，只对pageX到达第一个和最后一个进行了处理。 目前我自己先临时改了下，黄老师有空了改进下--!
