### ISSUE TITLE
pullingUp 和 finishPullUp() 的问题

### ISSUE THREAD

**Issue by 00ERNEST00** [ustbhuangyi/better-scroll#351]
当我执行pullingUp 上拉加载到最后没有数据的时候，会马上执行 finishPullUp()， 之后pullingUp 事件就会失效。
如果我 这样写  setTimeout(function (){
                                scroll.finishPullUp();
                                scroll.refresh();
                            }, 800)
则功能正常。
请大神获悉。

**Comment by ustbhuangyi** [comment]
参考一下 demo 的写法吧，如果没有数据的时候，调用一下 finishPullUp 没有毛病呀

**Comment by 00ERNEST00** [comment]
最后一次请求数据之后，轻轻上拉一次 是可以，但是 连续快速 往上拉   之后  pullingUp就会失效

**Comment by Geek-JCY** [comment]
Uncaught TypeError: this.scroll.finishPullUp is not a function 这是怎么回事呢？用的是 example中的scroll.vue 做的测试

**Comment by php4world** [comment]
> Uncaught TypeError: this.scroll.finishPullUp is not a function 这是怎么回事呢？用的是 example中的scroll.vue 做的测试

我也遇到了。解决了吗
