### ISSUE TITLE
在初始化滚动条的时候滚动高度计算错误

### ISSUE THREAD

**Issue by EdisonZhang1996** [ustbhuangyi/better-scroll#353]
请问 在页面滚动条初始化的时候由于页面数据比较多（没有做分页） 导致滚动高度scrollerHeight的高度计算错误 页面只能滚动一部分 console了一下scroll的属性  发现scrollerHeight跟实际滚动容器下的滚动高度不一样 在设置延时器之后可以正常滚动，但是当页面数据量非常多的时候 延时的时间需要很多 甚至需要一到两秒的时间去延时初始化滚动  请问除了页面数据做分页以外 怎么解决这个问题

**Comment by ustbhuangyi** [comment]
试试新版的 better-scroll 吧，支持了自动 refresh。

**Comment by johnqiuwan** [comment]
之前一直也在困惑类似的问题，谢谢新版本带来的便捷，省了我很多时间，希望better-scroll 越做越丰富
