### ISSUE TITLE
实现一个滚动区内子元素固定位置的问题

### ISSUE THREAD

**Issue by funkyfun** [ustbhuangyi/better-scroll#354]
需求是这样的，滚动区内是分上中下三个部分，中间部分是个tab分类栏，需要滚动到tab栏时，tab栏固定在滚动区顶部，本来想用fixed实现，由于transition对position:fixed影响，结果还是不会固定，求解决方案

**Comment by ustbhuangyi** [comment]
不要用 issue 来问问题
