### ISSUE TITLE
better-scroll一个重大BUG(左右联动！)

### ISSUE THREAD

**Issue by yzw2017** [ustbhuangyi/better-scroll#355]
# 左右联动
**比如**：在作者的饿了么项目中，当你点击左边的食品种类，按道理右边的food要跳的所选的种类中。
**BUG**： 当点击精选套餐的时候，右边的food已经跳到精选套餐的列表，可是左边的种类没有在点击的种类中显示高亮，而是在点击的上一个种类中高亮！(即爽口凉菜高亮了)
# **个人分析！**
因为左边的食品种类的高亮，是依赖右边的食品滚动，同时监听scrollY跟高度作对比，从而判断右边的食品种类的高亮。问题就出在当点击左边的列表，右边已经滚动到对应的位置，但是！！！滚动的位置有一些偏差！导致左边的列表高亮的位置不对
# 个人想到的解决方案
selectMenu(index) {
        let foodList = this.$refs.foodList
        let el = foodList[index]
        this.$refs.foodScroll.scrollToElement(el, 300, 0, 1)
      },
这代码来至作者的项目， 当点击左边的食品种类的时候，右边的滚动要滚动到对应的位置，要加上1个偏差值，这时左边的高亮才可以正确显示！ 滚动的时间越长效果越明显！希望这个BUG作者修复！，同时这个BUG在VUE2.0音乐播放器也存在！只是作者在点击左边的快速列表的过程中，联系人是瞬间到的，如果设置一个过渡时间，这BUG一样存在。请别删这个ISSUES

**Comment by ustbhuangyi** [comment]
这个问题和 better-scroll 本身有什么关系呢？
