### ISSUE TITLE
关于pc滚动组件无法第一时间滚动的问题

### ISSUE THREAD

**Issue by fyAgent** [ustbhuangyi/better-scroll#358]
最近看着您的当better-scroll遇上vue那篇文章也照着封装成了组件但是当我初始状态设置scroll组件的show为false的时候，那么当组件出现后无法第一时间滚动，只有当我改变了一下屏幕的大小的时候才可以滚动，额对了 slot插槽里我放的是一些router-link的列表，还有使用了 transition的过渡效果。求大神解答

**Comment by fyAgent** [comment]
当将初始的show改成 true的时候就可以滚动了这是为什么呢

**Comment by ngulee** [comment]
我也遇到首次无法滚动的情况，必须手动刷新页面才能够实现滚动效果

**Comment by ustbhuangyi** [comment]
试试新版的 better-scorll 吧，支持了自动 refresh。
