### ISSUE TITLE
滚动区溢出后在溢出区试图操作滚动响应不及时

### ISSUE THREAD

**Issue by xwpongithub** [ustbhuangyi/better-scroll#359]
测试过的better-scroll版本：1.4.0及以上版本
发现的问题：当在滚动区外部的溢出区试图滚动时，只有滚动结束后操作滚动才会响应，这个问题在1.4.0及以上版本才出现
调试地址：
https://codepen.io/xwpongithub/pen/Bwayqa

**Comment by ustbhuangyi** [comment]
溢出区滚动是什么意思？你这个 demo 难以在手机上调试啊

**Comment by xwpongithub** [comment]
就是在原来滚动区以外溢出的区域里用手指滑动的话，比如先向上滑，然后在滑动还没结束的过程中又向下滑，这个时候就不会响应滑动了，必须等滑动结束后才会响应。在滚动区内滑动就不会有这个问题了

**Comment by xwpongithub** [comment]
有时候是需要这种需求的啊，比如黄老师你的播放器那个music-list组件里，在溢出区滚动的话就不能很好的响应~

**Comment by ustbhuangyi** [comment]
fixed
