### ISSUE TITLE
react-lazyload在better-scroll1.5.1的版本remove了1.5.0的_initDOMObserver里的debounce函数造成的问题

### ISSUE THREAD

**Issue by cixiu** [ustbhuangyi/better-scroll#363]
1.5.0版本中对MutationObserver做的防抖函数debounce在1.5.1后被移除后[remove the use of debounce](https://github.com/ustbhuangyi/better-scroll/commit/f67962a262648f1c731369d3686506f6b557de6b)，在react-lazyload做图片懒加载后，快速滑动时有很大可能没有滚动动画就直接跳到了最底部，在scroll事件里处理的懒加载也没有实现。而1.5.0以下版本则没有这个问题。希望解决一下。其实debounce的设计蛮好的，为什么要remove掉呢

**Comment by ustbhuangyi** [comment]
这块其实还略有些复杂，考虑的场景比较多，目前还有一些细节问题，计划在 1.5.3 解决。

**Comment by ustbhuangyi** [comment]
已发布，可以去试试
