### ISSUE TITLE
首次加载页面，页面包含图片链接时，插件计算的高度没有包括图片高度，导致下拉不动怎么办？

### ISSUE THREAD

**Issue by shootingtheball** [ustbhuangyi/better-scroll#365]
我使用了refresh方法，放到了window.onload里也会失败

**Comment by shootingtheball** [comment]
我使用了refresh方法，放到了window.onload里也会失败

**Comment by ustbhuangyi** [comment]
你试试 1.5.3 版本的 better-scroll 呢？

**Comment by ustbhuangyi** [comment]
可使用最新版本的 better-scroll

**Comment by ChrisChenSZ** [comment]
我也出现了这个问题,当列表是图片的时候,在华为的配置较低手机上,还有魅蓝的手机上首次加载就会出现拉不到底部,目前是用了settimeout 0.5秒后可以解决大部分主流手机,但是这个方法在一些低配置手机上不行,而且当网络慢的时候,也会出现这个问题.明天试试1.53版本的,试试能否解决.
