### ISSUE TITLE
slide相互嵌套，出现的问题。

### ISSUE THREAD

**Issue by hulinNeil** [ustbhuangyi/better-scroll#369]
使用slide制作可以左右拖动的tab页面，在页面里面含有slide做的轮播图，拖动轮播图会导致整个页面也跟着拖动。滑动轮播图片的时候，可以看到beforeScrollStart函数执行了两次，打印this出来，第一个this指向轮播图，第二个this指向tab页面，该如何阻止其冒泡呢？或是有其他办法解决吗？

**Comment by ustbhuangyi** [comment]
请按 issue 规范提供可访问的 demo 地址描述你的问题
