### ISSUE TITLE
与滚动部分的 content 元素同级的div里面的input 元素的点击事件在vue-cli单页面开发下无法生效？

### ISSUE THREAD

**Issue by fantasy525** [ustbhuangyi/better-scroll#370]
`1.vue版本"^2.5.2",better-scroll:"^1.5.3" "vue-router": "^3.0.1"`
`2.我用vueCli单页面开发时滚动部份同级的input元素的点击事件没生效，但是我换成script引入方式就生效，这是怎么回事？`
[`3.demo链接`](http://jsrun.net/dniKp/show )
这个demo点击下面的input按钮可以alert，但是把demo的代码转换为vueCLI开发的单页面时就不会触发了，需要用到vue-router,配置路由，由于是移动端我用到了淘宝的flexible.js适配，就这些了吧，请测试下，谢谢

**Comment by ustbhuangyi** [comment]
有 JS 报错，你看一下初始化 better-scroll 的时机，wrapper 是否还没有获取到

**Comment by fantasy525** [comment]
黄老师，改好了，已经没有获取不到wrap dom的报错了，麻烦看下

**Comment by fantasy525** [comment]
我这边测试不管是放在跟滚动元素同级还是放在滚动元素里面都无法触发点击事件，demo的是放在滚动元素里面的。但是放在wrap同级就可以触发它的点击事件了

**Comment by fantasy525** [comment]
黄老师，经过我仔细测试发现问题出在同级的div里面的子元素如果是input元素，那对它绑定的点击事件就不会触发，图中class为btn的div可以触发点击事件，但是它里面的input则无法触发，我换为其他子元素比如p,button元素就可以触发了
![qq 20171203211552](https://user-images.githubusercontent.com/22516157/33525670-79039e04-d86f-11e7-8e21-f653b038bf25.png)

**Comment by fantasy525** [comment]
已经放在codesandbox上了,[CodeSandBox](https://codesandbox.io/s/92l3n2n72o)

**Comment by ustbhuangyi** [comment]
试试 1.5.5 版本呢？

**Comment by fantasy525** [comment]
OK，1.5.5版本测试可以了

**Comment by fantasy525** [comment]
但是我想问下，是什么原因？能否大概说下

**Comment by ustbhuangyi** [comment]
input 的 click 事件在捕获阶段 stopPropergation 影响了事件的派发，并且 input 不会响应手动派发的 click 事件。
