### ISSUE TITLE
snap 参数的文档不齐全

### ISSUE THREAD

**Issue by yuanyuanyuan** [ustbhuangyi/better-scroll#371]
文档 demo 里面说是用一个对象，
snap: {
            loop: this.loop,
            threshold: 0.3,
            speed: 400
          },

但我看慕课视频里说的是
  snap: true,
                snapLoop: this.loop,
                snapThreshold: 0.3,
                snapSpeed: 400

有点混乱？ 虽然好像两者都是可以运行的。

**Comment by ustbhuangyi** [comment]
视频是之前版本的，新版本的以文档为主。
