### ISSUE TITLE
移动端和谷歌移动端模拟器 <router-link> href 无法跳转

### ISSUE THREAD

**Issue by adouwt** [ustbhuangyi/better-scroll#375]
bs 版本： 1.5.4；
问题：移动端和谷歌移动端模拟器 <router-link> href 无法跳转 ，但是在pc 端可以点击，是不是移动端阻止了a 的默认操作；
跳转代码：
<router-link :to="'/courseid=' + i.id">
测试网址没有，本地调试

**Comment by ustbhuangyi** [comment]
CodePen、CodeSandbox、JSFiddle 都可以

**Comment by silence-may** [comment]
请问这个问题解决了吗？
