### ISSUE TITLE
better-scroll在下拉或上拉回弹动画中 点击按钮会导致无法点击或要多次点击甚至卡死

### ISSUE THREAD

**Issue by Mrmanshow** [ustbhuangyi/better-scroll#383]
![image](https://user-images.githubusercontent.com/18023425/33760429-93d817f8-dc40-11e7-8fe4-b9a874179c13.png)
包括安卓、苹果和PC

**Comment by ustbhuangyi** [comment]
目前的设计就是在下拉刷新及上拉回弹的动画以及在滚动的动画过程中，是不允许点击的。

**Comment by Mrmanshow** [comment]
动画停止 为什么按钮会点不动甚至卡死

**Comment by ustbhuangyi** [comment]
并没复现卡死的情况，提供详细复现步骤？

**Comment by Mrmanshow** [comment]
在下拉回弹的过程动画中 点击按钮 之后会点不动 要多点几次才会响应

**Comment by ustbhuangyi** [comment]
你需要等回弹完成后再点击

**Comment by Mrmanshow** [comment]
那非要这样是不要要监听 动画结束前 在页面顶部加个遮挡层 不让用户点击才可以

**Comment by ustbhuangyi** [comment]
并不需要吧，点击一般不都会有 active 样式的吗，你可以参考 https://ustbhuangyi.github.io/better-scroll/#/examples/vertical-scroll/en

**Comment by Mrmanshow** [comment]
请问样式怎么控制点击事件

**Comment by ustbhuangyi** [comment]
并不会啊，你拿手机试试吧，您不能再回弹的过程中不断点击，而是等回弹完毕后点击，能点击的情况会有一个 active 的样式，这也是参考微信列表的实现。

**Comment by Mrmanshow** [comment]
那您试一下在滚动动画中点击按钮 会不会导致按钮无效 要点击好几下才能跳转到下个页面

**Comment by ustbhuangyi** [comment]
这块可以考虑做成可配置的吧，来适应不同的场景。

**Comment by Mrmanshow** [comment]
在滑动到顶部或者底部 动画没结束 就会导致按钮失效 在中间滑动单击停止能正常进去        那目前是不是只能监听到顶部或者顶部动画没结束就设置一个遮挡层 不让用户单击

**Comment by Mrmanshow** [comment]
希望组件可以优化一下

**Comment by ChrisChenSZ** [comment]
回弹过程中连续点击按钮导致动画结束还是点击不了这个问题确实比较明显，在回弹的过程中连续点击不能click即使动画结束了，还要等动画结束后过几秒才能点击，有时还会卡死完全点击不了，而回弹过程中如果不连续点击，动画结束后就能正常的点击，问题在于为何回弹动画过程中连续点击就会导致后面动画结束出现很大概率的点击不了事件，回弹过程中设置不能点击然后连续点击就会导致回弹动画结束完后没法开启点击事件功能，我觉得问题出现在这里，作者应该检查下这里的代码的问题，为何回弹动画和下拉刷新过程中连续点击就会出现后面点击事件延迟好几秒。我目前是让下拉刷新回弹时间设置成100毫秒左右，尽量避免用户在下拉刷新回弹的时候点击

**Comment by ustbhuangyi** [comment]
@ChrisChenSZ ，会在 1.5.6 版本优化

**Comment by caokunyu** [comment]
下拉刷新回弹的时候反向滑动 白屏

**Comment by Mrmanshow** [comment]
请问下个版本大概能在什么时候发布

**Comment by ustbhuangyi** [comment]
@Mrmanshow 预计周三前，我还要对 snap 做一些优化，可能会发布 1.6 版本

**Comment by ustbhuangyi** [comment]
@Mrmanshow, @ChrisChenSZ  已发布 1.5.6 版本

**Comment by Mrmanshow** [comment]
新版本 下拉回弹有一定几率瞬间回弹   卡死的问题不会再出现了 但是有时也需要单击两三下才能跳转 一般是两下 第一下应该是停止动画时再一次才是实际跳转事件
