### ISSUE TITLE
better-scroll  猛的下拉 或者上拉 会出现 白屏 ，但是dom 貌似 还存在 这个 白屏中 点击事件依然可以触发

### ISSUE THREAD

**Issue by caokunyu** [ustbhuangyi/better-scroll#384]

**Comment by caokunyu** [comment]
就是下拽的过程中 突然上划一下 就会出现

**Comment by ustbhuangyi** [comment]
请按 issue 规范提，提供一个访问的 demo 及稳定复现的步骤

**Comment by programmer1000** [comment]
同出现该问题，
如果数据列表比较长，
在上下突然地来回滑动时会出现页面空白。
![d 3 eo9 d d01 akyiq](https://user-images.githubusercontent.com/22095849/34428134-9e35d72c-ec84-11e7-85be-0a90f6c77e1c.png)

**Comment by yulezhong** [comment]
在做项目的时候也遇到这个问题，在ios微信浏览器比较明显

**Comment by 1259932147** [comment]
同样碰到这个问题，deceleration:0.002 就可以了

**Comment by laoboxie** [comment]
我通过开启GPU加速解决了这个问题
