### ISSUE TITLE
在做下拉刷新过程中，有一定几率造成覆盖问题。

### ISSUE THREAD

**Issue by bestime** [ustbhuangyi/better-scroll#386]
### 有时候刷新后正常，有时候刷新后感觉像是复制了一层在执行拖动。
![default](https://user-images.githubusercontent.com/30017385/33816023-129d0152-de71-11e7-8c67-4f57d03c560f.gif)

**Comment by ustbhuangyi** [comment]
请按 issue 规范提供可以复现的 demo 链接

**Comment by caokunyu** [comment]
@ustbhuangyi   黄老师 怎么把我问题 删掉了 要不 我把demo 打个包 给你 你在移动端 试下

**Comment by ustbhuangyi** [comment]
@caokunyu ，可以用这个工具：https://codesandbox.io/s

**Comment by zhe-he** [comment]
给父级设置个背景色可以快速解决,即使有2层也看不见里面。 /斜眼笑

**Comment by bestime** [comment]
@zhe-he 这不科学。再说了`dome` 结构里确实只有一层。

**Comment by ustbhuangyi** [comment]
我的代码肯定不会帮你多复制一个层，多半是因为你的代码问题，这也是为什么需要你提供一个可访问的 demo 地址，否则我只能关 issue 了。

**Comment by bestime** [comment]
@ustbhuangyi这是我才弄的测试页面。 [http://show.bestime.live/test/06.html](url) 当页面有多个的时候，偶尔会有这个问题。审查元素确实是只有一层。

**Comment by ustbhuangyi** [comment]
@bestime 404 了，建议使用 https://codesandbox.io/s 来搞一个 demo，也方便我修改你的代码
