### ISSUE TITLE
ios 使用了better-scroll 后滑动时为什么input等输入框光标瞎移动位置不准确。

### ISSUE THREAD

**Issue by akumaLin** [ustbhuangyi/better-scroll#387]
代码：https://jsfiddle.net/12hzngn1/
[https://jsfiddle.net/12hzngn1/](url)
不怎么会使用github，求大神解答，怎么解决这个bug

**Comment by Niofh** [comment]
你解决了吗？

**Comment by ustbhuangyi** [comment]
试试1.10.3版本
