### ISSUE TITLE
从登陆页面跳转到首页（有slider），无法获取到挂载的子节点

### ISSUE THREAD

**Issue by Eline2017** [ustbhuangyi/better-scroll#388]
出现的问题：
<img width="908" alt="default" src="https://user-images.githubusercontent.com/23447167/33938665-4986ec9a-e043-11e7-9958-6e79a300c234.PNG">

用的谷歌的手机模拟状态和最新版本的better-scroll

**Comment by Eline2017** [comment]
把this.$nextTick换为setTimeout((),2000),并把执行时间调整到至少2000ms才会正常显示轮播图的正常样子

**Comment by ustbhuangyi** [comment]
请提供可以稳定复现的 demo 地址，建议使用 https://codesandbox.io/
