### ISSUE TITLE
初始化的时候好像获取不到总宽度,我自己手动计算添加的高度

### ISSUE THREAD

**Issue by youdianfan** [ustbhuangyi/better-scroll#389]
"better-scroll": "^1.5.6"版本,

`<ul data-v-18a6f8b7="" class="content" style="transition-property: transform; transition-timing-function: cubic-bezier(0.165, 0.84, 0.44, 1); transition-duration: 0ms; transform: translate(200px, 0px) translateZ(0px);
<ul data-v-18a6f8b7="" class="content" style="transition-property: transform; transition-timing-function: cubic-bezier(0.165, 0.84, 0.44, 1); transition-duration: 0ms; transform: translate(200px, 0px) translateZ(0px);`

`      _this.$nextTick(() => {
        let wrapper = document.querySelector('.wrapper')
        setTimeout(() => {
          _this.scroll = new BScroll(wrapper, {
            scrollX: true,
            click: true
          })
          let width = 0;
          for (var i = 0; i < _this.scroll.scroller.children.length; i++) {
            width += _this.scroll.scroller.children[i].clientWidth
          }
          console.log(width);
          _this.scroll.scroller.style = 'width:' + width + 'px;' + 'transition-property: transform; transition-timing-function: cubic-bezier(0.165, 0.84, 0.44, 1); transition-duration: 0ms; transform: translate(0px, 0px) translateZ(0px);'
        }, 200)
        
      })`

**Comment by youdianfan** [comment]
没法传图,明天到公司补上.难道是我css写的有问题吗?

**Comment by youdianfan** [comment]
![default](https://user-images.githubusercontent.com/27018910/33970121-3206cba8-e0ac-11e7-8dfb-ea016529a834.png)
![default](https://user-images.githubusercontent.com/27018910/33970129-3db3df54-e0ac-11e7-9031-761685bcd968.png)

**Comment by ustbhuangyi** [comment]
提供一下可以复现的 demo 吧，推荐使用 https://codesandbox.io/s

**Comment by youdianfan** [comment]
好的  晚上写一下 上班有点忙

**Comment by tjw935988288** [comment]
应该是你的CSS没有给this.wrapper设置高度值吧 
`let wrapperRect = getRect(this.wrapper)
 this.wrapperWidth = wrapperRect.width
 this.wrapperHeight = wrapperRect.height`
源码的refresh中会通过上面的语句计算this.wrapper.offsetWidth

**Comment by youdianfan** [comment]
我看官方demo也没有给啊,我要的上横向的滚动.我来把代码复现一下吧.我确实也在怀疑是不是我的css代码有问题

**Comment by youdianfan** [comment]
https://codesandbox.io/s/r48pnl088p

**Comment by ustbhuangyi** [comment]
很明显你还是没弄清楚 better-scroll 的滚动原理，只有内层容器 content 的宽度超过外层容器 wrapper 的宽度的时候才能滚动。
P.S 横向导向条的 demo 我们正在补充中，预计下周会放出来

**Comment by youdianfan** [comment]
我知道滚动原理，content宽度不应该计算后，添加上去吗？我有看demo都是有加上高度的，所以我自己也说了，自己手动添加了宽度就可以滚动了。我的理解是，插件应该就可以帮我们做好计算。

感谢，作者的回复！辛苦了，会持续关注！我还是会选择应用这个插件。
