### ISSUE TITLE
Bscroll 内部绝对定位和fiexd定位会跟着一起滚动？

### ISSUE THREAD

**Issue by gitwangyu451336451** [ustbhuangyi/better-scroll#390]
<div class="hd_wrapper" ref="hd_wrapper" v-initScroll="data" :path="path">
  	<div class="hd_wrapper_content">
            <div class="tbar_father_contain">xxxxxxxxxxxxxxx</div>

.tbar_father_contain{
  position: absolute;
  height: .4rem;
  width: 100%;
  top: 0;
  z-index: 999;
}

**Comment by ustbhuangyi** [comment]
请按 issue 规范提供 demo

**Comment by ZhengXiaowei** [comment]
因为滚动是使用transform进行滚动的 而fixed定位在transform里的效果等同于absolute 如果你想实现fixed效果 你可以将要fixed的元素放到scroll外 然后通过监听滚动 计算fixed/absolute的top值
