### ISSUE TITLE
better-scroll支持安卓5.0系统或者ios8系统吗？

### ISSUE THREAD

**Issue by linxiaowu66** [ustbhuangyi/better-scroll#391]
按照我目前的实践，在安卓5.0和ios8系统上，better-scroll中使用slide这个功能，基本都会出现滚动结束后没有触发scrollEnd事件，调试的时候在触发transitionEnd事件的时候进入transitionEnd函数中判断isInTransition这个if判断语句不成立 直接返回，所以不会触发。但是没找出为什么这会isInTransition会是false。在系统更高的手机上这个是为true的。所以问问作者这个问题。

@ustbhuangyi

**Comment by ustbhuangyi** [comment]
@linxiaowu66 你用的是哪个版本， 1.5.6 版本修复了一个标准 transitionend 事件名称的 bug

**Comment by linxiaowu66** [comment]
@ustbhuangyi 用的是最新版本1.5.6  你那边能够复现吗？在这个系统上我看用的是webview43 版本，算是比较旧的版本

**Comment by ustbhuangyi** [comment]
明天找 qa 找几台古董机器看看吧，理论上应该是没问题

**Comment by linxiaowu66** [comment]
好的 多谢了 @ustbhuangyi

**Comment by ustbhuangyi** [comment]
目前没发现问题，先关了，如果仍有问题，提供一下可以稳定复现的 demo 地址（建议使用 codesandbox），我们再看，
