### ISSUE TITLE
安卓手机不触发原生点击事件问题

### ISSUE THREAD

**Issue by FirstAurora183** [ustbhuangyi/better-scroll#392]
```js
<scroll ref="scroll" :click="scrollClick" :probeType="probeType" @scroll="scrollPOS" >
        <div @click="clickPOS" class="fiction-container" v-html="currentSerialContent">
        </div>
</scroll>
```
better-scroll之前用的版本1.3.1，现在升级到1.5.6  
我想获取到点击`fiction-container`的屏幕位置，设置`scrollClick`为false使用原生click，在chrome模拟手机端和iPhone上面可以触发click并获取到`screenY``screenX`等数据，但是安卓手机(小米、华为)不会触发原生click事件。  
而使用better-scroll模拟的click，安卓和iPhone都能触发click事件，但是想要获取到的`screenX`等数据都为0。  
请问安卓手机为何不触发原生click事件，或者模拟click事件如何获取屏幕位置信息等数据。

**Comment by ustbhuangyi** [comment]
click 为 false 是不会触发原生 click 事件的，因为 touchstart 的时候阻止了默认事件，目前 better-scroll 模拟的 click 事件确实没有加上这些额外数据，这块可以考虑加上。

**Comment by ustbhuangyi** [comment]
会在 1.6.0 版本支持

**Comment by bill-mark** [comment]
大哥  1.6今天能发版吗  现在就想用 挺急的  安卓click失效

**Comment by ustbhuangyi** [comment]
已发布 1.6.0
