### ISSUE TITLE
1.6版本在实现轮播时，实例属性click为true时不可点击（a标签跳转）， 为false时反而可以点击实现跳转

### ISSUE THREAD

**Issue by ym87498510** [ustbhuangyi/better-scroll#393]
this.slider = new BScroll(this.$refs.slider, {
          scrollX: true, // 水平滚动
          scrollY: false, // 垂直滚动
          momentum: false, // 惯性
          snap: true, // 轮播
          snapLoop: this.loop,
          snapThreshold: 0.3, //
          snapSpeed: 400, // 动画时间
          click: true //  *********此处是不是反了？？？？******
        })

**Comment by ustbhuangyi** [comment]
请按 issue 规范提供可访问的 demo 链接，另外 snap 属性已经是一个对象了，参考文档：https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options-advanced.html#snap
