### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by Anikinly** [ustbhuangyi/better-scroll#395]
隐藏的元素动态请求数据进来，然后实例化就滚动不了，移动端

**Comment by ustbhuangyi** [comment]
请按 issue 规范提，提供可以访问的 demo 地址（最好借助于 CodeSandbox），以及 better-scroll 的版本

**Comment by Anikinly** [comment]
已修改了问题的答案

**Comment by ustbhuangyi** [comment]
你试试用最新版本的 better-scroll

**Comment by Anikinly** [comment]
老师，麻烦请问原理上我滚动框是隐藏的，实例化的时候，这样子会有问题吗？ 我如果不隐藏是好，隐藏了实例化就有很多问题，感觉很卡的样子
