### ISSUE TITLE
在ios微信浏览器的滚动问题

### ISSUE THREAD

**Issue by mangoooooo** [ustbhuangyi/better-scroll#396]
1. 在微信中扫码打开better-scoll官网 列表demo;
2. 上下滚动会出现白块；
3. ios版本：11.1.2；

**Comment by ustbhuangyi** [comment]
同系统，并没有复现该问题

**Comment by programmer1000** [comment]
同出现空白块（上下速度很快的不停来回滑动）
ios版本 10.0.1
![d 3 eo9 d d01 akyiq](https://user-images.githubusercontent.com/22095849/34428078-10433df6-ec84-11e7-9ea1-0b88312bf7ef.png)

**Comment by ustbhuangyi** [comment]
请按 issue 规范提
