### ISSUE TITLE
在滚动区域content中使用fixed定位问题

### ISSUE THREAD

**Issue by sshien** [ustbhuangyi/better-scroll#398]
content 滚动区域中的的div 是基于滚动区域定位，而不是body。求解

**Comment by ustbhuangyi** [comment]
这类问题去 qq 群里讨论吧

**Comment by sshien** [comment]
QQ群是多少呢




发自网易邮箱大师
在2017年12月19日 19:31，HuangYi 写道：

Closed #398.
