### ISSUE TITLE
绑定时机问题

### ISSUE THREAD

**Issue by tanlucheng** [ustbhuangyi/better-scroll#40]
感谢老师这么好用的插件，提一个issue，当父节点display为none的时候，此时给其子节点绑定BScroll，把父节点display为block后，滚动不生效。必须在父节点display不为none的时候，绑定BScroll才有效。

**Comment by ustbhuangyi** [comment]
是这样的，因为 better-scroll 在初始化的时候需要有 dom 相关的计算，如果 display 为 none 的话肯定不能正确计算，所以一般 better-scroll 的初始化时机是 dom 渲染后。

**Comment by tanlucheng** [comment]
明白
