### ISSUE TITLE
下拉刷新时关于监听pullingDown事件时的bug

### ISSUE THREAD

**Issue by aioros2016** [ustbhuangyi/better-scroll#400]
今天在使用better-scroll组件的页面中，制作了下拉刷新的效果，监听了pullingDown事件并向父组件派发一个刷新的消息出去。效果完成后，频繁下拉刷新页面，发现页面有一定几率会无法监听到pullingDown事件，也就是说当把页面拉倒设定的阈值后，文字变为释放刷新。这时放开页面，有一定几率无法触发pullingDown事件。

**Comment by ustbhuangyi** [comment]
请按 issue 规范提供可访问的 demo 地址，推荐 codesandbox，以及详细的复现步骤，或者去看看 cube-ui 的下拉刷新实现。
