### ISSUE TITLE
1.6.0版本中设置click:true，a标签上href不能跳转，之前老版本没这个bug 

### ISSUE THREAD

**Issue by qiubi8801** [ustbhuangyi/better-scroll#401]
移动端页面

CSS:

    *{margin:0; padding:0;}
    .webview{position:fixed; left:0; right:0; top:0; bottom:0;}

 HTML：
   
    <div class="webview" id="J_webview">
        <div style="height:50rem;">
            <a href="http://www.baidu.com">百度</a>
        </div>
    </div>
    
    
JS: 引用的better-scroll 版本：1.6.0
    
    <script>
    var myScroll = new BScroll('#J_webview',{
        click: true
    });
    </script>

**Comment by ustbhuangyi** [comment]
请按 issue 规范提供可访问的 demo 地址，推荐 codesandbox

**Comment by ustbhuangyi** [comment]
试试 1.6.2 版本

**Comment by qiubi8801** [comment]
1.6.2版本已经完美修复这个问题  问题可以关闭了 谢啦 @ustbhuangyi
