### ISSUE TITLE
maxScrollX 不起作用?

### ISSUE THREAD

**Issue by Alicepp** [ustbhuangyi/better-scroll#404]
```javascript
new BScroll('.data-con',{
        startX: -(offsetleft  - (20/75 * (w/10)) ),
        scrollX: true,
        maxScrollX:-1000
 });
```
滚动位置滚动到了-1430，设置的-1000没起作用
![滚动图片](http://oi7sxakwb.bkt.clouddn.com/qb-sign.png)

**Comment by ustbhuangyi** [comment]
这个属性是计算而来的，并不支持配置

**Comment by Alicepp** [comment]
那有什么方法可以解决的我这个问题？申请加群了，通过一下

**Comment by ustbhuangyi** [comment]
@Alicepp 你要的是这种横向滚动条？https://ustbhuangyi.github.io/better-scroll/#/examples/nav-list/1/en
