### ISSUE TITLE
滚动到最后，总是无故多出一块空白

### ISSUE THREAD

**Issue by Alicepp** [ustbhuangyi/better-scroll#406]
```javascript
new BScroll('.data-con',{
        startX: -(offsetleft  - (20/75 * (w/10)) ),
        scrollX: true,
 });
```
滚动位置滚动到了-1430，导致右边多出一块空白，那有什么方法可以解决的我这个问题？
![滚动图片](http://oi7sxakwb.bkt.clouddn.com/qb-sign.png)

**Comment by ustbhuangyi** [comment]
参考 https://ustbhuangyi.github.io/better-scroll/#/examples/nav-list/1/en
代码在 https://github.com/ustbhuangyi/better-scroll/blob/master/example/pages/navigator.vue
