### ISSUE TITLE
纵向滚动的回弹效果

### ISSUE THREAD

**Issue by xzfd1010** [ustbhuangyi/better-scroll#407]
您好，现在想要用better-scroll制作fullpage的效果，希望能够在每次滚动到下一页的时候先越过顶部再回弹。类似这种：https://xzfd1010.github.io/webComponents/
目前copy的官网的横向轮播，做了纵向轮播，只为演示，您看过后会删掉这个库：https://xzfd1010.github.io/demo/index.html#/examples/vertical/zh
在fullpage.js中可以用easingcss3来指定贝塞尔曲线自定义回弹效果。
查better-scroll的文档没有找到相关的配置，请问有没有类似的配置项？

**Comment by ustbhuangyi** [comment]
目前应该还没有支持 snap 的缓动可配置，不过这个能力确实可以考虑开放出来，支持 fullpage 的场景。

**Comment by ustbhuangyi** [comment]
1.7.0 版本支持 snap 可以配置缓动函数
