### ISSUE TITLE
如何优化better-scroll上拉加载的性能

### ISSUE THREAD

**Issue by songkejiang** [ustbhuangyi/better-scroll#409]
初次使用better-scroll，感觉是个非常不错的插件，非常好用，在做列表的上拉加载时加载数据不多时表现还是不错的，但是数据越来越多时发现cpu占用很高，页面卡顿，有没有好的优化方法呢？上拉加载用的是pullUpLoad配置项监听pullingUp事件

**Comment by ustbhuangyi** [comment]
什么型号的手机，操作系统是什么？

**Comment by songkejiang** [comment]
手机是华为mate9Pro，Windows上用谷歌浏览器的模拟器也是这样

**Comment by ustbhuangyi** [comment]
你有多少条数据会卡顿，能否用 codesandbox 提供一个 demo 页面。

**Comment by songkejiang** [comment]
大概七十多条的时候会出现，demo页面没有，我把仓库地址给你吧https://github.com/songkejiang/yzg.git
，向上拖动六到七次就能感觉到卡顿，不知道是不是的js写的有问题

**Comment by songkejiang** [comment]
我知道原因了，是我的问题

**Comment by langlong149** [comment]
@songkejiang 是因为什么原因呢？ 我用着也很卡。。

**Comment by yulongwukong** [comment]
我用的是滚动加载更多  在iphone7 plus上数据超过700条是的时候开始出现卡顿现在
