### ISSUE TITLE
关于better-scroll计算高度的问题

### ISSUE THREAD

**Issue by mrfour44** [ustbhuangyi/better-scroll#41]
#遇到的问题
页面第一次加载进来better-scroll 计算不到图片的高度导致页面拉到一半就卡住了,再刷新一次就正常。（ps:图片是一张高度好大的商品详情图片）
初始化better-scroll 已经是在 
   mounted () {
           this.$nextTick(() => {
           this._initScroll();
          });}
请问老师有什么办法可以解决吗？谢谢！！！

**Comment by neurotoxinvx** [comment]
$nextTick 只是等待 DOM 更新后再去执行回调，并不会等到图片等资源加载完毕后再去执行
如果图片高度固定的话，可以选择为图片设置一个默认高度
如果图片高度不固定的话，可以选择预加载图片一下，当图片加载 onload 的时候再实例化 BScroll

**Comment by ustbhuangyi** [comment]
可以用个层包一下 image，根据图片的比例，固定这个层的高度即可。
