### ISSUE TITLE
这个弹力动画。弹出来的最大距离可以控制吗

### ISSUE THREAD

**Issue by huoguozhang** [ustbhuangyi/better-scroll#414]
ru如图，版本号1.6.3
![image](https://user-images.githubusercontent.com/25920764/34352821-b14183b0-ea5f-11e7-8392-cf7cd3759d9f.png)

**Comment by ustbhuangyi** [comment]
这种问题在 qq 群讨论吧

**Comment by huoguozhang** [comment]
好的老师
