### ISSUE TITLE
瀑布流content里面的元素使用浮动布局，better-scroll就不生效

### ISSUE THREAD

**Issue by fanxl12** [ustbhuangyi/better-scroll#417]
### Version
1.6.3

### Reproduction link
[https://github.com/fanxl12/scroller-test](https://github.com/fanxl12/scroller-test)

### Steps to reproduce
运行项目，默认就better-scroll就不生效，去掉style里面.box的float属性，再刷新，就可以了。因为我的列表是需要一个两列瀑布流效果

### What is expected?
content里面元素浮动也能用better-scroll

### What is actually happening?
不能使用

**Comment by ustbhuangyi** [comment]
很明显是你的布局问题，没有清除浮动导致布局塌陷，内容没有撑开高度，所以并不满足可以滚动的需求。
