### ISSUE TITLE
使用this.$refs.scroll.scrollTo(0, scroll)后 第一次纵向滚动会自动回到页面顶部

### ISSUE THREAD

**Issue by holdno** [ustbhuangyi/better-scroll#419]
### Version
1.6.3

### Steps to reproduce
使用keep-alive 两个页面(都用到better-scroll)进行跳转, 使用scrollTo()来回复之前浏览的位置,发现在切换页面并调用scrollTo后 第一次纵向滚动会自动回到页面顶部,当自动滚到到顶部时还伴有短暂的滑动失效(无法滑动页面).不知道是使用问题还是bug.返回第一页后先调用refresh()即可解决这个问题.可能是keep-alive下两个页面的better-scroll组件会有冲突

### What is expected?
不要自动回到顶部

### What is actually happening?
在项目首页向下滚动,随便进入一个直播详情
点击返回后通过this.$refs.scroll.scrollTo(0, scroll)使页面停留在跳转时的位置
此时向下滑动,页面会自动回到顶部

**Comment by ustbhuangyi** [comment]
如果重现需要构建工具，可以使用 CodeSandbox 或是提供一个 GitHub 仓库的链接。如果不需要构建工具，请提供一个尽可能精简的 JSFiddle, JSBin 或是 CodePen 链接。 
需要最小化重现，而不是直接用你的项目。

**Comment by holdno** [comment]
返回第一页后先调用refresh()即可解决这个问题.可能是keep-alive下两个页面的better-scroll组件会有冲突
