### ISSUE TITLE
滚动条bug

### ISSUE THREAD

**Issue by faimaklg** [ustbhuangyi/better-scroll#420]
![default](https://user-images.githubusercontent.com/18085334/34397606-6c2aa7a8-ebb2-11e7-9f7f-f2948c41304b.gif)
下拉刷新滚动条有明显的延迟

**Comment by ustbhuangyi** [comment]
这个效果是很合理的，当整个动作完成后，滚动条才消失。

**Comment by faimaklg** [comment]
不是指滚动条消失，是滚动条长度变化有卡顿

**Comment by faimaklg** [comment]
@ustbhuangyi
