### ISSUE TITLE
pullUpLoad没有stop选项

### ISSUE THREAD

**Issue by oyexiaozhi** [ustbhuangyi/better-scroll#421]
### What problem does this feature solve?
请教以下~~若想实现上拉加载数据时设置回弹停留距离的话该如何做呢？

### What does the proposed API look like?
期待pullUpLoad也可配置stop选项

**Comment by bestime** [comment]
你可以将你的加载动画放在scroll容器内部最后面，这样就会停在有效滚动视图的最后。我也觉得上拉相对于下拉可定制性太差，不如自己根据better-scroll封装一个。

**Comment by ustbhuangyi** [comment]
上拉加载目前没有设计可以停留的配置接口。
