### ISSUE TITLE
preventDefaultException事件捕捉or冒泡问题

### ISSUE THREAD

**Issue by tong233** [ustbhuangyi/better-scroll#422]
点击p没有效果，要直接点击在div.test上才触发active。
```
配置 preventDefaultException: {className:/(^|\s)test(\s|$)/}
```
```
<div class="test">
  <p>test</p>
  <p>test</p>
  <p>test</p>
</div>

<style>
.test:active {
  background: #ccc;
}
</style>
```

**Comment by ustbhuangyi** [comment]
因为你是针对这个 div 做的 preventDefaultException，所以只有这个层响应默认的 active

**Comment by tong233** [comment]
可以做到匹配某一div内全部子元素吗？如果嵌套很多层不好实现默认事件。

**Comment by ustbhuangyi** [comment]
active 的搞法可以尝试监听 touchstart 和 touchend 的方式通过 JS 去设置 class 的搞法，参考：https://github.com/ustbhuangyi/better-scroll/blob/master/example/components/index-list/index-list.vue
你说的那种应该搞不了，还有一种办法是设置 preventDefault 属性为 false

**Comment by tong233** [comment]
我去看看，谢谢
