### ISSUE TITLE
自动滚动到底部

### ISSUE THREAD

**Issue by davy-gan** [ustbhuangyi/better-scroll#425]
有没有方法可以自动滚动到底部  异步加载数据后让容器自动滚动到底部  ，并滚动到后抛出事件 告诉外部已经滚动到底部了 ，请问 有这个方法么  找了半天还没找到

**Comment by ustbhuangyi** [comment]
目前没有现成的接口，可以使用scrollTo 方法，横向和纵向的最大距离分别是 maxScrollX 和 maxScrollY，未来可以考虑封装一个现成的 API
