### ISSUE TITLE
不支持长按保存图片

### ISSUE THREAD

**Issue by davy-gan** [ustbhuangyi/better-scroll#428]
在safari 浏览器 chrome 浏览器中（其他浏览器暂时没测）  不支持长按保存图片 和选中文字的操作，这个插件不支持 touch 事件么  希望加上这个 功能 ，现在项目中就遇到这个问题了

**Comment by ustbhuangyi** [comment]
配置 preventDefaultException 可以解决这个问题，看文档吧。

**Comment by davy-gan** [comment]
好的  ，感谢大佬
