### ISSUE TITLE
当滚动列表li数目较少，无法撑开并超出 滚动的wrapper  的时候 就没有弹性效果，如果期望只有一条数据也有弹性效果怎么实现呢

### ISSUE THREAD

**Issue by bigger-yangjiali** [ustbhuangyi/better-scroll#43]
![image](https://cloud.githubusercontent.com/assets/24558396/24146249/e90c8b40-0e6f-11e7-9d5e-d0644b0f4e2b.png)

**Comment by lastIndexOf** [comment]
可不可以动态设置里面的内容wrapper高度？ 就是给它下面的空白设置一些高度

**Comment by liuxingzhijian1320** [comment]
你可以的给最后一个的加上min-height

**Comment by ustbhuangyi** [comment]
可以试试楼上的方法
