### ISSUE TITLE
按照文档敲了，可还是滚动不了！！

### ISSUE THREAD

**Issue by loanniss** [ustbhuangyi/better-scroll#434]
<template>
	  <div class="wrapper" ref="wrapper">
	  		<ul class="content">
	  			<li v-for="item in listData">{{item.name}}</li>
	  		</ul>
	  </div>		
</template>
<script>
  import BScroll from 'better-scroll'
  export default {
  	data(){
  		 return {
			    listData:[],
			    param: {
						data: {},
						page: {
							page:1,
							size:100
						},
						client: {},
						sid: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbWVpIjoiIiwidXNlcl9pZCI6MSwicGhvbmUiOiIifQ.a1AMWRSkbiYVKxiKGYgSnYE-BYVOm7BWKtfJuSiC8o0"
					},
      	};
  	},
  	created() {
				this.$http.post("/api-/api/portal/task/list",JSON.stringify(this.param)).then((res) => {
					res = res.body;
					if(res.state.code ==2000){
						this.listData = res.data;
						this.$nextTick(() => {
			        this._initScroll();
			      }) 
					}
				});						
  	},
    mounted() {

   },
   methods: {
   		_initScroll() {
   			this.scroll = new BScroll(this.$refs.wrapper, {
   				scrollY: true,
			    click: true
        }) 
   		}
   }
  }
</script>
<style>
	li{
		font-size: 20px;
		line-height: 42px;
	}
</style>

控制台报错！！！！！
Unable to preventDefault inside passive event listener due to target being treated as passive.

**Comment by ustbhuangyi** [comment]
这类问题去 qq 群交流吧
