### ISSUE TITLE
position：fixed ，is not effect

### ISSUE THREAD

**Issue by GOGOGOSIR** [ustbhuangyi/better-scroll#437]
use better-scroll components，inside，div isn't use fixed
eg：
<scrolls class='wrappers_1' :data="dataListArr" :pullup='true' @scrollToEnd="loadData" @getScroll='getScrollObj'>
    <div style='position:fixed'></div>
</scrolls>

**Comment by ustbhuangyi** [comment]
这类问题去群里问吧，不符合 issue 规范。
