### ISSUE TITLE
[New Feature] scrollbar的样式定制问题

### ISSUE THREAD

**Issue by ironmancaijian** [ustbhuangyi/better-scroll#438]
### What problem does this feature solve?
修改scrollbar的源码css无效 , 希望完成不滑动时半透明 , 滑动时不透明的需求 ,让用户知道这是可以下拉的 ,而不是全部

### What does the proposed API look like?
通过option传入相关的值 ,完成定制

**Comment by cker321** [comment]
借楼，问个问题，为何我这配置了scrollBar 但是不会显示呢

**Comment by yanaxua** [comment]
同需求滚动条样式定义

**Comment by HBITMP** [comment]
![image](https://user-images.githubusercontent.com/27177936/39106019-9ed93bda-46eb-11e8-8756-0173f5c6e8a0.png)
我是直接覆盖整个css样式实现的
`.bscroll-vertical-scrollbar{
	top: 89px !important;
	bottom: 52px !important;
}
.bscroll-indicator{
	background-color: white !important;
	width: 4px !important;
	right: 0 !important;
}`
这么写，感觉要被打，哈哈哈哈

**Comment by RoyXun** [comment]
+1
现在项目里只能通过important样式覆盖，有点恶心

**Comment by guoguangkun** [comment]
覆盖也没生效的怎么办？

**Comment by theniceangel** [comment]
refactor at v2.2.0
