### ISSUE TITLE
better-scroll 如何兼容iOS与安卓的click配置

### ISSUE THREAD

**Issue by keristylei** [ustbhuangyi/better-scroll#440]
最近做项目，由于项目需求不能暴力把浏览器的默认click事件禁止掉，如何根据不同的机型去分别阻止浏览器默认click事件。

![image](https://user-images.githubusercontent.com/10895858/34823707-903eab94-f706-11e7-9915-511e095d7fc9.png)

这是我写的代码根据不同机型分别取阻止click，但是安卓机一直返回true，求大神指点一下。多谢！！！

**Comment by ustbhuangyi** [comment]
这类问题去群里讨论，不要用 issue 问问题。

**Comment by keristylei** [comment]
方便告诉一下better-scroll的交流群号吗？谢谢~~~
