### ISSUE TITLE
.changelog 文件

### ISSUE THREAD

**Issue by johnqiuwan** [ustbhuangyi/better-scroll#441]
希望 @ustbhuangyi  在 repo 里面可以多放一个 .changelog 文件，里面罗列出，不同版本的新功能，或者哪些功能已经被移除等，或者新版本解决了哪些问题，或者新版本哪些地方与旧版本不能兼容等。

**Comment by ustbhuangyi** [comment]
建议去看 https://github.com/ustbhuangyi/better-scroll/releases/ 喔
