### ISSUE TITLE
在应用better-scroll的时候出现了一个问题一直无法解决。

### ISSUE THREAD

**Issue by guoyutong** [ustbhuangyi/better-scroll#443]
我在使用better-scroll的时候，出现了refresh()后解析有误的问题，一直无法解决，用定时器给refresh延时的方法已经用过了，无效。目前最有效的办法是重新初始化，但我觉得治标不治本，所以特来冒昧的提问，如有打扰非常抱歉。
https://segmentfault.com/q/1010000012811926?_ea=3163094
这个是我再segmentfault上提问的链接，如果您看到了，还请您能帮我分析一下，十分感谢。

**Comment by ustbhuangyi** [comment]
问问题建议去群里喔。
