### ISSUE TITLE
一个页面初始化两个better-scroll遇到的问题，希望您能帮忙回答一下

### ISSUE THREAD

**Issue by LYY1123** [ustbhuangyi/better-scroll#445]
场景描述：
  我有一个H5页面，主页面整个内容初始化了better-scroll,这个页面中有一个大的弹窗，弹窗内容也使用了better-scroll。但是这两个需要滚动的DOM不属于父子关系。因为是vue项目，所以初始化使用的DOM是通过vue的ref获取的。
问题：
 为防止弹窗内容滚动时触发整个主页面滚动，所以我在弹出中加了touchmove事件，在touchmove事件中阻止了事件冒泡event.stopPropagation().因此造成了弹窗内容无法滚动，整个主页面的滚动正常。去掉弹窗的event.stopPropagation()，主页面和弹窗内容均可滚动。
我在要滚动的主页面上绑定touchmove进行测试发现，滚动弹窗里的内容时，是会触发弹窗后整个主页面的touchmove事件，但是弹窗后整个主页面并不滚动，那所触发弹窗滚动的事件岂不是弹窗后面整个页面实例化的better-scroll触发的吗？
我是前端菜鸟，对此感到很不理解，望解答。

**Comment by ustbhuangyi** [comment]
可以加群讨论，不要用 issue 问问提。
