### ISSUE TITLE
在scroll中触发点击事件，点击事件执行了两次

### ISSUE THREAD

**Issue by guofeiwu** [ustbhuangyi/better-scroll#446]
<scroll @scroll="scroll"
          :listen-scroll="listenScroll"
          :probe-type="probeType"
          :data="data"
          class="listview"
          ref="listview">
    <ul>
      <li v-for="group in data" class="list-group" ref="listGroup">
        <h2 class="list-group-title">{{group.title}}</h2>
        <ul>
          <li @click.stop.prevent="selectItem(item)" v-for="item in group.items" class="list-group-item">
            <img class="avatar" v-lazy="item.avatar">
            <span class="name">{{item.name}}</span>
          </li>
        </ul>
      </li>
    </ul>
  </scroll>

 methods: {
  selectItem(item) {
        console.log('click event')
        this.$emit('select', item)
      }
}

这个selectItem方法中的log打印了两次，触发了两次select事件。

**Comment by ustbhuangyi** [comment]
不符合 issue 规范，你去试试最新的版本吧，如果还有问题，请按 issue 规范提。
