### ISSUE TITLE
[New Feature] vue axios 异步请求数据时  slide不能初始化成功

### ISSUE THREAD

**Issue by ajiaoyiyi** [ustbhuangyi/better-scroll#447]
### What problem does this feature solve?
vue项目中使用了 axios 异步请求数据时，  slide子组件已经设置this.$nextTick，但不能初始化成功，有解决办法吗？

### What does the proposed API look like?
父组件：
created() {
        this.getIndexBanner();
	  },
  	methods: {
  		getIndexBanner() {
  			let params = {apGradeno:'index_adv'}
		    getCommonAdv(params).then(res => {
					 this.homelist = res.adv_list
					console.log('11111')
			  }).catch(e => {
			  	console.log(e);
			  });
			}
	  }

子组件：
mounted() {
    this.update()
    //当调整浏览器窗口的大小时，发生 resize 事件。
    window.addEventListener('resize', () => {
      console.log('resize')
      if (!this.slide || !this.slide.enabled) {
        return
      }
      clearTimeout(this.resizeTimer)
      this.resizeTimer = setTimeout(() => {
        if (this.slide.isInTransition) {
          this.onScrollEnd()
        } else {
          if (this.autoPlay) {
            this.play()
          }
        }
        this.refresh()
      }, 60)
    })
  }, 
methods: {
    update() {
      this.$nextTick(() => {
          this.init()
      })
    },
    refresh() {
      this.setSlideWidth(true)
      this.slide.refresh()
    },
    init() {
      console.log('2222')
      this.currentPageIndex = 0
      this.setSlideWidth()
      if (this.showDot) {
        this.initDots()
      }  
      this.initSlider()
      if (this.autoPlay) {
        this.play()
      }
    },
}

...

**Comment by ustbhuangyi** [comment]
请参考 cube-ui 的 slide 组件 https://didi.github.io/cube-ui/#/zh-CN/docs/slide
