### ISSUE TITLE
ios 返回关闭交互

### ISSUE THREAD

**Issue by goldencolor** [ustbhuangyi/better-scroll#448]
iOS7.0及以上系统中，在新打开的页面中向右滑动，可以返回到上一个页面，
如果容器宽度为100%时，会把系统返回给阻止导致无法使用原有滑动返回交互，望修复或增加一个开关控制

**Comment by ustbhuangyi** [comment]
这个在边缘滑动仍然是可以左滑返回的，touchmove 事件无论如何还是需要 preventDefault 的，否则就会触发浏览器原生的滚动。

**Comment by goldencolor** [comment]
@ustbhuangyi 不行啊。。到边缘无法返回关闭

**Comment by pilgrim1385** [comment]
同样的问题，在iOS UIWebView 加载使用better-scroll的H5页面，不能正常侧滑返回。

**Comment by Clarkkkk** [comment]
确实不能侧滑返回。在左边加一个绝对定位的15px宽的透明div，将z-index设为10000，让浏览器有机会捕获touchmove事件，就可以触发侧滑返回了。
