### ISSUE TITLE
安卓4.3，点击事件无效

### ISSUE THREAD

**Issue by LingF** [ustbhuangyi/better-scroll#450]
### Version
1.8.0

### Reproduction link
[https://ustbhuangyi.github.io/better-scroll/#/examples/nav-list/1/en](https://ustbhuangyi.github.io/better-scroll/#/examples/nav-list/1/en)

### Steps to reproduce
直接访问文档的demo，在Navigation List中点击无效，可以滑动

### What is expected?
点击切换

### What is actually happening?
点击无响应

---
设备名称：Galaxy Note3 Lite 4G
型号：SM-N7506V
Android版本：4.3

**Comment by ChangerHe** [comment]
同遇到此问题

**Comment by wd4219** [comment]
这个有解决办法吗?

**Comment by ustbhuangyi** [comment]
普通列表点击正常吗，只有那个 demo 有问题？

**Comment by wd4219** [comment]
只要使用better-scroll的列表。我这边测试4.3点击事件都无效

**Comment by ustbhuangyi** [comment]
试试 1.8.2 版本，应该解决了这个问题

**Comment by LingF** [comment]
嗯测试可以了，谢谢
