### ISSUE TITLE
关于BS在ios上的表现,当元素少的时候,快速滑动页面会出现闪烁的问题

### ISSUE THREAD

**Issue by lyj505** [ustbhuangyi/better-scroll#452]
### Version
1.8.0

### Reproduction link
[http://ustbhuangyi.com/sell/#/goods](http://ustbhuangyi.com/sell/#/goods)

### Steps to reproduce
快速滚动在iphone6 iphoneX 上会出现闪烁白屏。。

### What is expected?
不清楚是什么情况,是我自己的配置不对还是什么，，但是这个是官方的demo

### What is actually happening?
。。。

**Comment by lyj505** [comment]
补充一下,刚才用Safari 测试了一下没问题,内嵌支付宝的页面也没有太大问题。。。主要是微信webview出了问题。。。微信什么鬼

**Comment by lyj505** [comment]
刚才测试了 设置betterscroll  useTransition关闭（fasle）,在微信的webview不卡顿了。。

**Comment by ustbhuangyi** [comment]
这应该是 iOS 11.x 的坑，出现问题的时候不仅仅是 better-scroll，应该是所有网页应用，包括原生 App 里的应用，用到了 transition 相关的都有问题，一般出现问题的时候可以通过重启手机解决。因为该问题是偶现，如果强制给这些版本的 transition 关了可能体验也不那么好。

**Comment by lyj505** [comment]
对的,我手机是ios10.3.3。用的iphoneX 是ios11。在微信环境中:
当scrollwp 里面元素多的时候,会造成gpu卡顿,这样的情况,我使用ios10.3.3 iphone6滑动就没有闪屏,而使用iphoneX依然出现闪频。
当scrollwp  里面元素少的时候,iphone6和iphoneX都会出现闪屏的现象
安卓机在以上2种情况上都表现正常。
在支付宝或者safari都表现在以上2种情况上都表现正常。

目前测试的情况是微信 ios机型出的问题,我这边先设置ios版本关闭吧。。看了BS还有很多开关比如
momentum: true 当快速滑动时是否开启滑动惯性,也没去测试了。。谢谢

**Comment by iceprosurface** [comment]
对!我也碰到这个问题了,  ios 11.2.5 还是没有解决这个问题, 主要问题最严重的 7p.

**Comment by ouzhou** [comment]
使用 backface-visibility 是否能解决闪屏？

**Comment by Chas2016** [comment]
@ustbhuangyi  这个问题目前有修复方案么

**Comment by ustbhuangyi** [comment]
@Chas2016 ，没有很好的，这种情况出现的时候手机所有应用和过渡相关的都有问题了

**Comment by ustbhuangyi** [comment]
白屏问题可以用 useTransition: false 解决，坏处是启动 JS 动画后滚动流畅度会降低。

**Comment by usercao** [comment]
真的是手机问题=  =，重启一下就好了
