### ISSUE TITLE
better-scroll对vue的keepalive功能支持

### ISSUE THREAD

**Issue by LJade** [ustbhuangyi/better-scroll#453]
### Version
1.8.0

### Reproduction link
[https://uatspeakout.com](https://uatspeakout.niohome.com)
### Steps to reproduce
微信企业号开发，针对bs@1.2.1版本，解决滚动过程中触控列表停止滚动，而不是触发列表的点击事件，为了解决问题，更新至bs@1.8.0
其中，对列表项有使用keep-alive功能，即点击某项进入详情，再点击微信的返回，回到刚才浏览的位置，现象：数据确实缓存，生命周期走了activated,但是列表位置回到了最顶端，而不是之前浏览的位置。回退版本到bs@1.2.1，缓存效果正常。
替换为解决滚动时停止版本bs@1.4.0，达到预期，不仅滚动正常，keepalive也是正常的

### What is expected?
bs不影响缓存滚动位置

### What is actually happening?
1.8.0回到顶部

---
我的项目开发中出现了这个现象，可以看一下这个问题 企业号开发，网址是私密的，无法打开请见谅，只是提一下这个现象

**Comment by ustbhuangyi** [comment]
better-scroll 和 vue 的 keep-alive 没有关系，另外我的个人项目也用了最新版本的 better-scroll，也用到了 keep-alive，并没有什么问题：http://ustbhuangyi.com/music/#/recommend
请确认是不是自己使用问题，以及我希望能遵循 issue 规范，提供一个最小化复现问题的 demo，确认是 better-scroll 的问题，我会 reopen 这个 issue。
