### ISSUE TITLE
在使用snap的时候，需要在左侧动态添加slide？

### ISSUE THREAD

**Issue by KevisLuo** [ustbhuangyi/better-scroll#457]
### What problem does this feature solve?
在使用snap的时候，需要在左侧动态添加slide，同时要保持显示当前的slide不变。请问有什么好的建议或方法处理吗？

### What does the proposed API look like?
求大神帮助~

**Comment by ustbhuangyi** [comment]
如果是 Vue 应用，建议直接去使用 cube-ui 的 Slide 组件，支持数据动态变化。
