### ISSUE TITLE
index.d.ts中next和prev方法可以不传参数，现在为必传

### ISSUE THREAD

**Issue by summersky2014** [ustbhuangyi/better-scroll#459]
### Version
1.8.0

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll/blob/master/types/index.d.ts#L155](https://github.com/ustbhuangyi/better-scroll/blob/master/types/index.d.ts#L155)

### Steps to reproduce
无

### What is expected?
next(time?: number, easing?: object): void;

prev(time?: number, easing?: object): void;

### What is actually happening?
tpyes中的描述和实际代码处理不同

**Comment by ustbhuangyi** [comment]
@linxiaowu66 ，看一下~

**Comment by linxiaowu66** [comment]
@summersky2014 ok, 我改一下

**Comment by ustbhuangyi** [comment]
v1.8.1 support this
