### ISSUE TITLE
better-scroll 是否可以使用在 app 中

### ISSUE THREAD

**Issue by johnqiuwan** [ustbhuangyi/better-scroll#462]
感谢这个方便的插件，为我们省却了很多开发时间。

想问问是否可以把这个插件运用到原生ios app 中。
如果不可以，不知道大家有什么好的library推荐？

感谢

**Comment by ustbhuangyi** [comment]
better-scroll 是可以开发内嵌在 app 里的网页应用的，这类问题去群里问吧
