### ISSUE TITLE
Snap can't go to the next page at the first scroll after the wrapper of which initial height is 0 getting some height

### ISSUE THREAD

**Issue by JackClown** [ustbhuangyi/better-scroll#465]
### Version
1.8.1

### Reproduction link
[https://jsfiddle.net/b37e7wzp/](https://jsfiddle.net/b37e7wzp/)

### Steps to reproduce
click the button and try to scroll the scroller to the second page.After transition is over ,scroll again

### What is expected?
The first time, the scroller is at the second page.The second time, it's still at the second page.

### What is actually happening?
The first time, the scroller can't go to the second page.The second time, it go to the second page.

---
In this situation, maybe I can handle *reset* by myself after the wrapper gettting some height, but actually the scroller just scrolls at horizontal and there is no need for wrapper's height.

**Comment by ustbhuangyi** [comment]
这种情况，你改变 wrapper 高度后应该手动调用一下 `scroller.refresh()`

**Comment by JackClown** [comment]
其实我是觉得这有点没必要，因为高度并不影响滚动方向，而源码里并没有对滚动方向做判断， 我在iScroll上也发现了这个问题，但better-scroll貌似会在滚动后refresh，所以能解决之后的滚动问题
