### ISSUE TITLE
keep-alive组件切换有几率发生无法滑动

### ISSUE THREAD

**Issue by KokoTa** [ustbhuangyi/better-scroll#466]
两个keep-alive情况下的组件刚开始渲染的时候可以进行滑动，使用了nextTick。
数据是异步加载的，此时过一段时间后切换组件，将导致组件无法滚动。
查看slider后发现hasVerticalScroll: false; scrollHeight/scrollerWidth/wrapperHeight/wrapperWidth: 0。
但是界面是已经渲染好且缓存了的，为什么会发生这种情况？
当监听hasVerticalScroll: false并refresh后回复正常，但滚动记录被重置。
难以还原具体代码，请见谅。

**Comment by ustbhuangyi** [comment]
需要按 issue 规范提供最小化复现问题的路径，否则无法定位问题
