### ISSUE TITLE
如果想使用body的滚动

### ISSUE THREAD

**Issue by sunlandong** [ustbhuangyi/better-scroll#468]
### Version
1.8.1

### Reproduction link
[https://h5.ele.me/msite/](https://h5.ele.me/msite/)

### Steps to reproduce
https://h5.ele.me/msite/

### What is expected?
上部分是固定内容，下面部分是滚动内容，滑动上面也要出现下面，同时下面是下拉加载更多，类似于饿了么app现在的首页

### What is actually happening?
无法实现

---
想用这个库实现类似于饿了么app首页哪样的功能，使用body的滚动，而不是容器的滚动

**Comment by ustbhuangyi** [comment]
这个需求是可以实现的，但是请不要用 issue 问这类问题，可以去群里讨论。
