### ISSUE TITLE
ios中位于scroll区域内的输入框无法使用长按复制

### ISSUE THREAD

**Issue by iceprosurface** [ustbhuangyi/better-scroll#469]
### Version
1.8.0

### Reproduction link
[https://ustbhuangyi.github.io/better-scroll/#/examples/form-list/en](https://ustbhuangyi.github.io/better-scroll/#/examples/form-list/en)

### Steps to reproduce
设备: iphone 7P (安卓设备未复现)

系统版本: 11.2.1

浏览器: 微信浏览器(微信版本 6.6.1)

1. 复制一段文本
2. 进入网页
3. 长按输入框区域

### What is expected?
出现粘贴,全选等文本操作选项

### What is actually happening?
无响应

**Comment by iceprosurface** [comment]
找到解决方案了

将设置中的 `autoBlur` 设置为 false 即可

**Comment by ustbhuangyi** [comment]
自动失焦的话确实会影响
