### ISSUE TITLE
click设为true，无法再次阻止默认事件

### ISSUE THREAD

**Issue by meteor9714** [ustbhuangyi/better-scroll#470]
### Version
1.8.1

### Reproduction link
[https://codesandbox.io/s/qzrp9qowp6](https://codesandbox.io/s/qzrp9qowp6)

### Steps to reproduce
Open in new window  -> 模拟移动设备  ->  点击链接

### What is expected?
无法跳转

### What is actually happening?
跳转

---
bug原因：
// cancelable set to false in case of the conflict with fastclick

const cancelable = false

期望：将canceable设置为可配置项或者判断已使用fastclick才设置为false

**Comment by ustbhuangyi** [comment]
click 为 true，就应该可以跳转的啊。如果不想让它跳转就把 click 设置为 false

**Comment by meteor9714** [comment]
希望设置click为true能通过preventDefault阻止原生事件。

**Comment by meteor9714** [comment]
具体场景为在vue中创建cell组件，当href为路由路径时阻止默认a标签跳转执行路由操作，当不为路由路径时使用a标签执行原生事件跳转。配置项click是对整个滚动区域生效的，在这种场景希望的是整个滚动区域可点击，个别地方可以通过preventDefault阻止默认事件。

**Comment by ustbhuangyi** [comment]
你这个需求应该通过 JS 控制跳转，而不要依赖 a 标签的默认行为

**Comment by meteor9714** [comment]
不是很赞同这种说法：
1、click设为true会理解为支持完整的click事件，而实际上会不支持preventDefault方法且文档没有说明，使用时错误排查困难。
2、页面间跳转使用a标签更符合语义化也更方便。
3、可能还存在其他情况需要在click设置为true的时候阻止默认事件。

个人建议：
可以在配置项中添加个类似compatibleFastclick的配置，改项设置为true的时候才将cancelable = false。

**Comment by ustbhuangyi** [comment]
你说的我同意，但解决方案不优雅，我再去研究一下 fastclick 这个库，看看更好的解决方案

**Comment by zhuguangy** [comment]
这个问题解决了吗？设为true后，还能阻止A标签的默认事件

**Comment by ustbhuangyi** [comment]
@zhuguangy 解决了还没发版

**Comment by ustbhuangyi** [comment]
@zhuguangy @meteor9714 可以试试 1.8.3 版本
