### ISSUE TITLE
1.8.1版本 goToPage()

### ISSUE THREAD

**Issue by cjc2011** [ustbhuangyi/better-scroll#472]
### Version
1.8.1

### Reproduction link
[http://jsbin.com/rovecelive/edit?html,js,output](http://jsbin.com/rovecelive/edit?html,js,output)

### Steps to reproduce
详见链接

### What is expected?
转跳到制定页

### What is actually happening?
实际转跳页比输入值要>1

**Comment by cjc2011** [comment]
嗯 索引是从0开始 调用scroll.goToPage(2, 0, 400) 应该是转跳到第三个slide 但是实际是转跳到第4个slide

**Comment by ustbhuangyi** [comment]
![image](https://user-images.githubusercontent.com/5359011/36777569-f0d84c1c-1ca4-11e8-84d1-fb9a54226ac6.png)
这是 `scroll.goToPage(2, 0, 400)` 的目标图片。
对应的数据是第三个 slide，图片是：http://jdxl-img.b0.upaiyun.com/uploads/edabb7b545704e6f961ca26c3eca8c44.jpg_wo800，没有问题啊

**Comment by cjc2011** [comment]
可能是我表达的不太清除   
麻烦再看下这个链接   http://jsbin.com/gigafacifi/edit?html,js,output 
这个与上面的jsbin中所有的代码都一样 只是BScroll版本不同 
但是调用scroll.goToPage(2, 0, 400)的显示却不一样
是不是新的版本中new BScroll有所变化

**Comment by ustbhuangyi** [comment]
是的，新版做了优化，goToPage 传递的索引就是数据对应的数据的索引，而不用考虑是否 loop 的情况，所有的差异都在内核层面做了抹平。
