### ISSUE TITLE
滚动问题

### ISSUE THREAD

**Issue by lixiaozhangme** [ustbhuangyi/better-scroll#477]
你好，我遇到一个奇怪的问题，我有两个页面， 两个页面使用了一个数据放在了store，均用了BS,开始两个页面均能正常滚动，但是，当一个页面数据改变了，另一个页面就滚动不了

**Comment by lixiaozhangme** [comment]
这个滚动就是对数据条数进行增加与删除

**Comment by ustbhuangyi** [comment]
请按 issue 规范最小化复现问题
