### ISSUE TITLE
[New Feature] bounce距离太大 体验不好

### ISSUE THREAD

**Issue by littleGauze** [ustbhuangyi/better-scroll#478]
### What problem does this feature solve?
在手机上快速滑动，根据文档和滑动速度计算的bounce值太大，体验不好。并且快速滑动文档会溢出容器，不会回弹，需要再滑动才会回弹。希望可以自定义bounceDistance。

### What does the proposed API look like?
options.bounceDistance

**Comment by littleGauze** [comment]
是内嵌到app webview中的

**Comment by ustbhuangyi** [comment]
你是觉得滚动距离太大，可能会导致回弹过远？可以去配置 deceleration，https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#deceleration
该值越大，速度衰减的越快，滚动距离越小

**Comment by littleGauze** [comment]
找不到一个合适的值 尽管设到0.006了只会影响正常（文档中间）滑动速度，文档两端快速滑动，bounce滚动距离还是太大。

**Comment by ustbhuangyi** [comment]
@littleGauze ，对比了一下端的一些列表，确实它们不会滚动太远，这个我做一下优化吧

**Comment by ustbhuangyi** [comment]
@linxiaowu66 ，试一下 1.8.4 版本

**Comment by littleGauze** [comment]
@ustbhuangyi 现在好多了 多谢
