### ISSUE TITLE
请问下，better-scroll的slide模块，我在横向拖动的时候抖的厉害，遇到过这种情况么。

### ISSUE THREAD

**Issue by gmdesting** [ustbhuangyi/better-scroll#479]

**Comment by ustbhuangyi** [comment]
需要按 issue 规范提供复现的地址，手机设备信息等。

**Comment by gmdesting** [comment]
我页面的最外层是betterscroll滚动，然后里面一层轮播图切换是用的slide，之后拖动轮播图就会抖。我重新测试下没用betterscroll做滚动的页面下的slide是没有这个问题的，所以这是嵌套后的手势冲突问题么？
