### ISSUE TITLE
当内容高度小于容器高度时，不能实现上拉和下拉动作

### ISSUE THREAD

**Issue by tuzhichang** [ustbhuangyi/better-scroll#48]
如果内容的高度没有超过容器高度，就没办法实现内容的弹性滚动，也就无法实现下拉刷新

**Comment by mingmo13** [comment]
我的解决办法是给内层元素加个min-height 101%

**Comment by ustbhuangyi** [comment]
本质上 better-scroll 的滚动原理是当内容的高度（宽度）超过外层容器的高度（宽度）才可以滚动，可以试试楼上的方法
