### ISSUE TITLE
多次调用 `finishPullUp` 方法会导致 `pullingUp` 事件多次触发

### ISSUE THREAD

**Issue by nilptr** [ustbhuangyi/better-scroll#483]
### Version
1.8.0

### Reproduction link
[https://codepen.io/anon/pen/BravxZ](https://codepen.io/anon/pen/BravxZ)

### Steps to reproduce
当 `bscroll.pullupWatching` 为 true 时多次调用 `bscroll.finishPullUp`

### What is expected?
多次调用 `finishPullUp` 不应产生副作用

### What is actually happening?
会重复添加多个 `checkToEnd` 事件监听器，一次性触发多个 `pullingUp` 事件

**Comment by ustbhuangyi** [comment]
下个版本修复

**Comment by ustbhuangyi** [comment]
1.9.0 版本已修复
