### ISSUE TITLE
数据量较大时滑动缓慢及卡顿

### ISSUE THREAD

**Issue by xeoshow** [ustbhuangyi/better-scroll#487]
### Version
1.8.4

### Reproduction link
[http://ustbhuangyi.com/sell/](http://ustbhuangyi.com/sell/)

### Steps to reproduce
http://ustbhuangyi.com/sell/

您好，我试验上面的演示项目时，如果把菜品加到500条记录，滑动会很慢，及卡顿。不知是否可以改进？谢谢。

### What is expected?
滑动顺畅

### What is actually happening?
滑动慢及卡顿

**Comment by ustbhuangyi** [comment]
500 条数据貌似原生 App 也会卡顿吧，对于图文数据图片最好懒加载。

**Comment by xeoshow** [comment]
谢谢哈。better-scroll里怎么达成懒加载呢？最好是静默懒加载那种方式。要是可以在sell这个演示里，作为讲解补充上就好了。感谢。

**Comment by ustbhuangyi** [comment]
比如 Vue 里可以配合 vue-lazyload 插件，比如：http://ustbhuangyi.com/music/#/singer

**Comment by xeoshow** [comment]
看到。可是就sell项目而言，用户很可能直接左边滑到最下面的菜品分类，点击最下面分类，进入对应菜品列表区域。加上 vue-lazyload 后，也可以吗？

**Comment by ustbhuangyi** [comment]
可以

**Comment by silviawxy** [comment]
> 可以

react项目要实现懒加载 有什么插件推荐呢
