### ISSUE TITLE
刷新后无法滚动的问题

### ISSUE THREAD

**Issue by mingmo13** [ustbhuangyi/better-scroll#49]
在created函数里new  了Bscroll ，是在nextTick中运行的  但是刷新后无法滚动，把BScroll打印出来发现，刷新后scrollerHeight 的高度和外层容器的高度是一样的，因此无法滚动（实际上内层元素比外层容器要高）。不知道为啥会出现这样的问题，求大大指点

**Comment by ustbhuangyi** [comment]
应该是时机问题，确保内层元素渲染出来的时候初始化 scroll 或者手动调用 refresh 方法重新计算
