### ISSUE TITLE
[New Feature] 原来依靠滚动条的图片懒加载插件失效，有其他兼容better-scroll的图片懒加载插件吗？

### ISSUE THREAD

**Issue by xlkit456852** [ustbhuangyi/better-scroll#491]
### What problem does this feature solve?
如题~原来依靠滚动条的图片懒加载插件失效，有其他兼容better-scroll的图片懒加载插件吗？

### What does the proposed API look like?
原来用的是vux里面的图片懒加载~现在不起效了。

**Comment by ustbhuangyi** [comment]
Vue 的话可以使用 vue-lazyload 插件

**Comment by johnqiuwan** [comment]
@ustbhuangyi ，有没有办法解决这个问题呢，如果只能使用 vue-lazyload 来解决图片懒加载这个问题 那么这插件就会有一定的局限性（某些功能只能配合vue）。
