### ISSUE TITLE
关于连续套用better-scroll的事件冒泡问题

### ISSUE THREAD

**Issue by OctupleSakura** [ustbhuangyi/better-scroll#492]
您好
最近在使用better-scroll的时候有这样一个场景，首先是首页上的banner图需要使用到slider的功能，另一个是在切换菜单的时候也需要使用到slider的功能，但是同时套用封装好的slider插件时，在滚动banner的时候两个都会触发，想请问一下这个问题能如何解决,在文档中似乎并没有阻止事件冒泡的配置选项

**Comment by ustbhuangyi** [comment]
你配置一下 `bindToWrapper` 属性为 true 看看是否能解决你的问题。

**Comment by ustbhuangyi** [comment]
这个问题会在下个版本修复

**Comment by ustbhuangyi** [comment]
1.9.0 版本已支持

**Comment by OctupleSakura** [comment]
好的谢谢
