### ISSUE TITLE
onscroll event always trigger

### ISSUE THREAD

**Issue by zhongxiaolian** [ustbhuangyi/better-scroll#494]
When i use pulldown to refresh，before finishPullUp ，the onscroll event always trigger.

**Comment by ustbhuangyi** [comment]
So it does, any questions?

**Comment by zhongxiaolian** [comment]
在onscrll回调函数中通过$emit派发事件，如果数据请求的时间稍长，那么会一直触发onscroll，会占用太多内存，不知道是我写的问题，还是什么问题。

**Comment by ustbhuangyi** [comment]
派发事件为什么会占用内存，难道是你监听 scroll 事件后去做了什么占内存的操作？

**Comment by zhongxiaolian** [comment]
对的，获得每次滚动过的距离，然后动态计算出当前显示的内容所属的tab栏。

**Comment by ustbhuangyi** [comment]
那这也不吃内存啊

**Comment by zhongxiaolian** [comment]
....我想多了，当时感觉有大量的运算会影响性能，不好意思，打扰了。better-scorll用着挺顺手的，谢谢啦。
