### ISSUE TITLE
关于：Vue 2.0 高级实战-开发移动端音乐WebApp

### ISSUE THREAD

**Issue by zboboan** [ustbhuangyi/better-scroll#496]
老师 移动端音乐WebApp 播放音乐的播放地址变了，现在QQ音乐加密了，不知道怎么获取，能说一下嘛？万分感谢

**Comment by ustbhuangyi** [comment]
这类问题课程源码都已解决，前提是你需要购买正版课程才能获得源码权限，请不要在这里问其他的问题

**Comment by zboboan** [comment]
我去年在慕课网买了教程，跟着教程做的

**Comment by ustbhuangyi** [comment]
那就去看源码吧，问题已经解决了
