### ISSUE TITLE
[New Feature] 数据没有超过容器高度时如何实现下拉刷新？

### ISSUE THREAD

**Issue by TroyBug** [ustbhuangyi/better-scroll#497]
### What problem does this feature solve?
文档中提到，当数据高度没有超过容器高度时，better-scroll是不会滚动的，请问在这种情况下如何实现下拉刷新功能呢？这个场景出现在数据很少的时候。

### What does the proposed API look like?
在数据少的情况下，better-scroll能响应手指的偏移量吗？

**Comment by 1259932147** [comment]
min-height:101%
