### ISSUE TITLE
[New Feature] 为什么scroll事件无效？？就是时时监听滚动事件。

### ISSUE THREAD

**Issue by jundy-kk** [ustbhuangyi/better-scroll#498]
### What problem does this feature solve?
..

### What does the proposed API look like?
..

**Comment by smphp** [comment]
设置 pullUpLoad 为true

**Comment by ustbhuangyi** [comment]
请按 issue 规范提问题

**Comment by jundy-kk** [comment]
哦，，，！sorry.是我布局写乱了。
