### ISSUE TITLE
better-scroll不计算子元素margin导致滑动不到底部

### ISSUE THREAD

**Issue by cnhekai** [ustbhuangyi/better-scroll#499]
### Version
1.9.0

### Reproduction link
[https://03mz59ojxp.codesandbox.io/](https://03mz59ojxp.codesandbox.io/)

### Steps to reproduce
设置父元素高度为300px，子元素高度为30px，子元素margin:20px，十个子元素上下排列

### What is expected?
能滑动到底部并保持margin，这样就能漏出背景色，避免多余的HTML结构或者伪元素

### What is actually happening?
better-scroll不计算nargin的值，导致不能滚动到最底部

---
谢谢提供这么强大的库~我也不知道这是功能要求还是BUG。。。所以提到了这里

**Comment by cnhekai** [comment]
额，那个是效果地址
这个是源码地址：https://codesandbox.io/s/03mz59ojxp

**Comment by ustbhuangyi** [comment]
从布局上可以解决这个问题，边界不要使用 margin，因为 better-scroll 计算高度是不包含 margin 的，你可以在 wrapper 层使用 margin。内部建议用 padding。
