### ISSUE TITLE
使用better-scroll影响v-if、v-show

### ISSUE THREAD

**Issue by vmto** [ustbhuangyi/better-scroll#5]
Bug出现场景：

<template>
    <button @click="toggle()">btn</button>
    <div v-show="show">content</div>
</template>

mounted() {
        this.initScroll();
},
methods: {
        initScroll() {
            new BScroll(document.getElementById('box'), {});
        },
        toggle(){
          this.show =! this.show;
        }
}

以上代码，使用better-scroll影响v-if、v-show，PC浏览器可以，手机上切换失效

报错信息：
Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted

已经解决：
new BScroll(document.getElementById('user'), {
          click:true
      });

**Comment by 60late** [comment]
求问Ignored attempt这个错误是怎么解决的
