### ISSUE TITLE
刷新后，滚动不到最底部，能帮我解决大神？！

### ISSUE THREAD

**Issue by thomasyc** [ustbhuangyi/better-scroll#50]
就是created钩子后 
if (!this.homeScroll) {
          this.homeScroll = new BScroll(this.$refs.homeWrapper, {
            click: true,
            probeType: 3
          });
        } else {
          this.homeScroll.refresh();
        }
}

**Comment by lastIndexOf** [comment]
换mounted看看？ created 的时候DOM未渲染

**Comment by thomasyc** [comment]
@lastIndexOf 也不行

**Comment by thomasyc** [comment]
@lastIndexOf 早就试过了

**Comment by thomasyc** [comment]
@lastIndexOf 我放在 $nextTick的回调里面的

**Comment by ustbhuangyi** [comment]
确保你初始化或者 refresh scroll 的时候，你的 dom 是正确渲染的并且内层元素的高度是小于外层元素的高度的。

**Comment by thomasyc** [comment]
@ustbhuangyi webpack自动更新一次是正确渲染的，但是自己手动刷新就不行的了，就滚不到底部

**Comment by thomasyc** [comment]
很诡异的东西
