### ISSUE TITLE
上拉加载更多数据以后，慢慢滚动出现卡顿。

### ISSUE THREAD

**Issue by hjsen** [ustbhuangyi/better-scroll#500]
使用bscroll 渲染列表，首屏没有问题。但是上拉加载更多数据以后，慢慢滚动出现卡顿。并且调用了refresh的。
整体感觉是滑动不够灵敏了。两页数据一共40条吧。
在iphone6s p上面，请问这种情况可能是什么原因呢

**Comment by ustbhuangyi** [comment]
请按 issue 规范最小化复现问题
