### ISSUE TITLE
bettre-iscroll初始化后，无法使用

### ISSUE THREAD

**Issue by Sun-Traget** [ustbhuangyi/better-scroll#502]
![image](https://user-images.githubusercontent.com/19965020/38018679-28a703c2-32a8-11e8-983d-c2f089d241dd.png)
![image](https://user-images.githubusercontent.com/19965020/38018847-a90ade44-32a8-11e8-997f-6569c9cd2097.png)

![image](https://user-images.githubusercontent.com/19965020/38018833-9d8ea4d8-32a8-11e8-88dd-30c36aa9d8eb.png)
![image](https://user-images.githubusercontent.com/19965020/38019649-b88721c8-32aa-11e8-8ea1-61a8693eec69.png)

初始化了，但是没办法滚动，难道跟异步有关吗？但是我已经放在异步里执行了

**Comment by ustbhuangyi** [comment]
请按 issue 规范提
