### ISSUE TITLE
多张图片加载时，滚动有明显卡顿现象

### ISSUE THREAD

**Issue by lytian** [ustbhuangyi/better-scroll#505]
当多张图片加载时，滚动有明显卡顿现象。感觉图片加载时，会影响better-scroll

**Comment by ustbhuangyi** [comment]
图片加载多肯定卡，这个原生 APP 也一样会卡，不过不知道你的多具体量化是多少图片

**Comment by lytian** [comment]
20张图片，每张大概2M左右。IiPhone X运行流畅，Android (华为 P10)明显的卡顿

**Comment by ustbhuangyi** [comment]
图片太大了吧，你试试配置 useTransition 为 false，或者配置 HWCompositing 为 false 试试吧

**Comment by lytian** [comment]
感觉没效果。是不是把图片质量放低一点会好一点？

**Comment by ustbhuangyi** [comment]
图片小一点肯定会好，正常图片，几百条数据应该都不会卡，一般来说 web 上的图片大小不应超过 60kb

**Comment by lytian** [comment]
好的，我尝试把图片处理一下
