### ISSUE TITLE
[New Feature] use css3 GPU acceleration

### ISSUE THREAD

**Issue by ouzhou** [ustbhuangyi/better-scroll#506]
### What problem does this feature solve?
http://www.frontopen.com/1463.html
https://www.w3cplus.com/css3/introduction-to-hardware-acceleration-css-animations.html
please use translate3d or just use scale(1,1,1) to hack

### What does the proposed API look like?
can you improve it on android?

**Comment by ustbhuangyi** [comment]
已经用了 translateZ 触发了GPU 加速。
