### ISSUE TITLE
将页面隐藏后再显示，自动轮播会失效

### ISSUE THREAD

**Issue by summersky2014** [ustbhuangyi/better-scroll#508]
### Version
1.9.0

### Reproduction link
[https://ustbhuangyi.github.io/better-scroll/#/examples/full-page-slide/en](https://ustbhuangyi.github.io/better-scroll/#/examples/full-page-slide/en)

### Steps to reproduce
1. 把页面的display设置为none;
2. 隐藏时间大于自动轮播的间隔时间;
3. 取消页面的隐藏

### What is expected?
页面隐藏在显示后，自动轮播的效果依然还在。

### What is actually happening?
将页面隐藏后再显示，自动轮播会失效

**Comment by ustbhuangyi** [comment]
这个不属于 better-scroll 内核层面需要解决的问题，而是基于 better-scroll 二次封装轮播组件需要考虑的事情
