### ISSUE TITLE
[New Feature] wheelTo 方法的接口应和 scrollTo 一致， 应支持传入缓动动画的时间和函数

### ISSUE THREAD

**Issue by fjc0k** [ustbhuangyi/better-scroll#511]
### What problem does this feature solve?
在做 `picker` 组件时，选项含 `disabled` 属性，在 `scrollEnd` 回调中，会检查选中的条目是否是禁用的，以及查找下一个可用的条目并跳转去。目前因 `wheelTo` 方法不支持传入缓动动画的时间和函数，跳转效果很生硬。

### What does the proposed API look like?
wheelTo(index, time, easing)

**Comment by ustbhuangyi** [comment]
可以直接用 scrollTo, 计算一下 y 值。
![image](https://user-images.githubusercontent.com/5359011/38434980-e6d82b26-3a02-11e8-9ae3-32168bd9e615.png)
