### ISSUE TITLE
[New Feature] 手动调用 scrollTo 结束应触发 scrollEnd 事件

### ISSUE THREAD

**Issue by fjc0k** [ustbhuangyi/better-scroll#513]
### What problem does this feature solve?
在 scroll 初始化时，会 scrollTo 上次记忆的位置，那么，我们只需要监听 scrollEnd 即可处理 scrolled 后的逻辑，但目前对于手动调用 scrollTo 是不会触发事件的，这就很尴尬了。

### What does the proposed API look like?
scrollTo 结束触发 scrollEnd

**Comment by fjc0k** [comment]
测试发现是 time = 0 时不会触发 scrollEnd 事件，而 wheelTo 暂不支持传入 time，默认的 time 恰巧是 0

**Comment by ustbhuangyi** [comment]
time 为 0 的时候是同步的行为，不需要监听 scrollEnd
