### ISSUE TITLE
pc端 支持的鼠标滑轮很生硬 希望能有移动端滑轮缓动的作用

### ISSUE THREAD

**Issue by 1142338114** [ustbhuangyi/better-scroll#516]
https://cube-ui.github.io/cube-issue-helper/?repo=ustbhuangyi/better-scroll
希望能优化

**Comment by 1142338114** [comment]
https://ustbhuangyi.github.io/better-scroll/#/examples/free-scroll/zh
这个是你当前的效果 h鼠标滑动的时候

**Comment by ustbhuangyi** [comment]
v1.10.0 支持
