### ISSUE TITLE
当获取列表数据为空时，气泡动画问题

### ISSUE THREAD

**Issue by Ericrenhui** [ustbhuangyi/better-scroll#517]
### Version
1.8.0

### Reproduction link
[https://ustbhuangyi.github.io/better-scroll/#/examples/vertical-scroll/zh](https://ustbhuangyi.github.io/better-scroll/#/examples/vertical-scroll/zh)

### Steps to reproduce
运行vertical-scroll.vue，将默认两行数据删除，下拉的气泡消失后显示的“刷新成功”是否向上运动消失

### What is expected?
当获取列表数据为空时，似乎会导致下拉的气泡消失后显示的"刷新成功"向上运动消失，求大神给个思路

### What is actually happening?
按照example里scroll组件，当获取列表数据为空时，似乎会导致下拉的气泡消失后显示的“刷新成功”不是向上运动消失

**Comment by Ericrenhui** [comment]
我重新运行了你们的项目文件，将默认两个数据去掉，发现没有问题，我根据vertical-scroll.vue ，并简化了scroll.vue组件，可能是我漏了什么东西

**Comment by ustbhuangyi** [comment]
建议去看 cube-ui 的 scroll.vue
