### ISSUE TITLE
学习老师的vue-music课程时，发现better-scroll无法循环轮播，调试发现goToPage方法有问题，请老师看一下。

### ISSUE THREAD

**Issue by xiaer93** [ustbhuangyi/better-scroll#521]
BScroll.prototype.goToPage = function (x, y, time, easing) {
  var snap = this.options.snap
  if (!snap) {
    return
  }
  if (snap.loop) {
    var len = void 0
    if (snap._loopX) {
      len = this.pages.length - 2
      if (x >= len) {//////////////////////////////////这里是的判断是不要要改为：x > len  ？
        x = len - 1
      } else if (x < 0) {
        x = 0
      }
      x += 1
    } else {
      len = this.pages[0].length - 2
      if (y >= len) {
        y = len - 1
      } else if (y < 0) {
        y = 0
      }
      y += 1
    }
  }
  this._goToPage(x, y, time, easing)
}

**Comment by ustbhuangyi** [comment]
因为这块 better-scroll 有修改，你用新版就得用新版的 API，最好的方式是去看文档。
如果你购买了课程，可以看课程的最新源码，已经适配了最新的 better-scroll 版本。
