### ISSUE TITLE
[New Feature] better-scroll pc下鼠标滚动至底部，或者mac触摸滑动到底部无法触发pullingUp事件，或者有没有其他的解决方法

### ISSUE THREAD

**Issue by IFmiss** [ustbhuangyi/better-scroll#522]
### What problem does this feature solve?
pc端如果不通过鼠标点击滚动，滚轮的滚动方式是无法触发下拉加载的，难道只能在鼠标滚到到底部的时候再请求数据渲染数据吗

### What does the proposed API look like?
如果实在无法触发pullingUp，只能判断用户是否滚动到底部来触发对应的事件

**Comment by ustbhuangyi** [comment]
可以考虑支持滚轮的上拉加载

**Comment by ustbhuangyi** [comment]
v1.10.0 支持

**Comment by shijunti19** [comment]
最新版本不支持这个
