### ISSUE TITLE
slide 组件只有一张图片的时候有问题

### ISSUE THREAD

**Issue by cb15618399117** [ustbhuangyi/better-scroll#525]
### Version
1.9.0

### Reproduction link
[https://cube-ui.github.io/cube-issue-helper/?repo=ustbhuangyi/better-scroll](https://cube-ui.github.io/cube-issue-helper/?repo=ustbhuangyi/better-scroll)

### Steps to reproduce
slide 组件只有一张图片的时候有问题

### What is expected?
slide 组件只有一张图片的时候有问题

### What is actually happening?
slide 组件只有一张图片的时候有问题

---
slide 组件只有一张图片的时候有问题

**Comment by ustbhuangyi** [comment]
有什么问题
