### ISSUE TITLE
滑动超出设备边界

### ISSUE THREAD

**Issue by joyhao** [ustbhuangyi/better-scroll#527]
### Version
1.10.0

### Reproduction link
[https://github.com/joyhao/fullpage.git](https://github.com/joyhao/fullpage.git)

### Steps to reproduce
首页导航列表  (第一次手指左右滑动，超出设备范围，内容容器不会，回弹，也不会滑到下一个div，其他时候不会)，我应该怎么出来？？

### What is expected?
在超出边距，如果大于屏幕一半 进入下一页，小于则回弹

### What is actually happening?
导航列表

**Comment by ustbhuangyi** [comment]
你先确保你的 repo 没有报错
