### ISSUE TITLE
1.10.0版本PC端鼠标滚动卡顿

### ISSUE THREAD

**Issue by usercao** [ustbhuangyi/better-scroll#528]
1.9.1是很流畅的，刚更新了1.10.0之后滚动就非常卡顿

**Comment by ustbhuangyi** [comment]
不应该呀，你是什么系统

**Comment by usercao** [comment]
Mac os最新版本，Chrome最新版本，我当时未改动任何代码，只是升级了版本之后能感觉到明显的卡顿，然后我回滚到1.9.1的版本就好了

**Comment by ustbhuangyi** [comment]
我找了很多群友测试反馈都不卡顿，如果觉得卡可以配置 easeTime 为 0，参考：https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options-advanced.html#mousewheelv180

**Comment by usercao** [comment]
刚才试了还是卡顿，能否留个邮箱我把代码给你测试一下？

**Comment by ustbhuangyi** [comment]
提供一个可以最小化复现问题的 repo 也可以

**Comment by ustbhuangyi** [comment]
直接在 GitHub 上建个仓库吧

**Comment by ustbhuangyi** [comment]
@usercao refer to #553
