### ISSUE TITLE
结合mint-ui默认滚动时候DOM渲染有问题

### ISSUE THREAD

**Issue by Niofh** [ustbhuangyi/better-scroll#530]
### Version
1.9.0

### Reproduction link
[ https://niofh.github.io/show-demo/dist/index.html]( https://niofh.github.io/show-demo/dist/index.html)

### Steps to reproduce
BS结合mint-ui默认滚动时候DOM渲染有问题，以前版本没有问题的。但现在滚动到对应区域UI才渲染，给人感觉是渲染不全的感觉。

### What is expected?
希望滚动的时候DOM不要延迟出现

### What is actually happening?
滚动的时候DOM延迟出现了

![image](https://user-images.githubusercontent.com/15324717/39110164-a726cc78-4702-11e8-82a1-65b545a69c7a.png)

**Comment by ustbhuangyi** [comment]
请按 issue 规范提供我可以访问的链接，或者提供 repo

**Comment by Niofh** [comment]
演示链接: demo: https://niofh.github.io/show-demo/dist/index.html
源文件: https://github.com/Niofh/show-demo

**Comment by Niofh** [comment]
scroll 组件是复制你scrollList来做的。

**Comment by ustbhuangyi** [comment]
你是什么版本后才出现这个问题的，我怎么感觉是 mint-ui 的问题呢，另外欢迎使用 cube-ui 哦~

**Comment by Niofh** [comment]
@ustbhuangyi  就是新版BS出现的。以前做音乐APP那个版本还没有问题的。

**Comment by Niofh** [comment]
@ustbhuangyi   发现每次这个pointer-events: none; 每次都把dom隐藏了
![image](https://user-images.githubusercontent.com/15324717/39661075-8cfb8250-507e-11e8-94a9-aa2911b2aafa.png)

**Comment by Niofh** [comment]
@ustbhuangyi  找到问题了 BS 结合router-link 标签滚动就会出现这样的现象！！！
