### ISSUE TITLE
touchEnd事件问题反馈

### ISSUE THREAD

**Issue by lshaohua5** [ustbhuangyi/better-scroll#534]
this.clientScroll.on('touchEnd', (pos) => {
          console.log(pos.y);
          if (pos.y <= (this.clientScroll.maxScrollY - 80)) {
            this.loadListShow = true;
            this.page += 1;
          } else {
            this.clientScroll.refresh();
          }
})
vue中用scroll绑定touchEnd事件，为什么touchEnd后触发两次？
-224.66666666666666  
-182   
![scroll](https://user-images.githubusercontent.com/25662784/39236453-872b31d4-48ab-11e8-9bca-476543183fb0.png)

**Comment by ustbhuangyi** [comment]
请按 issue 规范提供一个最小化复现的 demo
