### ISSUE TITLE
preventDefaultException  使用无效

### ISSUE THREAD

**Issue by fantasthu** [ustbhuangyi/better-scroll#535]
- 操作情况
1. 初始化配置scroll
``` 
 this.scroll = new Bscroll(this.$refs.wrapper, {
          mouseWheel: true,
          click: true,
          tap: true,
          preventDefault: true,
          preventDefaultException: { className: /(^|\s)text(\s|$)/ }
        })
```
2.html 中
```
 <div class="content">
                <div class="text" v-if="item.msgType == 'text'">{{item.msg}}</div>
                <div class="image" v-if="item.msgType == 'image'"><img :src="item.msgPicUrl" alt="" 
                      @click.stop="showMsgPic(item.msgPicUrl)"></div>
              </div>
```
- 测试结果
1.preventDefault = false的时候是可以复制的
2.preventDefault = true , preventDefaultException: { className: /(^|\s)text(\s|$)/ }
class 为text的文本复制不了

**Comment by ustbhuangyi** [comment]
请按 issue 规范提供可最小化复现的 demo 或者 repo

**Comment by ustbhuangyi** [comment]
滑动除非你配置 preventDefault: false，但这样的话就不会阻止浏览器的滚动了。

**Comment by ustbhuangyi** [comment]
@fantasthu ，想到了你这个需求的完美解决方法：
配置 eventPassthrough:horizontal

**Comment by fantasthu** [comment]
@ustbhuangyi 谢谢,很感动,感谢大神

**Comment by lynxerzhang** [comment]
我有一个需求是做iOS上的列表滚动，就是上下滚动的列表，但是同时也需要左右滚动（为了切换Tab界面），一开始无法左右滚动，我也是发觉是preventDefault的问题，然后还自己去判断是左右滑动还是上下滑动，其实只要加上 eventPassthrough:horizontal 属性就行了。

**Comment by cutaoki** [comment]
大佬们，如果我又想放开标签，又想单独给一个类名放开，preventDefaultException配置该怎么写，我试了下好像{tagName: /^(IMG|VIDEO)$/, className:/(^|\s)allowcopy(\s|$)/} 不行

**Comment by moxaIce** [comment]
这个问题ios移动端怎么解决呢？ 按楼主2.preventDefault = true , preventDefaultException: { className: /(^|\s)text(\s|$)/ }
class 为text的文本复制不了 ；； 这种方式在移动端复制可以显示出来，但是选区滑不动；

**Comment by towry** [comment]
> @fantasthu ，想到了你这个需求的完美解决方法： 配置 eventPassthrough:horizontal

这个会导致上下滚动时，页面会随着动一下。
