### ISSUE TITLE
您好，请教一下在ng4里编译总是报错: Module ''better-scroll'' has no default export

### ISSUE THREAD

**Issue by lycHub** [ustbhuangyi/better-scroll#536]
黄老师，我在angular4里引入bs
import BScroll from 'better-scroll'

但编译的时候经常无法通过，Module ''better-scroll'' has no default export
尽管有时编译能通过，但也会报一个这种错误
您知道是什么原因吗？

**Comment by ustbhuangyi** [comment]
你是使用 TypeScript 吗，版本是多少？

**Comment by ustbhuangyi** [comment]
试试 2.7 以上版本的 ts 吧
