### ISSUE TITLE
bug: slide组件只有一张图片并且设置loop: true，滑动时出现空白

### ISSUE THREAD

**Issue by py419569317** [ustbhuangyi/better-scroll#539]
### Version
1.10.0

### Reproduction link
[https://20x1jk0l5r.codesandbox.io/](https://20x1jk0l5r.codesandbox.io/)

### Steps to reproduce
1、clone到本地运行
2、slide-render中的items数组第一项，只保留一张图片
3、轮播图想左滑动，出现空白，实际上页面只创建了一个 slide-item

### What is expected?
可以正常循环滑动

### What is actually happening?
页面只有一个 slide-item，导致向左滑动出现空白

**Comment by ustbhuangyi** [comment]
只有一个元素是不支持 loop 的，因为现在 loop 既支持横向，又支持纵向，只有一个元素根本不知道往哪个方向循环，另外一个元素循环也是不合理的

**Comment by py419569317** [comment]
好的，了解了，谢谢回答！
