### ISSUE TITLE
ios 表单元素，在聚焦状态，再次多次点击input表单，导致键盘不停的重复唤起，关闭

### ISSUE THREAD

**Issue by xiaohuangyuson** [ustbhuangyi/better-scroll#540]
感觉像是touchstart 然后input就失去焦点了，touchend时，焦点再次回到input上。导致键盘不停打开。

当然前置条件是 input表单元素，在better-scroll实例中.

不是很严重，期望优化

**Comment by xiaohuangyuson** [comment]
我看了下源码是这里导致的。为什么要在这个时候。去掉他的焦点呢

BScroll.prototype._handleAutoBlur = function () {
    this.on('beforeScrollStart', function () {
      var activeElement = document.activeElement;
      if (activeElement && (activeElement.tagName === 'INPUT' || activeElement.tagName === 'TEXTAREA')) {
        activeElement.blur();
      }
    });
  };

**Comment by ustbhuangyi** [comment]
你是什么手机会导致此现象，这个为了是让触发滚动的时候键盘能自动下去。可否提供一个稳定复现的 demo 或者 repo。

**Comment by xiaohuangyuson** [comment]
这个问题只在ios 系统下 也就是苹果手机才会出现。安桌上完全正常。  
也就是在input foucs 的情况下，键盘本身是打开的，再轻点一下input就会出现这种现象。

体验问题还好。如果把上面的代码去掉。确实不会出现此问题。但是滑动的时候，会出现光标还在原位置 闪硕。....尴尬.


demo : 

new BScroll ( el , { click : true} );

html

`<div style="height: 100vh" class="el">
<div style="height: 2000px">
   <input />
</div>
</div>`

**Comment by xiaohuangyuson** [comment]
好吧，还有一个衍生问题就是。ios下的better-scroll实例中   包含 的input    无法复制，粘帖了。
因为每次都会失去焦点。

**Comment by ustbhuangyi** [comment]
试试 1.10.3 版本

**Comment by 13032519955** [comment]
> 试试1.10.3版本
移动端效验是在input失去焦点的时候出发的...效验失败后弹出框 ...  - -
