### ISSUE TITLE
一块滚动区域的中间有一个导航栏，区域滚动时，当导航栏接触到顶部时，自动固定到顶部，滚动区域可以继续进行滚动。

### ISSUE THREAD

**Issue by y-cares** [ustbhuangyi/better-scroll#541]
### Version
1.10.0

### Reproduction link
[https://2orx55p060.codesandbox.io/](https://2orx55p060.codesandbox.io/)

### Steps to reproduce
一块滚动区域的中间有一个导航栏，区域滚动时，当导航栏接触到顶部时，导航栏的position:fixed，没有起效果，而是跟着滚动区域一起滚动。

### What is expected?
一块滚动区域的中间有一个导航栏，区域滚动时，当导航栏接触到顶部时，设置position:fixed后，自动固定到顶部，滚动区域可以继续进行滚动。

### What is actually happening?
导航栏接触到顶部时，设置position:fixed后，并没有固定在顶部，而是跟着滚动区域一起滚动。

**Comment by ustbhuangyi** [comment]
建议把 fixed 布局的容器放到 scroll 外面

**Comment by y-cares** [comment]
@ustbhuangyi    目前就是这样解决的   但是  有没有更好的解决方法？！
