### ISSUE TITLE
使用keep-alive后,better-scroll没有执行refresh方法,也没有执行init,但是数据刷新了,求解答

### ISSUE THREAD

**Issue by fantastiche** [ustbhuangyi/better-scroll#543]
### Version
1.10.0

### Reproduction link
[https://github.com/fantastiche/MGG-web](https://github.com/fantastiche/MGG-web)

### Steps to reproduce
使用keep-alive后,better-scroll没有执行refresh方法,也没有执行init,但是数据刷新了

### What is expected?
使用keep-alive后,better-scroll没有执行refresh方法,也没有执行init,但是数据刷新了

### What is actually happening?
使用keep-alive后,better-scroll没有执行refresh方法,也没有执行init,但是数据刷新了

---
使用keep-alive后,better-scroll没有执行refresh方法,也没有执行init,但是数据刷新了

**Comment by ustbhuangyi** [comment]
不符合 issue 规范，既然你用了 keep-alive，就应该利用它的生命周期去做一些事情
