### ISSUE TITLE
轮播图问题 只有一张图片的时候下一张空白

### ISSUE THREAD

**Issue by jifengdehao** [ustbhuangyi/better-scroll#544]

**Comment by jifengdehao** [comment]
例子中的slide 组件

**Comment by ustbhuangyi** [comment]
参考这个 issue:https://github.com/ustbhuangyi/better-scroll/issues/539
另外，slide.vue 参考 cube-ui 的实现：https://github.com/didi/cube-ui/blob/dev/src/components/slide/slide.vue
