### ISSUE TITLE
关于两个实例同步滚动，有什么好方法吗。

### ISSUE THREAD

**Issue by xiaohuangyuson** [ustbhuangyi/better-scroll#546]
在某些情况下限于dom布局，必须生成两个滚动实例。但这两个实例是应该同步滚动的。
我现在在onscroll时，不断更新X，轴，同步滚动。感觉会有些抖到。有比较好的解决方案吗？
this.scrollX.on('scroll', (pos) => {
            this.scrollHeader.scrollTo(pos.x, 0)
        });

        this.scrollHeader.on('scroll', (pos) => {
            this.scrollX.scrollTo(pos.x, 0)
        });

**Comment by ustbhuangyi** [comment]
请不要用 issue 问问题，可以群里和大家讨论
