### ISSUE TITLE
wrapper高度100%的时候 wrapperScrollHeight和scrollBarHeight高度相等

### ISSUE THREAD

**Issue by XdyGoGo** [ustbhuangyi/better-scroll#547]
hasVerticalScroll为true   wrapperScrollHeight和scrollBarHeight高度相等wrapper高度100% 无法滚动
解决办法 100%的高度换成100vh
想知道是什么原因

**Comment by ustbhuangyi** [comment]
看一下文档中的滚动原理，也请不要用 issue 问问题，有问题可以去群里讨论
