### ISSUE TITLE
上拉加载更多分页数据怎么实现？

### ISSUE THREAD

**Issue by lixsh8** [ustbhuangyi/better-scroll#55]
上拉加载更多分页数据怎么实现？有没有判断往上滑动还是往下滑动的属性或者接口？

**Comment by shuangbofu** [comment]
初始化的时候计算最大高度，只要pos.y的绝对值大于最大高度就执行loadMore函数，数据渲染完重新计算高度

**Comment by ustbhuangyi** [comment]
推荐看这篇文章： https://github.com/DDFE/DDFE-blog/issues/15
