### ISSUE TITLE
关于better-scroll在IOS上的表现，快速滑动（向上或向下）时，页面出现一片空白。

### ISSUE THREAD

**Issue by jiangweipeng** [ustbhuangyi/better-scroll#551]
### Version
1.8.4

### Reproduction link
[http://ustbhuangyi.com/sell/#/goods](http://ustbhuangyi.com/sell/#/goods)

### Steps to reproduce
点击商品进入商品详情，快速滑动出现空白（上滑出现空白频率较大）

### What is expected?
期望正常滑动不出现空白

### What is actually happening?
..................

---
测试环境：苹果6ps   IOS10.2.1   苹果7 IOS11.3.1

如果需要地址验证，我可以提供项目真实地址

**Comment by ustbhuangyi** [comment]
我这并没有复现啊，提供一个最小化复现的 repo?

**Comment by jiangweipeng** [comment]
昨天下班太晚了，就没有做这个复现。
不知为什么在微信浏览器上就是获取不了数据。
测试的时候请使用IOS自带浏览器查看。
https://mshoppro.mzywx.com/mshop_pro/img/dist/index.html

**Comment by ustbhuangyi** [comment]
白屏问题可以用 useTransition: false 解决，坏处是启动 JS 动画后滚动流畅度会降低。

**Comment by renyuns** [comment]
我也有这个问题,想问楼主解决了吗

**Comment by ustbhuangyi** [comment]
refer to https://github.com/ustbhuangyi/better-scroll/issues/580

**Comment by zxflslzyx** [comment]
问个问题啊，
ios 滚动过快的时候 滑倒顶部，弹的幅度会很大，会弹两几下，
请问 这个有办法解决吗

**Comment by laoboxie** [comment]
我通过开启GPU加速解决了这个问题
