### ISSUE TITLE
使用鼠标滚轮滑动时,页面变得非常卡顿

### ISSUE THREAD

**Issue by 342708096** [ustbhuangyi/better-scroll#553]
版本为v1.11.1,   触摸滑动时没有问题

**Comment by 342708096** [comment]
v1.8.0版本没有问题

**Comment by ustbhuangyi** [comment]
请按 issue 规范提供一个最小化复现的地址

**Comment by ustbhuangyi** [comment]
试试配置 easeTime 为 0 
https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options-advanced.html#mousewheelv180

**Comment by dengjianf** [comment]
[我的博客](http://dengjianf.github.io)现在就出现了这个问题。。怎么解决？
