### ISSUE TITLE
probeType = 3 ，momentum过程中 scroll 事件的参数(x, y)没有变化

### ISSUE THREAD

**Issue by lilong7676** [ustbhuangyi/better-scroll#555]
### Version
1.11.1

### Reproduction link
[https://jsfiddle.net/lilong7676/84anc4jn](https://jsfiddle.net/lilong7676/84anc4jn)
### Steps to reproduce
请打开控制台查看输出。

### What is expected?
scroll 事件的参数(x, y)正常变化

### What is actually happening?
scroll 事件的参数(x, y)没有变化

**Comment by ustbhuangyi** [comment]
not a bug
