### ISSUE TITLE
内容未填满wrapper高度下拉刷新不生效

### ISSUE THREAD

**Issue by lvchenyang** [ustbhuangyi/better-scroll#556]
### Version
1.11.1

### Reproduction link
[https://codesandbox.io/s/5k15lx104k](https://codesandbox.io/s/5k15lx104k)

### Steps to reproduce
直接点击拖拽鼠标下拉刷新

### What is expected?
能够触发下拉刷新事件

### What is actually happening?
未触发下拉刷新事件

---
在React中使用的better-scroll

**Comment by ustbhuangyi** [comment]
内容未超过容器本身也不会触发滚动，所以也就不会有下拉刷新，你可以给内容加个 min-height，参考这个 demo: https://ustbhuangyi.github.io/better-scroll/#/examples/vertical-scroll/en

**Comment by lvchenyang** [comment]
追加一个问题，当列表滚动到最顶部或最底部的时候，`scrollEnd`事件会被执行多次，难道不应该是执行一次？示例代码见：[https://codesandbox.io/s/5k15lx104k](https://codesandbox.io/s/5k15lx104k)

**Comment by ustbhuangyi** [comment]
你滚动姿势的问题，应该是触碰滚动

**Comment by lvchenyang** [comment]
滚动的姿势是使用macos触控板两个手指头直接往下拉的
