### ISSUE TITLE
[New Feature] 能否实现下拉刷新时Dom复用 就像iscroll 支持的那样

### ISSUE THREAD

**Issue by mrKylinZhou** [ustbhuangyi/better-scroll#557]
### What problem does this feature solve?
iscroll是支持无限滚动的，在滚动过程中会复用之前的Dom。像这个网址一样：http://lab.cubiq.org/iscroll5/demos/infinite/

不知道better-scroll是否支持这样的功能，还麻烦提供较为详细的使用文档

### What does the proposed API look like?
infinite: true

**Comment by ustbhuangyi** [comment]
看上去就是一个上拉加载的 feature？这个是已经支持的。

**Comment by ustbhuangyi** [comment]
这个数据量确实是挺庞大的了，可以考虑支持一下

**Comment by ustbhuangyi** [comment]
不过看了一下 iscroll 的实现，虽然可以保证只有一定数量的 DOM，但是在数据量少的时候其实并没有优势，反而更卡，因为它是监听 scroll 事件不断循环做计算的，这个性能消耗也挺大的。而且对于数据 -> DOM 的更新，iscroll 由于只缓存了数据，所以这部分是交给用户去做的，这部分使用起来也有成本。总感觉是一个成本大于收益的搞法，不过你 5w 条数据的场景是否合理，用户一开始也只会展示一部分数据吧，那有多少概率会把所有数据都拉取完毕呢？

**Comment by mrKylinZhou** [comment]
我们是一个大数据的场景，出现这种情况并不是在小场景下才会出现的。iscroll 是把之前的Dom缓存起来并将数据做了替换后用 innerHTML 来做内容替换的，并且开启了GPU加速，性能来说感觉并不会特别差

**Comment by mrKylinZhou** [comment]
我也在调研这一块，你可以参考这篇文章[无尽滚动的复杂度](https://mp.weixin.qq.com/s?__biz=MjM5MTA1MjAxMQ==&mid=2651228694&idx=1&sn=4b5c08e19675694de749ef8fffc10100&chksm=bd4953928a3eda84cd21d55044423e4d64e728706a9ceb057de466316a89944609664cb1a516&mpshare=1&scene=1&srcid=0521s6BfvQmTQ1IsaqtcRk8y#rd)写的还不错。 如果better-scroll 支持Dom复用的话，将会非常有用

**Comment by longweixia** [comment]
大神对大神

**Comment by ustbhuangyi** [comment]
@mrKylinZhou ，可以体验一下，在那篇文章的基础上，还实现了滚动到底部的能力。
https://ustbhuangyi.github.io/better-scroll/#/examples/infinity/en
是否达到了你的需求？

**Comment by ustbhuangyi** [comment]
1.12.0 已支持
