### ISSUE TITLE
使用鼠标滑轮进行滚动时，无法检测到scrollEnd事件？

### ISSUE THREAD

**Issue by hz0324** [ustbhuangyi/better-scroll#558]
如题，我们主要是用在PC端，试过iSroll和better-scroll，发现都不能检测到鼠标wheel滚动时的end和start事件。请问这个能解决吗？

多谢

**Comment by ustbhuangyi** [comment]
你用的什么版本，会派发 scrollStart 和 scrollEnd 事件啊
