### ISSUE TITLE
黄老师，我做外卖app用better-scroll的时候遇到一个是否需要阻止默认事件的问题，期望您能帮我解惑

### ISSUE THREAD

**Issue by zhou-losdust** [ustbhuangyi/better-scroll#56]
最近在看那个外卖app视频学vue，我发现里边的加减按钮的那个组件里边，为了防止在pc端触发两次，里边用event._constructed做了一个判断，如果不是派发的点击事件就直接return掉，但是这样的话，如果这个组件没有用在better-scroll上的话，点击事件没办法触发，没有想到什么好的解决办法，所以我就将preventDefault改为false了，把派发的click事件去掉了，测了测是没有问题的，我想问问您这样做会不会有什么隐藏的隐患，为什么初始化的时候要将默认事件阻止掉，通过派发来实现点击事件（前端小白一枚，问的问题可能不太成熟，您勿怪）

**Comment by ustbhuangyi** [comment]
event._constructed 是 better-scroll 派发事件的时候设置的私有属性，如果没有用 better-scroll 的话监听正常的点击事件就可以了。

**Comment by zhou-losdust** [comment]
但是event._constructed这个是写在组件里边的，如果是正常的点击事件就直接return掉了，不return掉的话，better-scroll上的点击事件就会触发两次了，难两全啊.....
