### ISSUE TITLE
当better-scroll于vue-lazyload一起使用的时候,页面会闪烁刷新

### ISSUE THREAD

**Issue by dogsmall** [ustbhuangyi/better-scroll#560]
### Version
1.9.0

### Reproduction link
[https://ustbhuangyi.github.io/better-scroll/#/examples/full-page-vertical-slide/en](https://ustbhuangyi.github.io/better-scroll/#/examples/full-page-vertical-slide/en)

### Steps to reproduce
better-scroll中的full-page-vertical-slide图片地址改成百度图片地址,然后将图片以<img v-lazy="xxxx">引入,会看到当手指按下慢慢将图片向上滑动到一定位置时,会重新回到起始位置,松开手时会跳到下一页

### What is expected?
期望是会跟随手指滑动,放开手指的时候判断是否跳到下一页

### What is actually happening?
缓慢向上滑动到一定位置的时候,当前滑动页面回到起始的位置了

---
我不知道这个问题算不算bug,毕竟这可能不是better-scroll的问题,但是我在使用的时候确实遇到了这个问题,所以来发一个issue,我怀疑是v-lazy在滑动到一定位置时触发了加载后面的图片,导致dom可能发生了变化,触发了刷新,然后better-scroll会跳到当前页,当前页是我手指正在滑动的那张,这也是为什么我手指没有松开的情况下页面会闪烁刷新到起始位置

**Comment by yangjingzwb** [comment]
可以试试为滑动的节点增加:key属性

**Comment by ustbhuangyi** [comment]
你是滑动过程中超出屏幕才会回退吧，这个现象应该跟你用不用外部图片无关，可否录制复现视频？

**Comment by cnsuer** [comment]
gif: [https://gitee.com/cnsuer/excel/blob/master/test.gif](url)

 "better-scroll": "^1.13.2"
"vue-lazyload": "^1.2.6"

`<img v-lazy="item.imgUrl">` 会出现这个问题
`<img :src="item.imgUrl">` 就不会出现这个问题了
