### ISSUE TITLE
省市区三级联动 特定情况下 省份未正确滚动

### ISSUE THREAD

**Issue by SmileDong** [ustbhuangyi/better-scroll#561]
执行步骤：1、点击显示三级联动的 picker组件  2、任意选择省市区 （不点击confirm）点击遮罩或cancel隐藏组件  3、再次点击显示三级联动的 picker组件 此时会发现 省份 未滚动到正确位置

黄老师这是个小bug，我已经修复了。我的做法如下：
1、获取省份滚动的位置并保存===>this.cityIndex = this.wheels[0].getSelectedIndex()
2、在watch中调用 this.scrollTo(0, this.cityIndex)方法

**Comment by ustbhuangyi** [comment]
这个是 demo 的问题，可以参考：https://didi.github.io/cube-ui/#/zh-CN/docs/cascade-picker，这个基是于 better-scroll 的上层封装。
