### ISSUE TITLE
配置eventPassthrough为横向原生滚动后在ios 移动端上滑动不流畅

### ISSUE THREAD

**Issue by xuxiaoxiao312** [ustbhuangyi/better-scroll#562]
### Version
1.10.3

### Reproduction link
[https://github.com/xuxiaoxiao312/vue-demo](https://github.com/xuxiaoxiao312/vue-demo)

### Steps to reproduce
设置  eventPassthrough: 'horizontal'，div设置overflow:scroll 后，在android滑动顺畅，但在ios没有原生滑动的流畅感

### What is expected?
在ios 横向滑动效果与android一致

### What is actually happening?
在ios 横向滑动卡顿明显

**Comment by ustbhuangyi** [comment]
eventPassthrough 是为了让某个方向保持原生的滚动，如果卡的话问题不在于 better-scroll
