### ISSUE TITLE
【问题反馈】UC浏览器11.6.8.952上轮播无法拖动的问题（抖动），麻烦进来了解一下！

### ISSUE THREAD

**Issue by dficonfont** [ustbhuangyi/better-scroll#565]
### Version
1.11.1 （1.5.2之后的版本有这个问题）

### Reproduction link
[http://ustbhuangyi.com/music/](http://ustbhuangyi.com/music/)

### Steps to reproduce
在您的这个演示地址中就有这个问题【Vue.js 音乐 App 高级实战课程 项目演示地址】，UC浏览器11.6.8.952上轮播图无法拖动，注意表现为拖动时抖动。

### What is expected?
希望能解决这个问题！谢谢

### What is actually happening?
UC浏览器11.6.8.952上轮播图无法拖动，注意表现为拖动时抖动。

**Comment by ustbhuangyi** [comment]
PC 还是移动端

**Comment by ustbhuangyi** [comment]
你试试配置 observeDOM 为 false
