### ISSUE TITLE
移动端下better-scroll阻止了element ui table组件在数据过多时的横向滚动

### ISSUE THREAD

**Issue by TothingWay** [ustbhuangyi/better-scroll#570]
### Version
1.11.1

### Reproduction link
[https://jsfiddle.net/vqmtg9a7/9/](https://jsfiddle.net/vqmtg9a7/9/)

### Steps to reproduce
使用chrome的移动端模式打开https://fiddle.jshell.net/vqmtg9a7/7/show/,鼠标横向滚动表格，底部会短暂出现横向滚动条，但立刻消失，无法横向滚动

### What is expected?
在使用better-scroll嵌套element ui table组件时候，能让table组件横向滚动

### What is actually happening?
在使用better-scroll嵌套element ui table组件时候，table组件不能横向滚动

**Comment by ustbhuangyi** [comment]
试试配置 eventPassthrough 为 horizontal

**Comment by TothingWay** [comment]
感谢，解决了，我之前设置了preventDefault 为 false也可以解决，现在使用eventPassthrough 为 horizontal

**Comment by TothingWay** [comment]
@ustbhuangyi 
发现了新问题，在配置了 eventPassthrough 为 horizontal后，在 ios 下无法阻止浏览器的原生滚动回弹，会有冲突，但同时又想保持element ui table组件在数据过多时的横向滚动该怎么处理？
