### ISSUE TITLE
关于在scroll组件中使用picker组件问题

### ISSUE THREAD

**Issue by guigui730** [ustbhuangyi/better-scroll#572]
picker组件是作为一个子组件引入到页面中，父组件中使用了BScroll ，但是父组件的页面高度超过了一个屏幕，导致picker组件的popup弹出的时候，是从屏幕下方开始的，只能看到半个popup，而且这时候在popup上滑动，整个父组件也会跟着动？请问是用通过配置wheel来解决吗？  具体怎么做

**Comment by ustbhuangyi** [comment]
不符合 issue 规范，请不要要用 issue 问问题，有问题可以去群里讨论

**Comment by webxing** [comment]
请问解决了么
