### ISSUE TITLE
better-scroll 会对router-link append造成影响

### ISSUE THREAD

**Issue by Astaca** [ustbhuangyi/better-scroll#574]
ersion
1.11.1

Reproduction link
https://k31k5xvk73.codesandbox.io/#/

Steps to reproduce
使用chrome的移动端模式或者手机微信打开https://k31k5xvk73.codesandbox.io/#/  ，快速点击12313，
双击会造成路由的再次追加，路由变为https://k31k5xvk73.codesandbox.io/#/a/a， 无引用better-scroll不会出现追加

**Comment by ustbhuangyi** [comment]
提供一下你这个 codesandbox 可编辑代码的地址

**Comment by Astaca** [comment]
https://codesandbox.io/s/k31k5xvk73

**Comment by ustbhuangyi** [comment]
看了一下你这个问题和是否使用 better-scroll 无关， 普通 div 也会。本质原因是你的路由切换时一个动画，当新的路由还没有切入的时候你又再次点击按钮就会出现你这个情况。

**Comment by Astaca** [comment]
https://codesandbox.io/s/k31k5xvk73
注释组件并不会出现这个情况

**Comment by ustbhuangyi** [comment]
https://q9pq458zw6.codesandbox.io/#/
不用 better-scroll 一样会出现这个问题

**Comment by Astaca** [comment]
发现矛盾点在于 better-scroll 和 切换动画，请问有什么解决办法吗
