### ISSUE TITLE
设置disableMouse为true后，scrollbar.interactive失效

### ISSUE THREAD

**Issue by vsme** [ustbhuangyi/better-scroll#579]
### Version
1.12.0

### Reproduction link
[https://jsfiddle.net/50wL7mdz/352594/](https://jsfiddle.net/50wL7mdz/352594/)

### Steps to reproduce
```

            // 定义scroll组件
            new BScroll(this.$refs.scroll, {
              scrollbar: {
                fade: true,
                interactive: true // 表示滚动条是否可以交互
              },
              disableMouse: true, // false 鼠标会拖动页面
            })
```

### What is expected?
鼠标不拖动页面，滚动条并可以交互

### What is actually happening?
设置disableMouse为true后，scrollbar.interactive失效

---
平台：mac chrome

**Comment by ustbhuangyi** [comment]
disableMouse 的含义就是让鼠标失效，自然滚动条不能用鼠标交互也是合理的。
