### ISSUE TITLE
betterScroll内部的textera内容无法滑动

### ISSUE THREAD

**Issue by GOGOGOSIR** [ustbhuangyi/better-scroll#581]

**Comment by GOGOGOSIR** [comment]
设置了preventDefaultException 这个属性也没有用，

**Comment by ustbhuangyi** [comment]
preventDefault 设置为 false，或者自己模拟实现 textarea

**Comment by axiang51** [comment]
preventDefault 设置为 false导致页面滚动受阻，出现了众多bug，只能模拟实现textarea吗
