### ISSUE TITLE
[New Feature] 能否把DEMO的源码贴出来

### ISSUE THREAD

**Issue by yusk013** [ustbhuangyi/better-scroll#584]
### What problem does this feature solve?
这个插件的功能很好，DEMO也是我想要的，但是没有DEMO的Code，这太让人沮丧了，根本找不到该怎么用。找到其他人的DEMO以及Code，自己照着写，依然实现不了功能。

### What does the proposed API look like?
有实例代码最好了。

**Comment by ustbhuangyi** [comment]
demo 的代码在 example 目录里啊

**Comment by yusk013** [comment]
服了，虽然我已经找到怎么弄了，但是你这个example实在是不友好。
