### ISSUE TITLE
如果用户多次上拉加载，页面会明显卡顿

### ISSUE THREAD

**Issue by codecatgo** [ustbhuangyi/better-scroll#586]
### Version
1.12.0

### Reproduction link
[http://www.lfeel.com/APP_web/voting_activities/index.html?id=40](http://www.lfeel.com/APP_web/voting_activities/index.html?id=40)

### Steps to reproduce
如果用户多次上拉刷新，页面会明显卡顿，请问怎么解决

### What is expected?
如果用户一直上拉加载可以不卡顿，滑动流畅

### What is actually happening?
如果用户一直上拉加载，页面明显卡顿

**Comment by ustbhuangyi** [comment]
如果是数据过多的话，可以考虑使用无限滚动。
https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options-advanced.html#infinityv1120

**Comment by codecatgo** [comment]
是加载过程没有完成，但是用户可能一直在那里上拉，就会多次触发加载事件，加载完成后，页面会卡顿

**Comment by ustbhuangyi** [comment]
你没有 finsh 的话是不会多次派发事件的，除非你逻辑写的有问题。

**Comment by Sapphire2k** [comment]
遇到同样的问题，就是最后一页加载完成之后，上拉加载并且一直上拉，会多次触发事件，用的是slot渲染~
