### ISSUE TITLE
 warpper容器下的content元素(滚动元素)存在fixed布局子元素的话, 定位不起作用

### ISSUE THREAD

**Issue by yusifeng** [ustbhuangyi/better-scroll#587]
### Version
1.12.0

### Reproduction link
[https://jsbin.com/yufifov/edit?html,output](https://jsbin.com/yufifov/edit?html,output)

### Steps to reproduce
想知道这个是一个bug还是说就应该产生这种效果.谢谢你们提供这么好的框架

### What is expected?
我希望这个子元素可以跟一般fixed元素一样

### What is actually happening?
null

**Comment by ustbhuangyi** [comment]
fixed 元素要拿到外面去，因为它会受到 transform 的影响

**Comment by kid1412621** [comment]
@ustbhuangyi 你好,请问我需要将我自己封装的一个组件在一个状态随 bscroll 滚动,另一状态 fixed 怎么实现呢?

**Comment by kid1412621** [comment]
想到实现方式了, 使用 :slot 判断是将组件放在滚动区域还是非滚动区域
