### ISSUE TITLE
preventDefaultException bug

### ISSUE THREAD

**Issue by lbca** [ustbhuangyi/better-scroll#588]
### Version
1.12.0

### Reproduction link
[https://jsfiddle.net/50wL7mdz/397613/](https://jsfiddle.net/50wL7mdz/397613/)

### Steps to reproduce
preventDefaultException在touchmove中无效

### What is expected?
textarea滚动

### What is actually happening?
不滚动

---
打包后代码1046行，改成如下，可正常运行：
if (this.options.preventDefault && !preventDefaultException(e.target, this.options.preventDefaultException)) {

**Comment by vanoneang** [comment]
@lbca  请问你解决了吗？ 怎么实现的？ 谢谢

**Comment by axiang51** [comment]
> @lbca 请问你解决了吗？ 怎么实现的？ 谢谢

你解决了吗，有没有实现啊，谢谢
