### ISSUE TITLE
最新版企业微信pc端无法滚动

### ISSUE THREAD

**Issue by kwdiwt** [ustbhuangyi/better-scroll#589]
### Version
1.12.0

### Reproduction link
[http://ustbhuangyi.com/music/#/recommend](http://ustbhuangyi.com/music/#/recommend)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/7121840/41828206-980e5702-7866-11e8-8c2c-637de3df644f.png)
最新版企业微信pc端 无法滚动~~~  

### What is expected?
this.scroll.on("scroll", pos => {})

### What is actually happening?
无法滚动

**Comment by ustbhuangyi** [comment]
滚动姿势问题？

**Comment by kwdiwt** [comment]
@ustbhuangyi scroll事件没有驱动起来 我调调

**Comment by kwdiwt** [comment]
调不出来 放弃治疗 ☺️

**Comment by ustbhuangyi** [comment]
scroll 事件应该和 probeType 的配置相关，看文档吧

**Comment by ustbhuangyi** [comment]
参考：https://github.com/ustbhuangyi/better-scroll/issues/595
