### ISSUE TITLE
派发probeType:3 事件，会不断重新实例化scroll对象，导致_event里面重复生成事件

### ISSUE THREAD

**Issue by thomasyc** [ustbhuangyi/better-scroll#59]
![screenshot 2017-05-09_17-21-18](https://cloud.githubusercontent.com/assets/24216880/25844255/6f232b84-34dc-11e7-88bd-19cc4e09d401.png)
![screenshot 2017-05-09_17-21-27](https://cloud.githubusercontent.com/assets/24216880/25844257/6f2b9cf6-34dc-11e7-9325-04230ba44685.png)
![screenshot 2017-05-09_17-21-37](https://cloud.githubusercontent.com/assets/24216880/25844256/6f2a7b78-34dc-11e7-94bd-c6f5982df978.png)
![screenshot 2017-05-09_17-21-48](https://cloud.githubusercontent.com/assets/24216880/25844260/6f4d6c78-34dc-11e7-8745-1cee96179e29.png)
![screenshot 2017-05-09_17-23-55](https://cloud.githubusercontent.com/assets/24216880/25844262/6f5a4c36-34dc-11e7-874f-3be3f77dc6d8.png)

可能我说的不太准确，不过看图应该能明白。请及时修复！！！！

**Comment by zenga2** [comment]
@thomasyc  你绑定事件的那个方法很可能执行了多次；
                    你在绑定事件的那个地方打个日志验证一下

**Comment by thomasyc** [comment]
@zenga2 额...这个日志验证怎么弄?

**Comment by zenga2** [comment]
在你绑定事件的地方加一行console.log('www')

**Comment by zenga2** [comment]
你再刷新项目，看控制台有几条信息

**Comment by ustbhuangyi** [comment]
在 new BScroll 后绑定一次事件即可，不要每次都绑定事件。

**Comment by thomasyc** [comment]
@zenga2 只有一条信息
![screenshot 2017-05-09_18-13-49](https://cloud.githubusercontent.com/assets/24216880/25846150/4e70dfec-34e3-11e7-9a6f-0c8a16d787bd.png)

**Comment by thomasyc** [comment]
@ustbhuangyi 
![screenshot 2017-05-09_18-20-04](https://cloud.githubusercontent.com/assets/24216880/25846374/2a4b6e38-34e4-11e7-9354-c847a152a52b.png)
我发现pos.y会返回两次，是bug?

**Comment by ustbhuangyi** [comment]
事件的回调只会执行一次，你之前的 bug 是因为你多次绑定了事件
