### ISSUE TITLE
滚动内容是video的话，视频点击无法播放

### ISSUE THREAD

**Issue by yangjianwei1223** [ustbhuangyi/better-scroll#590]
### Version
1.12.0

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll](https://github.com/ustbhuangyi/better-scroll)

### Steps to reproduce
滚动内容是视频的话，无法点击播放。

### What is expected?
是否能帮忙看下。

### What is actually happening?
是否能帮忙看下。

**Comment by ustbhuangyi** [comment]
Reproduction link 不符合 issue 规范
