### ISSUE TITLE
列表内容是视频的话，点击不能播放。

### ISSUE THREAD

**Issue by yangjianwei1223** [ustbhuangyi/better-scroll#591]
重现链接：
http://www.meiqingshuma.top/vue/index.html#/better-scroll

好吧，谷歌浏览器仿真不能播放。真机上面可以。。

**Comment by dficonfont** [comment]
是不是touch 和 click的关系？

**Comment by yangjianwei1223** [comment]
没写事件，就是手机系统对video自动加的控件的点击事件。

**Comment by ustbhuangyi** [comment]
preventDefaultException 里配置一下 video 标签

**Comment by yangjianwei1223** [comment]
配置了也不行。而且手机上在播放器上滑动也滑不了。

**Comment by hezhongfeng** [comment]
@yangjianwei1223 
我没配置的话在安卓播放按键失效，在ios下可以
添加VIDEO以后可以

**Comment by GongLLei** [comment]
@yangjianwei1223  

你好， 遇到了同样的问题，这个问题现在有解决吗？

**Comment by wuyuedefeng** [comment]
手机上在播放器上滑动不了的问题有解决吗； Android其他区域可滑动，但是滑动手势在video上时，页面无法滑动。
