### ISSUE TITLE
用的v-html读取标签内容，第一次进入由于图片过大加载缓慢better-scroll无法计算高度导致无法滚动，再次进入的时候又能滚动请问大神怎么解决

### ISSUE THREAD

**Issue by TJLHQ** [ustbhuangyi/better-scroll#593]

**Comment by dficonfont** [comment]
图片加载好再执行better-scroll

**Comment by TJLHQ** [comment]
处理好了；
由于的img标签是富文本生成的，所以是动态加载出来的，无法绑定img的load事件，我的解决办法是监听beforeScroll 再次调用refresh方法重新计算，完美解决

**Comment by renyuns** [comment]
@TJLHQ 我的也是这样的,请问老铁具体是怎么解决的的,监听 beforeScroll ? 还是监听返回的富文本里面的图片加载完成再去调用 refresh

**Comment by renyuns** [comment]
@TJLHQ 老铁,你说的监听 beforeScroll 是怎么个实现
