### ISSUE TITLE
请教大佬类似微信上拉加载更多聊天记录功能有没有办法实现？目前脑袋空空，请指教！

### ISSUE THREAD

**Issue by dficonfont** [ustbhuangyi/better-scroll#594]
请教大佬类似上拉加载更多聊天记录功能有没有办法实现？目前脑袋空空，请指教！，有没有用better-scroll都可以。

主要问题是加载更多的时候，需要在前面插入，不能有闪烁感，当前看到第几条消息不能跳到别的地方去

**Comment by ustbhuangyi** [comment]
不要用 issue 问问题，可以加群讨论
