### ISSUE TITLE
企业微信项目中页面不能滚动

### ISSUE THREAD

**Issue by LuHugo** [ustbhuangyi/better-scroll#595]
### Version
1.12.0

### Reproduction link
[https://ustbhuangyi.github.io/better-scroll/#/examples/infinity/en](https://ustbhuangyi.github.io/better-scroll/#/examples/infinity/en)

### Steps to reproduce
在windows系统下最新版（版本：2.4.22.2024）的企业微信中无法滚动，也无法下拉、上拉。MacOS版本的企业微信无问题。

重现步骤：
在windows下的企业微信中打开官方的例子

### What is expected?
可以滚轮滚动、拖动滚动、上拉、下拉等

### What is actually happening?
无法滚动、无法拖动、无法下拉、无法下拉

---
官方有些例子可以滚轮滚动但是不能拖动滚动

**Comment by ustbhuangyi** [comment]
先定位一下是否支持 mousemove 和 touchmove 事件

**Comment by LuHugo** [comment]
@ustbhuangyi 企业微信应该是支持这两个事件的，因为打开iscroll的例子是没问题，可以用鼠标拖动滚动、下拉、上拉的

**Comment by LuHugo** [comment]
iscroll(5.2.0) 最新版本在windows系统下最新版本（2.4.22）的企业微信有问题，使用iscroll 5.1.3版本没问题。

**Comment by ustbhuangyi** [comment]
我这没有环境，你那边能否调试一下源码，看看什么问题？

**Comment by LuHugo** [comment]
@ustbhuangyi 
企业微信很难调试（基本上无法调试）-_-|

问题找到了
https://github.com/cubiq/iscroll/pull/1229

需要强制开启touch模式，禁用poiner事件
>This is the same question in 5.2.0;You can try to set options like this
disablePointer: true, // important to disable the pointer events that causes the issues
disableTouch: false, // false if you want the slider to be usable with touch devices
disableMouse: false // false if you want the slider to be usable with a mouse (desktop)
disable pointer event，force to use touch

**Comment by LuHugo** [comment]
上面的三个属性我都设置了，然后就可以滚动了。没有一个一个去试。
