### ISSUE TITLE
非vue调用，当执行第一次上拉操作后再次执行会无限传递scroll事件

### ISSUE THREAD

**Issue by cys375338985** [ustbhuangyi/better-scroll#596]
### Version
1.12.0

### Reproduction link
[https://github.com/cys375338985/better-scroll-test](https://github.com/cys375338985/better-scroll-test)

### Steps to reproduce
进入页面后，下拉操作，等数据加载完成后，再次执行下拉操作。

### What is expected?
第二次执行下拉操作，可以顺利加载数据 

### What is actually happening?
程序停在了下拉操作的过程中

---
不要问我为什么不使用vue

**Comment by ustbhuangyi** [comment]
https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/api-specific.html#finishpulldown
这个方法你调用了？

**Comment by cys375338985** [comment]
没有。。。
