### ISSUE TITLE
better-scroll在PC端的问题

### ISSUE THREAD

**Issue by lkoma** [ustbhuangyi/better-scroll#598]
version： 1.12.0
PC端
     我在vue中用better-scroll做竖屏全屏滚动。
     问题：
          鼠标稍微一滚动就翻页，如果鼠标一下滚的距离多的话，就不能到达正确的页面。
     期望： 
          鼠标滚动一定幅度之后，才触发滚动，而不是在鼠标滚动开始时就触发滚动。
有什么办法能解决吗？

**Comment by ustbhuangyi** [comment]
你是要这种效果？https://ustbhuangyi.github.io/better-scroll/#/examples/full-page-vertical-slide/en

**Comment by lkoma** [comment]
是这个效果，但是这个demo是移动端的，我在移动端也是没有问题的，如果在PC端的话，鼠标稍微滚动的快，页面就不能正确的显示

**Comment by xiaohelang** [comment]
better-scroll能支持放大缩小吗？

**Comment by xg-qd** [comment]
better-scroll 内置了PC端滚轮滚动吗？

**Comment by runjen** [comment]
我用最新版本的better-scroll 依旧出现pc端不能滚动的事情

**Comment by long-woo** [comment]
我也有同样问题

**Comment by Yxjhasadream** [comment]
> 我用最新版本的better-scroll 依旧出现pc端不能滚动的事情

你可能要设置一下属性。
scrollbar: {
                        fade: false,
                        interactive: true // 1.8.0 新增
                    },
                    mouseWheel: {
                        speed: 20,
                        invert: false,
                        easeTime: 300
                    },
                    bindToWrapper: true,
                    //disableTouch: true,
                    disableMouse:true // 感觉better-scroll的文档描述有问题，应该是源码弄错了，把禁用touch和禁用鼠标搞反了。 禁用了鼠标反而把touch功能给禁了。禁用了touch仍然可以在PC页上直接拖动。

**Comment by cccnoob** [comment]
2.0  插件  scrollbar 在pc chrome上，容器高度发生变化，滚动条长度不能够自动更新。需要手动 refresh()

**Comment by zibuyu1** [comment]
better-scroll影响第三方组件库样式怎么办

**Comment by cmazxy** [comment]
> > 我用最新版本的better-scroll 依旧出现pc端不能滚动的事情
> 
> 你可能要设置一下属性。
> scrollbar: {
> fade: false,
> interactive: true // 1.8.0 新增
> },
> mouseWheel: {
> speed: 20,
> invert: false,
> easeTime: 300
> },
> bindToWrapper: true,
> //disableTouch: true,
> disableMouse:true // 感觉better-scroll的文档描述有问题，应该是源码弄错了，把禁用touch和禁用鼠标搞反了。 禁用了鼠标反而把touch功能给禁了。禁用了touch仍然可以在PC页上直接拖动。

的确是弄反了

**Comment by theniceangel** [comment]
fixed it v2.0.0

**Comment by ddzy** [comment]
> > fixed it v2.0.0
> 
> v2.3.1 LZ所说的问题仍然存在，具体可以试一下这个例子：[vertical-scroll](https://github.com/ustbhuangyi/better-scroll/blob/dev/packages/examples/vue/components/mouse-wheel/vertical-scroll.vue)
> 
> **问题：** 滚动前 ![image](https://user-images.githubusercontent.com/9698418/121144541-a8ded400-c870-11eb-88e2-dd72029766f4.png)
> 
> 滚动后（滚轮向下滚动一下） ![image](https://user-images.githubusercontent.com/9698418/121144623-bc8a3a80-c870-11eb-8273-71bd2721a591.png)
> 
> 可以看到，**鼠标滚动一次，页面滚动了5行**。
> 
> chrome：大约250px firefox：大约100px IE：大约450px
> 
> **诉求：** 可以控制滚轮的单位滚动距离，但是通过现有文档提供的`speed`还是不起作用。 https://better-scroll.github.io/docs/zh-CN/plugins/mouse-wheel.html#speed

2.4.2 同样的问题，Chrome 下设置步长也不起作用，Firefox 正常
