### ISSUE TITLE
使用better-scroll影响@click

### ISSUE THREAD

**Issue by vmto** [ustbhuangyi/better-scroll#6]
使用better-scroll影响Vue2.0的点击事件@click：
问题：scroll容器内的点击事件，在使用了this.$nextTick()的情况下，第1次点击执行1次，第2次点击执行2次，第3次点击执行3次...

加上如下代码：
if(event._constructed){
    return;
};
PC端正常，手机端直接失效了。。。

**Comment by ustbhuangyi** [comment]
应该是 !event._constructed 的条件 return

**Comment by TerrenceFong** [comment]
@vmto 我加了如下代码就可以了
`if (!event._constructed && !event.forwardedTouchEvent) {
	return
}`
按照作者的那种写法就不行

**Comment by lemontree2000** [comment]
@ustbhuangyi   我也遇到了类似的情况  ，每点一次会以两倍触发 。我的手机和chrome都会有这个现象。

![bscroll](https://cloud.githubusercontent.com/assets/21957062/24040039/4de08962-0b42-11e7-8cf4-78b7c597886b.gif)

图上 ，三个层都用了 插件。

**Comment by gaoshijun1993** [comment]
遇到了 同@lemontree2000 一样的情况

**Comment by lemontree2000** [comment]
@gaoshijun1993 我后面找到了问题 ，因为每次都是new Bscroll.    正确的是如果已经初始化了better-scroll， 那下次就刷新一下better-scroll就好了。
