### ISSUE TITLE
无论我怎么验证，scroll事件返回的位置pos对象返回两次

### ISSUE THREAD

**Issue by thomasyc** [ustbhuangyi/better-scroll#60]
![screenshot 2017-05-09_19-07-42](https://cloud.githubusercontent.com/assets/24216880/25847955/de32c49a-34ea-11e7-938c-13c63a7ac13a.png)
![screenshot 2017-05-09_19-09-15](https://cloud.githubusercontent.com/assets/24216880/25847987/03a8ecc2-34eb-11e7-9a09-bb10a7be0fec.png)
请及时修复

**Comment by ustbhuangyi** [comment]
你这个只是派发了 2 次事件，位置相同而已，并没有什么问题啊。如果按你说的派发 2 次事件，那应该每个位置都应该出现 2 次

**Comment by thomasyc** [comment]
@ustbhuangyi 问题我只是需要它出现一次，然后用来做下拉下载更多的功能！

**Comment by ustbhuangyi** [comment]
监听 scroll 滚动事件，当 scroll.y < scroll.maxScrollY 的时候，表示 scroll 滚动到底部 ,上拉加载就是根据这个原理实现。这个 scroll 滚动事件派发的本身是没有任何问题的。
