### ISSUE TITLE
删除数据的时候会导致滚动失效

### ISSUE THREAD

**Issue by zangxx66** [ustbhuangyi/better-scroll#602]
### Version
1.12.0

### Reproduction link
[https://codepen.io/anon/pen/WKNZoW](https://codepen.io/anon/pen/WKNZoW)

### Steps to reproduce
push数组的时候正常，删除数据元素之后滚动失效，即使maxScrollY是一个很大的负数

### What is expected?
删除数组元素后应该保持滚动效果，只是maxScrollY值变大

### What is actually happening?
删除数据元素之后滚动失效，即使maxScrollY是一个很大的负数

**Comment by ustbhuangyi** [comment]
你提供的 codepen 例子跑不起来
