### ISSUE TITLE
Clicking on an item in a wheel doesn't work if wheel item has extra classes

### ISSUE THREAD

**Issue by dlee** [ustbhuangyi/better-scroll#607]
### Version
1.12.0

### Reproduction link
[https://codesandbox.io/s/mq3214nkmy](https://codesandbox.io/s/mq3214nkmy)

### Steps to reproduce
Add an extra class to a wheel item besides the one used for `wheelItemClass`.

If you click on that wheel item, the wheel will NOT select it.

### What is expected?
Clicking on a wheel item should select it.

### What is actually happening?
Click on a wheel item does not select it.

---
I believe the bug is located here:
https://github.com/ustbhuangyi/better-scroll/blob/master/src/scroll/core.js#L600

There's also another place in the code where class inclusion is wrongly implemented:
https://github.com/ustbhuangyi/better-scroll/blob/master/src/scroll/core.js#L344

**Comment by ustbhuangyi** [comment]
OK，it's  a bug，I'll fix it.

**Comment by ustbhuangyi** [comment]
Fix in v1.12.5
