### ISSUE TITLE
横向滚动，立即点击router-link无效，需要等待一段时间点击才可以，比较明显

### ISSUE THREAD

**Issue by asiareal** [ustbhuangyi/better-scroll#609]
# 版本：
"better-scroll": "^1.12.4"
"vue": "^2.5.2",
"vue-router": "^3.0.1"
# 页面布局
![image](https://user-images.githubusercontent.com/26968189/42733876-5db9f9ec-886c-11e8-94c2-da76792b2be1.png)

**Comment by ustbhuangyi** [comment]
滚动结束才允许点击，就是这么设计的
