### ISSUE TITLE
手机端，使用Bscroll后，内层ul的子元素 hover active 状态背景颜色更改失效了

### ISSUE THREAD

**Issue by Stonehsong** [ustbhuangyi/better-scroll#61]
如题，手机端，使用Bscroll后，内层ul的子元素 hover active 状态背景颜色更改失效了，点击某个有 active 或者 hover 状态的子元素，不再看到CSS状态改变。
有什么解决办法吗？

**Comment by ustbhuangyi** [comment]
因为 better-scroll 会 preventDefault，所以 acitve 的实现需要配合 js 动态添加 class 来实现了
