### ISSUE TITLE
切换路由的瞬间，垂直滚动，就会出现滚动高度计算错误（为前一个页面可滚动高度）

### ISSUE THREAD

**Issue by asiareal** [ustbhuangyi/better-scroll#610]
# 版本：
"better-scroll": "^1.12.4"
"vue": "^2.5.2",
"vue-router": "^3.0.1"
# 页面布局
![image](https://user-images.githubusercontent.com/26968189/42733876-5db9f9ec-886c-11e8-94c2-da76792b2be1.png)
上面为固定菜单按钮，点击切换路由，下面内容动态变化。
手动触发refresh()依旧无效

**Comment by ustbhuangyi** [comment]
请按 issue 规范最小化复现问题，而不要直接拿你的代码
