### ISSUE TITLE
触屏电脑点击事件无响应

### ISSUE THREAD

**Issue by kakanjau** [ustbhuangyi/better-scroll#613]
### Version
1.12.0

### Reproduction link
[http://m.ppsport.com](http://m.ppsport.com)

### Steps to reproduce
1. 使用支持触屏的电脑，比如surface pro。
2. 访问 m.ppsport.com
3. 点击 首页任意链接

### What is expected?
点击链接后，页面跳转

### What is actually happening?
点击无响应

---
问题原因在于对touch支持的判断代码：
var hasTouch = inBrowser && ('ontouchstart' in window || isWeChatDevTools);
这里判断支持touch之后，就不在支持mouse行为：

在触屏电脑上，会导致用户采用鼠标操作的方式点击时，无法触发事件

**Comment by ustbhuangyi** [comment]
你可以传入 disableMouse: false

**Comment by aaawhz** [comment]
@ustbhuangyi   your eyes  Squint into a line

**Comment by YufJi** [comment]
同时需要传入 click: true
