### ISSUE TITLE
keepAlive情况下，滚动区内包含<router-link to="/my">时，跳转到my页面再返回时,滚动区会回到顶部

### ISSUE THREAD

**Issue by csdudu** [ustbhuangyi/better-scroll#615]
### Version
1.12.0

### Reproduction link
[http://demo.jyg.cn/dist/#/shop](http://demo.jyg.cn/dist/#/shop)

### Steps to reproduce
1、当滚动区内含有<router-link to="/my"></router-link>时，点击滚动区内、外的任意my链接，再返回时，此滚动区会回到顶部(无法记住滚动位置）。
2、当把<router-link>改为<div @click="linkto("/my")></div>，用函数方式触发链接时，再返回本页时，滚动区可以保持原滚动位置。
3、只会影响滚动区中那一个链接（点击后无法返回原滚动位置），点别的链接，都能保持滚动位置。如果把滚动区中的my链接换成别的链接，换成哪个，就影响哪个。

综上，因此怀疑是bug。我用的是vue-cli 3.0。

### What is expected?
希望在keepAlive的组件中，跳出后再返回时，能保持原来的滚动位置。

### What is actually happening?
上文描述情况时，未能保持滚动位置。

**Comment by ustbhuangyi** [comment]
请按 issue 规范最小化复现问题，同时要提供 demo 的源码
