### ISSUE TITLE
scroll区域文字模糊

### ISSUE THREAD

**Issue by piexl** [ustbhuangyi/better-scroll#616]
### Version
1.12.0

### Reproduction link
[https://codepen.io/piexl-the-selector/full/QBKYQN/](https://codepen.io/piexl-the-selector/full/QBKYQN/)

### Steps to reproduce
浏览器chrome 67，手机模拟器

"scroll-wrapper"直接子元素加"transform: translate(0px, 0px) scale(1) translateZ(0px);"导致滚动区域模糊，
去掉transform这个行里样式就不模糊了

### What is expected?
滚动区域的内容文字不模糊

### What is actually happening?
滚动区域的内容文字模糊

**Comment by ustbhuangyi** [comment]
奇怪，并没有感觉到模糊呀

**Comment by piexl** [comment]
打扰了，是我本地调试的模拟器设置显示95%导致的。
谢谢啦！

**Comment by fantasy525** [comment]
@piexl 我的比例正确也模糊，怎么回事，在pad上
