### ISSUE TITLE
[New Feature] 支持编程式的启用下拉刷新

### ISSUE THREAD

**Issue by likyh** [ustbhuangyi/better-scroll#617]
### What problem does this feature solve?
better-scroll 目前没有那种立刻进行下拉刷新的函数，比如说我有一个按钮，按一下想进行下拉刷新。
或者我刚进入某一个页面的时候，就像自动开始下拉刷新（无法单独做一个加载中的样式，因为刚打开页面可能是有内容的。）

### What does the proposed API look like?
startPullDown
调用即滚动到顶部并进行下拉刷新

**Comment by ustbhuangyi** [comment]
从需求的角度来看，我理解下拉刷新的目的是一种通过下拉的交互行为达到刷新的目的（通常会去服务端请求信数据）。那么如果你已经是点击按钮（本身也是一种交互行为），那么直接去刷新就好了，完全没必要再去模拟一次什么下拉的动作，只会多此一举。
