### ISSUE TITLE
在华为pad中滚动区域文字稍微模糊，不用bs的地方文字不会模糊

### ISSUE THREAD

**Issue by fantasy525** [ustbhuangyi/better-scroll#618]
### Version
1.11.1

### Reproduction link
[https://codesandbox.io/s/j24x0m7nnw](https://codesandbox.io/s/j24x0m7nnw)

### Steps to reproduce
我们使用的是华为pad, 分辨率1920*1080，dpr=1.5,使用bs的区域文字有模糊，不适用的未模糊，去掉translateZ(0px)就不模糊了，这怎么办

### What is expected?
文字不模糊

### What is actually happening?
文字模糊

**Comment by ustbhuangyi** [comment]
那你可以根据 ua，初始化 better-scroll 的时候配置参数不同即可：
https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#hwcompositing
