### ISSUE TITLE
scrollEnd not triggered by mousewheel when quickly scrolling to the end

### ISSUE THREAD

**Issue by vcomeau** [ustbhuangyi/better-scroll#619]
### Version
1.12.0

### Reproduction link
[https://codepen.io/vcomeau/pen/MBEWeR](https://codepen.io/vcomeau/pen/MBEWeR)

### Steps to reproduce
Set up a simple better scroll with mouseWheel set to true and a console log in the scrollEnd event.
It's easier to reproduce if the scrollable area is small.
Scroll down to the bottom quickly or in one stroke.
Notice that scrollEnd is not triggered. It is triggered if the new mousewheel ease has time to fully complete.

### What is expected?
The scrollEnd event should be triggered.

### What is actually happening?
scrollEnd is not being triggered because there is an ease time and the transition was not completed.

**Comment by ustbhuangyi** [comment]
v1.12.6 has fixed this bug.
