### ISSUE TITLE
另类需求：下拉加载 加载

### ISSUE THREAD

**Issue by hasbug** [ustbhuangyi/better-scroll#622]
### What problem does this feature solve?
下拉刷新完成事件finishPullDown会触发反弹到最顶，但是我是用来下拉加载历史内容到顶部，希望scroll保持当前位置，用户再自己下拉看已经加载到顶部的数据，大家有没有新的思路？

我目前的做法：

定义2个变量，
1。下拉加载前存储最大Y值，
2.下拉结束后（finishPullDown），在scroll刷新的时候存储最新Y值。

然后通过scrollTo滚动到两者的差值，虽然能实现我想要的结果，但过程不是很好看，因为finishPullDown会先将scroll弹到最顶，然后我scrollTo再刷下来，页面上上下下，有点尴尬。

### What does the proposed API look like?
finishPullDown

**Comment by lb091188** [comment]
不要用 finishPullDown， 自己根据页面的参数（最大高度）和当前的位置（scroll事件）来实现一个吧，查看历史消息，如果不是网速过于慢的情况下应该是不需要下拉刷新那种效果的，个人看法
