### ISSUE TITLE
Mobile end pages cannot slide（移动端页面整体不能滑动了 如果只是个轮播图，下面有还有很多内容的时候，往下滑不动了）

### ISSUE THREAD

**Issue by zhaozhinan** [ustbhuangyi/better-scroll#625]
### Version
1.12.0

### Reproduction link
[https://shop.evente.cn/100013](https://shop.evente.cn/100013)

### Steps to reproduce
问题复现步骤：手机上按住轮播图，上下滑动；
问题说明：页面很长的时候 在轮播图上往下滑动的时候 滑不动了，整个页面显得就只有一屏了，‘Link to minimal reproduction’这里提供了链接。
看您提供的demo也是有这样的问题的，如把body标签的高度设置到很高，在组件上滑动页面也是不行的，可以提供下解决方案吗，如添加一个配置

### What is expected?
hope to be solved

### What is actually happening?
（page sliding problem）
手机上按住轮播图，上下滑动 页面不能滑动了，
看您提供的demo也是有这样的问题的，如把body标签的高度设置到很高，滑动组件也是不能滑动的

**Comment by ustbhuangyi** [comment]
请按 issue 规范提供最小化复现的 demo 链接，并附相关代码

**Comment by zhaozhinan** [comment]
写了呀 
Reproduction link
https://shop.evente.cn/100013

代码：
this.slider = new BScroll(this.$refs.swiper, {
          scrollX: true,
          scrollY: false,
          momentum: false,
          snap: {
            loop: this.loop,
            threshold: 0.3,
            speed: 400,
          },
          click: true,
});

**Comment by ustbhuangyi** [comment]
这种链接是不 ok 的，需要最小化复现问题的链接，另外我可以去编辑其中的代码，用 codesandbox、codepen 这些工具都可以，或者是提供一个 Github repo

**Comment by zhaozhinan** [comment]
https://github.com/ustbhuangyi/better-scroll
安装后本地地址：http://localhost:8081/#/examples/full-page-slide/en
测试环境：手机或浏览器上的移动端模拟器
复现步骤：把body设置一个高度，如 3000px

这样可以吗？？

**Comment by ustbhuangyi** [comment]
你的需求就是保持在垂直方向上的原生滚动吧，配置 eventPassthrough: 'vertical' 即可
