### ISSUE TITLE
在better-scroll内的元素dispaly:fixed变成不是相对浏览器的？

### ISSUE THREAD

**Issue by 649579742** [ustbhuangyi/better-scroll#63]
需要在滑动到某个位置的时候导航栏一直显示在视口最上方，fixed用不了，用绝对定位的top设置成Y坐标的话惯性滑动的时候导航栏会一直抖动，请问有什么好的方法解决吗？

**Comment by 649579742** [comment]
fixed会变成和绝对定位一样，页面继续往下滑动的时候，导航栏无法一直定位在浏览器最上面了

**Comment by 649579742** [comment]
查了资料有说transfrom会影响fixed，不知道为什么没法做的跟通讯录一样使元素绝对定位在最上方。。我看了css几乎没什么区别。。。

**Comment by ustbhuangyi** [comment]
推荐你去看一下这个教学视频：http://coding.imooc.com/class/107.html，这里面会教你如何把 better-scroll 封装成 Vue 的 scroll 组件，以及如何在 scroll 组件的基础上再次封装成通讯录组件。
