### ISSUE TITLE
请教：用better-scroll用详情页的滚动，第一次打开页面不能滚动，第二次进入就正常了。

### ISSUE THREAD

**Issue by kosaskle** [ustbhuangyi/better-scroll#632]
你好，项目中发现问题，目前没有找到解决方案。

第一次进入详情页的时候不能滚动或者滚动不全（不能全部滚动到），第二次才可以正常滚动。
实例初始化的时候是在mouted，使用this.nextTick和settimeout多加点时间 都不能解决。。。
请教到底是什么原因，如何解决？

感谢：）

**Comment by ustbhuangyi** [comment]
请不要用 issue 问问题，可以加群讨论

**Comment by xiaonuonuo** [comment]
同问遇到这个问题，请问解决了吗
