### ISSUE TITLE
结合 vue keepalive 使用，在滚动未停止时切换掉路由问题。

### ISSUE THREAD

**Issue by 501468940** [ustbhuangyi/better-scroll#634]
结合 vue keepalive 使用，在滚动未停止时切换路由问题， 会一直调用 scroll 方法。当再次返回页面是，如果postionY的位置未 0 时，会时而出现不能滚动。

**Comment by ustbhuangyi** [comment]
你需要在合适的生命周期做一些销毁操作，可以参考 cube-ui scroll 组件的实现

**Comment by 501468940** [comment]
并没有合适的生命周期可以销毁，我使用了 cube-ui scroll 也一样的。  keep-alive 在路由跳转的时候好像没有触发任何的生命周期钩子。

**Comment by 501468940** [comment]
重新看了 vue 文档， keep-alive 有钩子函数。activated
