### ISSUE TITLE
[New Feature] make INDICATOR_MIN_LEN optional

### ISSUE THREAD

**Issue by ccpu** [ustbhuangyi/better-scroll#641]
### What problem does this feature solve?
"INDICATOR_MIN_LEN" is not available in options, is there any specific reason?
The current value '8' is too small, I did try different value and it works fine. so why not have it as an option!

### What does the proposed API look like?
for example; introduce an option under the scrollbar options:
```
   scrollbar: {
      fade: true,
      interactive: false,
      indicatorMinHeight: 8
  }
```

and replace 'INDICATOR_MIN_LEN' with  this.options.scrollbar.indicatorMinHeight

**Comment by theniceangel** [comment]
refactor at v2.2.0
