### ISSUE TITLE
滚动 iframe，无法触发 better-scroll 滚动

### ISSUE THREAD

**Issue by vince-fly** [ustbhuangyi/better-scroll#642]
在移动端，iframe加载https://www.youtube.com 下的视频，滚动失效了。页面卡住。只有在触动iframe外部，才能滚动。
原生滚动的话，是可以正常的。

**Comment by vince-fly** [comment]
换成任何连接，都是不行。
包括 baidu,163，等国内站点。
现在开始考虑换成iscroll试试了。

**Comment by vince-fly** [comment]
`new BScroll('.container', {
  mouseWheel: true,
  scrollX: false,
  scrollbar: {
    fade: true,
    interactive: false
  },
  probeType: 3,
  click: true,
  tap:true  
});`
把代码粘出来，是我使用方法不对吗?

**Comment by nicoleWong007** [comment]
@vince-fly 我碰到了同样的问题

**Comment by never615** [comment]
+1

**Comment by never615** [comment]
楼主找到解决办法了吗?

**Comment by qinouz** [comment]
遇到同样问题 +1

**Comment by theniceangel** [comment]
eventPassthrough属性。

**Comment by zenghj** [comment]
@theniceangel 按照文档 [eventpassthrough](https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#eventpassthrough)中的描述，使用eventpassthrough实际上就是在该方向上不使用better-scroll 模拟的滚动，我遇到的问题现象是，我在页面纵向使用better-scroll 模拟滚动，恰好页面内有一个iframe（比如一个google广告位iframe或者上面提到的youtube视频iframe），这时手指触在iframe内容区进行上滑或者下滑,会出现页面无法上下滚动的现象，手指触在iframe内容区外则是可以的。    @vince-fly 描述的应该也是这种现象。使用  eventpassthrough 是没办法解决的，因为本身在纵向就是希望使用better-scroll 模拟滚动。。。

**Comment by zenghj** [comment]
感觉问题的关键是better-scroll的滚动原理是监听touchstart、touchmove、touchcancel、touchend等事件（见`BScroll.prototype._handleDOMEvents`）然后模拟滚动，但是如果滚动区有iframe，并且事件是触发在iframe内，这时导致this.wrapper无法监听到事件，从而无法做出响应。。。

**Comment by theniceangel** [comment]
> 感觉问题的关键是better-scroll的滚动原理是监听touchstart、touchmove、touchcancel、touchend等事件（见`BScroll.prototype._handleDOMEvents`）然后模拟滚动，但是如果滚动区有iframe，并且事件是触发在iframe内，事件无法冒泡到`this.wrapper`，这时导致`this.wrapper`无法对事件做出响应，从而无法产生滚动效果。。。

嗯。iframe 相当于是另外一个 HTML 了。这个只能自己硬编码，通过在 iframe 去计算滚动距离，然后驱动父页面的 bs 实例

**Comment by weixinfei123** [comment]
遇到同样问题 +1

**Comment by molysama** [comment]
遇到了同样的问题，wrap包着div，div内有iframe，div与iframe的高度一致并设了iframe的scrolling="no"，也做了bs的refresh。目前看来是没有触发div的滚动事件

**Comment by miss7cd** [comment]
同样的问题 + 1
