### ISSUE TITLE
初始化better-scroll的盒子发生滚动

### ISSUE THREAD

**Issue by magic-dm** [ustbhuangyi/better-scroll#647]

**Comment by magic-dm** [comment]
遇到这样一个场景：页面有上下两部分，下边的盒子里初始化了better-scroll，里边可以产生滚动，上边的盒子随着下边的盒子的滚动大小发生变化，这样导致下边的盒子位置改变了，从而下边盒子里的内容最大滚动高度就不准，导致不能触发加载下一页数据，这个问题要怎么解决？

**Comment by hasbug** [comment]
···建议定义滚动区块的高度，否则会出问题

**Comment by ustbhuangyi** [comment]
不符合 Issue 规范
