### ISSUE TITLE
双层嵌套问题

### ISSUE THREAD

**Issue by vijay19920608** [ustbhuangyi/better-scroll#648]
双层嵌套使用了stopPropagation: true，但是里面的滚动如果滚到底或者滚到顶部，触发不了最外层的滚动

**Comment by vijay19920608** [comment]
希望里层的滚动到顶部或者底部的时候，就能触发最外层的滑动，如果里面的滚动没到顶部或者底部，就只触发里层的滑动

**Comment by ustbhuangyi** [comment]
这个问题 cube-ui 已经在尝试解决方案，从 better-scroll 底层是不解决的，解决方案需要上层的封装

**Comment by vijay19920608** [comment]
有例子吗？？

**Comment by hezhongfeng** [comment]
这个的确是个问题，在cube-ui解决了的话也是棒棒哒，期待

**Comment by dolymood** [comment]
cube-ui 在 1.12 的版本中加入了 Scroll 组件的 nestMode 用于控制这种交互行为，欢迎体验。
