### ISSUE TITLE
new BScroll 实例化过早,即使是Ajax数据之后再实例化同样提前了。导致滚动不底部，但刷新之后就可以了

### ISSUE THREAD

**Issue by thomasyc** [ustbhuangyi/better-scroll#65]
![screenshot 2017-06-06_15-56-53](https://cloud.githubusercontent.com/assets/24216880/26819287/cec02d30-4ad0-11e7-9562-5a054903c223.png)
![screenshot 2017-06-06_15-57-01](https://cloud.githubusercontent.com/assets/24216880/26819288/cef023aa-4ad0-11e7-87dd-42d60f86128c.png)
在我家里setTimeout之后，延迟实例化到时可以。

**Comment by thomasyc** [comment]
请问是个BUG吗？

**Comment by ustbhuangyi** [comment]
你初始化的时机不对，建议看一篇文章:https://github.com/DDFE/DDFE-blog/issues/15
