### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL> 吗，chrome内部限制了，库可以兼容处理一下吗

### ISSUE THREAD

**Issue by dirkhe1051931999** [ustbhuangyi/better-scroll#654]

**Comment by dirkhe1051931999** [comment]
在touch的事件监听方法上绑定第三个参数{ passive: false }，
通过传递 passive 为 false 来明确告诉浏览器：事件处理程序调用 preventDefault 来阻止默认滑动行为。

**Comment by ustbhuangyi** [comment]
https://github.com/ustbhuangyi/better-scroll/blob/master/src/util/dom.js#L42-L48
已经这么处理了
