### ISSUE TITLE
在momentum模式下使用scrollTo实现瞬间跳转时，会出现异常回弹（多次快速滑动时出现）

### ISSUE THREAD

**Issue by Mrsususu** [ustbhuangyi/better-scroll#655]
### Version
1.12.0

### Reproduction link
[https://codepen.io/Mrsusu/pen/yxvBzE](https://codepen.io/Mrsusu/pen/yxvBzE)

### Steps to reproduce
在实现一个移动端单列无限循环滚动需求（需要带有momentum效果）时遇到了以下问题：demo中多次快速上滑或者在一些临界位置上滑时，会出现一段向反方向回弹的异常。  
也就是说在momentum动画进行的情况下，使用scrollTo函数进行瞬间跳转，会出现一段计算紊乱。  
猜测是由于momentum动画和scrollTo函数同时执行时，偶尔会出现startY没有及时更新的问题。

### What is expected?
在开启momentum的情况下，使用scrollTo函数瞬间跳转后依然能继续之前的滚动动画效果而不会出现异常的回弹。

### What is actually happening?
出现一段向反方向回弹的异常

**Comment by ustbhuangyi** [comment]
竖向循环滚动建议使用 snap 去实现
