### ISSUE TITLE
页面切换后当前页面无法实现滚动

### ISSUE THREAD

**Issue by gyt95** [ustbhuangyi/better-scroll#66]
父组件点击按钮，子组件右侧滑出，但是无法下拉滚动。
通过opacity透明度设置，发现父组件在滚动，子组件无法滚动，如何解决

下面是子组件的show()中的代码

show(){
this.showFlag = true;
this.$nextTick(() => {
                    if (!this.scroll) {
                        this.scroll = new BScroll(this.$el, {
                            click: true,
                            scrollY: true
                        });
                    } else {
                        this.scroll.refresh();
                    }
                });
}

**Comment by ustbhuangyi** [comment]
不符合提 issue 规范
