### ISSUE TITLE
wheel-item的rotateX计算错误可能的原因请教

### ISSUE THREAD

**Issue by AlbertKnag** [ustbhuangyi/better-scroll#660]
### Version
1.12.0

### Steps to reproduce
偶发情况下，Picker组件wheel-item的rotateX计算错误(比如就5条数据，选中的计算为-100，最下面的一条为0，造成选中的那一条显示效果特别窄，看不清)。想请教一下，什么情况下会出现这种情况。目前有两列数据，第一列的数据是正常的，就第二列的数据显示有问题，用手滑一下就能修复这个问题。另外，偶尔还会出现wheel.selectedIndex的值为NaN，百思不得其解，尝试了各种方式都没办法稳定复现（比如调慢时间选择框的上移速度等）。想问问可能的原因是怎么样的，不胜感激！

### What is expected?
期望为正常显示

### What is actually happening?
显示异常

**Comment by AlbertKnag** [comment]
分析了一下原因，调用wheel.wheelTo方法时出现了问题，弹出框从下网上弹出，执行wheelTo方法时位置计算出现了问题，调用后再调用wheel.refresh()也无法修复rotateX计算错误问题。最终使用setTimeout(() => wheel.wheelTo(num || 0), 100)来处理该问题，目前看来复现几率小很多了

**Comment by tangtangtangtangtang** [comment]
这为仁兄的issues真是救了我一命，我也是这个问题setTimeout一下就好了。面向巧合编程啊，呵呵😄

**Comment by AlbertKnag** [comment]
> 这为仁兄的issues真是救了我一命，我也是这个问题setTimeout一下就好了。面向巧合编程啊，呵呵😄

哈哈哈，我也是折腾了好久才想到这种骚操作的！~
