### ISSUE TITLE
[New Feature] 能考虑加一个pullDownLoad选项吗？

### ISSUE THREAD

**Issue by readyou** [ustbhuangyi/better-scroll#661]
### What problem does this feature solve?
有些场景，消息是从中间某个地方加载的，需要上滑刷新和下滑刷新，现在只有下拉刷新（需要开启bounce）和上滑刷新。如果能有个和pullUpLoad相对应的pullDownLoad选项就好了

### What does the proposed API look like?
和pullUpLoad相对应的pullDownLoad

**Comment by theniceangel** [comment]
请提供场景
