### ISSUE TITLE
windows pc 微信打开h5页面,无法滚动,其他浏览器没有问题?

### ISSUE THREAD

**Issue by gaoyixiao2** [ustbhuangyi/better-scroll#666]
如题,window 微信端打开网页的时候,它不是用默认浏览器打开,用了内置的浏览器打开;
拖动鼠标,好像没有触摸滚动,鼠标滚动的时候,好像处于选择文本状态;
demo中的滚动也不起作用,不知道有没有遇到同样问题的,希望能得到回复啊?

**Comment by HiramYong** [comment]
我也碰到这种问题，微信中h5界面，无法滚动，正在找解决方案，谷歌测试正常

**Comment by theniceangel** [comment]
请提供复现的demo
