### ISSUE TITLE
怎么判断滚条滚动到最底

### ISSUE THREAD

**Issue by venkenwj** [ustbhuangyi/better-scroll#67]
scrollEnd事件是每次滚条结束就会触发，现在我想滚条结束且是要滚动到最下面才刷新数据，请大神指点。。

**Comment by zangse** [comment]
我也是小白
我是这样判断的，不知道对不对
我判断的是当他来到最底，然后再下拉100px,就去请求刷新
`wrapper.on('scroll', () => {
                    if (wrapper.y < wrapper.maxScrollY - 100) {
                        console.log('下拉到底了---')
                      dosomething();
                    }
                });`

**Comment by venkenwj** [comment]
谢谢，我现在也是这么做的

**Comment by ustbhuangyi** [comment]
可以参考这篇文章，https://github.com/DDFE/DDFE-blog/issues/15
