### ISSUE TITLE
在安卓5.1上出现“Uncaught SyntaxError: Unexpected token =”错误

### ISSUE THREAD

**Issue by sakuraLili** [ustbhuangyi/better-scroll#670]
我使用的是Vue框架：
"vue": "^2.5.17",
"vue-router": "^3.0.1",
"vuex": "^3.0.1",

在APP开发中，其他安卓机型没有问题。但是在安卓5.1上出现“Uncaught SyntaxError: Unexpected token =”错误

**Comment by ustbhuangyi** [comment]
先自己排查一下错误的位置吧
