### ISSUE TITLE
哪位帮忙看看，添加了scroll事件，但是不起作用

### ISSUE THREAD

**Issue by bihongbin3027** [ustbhuangyi/better-scroll#671]
![image](https://user-images.githubusercontent.com/15045200/46073978-eed6d500-c1b8-11e8-9429-9a7bfdb2157d.png)

probeType已经赋值为3，已经进入了if(this.props.scroll)语句，并且执行了事件的绑定，但是不起作用

**Comment by WhatMakesPeopleLazy** [comment]
你new BScroll第一个参数是dom元素，你给字符串，你应该document.querySelector('.scroll')

**Comment by bihongbin3027** [comment]
> 你new BScroll第一个参数是dom元素，你给字符串，你应该document.querySelector('.scroll')

这样是可以用的，我去掉了eventPassthrough参数，就可以触发滚动事件了

**Comment by XinChou16** [comment]
你是在Vue哪个生命周期进行调用的？

**Comment by theniceangel** [comment]
@bihongbin3027 `eventPassthrough` 这个字段是用来控制允许原生滚动的，比如你bs是竖向滚动，`eventPassthrough` 就不能设置为 `vertical`，否则竖向滚动会失效。
