### ISSUE TITLE
滑动过程中，点击屏幕停止问题

### ISSUE THREAD

**Issue by yingshancool** [ustbhuangyi/better-scroll#674]
### Version
1.13.0

### Reproduction link
[https://jsfiddle.net/2be18vdg/](https://jsfiddle.net/2be18vdg/)

### Steps to reproduce
用vue   better-scroll 制作一款类似头条的产品时候，快速向上或下滑动过程中点击屏幕停止滑动且无法精准的停止，会出现一小小段的滑动，肉眼能看到屏幕抖动。

### What is expected?
修复这个问题

### What is actually happening?
屏幕抖动

---
  BScroll.prototype.stop = function () {
    if (this.options.useTransition && this.isInTransition) {
      this.isInTransition = false;
      cancelAnimationFrame(this.probeTimer);
      var pos = this.getComputedPosition();
      alert('xxxxxxxxxxx')
      // this._translate(pos.x, pos.y);

在编译好的文件bscroll.esm.js文件的1642行，修改成上述的代码
由于alert的阻塞，动画继续，取消动画的函数cancelAnimationFrame无效，cancelAnimationFrame使用前需要将配置 probeType 设置为3，此时有this.probeTimer的id，但是依然无法暂停动画。
导致停止不精准。
this._translate(pos.x, pos.y); 这个函数仅仅是在滑出点击停止的位置一小小段距离后，重新滑动回去。

求助！！！

**Comment by ustbhuangyi** [comment]
refer to https://github.com/ustbhuangyi/better-scroll/issues/580
