### ISSUE TITLE
[New Feature] 下拉刷新时，回弹的时机如何跟请求数据同步？

### ISSUE THREAD

**Issue by yulei521** [ustbhuangyi/better-scroll#676]
### What problem does this feature solve?
代码设置的回弹动效时间是800ms，当下拉刷新请求数据时，时间可能超过了800ms，即使我执行了this.finishPullDown这时可能出现数据还没有回来，回弹动画已经执行完了。

当时想过在下拉刷新时，通过设置回弹动效时长来让动画‘禁止’，比如设置一个特别长的回弹时间：
this.options.bounceTime = maxTime 
这时会引起其他问题。

### What does the proposed API look like?
api可以控制回弹的时机，比如当数据加载完成后才可以开始回弹。

**Comment by theniceangel** [comment]
pullDown的回弹有两次，比如你下拉了100px，会派发 pullDown 事件，紧接着会回滚到一个默认距离顶部 stop 值（40px）的状态，这是第一次回弹。这个时候你在 pullDown 请求完数据之后再调 finishPullDown，会把位置置零。这个是第二次的回弹。

**Comment by yulei521** [comment]
你说的是pullingDown吗？我在pullingDown加了异步请求，然后在请求回来的时加了finishPullDown；跟你说的情况一样。
但是有个问题，就是如果异步请求还没有回来，也会回弹到位置置零（并有没有手动调用finishPullDown）。因为bounceTime参数默认设置了800ms，超过这个时间，会自动回弹到位置零，无论请求回不回来。

**Comment by theniceangel** [comment]
如果你没有调 finishPullDown，是不会走到位置清零的逻辑，可以提供线上的 demo 以及使用的版本么

**Comment by songzeng2016** [comment]
[https://ustbhuangyi.github.io/better-scroll/#/examples/vertical-scroll/zh](url)
线上的 demo 就有这个问题，vertial-scroll.vue 组件里面经常还没走到 onPullingDown 方法的 setTimeout 里面列表就回弹到零的位置了，这个时候把列表的背景设为透明是可以看到下拉动画还在执行。

vertial-scroll.vue 组件

```
      onPullingDown() {
        // 模拟更新数据
        console.log('pulling down and load data')  // 这句执行完列表就回弹到位置零
        setTimeout(() => {
          console.log(0)  // 这一句还没执行
          if (this._isDestroyed) {
            return
          }
          if (Math.random() > 0.5) {
            // 如果有新数据
            this.items.unshift(this.$i18n.t('normalScrollListPage.newDataTxt') + +new Date())
          } else {
            // 如果没有新数据
            this.$refs.scroll.forceUpdate()
          }
        }, 2000)
      },
```

**Comment by songzeng2016** [comment]
> 如果你没有调 finishPullDown，是不会走到位置清零的逻辑，可以提供线上的 demo 以及使用的版本么

[https://ustbhuangyi.github.io/better-scroll/#/examples/vertical-scroll/zh](url)
线上的 demo 就有这个问题，vertial-scroll.vue 组件里面经常还没走到 onPullingDown 方法的 setTimeout 里面列表就回弹到零的位置了，这个时候把列表的背景设为透明是可以看到下拉动画还在执行。

vertial-scroll.vue 组件

```
      onPullingDown() {
        // 模拟更新数据
        console.log('pulling down and load data')  // 这句执行完列表就回弹到位置零
        setTimeout(() => {
          console.log(0)  // 这一句还没执行
          if (this._isDestroyed) {
            return
          }
          if (Math.random() > 0.5) {
            // 如果有新数据
            this.items.unshift(this.$i18n.t('normalScrollListPage.newDataTxt') + +new Date())
          } else {
            // 如果没有新数据
            this.$refs.scroll.forceUpdate()
          }
        }, 2000)
      },
```

**Comment by songzeng2016** [comment]
不知道和时间有没有关系，setTimeout 的时间设成 500 就没出现这个问题

**Comment by songzeng2016** [comment]
非常神奇的问题，昨天在家用 mac 线上 demo 和我本地跑的基本每次都有问题，今天在公司用 windows 又都没问题了。
