### ISSUE TITLE
请问如何调节滑动的灵敏度？

### ISSUE THREAD

**Issue by meidongwei** [ustbhuangyi/better-scroll#679]
在做一个点菜页面，手指在手机上轻轻滑动，列表会滑好多菜品，可以调灵敏度吗？想要的效果更加接近原生app，类似美团、饿了么app滑动的体验

**Comment by theniceangel** [comment]
[动量](https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#deceleration)，不过需要自己慢慢的调试
