### ISSUE TITLE
配置 eventPassthrough 为 horizontal 之后，在 ios 下垂直滚动会出现 bug

### ISSUE THREAD

**Issue by TothingWay** [ustbhuangyi/better-scroll#681]
### Version
1.13.0

### Reproduction link
[https://jsfiddle.net/vqmtg9a7/13/](https://jsfiddle.net/vqmtg9a7/13/)

### Steps to reproduce
 为了保留 elementUI table 组件默认的横向滚动，在配置 eventPassthrough 为 horizontal 之后，用力快速滑动，会和 ios 默认浏览器的边界回弹冲突。
手机直接打开页面预览效果：https://fiddle.jshell.net/vqmtg9a7/9/show/

### What is expected?
 在配置 eventPassthrough 为 horizontal 之后，保留 elementUI table 组件默认的横向滚动，同时禁用 ios 默认的边界回弹

### What is actually happening?
 为了保留 elementUI table 组件默认的横向滚动，在配置 eventPassthrough 为 horizontal 之后，用力快速滑动，会和 ios 默认浏览器的边界回弹冲突

**Comment by theniceangel** [comment]
这个属于应用层的

**Comment by AMrainman** [comment]
@TothingWay 兄弟解决了吗

**Comment by TothingWay** [comment]
@AMrainman 也不算解决，目前就是不设置 eventPassthrough 为 horizontal ，然后再使用一层 scroll 嵌套 table，达到横向滚动的目的

**Comment by AMrainman** [comment]
给要禁止回弹的div加个touchmove事件阻止默认行为，就可以了，不过也禁止了子级的滚动
