### ISSUE TITLE
Why don't scroll/event#off delete the whole array of [fn, context]

### ISSUE THREAD

**Issue by MondoGao** [ustbhuangyi/better-scroll#682]
### Version
1.13.0

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll/blob/master/src/scroll/event.js](https://github.com/ustbhuangyi/better-scroll/blob/master/src/scroll/event.js)

### Steps to reproduce
On line 31: `_events[count][0] = undefined` remove the cb, but the whole cb array is still in the memory, is there any chance that it would cause a memory leak?

### What is expected?
Maybe `_events.splice(count, 1)`

### What is actually happening?
`_events[count][0] = undefined`

**Comment by theniceangel** [comment]
It will not cause memory leak, but as you say, GC mechanism will not be triggered, we will take your advice into consideration, or you can provide a pr to optimize it.

**Comment by MondoGao** [comment]
> It will not cause memory leak, but as you say, GC mechanism will not be triggered, we will take your advice into consideration, or you can provide a pr to optimize it.

Already done, please review.

**Comment by MondoGao** [comment]
BTW, util/spliceOne is copied from nodejs/node. Maybe there is a  license issue, but I'm not familiar with this, hope you can check it before merging.
