### ISSUE TITLE
1.13.2 IOS8 不支援 會出現錯誤

### ISSUE THREAD

**Issue by MarsCaiWORD** [ustbhuangyi/better-scroll#683]
### Version
1.13.2

### Reproduction link
[https://fiddle.jshell.net/vqmtg9a7/9/show/](https://fiddle.jshell.net/vqmtg9a7/9/show/)

### Steps to reproduce
iphone5 IOS8  safari  
滾動時 不能滾動 會出現 object is undefined 錯誤
iphoneSE IOS8  safari  
滾動內容空白沒顯示

其他版本可以

### What is expected?
修復錯誤

### What is actually happening?
不能滾動

---
希望能修復

**Comment by theniceangel** [comment]
嗯，我们找个测试机重现下

**Comment by yaxunliu** [comment]
我在 iOS 9.0 的 safari 上 无法滚动，其他设备暂时没有遇见这个问题。

**Comment by zjydipingxian** [comment]
ios 8， 9 ， 10 不能滚动是什么原因？

**Comment by LKKitty** [comment]
我在ios9.3.5的 safari 上 无法滚动,请问现在有解决办法吗？

**Comment by LKKitty** [comment]
不滚动的原因已经找到，是因为ios9及以下的版本不支持es6的写法，连let都不支持，与better-scroll无关。

**Comment by MarsCaiWORD** [comment]
要不要babel 一下

**Comment by LKKitty** [comment]
问题已经解决了，非常感谢
