### ISSUE TITLE
当触发pullingDown初始化后，pullingUp事件不会被监听了....

### ISSUE THREAD

**Issue by Hideer** [ustbhuangyi/better-scroll#688]
### Version
1.13.0

### Reproduction link
[https://codesandbox.io/s/n04o7m9qr0](https://codesandbox.io/s/n04o7m9qr0)

### Steps to reproduce
当监听到时最后一页后不可上拉加载更多，然后执行下拉刷新，重置，以上逻辑都没问题，但是当重置后pullUpLoad事件则不执行了（因为我这里做了判断如果有下一页就执行数据请求方法，没有则什么都不执行，但是这个事件监听不执行了）

### What is expected?
pullingUp继续监听

### What is actually happening?
pullingUp无法监听了

**Comment by theniceangel** [comment]
不管是下拉刷新还是上拉加载完，都得调相应的finish事件去告知 bs 做完了这个动作。详细看[finishpullup](https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/api-specific.html#finishpullup)

**Comment by Hideer** [comment]
@theniceangel 非常感谢，在昨天我发布完问题后，经过尝试，找到了原因，和你说的一致，但是为啥会这样，有待进一步研究

**Comment by hongxb** [comment]
@Hideer @theniceangel 
[https://codesandbox.io/s/n04o7m9qr0](https://codesandbox.io/s/n04o7m9qr0)
上述示例中，pullingUp事件连续触发两次（相当于底部已无数据，再上拉触发了pullingUp事件），pullingUp事件就失效了

**Comment by Hideer** [comment]
@hongxb  具体是遇到什么交互是问题么？

**Comment by Hideer** [comment]
@hongxb 我翻阅了之前的demo发现确实存在这个问题，请你你发现了什么么

**Comment by shady-xia** [comment]
我也遇到了这个问题，上拉加载了几页数据后，手动滚到顶部，再下拉刷新，这之后再也不会监听到上拉加载事件了

**Comment by yangmeijuan** [comment]
> @theniceangel 非常感谢，在昨天我发布完问题后，经过尝试，找到了原因，和你说的一致，但是为啥会这样，有待进一步研究

 请问如何解决的 哭哭 解决了一天还没好

**Comment by yangmeijuan** [comment]
> 我也遇到了这个问题，上拉加载了几页数据后，手动滚到顶部，再下拉刷新，这之后再也不会监听到上拉加载事件了

请问如何解决

**Comment by shady-xia** [comment]
> > 我也遇到了这个问题，上拉加载了几页数据后，手动滚到顶部，再下拉刷新，这之后再也不会监听到上拉加载事件了
> 
> 请问如何解决

我是这样解决的：每次pullingDown回调完后，手动destroy，然后再重新new BScroll，重新监听

**Comment by yangmeijuan** [comment]
好的 谢谢小哥哥 万分感谢




------------------ 原始邮件 ------------------
发件人: "Shady"<notifications@github.com>;
发送时间: 2019年8月16日(星期五) 上午9:10
收件人: "ustbhuangyi/better-scroll"<better-scroll@noreply.github.com>;
抄送: "吃饱了还能次"<842277831@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ustbhuangyi/better-scroll] 当触发pullingDown初始化后，pullingUp事件不会被监听了.... (#688)



  
我也遇到了这个问题，上拉加载了几页数据后，手动滚到顶部，再下拉刷新，这之后再也不会监听到上拉加载事件了
  
请问如何解决
  
我是这样解决的：每次pullingDown回调完后，手动destroy，然后再重新new BScroll，重新监听

**Comment by guobing1993** [comment]
> > > 我也遇到了这个问题，上拉加载了几页数据后，手动滚到顶部，再下拉刷新，这之后再也不会监听到上拉加载事件了
> > 
> > 
> > 请问如何解决
> 
> 我是这样解决的：每次pullingDown回调完后，手动destroy，然后再重新new BScroll，重新监听

这个太暴力了吧

**Comment by guobing1993** [comment]
![image](https://user-images.githubusercontent.com/22333388/64100018-44d6d400-cd9d-11e9-9e31-69cb77cc7b32.png)
所以在判断已经不可以加载更多时，不能立即去finishPullUp,在vue里$nextTick一下就ok了。

或者在pulldown之后openPullUp()就好了

**Comment by shady-xia** [comment]
> ![image](https://user-images.githubusercontent.com/22333388/64100018-44d6d400-cd9d-11e9-9e31-69cb77cc7b32.png)
> 所以在判断已经不可以加载更多时，不能立即去finishPullUp,在vue里$nextTick一下就ok了。
> 
> 或者在pulldown之后openPullUp()就好了

原来如此，感谢！
