### ISSUE TITLE
下拉刷新回弹动画和下拉时间见处理有问题，造成快速下拉动画抖动以及卡顿的问题

### ISSUE THREAD

**Issue by Hideer** [ustbhuangyi/better-scroll#691]
### Version
1.13.0

### Reproduction link
[https://ustbhuangyi.github.io/better-scroll/#/examples/vertical-scroll/en](https://ustbhuangyi.github.io/better-scroll/#/examples/vertical-scroll/en)

### Steps to reproduce
如题;
可以使用官方demo进行复现，当进行下拉刷新动作的时候，当回弹动画未结束的时候再次进行下拉刷新事件操作，会导致动画混乱（如，无回弹效果，以及接下来的几次回弹时间异常）建议：将下拉事件是否生效和动画结束的阀门绑定，放置，动画未结束，下拉事件再次触发，将上一个动画强制重置！

### What is expected?
回弹动画优雅

### What is actually happening?
快速下拉回弹动画不流畅

**Comment by ZHENGGEGE** [comment]
您好，这个问题是怎样解决的
