### ISSUE TITLE
[New Feature] 建议

### ISSUE THREAD

**Issue by enyyongyang** [ustbhuangyi/better-scroll#694]
### What problem does this feature solve?
1.better-scroll  还是有js 版本的需要的，希望可以单独出来。
2.官方的demo 没有代码示例，需要去源代码找
3.官方的gitbook  方法函数啥的也没有示例

工作量不小

### What does the proposed API look like?
...

**Comment by dolymood** [comment]
如果你有兴趣的话，欢迎 PR
