### ISSUE TITLE
better-scroll在安卓4.4和5.0版本的手机滑动很卡顿,请问兼容安卓5.0版本一下的安卓机吗,框架用的react

### ISSUE THREAD

**Issue by lcyh** [ustbhuangyi/better-scroll#696]
better-scroll在安卓4.4和5.0版本的手机滑动很卡顿,请问兼容安卓5.0版本一下的安卓机吗,框架用的react

**Comment by theniceangel** [comment]
卡顿与手机性能有关

**Comment by lcyh** [comment]
现在做的移动端 h5商城要兼容 低版本的安卓(安卓5.0以下),better-scroll滑动很卡顿,要想兼容低版本的安卓手机,better-scroll也解决不了了吗

**Comment by theniceangel** [comment]
一个库怎么能解决手机性能的问题呢？
