### ISSUE TITLE
[New Feature] 请教一下大神，PC端，如何阻止上拉和下拉事件

### ISSUE THREAD

**Issue by pheeno** [ustbhuangyi/better-scroll#699]
### What problem does this feature solve?
觉得Better-Scroll 超赞，敢问大神，在PC端如何阻止上拉加载和下拉加载事件，由于PC端不需要上拉和下拉加载，导致在滚动到顶部或者底部时，滚动条不能马上隐藏，需要上拉和下拉操作完毕后才能隐藏，请指教，谢谢！

### What does the proposed API look like?
none

**Comment by Lstoryc** [comment]
同求 敢问如何解决？
