### ISSUE TITLE
希望能完善下文档

### ISSUE THREAD

**Issue by stackjie** [ustbhuangyi/better-scroll#70]
😊一些bscroll对象的属性似乎没有列出来, y、x、maxScrollY之类的没有列出了

**Comment by jinzaifeng** [comment]
scroll.on('touchend', function (pos) {
          if (this.maxScrollY - pos.y > 50) {
这些应该是和iscroll一样

**Comment by ustbhuangyi** [comment]
已经完善了一些，会持续更新

**Comment by 2015-lizaiyang** [comment]
文档真心写的不好，一个使用示例都没有，都不懂您这些方法去哪里调用，参数方法太凌乱，已经看不下去了，既然是工具，那么应该开箱即用。而不是堆配置方法，弱鸡根本看懂您这对配置，尤其cube-ui里scroll好乱。
