### ISSUE TITLE
动画有点奇怪，希望优化一下

### ISSUE THREAD

**Issue by joenil** [ustbhuangyi/better-scroll#701]
在iOS上测试的，轻轻一滑，到边缘后动画幅度有点过猛

**Comment by joenil** [comment]
还有滑动时，力度不是很大，也有一种动画幅度过猛的感觉

**Comment by theniceangel** [comment]
bs 暴露对应的参数，详见文档

**Comment by joenil** [comment]
`bounceTime `,`momentumLimitTime `,`momentumLimitDistance `,`swipeTime `,`swipeBounceTime `,`deceleration `,`flickLimitTime `,`flickLimitDistance `，这些都试过了，还是没法配置出像原生iOS那种回弹自然的感觉。

**Comment by joenil** [comment]
我感觉是不是算法有问题？
