### ISSUE TITLE
触摸屏 电脑 滑动无效

### ISSUE THREAD

**Issue by FeiVincent** [ustbhuangyi/better-scroll#705]
电脑支持触摸屏，但是不能触摸滑动，可以鼠标点击滑动，怎么解决？可以手指在滚动条的位置滑动，但是很难操作

**Comment by 93Alliance** [comment]
@theniceangel 如果pc端是触摸屏则，强制disableTouch 为 false也不能滑动是吗？目前我测试是这样

**Comment by 93Alliance** [comment]
IScroll 我确信是可以的
