### ISSUE TITLE
[New Feature] 支持 Code-Splitting 吗？

### ISSUE THREAD

**Issue by jiankafei** [ustbhuangyi/better-scroll#713]
### What problem does this feature solve?
移动端使用，减小包的大小，仅使用需要的功能

### What does the proposed API look like?
把其他模块独立出来，通过 use 的方式来使用，就像 swiper 的使用方法一样。

**Comment by dolymood** [comment]
目前还不支持，不过未来准备重构开发 2.x 版本，会支持插件的方式。

**Comment by jiankafei** [comment]
了解

**Comment by jiankafei** [comment]
希望把scroller滚动核心还有手势滚动独立出来，然后在其之上开发 pullup pulldone infinity swiper 等插件效果。不知道什么时候能出来，这样的话，better-scroll 会不会变成一个 scroll 效果平台？

**Comment by theniceangel** [comment]
fixed in v2.0.0
