### ISSUE TITLE
我发现README文档中示例图中的单词wrapper拼写有错误, 请更正

### ISSUE THREAD

**Issue by ilexwg** [ustbhuangyi/better-scroll#721]
### Version
1.13.0

### Reproduction link
[https://github.com/ilexwg/ele/blob/master/images/better-scroll.png](https://github.com/ilexwg/ele/blob/master/images/better-scroll.png)

### Steps to reproduce
我发现README文档中示例图中的单词wrapper拼写有错误, 请更正
我已经做了一张更正后的图片了, 在minimal reproduction中的地址就是图片的地址, 如果觉得合适可以采用

### What is expected?
正确拼写wrapper

### What is actually happening?
错误拼写wrpper

**Comment by ilexwg** [comment]
我不知道我修改的图片该存放到哪里比较合适 :P

HuangYi <notifications@github.com> 于2018年12月24日周一 上午9:22写道：

**Comment by ustbhuangyi** [comment]
可以放到 static 下的 image 目录里

**Comment by ilexwg** [comment]
哈哈, 已经提交啦~

**Comment by ilexwg** [comment]
> 可以放到 static 下的 image 目录里
哈哈, 已经提交啦~

**Comment by ilexwg** [comment]
> 可以放到 static 下的 image 目录里

哈哈, 已经提交啦~
