### ISSUE TITLE
对于判断滚动到达底部的运算BUG

### ISSUE THREAD

**Issue by Lukunlin** [ustbhuangyi/better-scroll#727]
在初始化配置选项里，有一个配置“pullUpLoad”的选项。
文档里面提到，如有需要，可以配置为：
pullUpLoad: true
或
pullUpLoad: {
  threshold: 50
}
可当我配置了threshold为50以后依然发现，到达了底部，甚至没达到底部，就已经触发了“pullingUp”事件的派发。

然后我就去翻源码，在项目里的 src/scroll/pullup.js 里的 第22行，即在 原型上的“_checkToEnd ”方法里对于到底底部判断，在运算上，使用“+”去加上“threshold”变量，即“pullingUp”配置里的“threshold”。
这样做，对于一个 负数 比较 负数的条件来说， 另外一个负数去加上一个正数，无疑是减小了这个负数，再去做比较。肯定小于原来要比较的数值，然而官方文档里的提供配置信息又是正数。
所以解决方法有2个。
1、官方文档的配置应该使用负数
2、在“_checkToEnd”的校验函数里，运算符应该使用“-”运算符号

**Comment by dolymood** [comment]
这不是bug 这是就是这样的逻辑，当差50到底部的时候 触发pullupLoad

**Comment by Lukunlin** [comment]
这样的解释很牵强，您的意思是，选项里的“pullingUp”配置的“threshold”给定50的意思是，我距离原本100才就触发到达底部了，现在变成了，到达50的scroll距离就触发了到达底部吗？也就是缩小了maxScrollY的值吗？
因为同样的对于“pullUpLoad”里的“threshold”，意思就则是相反的，对于“pullingDown”事件的派发，
“threshold”配置正数是增加了他下拉高度，决定他是否去派发“pullingDown”事件，这样一对比的话，很容易让人联想到对于“pullUpLoad”的“threshold”来说，是增加到达底部的距离而不是缩小~太容易误会了~
如果确实是这样的逻辑的话，建议在文档里说的更详细一点
