### ISSUE TITLE
[New Feature] 请问在设置了下拉刷新之后如何实现在快速下滑的时候不会发生回弹效果

### ISSUE THREAD

**Issue by imgoddqp** [ustbhuangyi/better-scroll#728]
### What problem does this feature solve?
用户在做下滑动作的时候，可能只是想滚动到上面，此时y=0的时候，想要让他不再继续滚动，不产生回弹效果。只有y=0时候才让下拉刷新动作enable,类似淘宝app的首页

### What does the proposed API look like?
能够支持回弹触发的条件或者其他能实现需求的办法。

**Comment by theniceangel** [comment]
参考文档

**Comment by imgoddqp** [comment]
能给个思路吗？文档读了好多次，谢谢！

**Comment by imgoddqp** [comment]
如果在bounce设置为false的时候，也能实现下拉就好了
