### ISSUE TITLE
使用pullingup发生一些很诡异的问题

### ISSUE THREAD

**Issue by Herryjoeson** [ustbhuangyi/better-scroll#732]
我参考了demo并且使用react实现了一份一模一样的代码.当我在使用pulling up的时候,并且设置了滑倒底部的提示容器。但是无论如何都无法滚动到提示的容器这个位置
![image](https://user-images.githubusercontent.com/19682746/50947820-01141f00-14db-11e9-8ced-376fde3bf36d.png)
实际我的页面只能看到
![image](https://user-images.githubusercontent.com/19682746/50947833-125d2b80-14db-11e9-95ee-93e2ccf83fc1.png)
当我尝试往上拉看到了 但是他回弹把它藏起来了
![image](https://user-images.githubusercontent.com/19682746/50947850-2012b100-14db-11e9-86ff-3ded313bfb03.png)
实际我想要就是能够把classname为pullup-wrapper这个能展示出来

**Comment by Herryjoeson** [comment]
我现在就是说要让pull-wrapper的容器能显示正常滚到哪里。我是在他的后面加多了一个div并且设置一定的高度

**Comment by theniceangel** [comment]
提供线上可调试demo

**Comment by Herryjoeson** [comment]
稍等

**Comment by Herryjoeson** [comment]
@theniceangel  http://wubing.saltwater.xin/#/pages/test/test

**Comment by theniceangel** [comment]
看demo没啥问题

**Comment by Herryjoeson** [comment]
那个加载提示的容器不应该在到底部会显示出来的吗

**Comment by Herryjoeson** [comment]
比如我设置上拉前的底部文字应该是上拉加载下一页。可是我现在滚动到底部。看不到那个容器。需要我上拉看到。并且回弹就藏起来了

**Comment by theniceangel** [comment]
看现象应该是高度计算错误，确保所有的dom渲染之后，再初始化bs

**Comment by Herryjoeson** [comment]
我已经更新了demo,并且在对应的console输出了东西,来确定定位问题.

**Comment by Herryjoeson** [comment]
这一次我在react渲染dom完输出了console.log,并且初始化bs使用3秒。。结果并没有看到底部。但是奇怪的是我如果滚动了一下滚动条 3秒后定时器去初始化的时候底部看的到了,但是之前发生滚动的那些试图在也看不到了 具体你可以尝试一下,我第一个是子元素给0的哪一个

**Comment by lllllleo-chan** [comment]
看你的demo你把wrapper设置成了100vh，忽略了topbar的高度，实际上bs没有滚动

**Comment by Herryjoeson** [comment]
我设置成100%就和撑成实际的高度了

**Comment by Herryjoeson** [comment]
按照大佬的意思。我需要如何改动

**Comment by lllllleo-chan** [comment]
你可以把overflow设置成auto

**Comment by Herryjoeson** [comment]
我晚点试试。

**Comment by Herryjoeson** [comment]
用了auto后好像多出一点内容

**Comment by lllllleo-chan** [comment]
你可以用flex布局让main-content自适应+overflow：auto，然后里面的内容高度100%，我也不太清楚你的空白怎么来的，我现在开发都是这样玩的，应该不会有什么问题

**Comment by Herryjoeson** [comment]
空白不加1px就没问题

**Comment by Herryjoeson** [comment]
我现在就先用着后面的dom来顶前面的bottombar来显示出来

**Comment by Herryjoeson** [comment]
我最奇怪的就是不知道为什么我的定时器没到600毫秒执行的期间滑动了页面 底部可以直接看到但是头顶的那个元素会遮挡bar的高度

**Comment by Herryjoeson** [comment]
终于解决了

**Comment by yangmeijuan** [comment]
> 终于解决了

请问我也遇到相似问题 ，能提供一下解决方法吗

**Comment by xaviertung** [comment]
@Herryjoeson 请问怎么解决的，方便贴出来吗，我也遇到类似的问题了。

**Comment by Herryjoeson** [comment]
你需要明确一个高度给到scroll不然计算有问题就会导致这样

**Comment by xaviertung** [comment]
> 你需要明确一个高度给到scroll不然计算有问题就会导致这样@xaviertung

是2.0beta2版本的问题，安卓微信客户端上拉刷新时未正常计划滚动条高度。
