### ISSUE TITLE
snap和mouseWheel配置问题

### ISSUE THREAD

**Issue by long-woo** [ustbhuangyi/better-scroll#733]
### Version
1.13.4

### Reproduction link
[https://codepen.io/long0woo/pen/oQodyM](https://codepen.io/long0woo/pen/oQodyM)

### Steps to reproduce
开发slide组件时，鼠标滚动后1->3，会跳过中间2。

### What is expected?
鼠标滚动一次切换一个

### What is actually happening?
看了源码，是在下图位置
![image](https://user-images.githubusercontent.com/3394035/51367683-b91e7900-1b26-11e9-9dd8-551ad933b33a.png)

**Comment by TothingWay** [comment]
解决了吗？

**Comment by theniceangel** [comment]
fixed in v2.0.0
