### ISSUE TITLE
嵌套滚动条如何滚动到底部后可以继续滚动body滚动条？

### ISSUE THREAD

**Issue by 93Alliance** [ustbhuangyi/better-scroll#734]
我在一个 `div` 内会有一个滚动条，同时`body`内也有一个滚动条，目前我`div`内的滚动条滚动到底部之后，不会触发 `body`的滚动条继续滚动，而原生的滚动条可以，请问有什么好的方法解决吗？

**Comment by theniceangel** [comment]
滚动到底部的时候，disable bs就可以

**Comment by 93Alliance** [comment]
这不是好的办法啊，当再次滑动这个区域的时候，岂不是不会响应？

**Comment by 93Alliance** [comment]
我该如何重新激活？谢谢

**Comment by tank0317** [comment]
@93Alliance 你的body 的滚动也是 better-scroll 实现的吗？如果想要实现内外级联的滚动，需要自己实现这部分逻辑。大致逻辑就是在内层滚动到边界的时候禁止内层的滚动，否则启用外层的滚动。

**Comment by tank0317** [comment]
或者你可以了解下 [Cube-UI](https://didi.github.io/cube-ui/#/zh-CN/docs/scroll) 里面的 Scroll 组件支持这种级联的滚动场景。

**Comment by 93Alliance** [comment]
我查看了这个项目的scroll代码，这里解决了移动端触摸和PC端鼠标移动，但是我想解决鼠标滚轮，目前卡在 鼠标滚轮scroll，不能获取distX和distY,值为undefind。是否可以在处理鼠标滚轮事件的源码中增加对distX和distY属性的赋值？

**Comment by 93Alliance** [comment]
谢谢你，我已经解决了

**Comment by tomorrowzjz** [comment]
@93Alliance 我也遇到这个问题了，请问你是怎么触发body的滚动事件的。

**Comment by 93Alliance** [comment]
判断BS是否滚动到边界，如果是 disable BS，然后监听body的滚动条，如果body滚动，则enable BS，这样就ok了

**Comment by tomorrowzjz** [comment]
@93Alliance 感谢

**Comment by wuxiuran** [comment]
@93Alliance 我按照你说的办法，但是必须要重新触发touchstart touchmove事件，才能实现BS和原生滚动之前的切换效果，有没有办法在滚动的过程中两者切换呢？

**Comment by 93Alliance** [comment]
不需要的啊,第一你可以参考 [Cube-UI](https://didi.github.io/cube-ui/#/zh-CN/docs/scroll)的实现.
第二,你监听BS滚动事件,即 `scroll`,如果BS到达边界,关闭BS即`disbale`,
```
innerScroll.resetPosition();
innerScroll.disable();
```
再监听`touchEnd`事件,如果滚动结束,没有到达边界,激活BS
```
innerScroll.enable();
```
如果原生滚动条开始移动,停止BS
```
innerScroll.stop();
innerScroll.resetPosition();
```

我已经挤不太清楚了,我直接看 Cube-UI 就可以实现

**Comment by wuxiuran** [comment]
@93Alliance 刚刚看了Cube-UI和我这边的产品功能效果不一样，我这边要求是手指不离开屏幕的前提下实现滚动的切换。。说服产品放弃这个功能了
