### ISSUE TITLE
手机滑动的时候，如果是缓慢滑动会卡顿，现象为顿挫感，如果快速滑动则没有

### ISSUE THREAD

**Issue by 93Alliance** [ustbhuangyi/better-scroll#737]
### Version
1.14.0

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
略

### What is expected?
怎么解决？

### What is actually happening?
略

---
测试为 华为Mate 9 chrome浏览器，我在Angular项目中使用的。

**Comment by TornadoLess** [comment]
同遇到这个问题，在页面中图片多的时候特别明显，此时如果修改图片会出现明显抖动，感觉整体transform的性能非常差，如果transform的dom节点太多，部分节点的元素又在滑动中变化的话和android原生的listview差别明显


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by xuan-zi** [comment]
可能你用的是微信的那个浏览器吧，你拷贝链接到其他浏览器打开应该就不会有这个问题了
