### ISSUE TITLE
不能如期正常滚动

### ISSUE THREAD

**Issue by liudianliang** [ustbhuangyi/better-scroll#74]
我要实现一个商品的详情页面，一共两个页，上面是商品的基本信息（价格，规格型号），下面是商品图文详情，两个页面的高度都不是确定的，我要实现，第一页上拉可以到第二页，第二页下拉可以到第一页，（我获取了父容器的高度，子容器在父容器高度上+10px，我在mounted，nextTick下获取ajax数据，在ajax后面初始化的bs），现在有的时候可以滚动，有的时候不能滚动，不知道问题出在哪里，或是bs并不适合这个场景？

**Comment by liudianliang** [comment]
我分别为两个页面实例化了bs，

**Comment by ustbhuangyi** [comment]
不符合提 issue 规范
