### ISSUE TITLE
在多tab中使用， hasVerticalScroll 为false ，导致不能滑动

### ISSUE THREAD

**Issue by aoliaoliao** [ustbhuangyi/better-scroll#741]
### Version
1.14.0

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll/blob/master/example/components/scroll/scroll.vue ](https://github.com/ustbhuangyi/better-scroll/blob/master/example/components/scroll/scroll.vue )

### Steps to reproduce
1. 移动端设备， 在 vue 中使用，组件就使用 'example' 中 https://github.com/ustbhuangyi/better-scroll/blob/master/example/components/scroll/scroll.vue  的封装

2. 在两个tab页，tabA，tabB中使用，每个 tab 中都有下拉刷新功能，操作是 在tabA中下拉，在数据加载完之前切换到 tabB，然后再切回到 tabA，就发现tabA的页面已经不能滑动

3. 跟踪了下源码发现，原因是在下拉加载数据之后，tabA 的 scroll 实例进行了 refresh()。但此时因为tabA已经被 ‘display：none’了， 所以在refresh时得到的 this.hasVerticalScroll 值为false，deltaY就恒为 0，所以页面就不能滑动了

4. 建议是否可以将 this.hasVerticalScroll 值的判断移动到 下拉加载数据之前，这样可以避免对 hasVerticalScroll 属性的影响

### What is expected?
切回页面之后，页面可以正常滑动

### What is actually happening?
页面不能正常滑动

**Comment by theniceangel** [comment]
在激活的 tabA 的时候，refresh 下。
