### ISSUE TITLE
Internet Explorer 11 does not pick up "transitionEnd" Event

### ISSUE THREAD

**Issue by steinm91** [ustbhuangyi/better-scroll#743]
### Version
1.13.1 (Plunkr)

### Reproduction link
[https://plnkr.co/edit/IPfC0Lu6nFbgnaJO?preview](https://plnkr.co/edit/IPfC0Lu6nFbgnaJO?preview)

### Steps to reproduce
Click on the Arrow-Buttons on the Scroll-Container in the Plunkr to switch between images. You'll notice that the scroll container does not adjust itself to the image height.

### What is expected?
Our App is listening to the "scrollEnd" event of better-scroll. If it is fired we adjust the height of the scroll container so it matches the height of the image. So it's necessary that "scrollEnd" is fired when the transition has finished.

### What is actually happening?
On IE11 the event "scrollEnd" is not fired and we can't adjust the height of the scroll container. This is due to the fact that better-scroll internally registers to the event "msTransitionEnd" instead of "transitionend". Maybe the former is necessary for IE < 11, but for IE11 it does not seem to work.
If we manually change from "msTransitionEnd" to "transitionend" everything works and the custom event "scrollEnd" is fired and we can adjust the height of the scroll container.

**Comment by theniceangel** [comment]
Thank you, we will solve it next minor version.
