### ISSUE TITLE
scrollEnd不支持鼠标滚动到底部触发事件？

### ISSUE THREAD

**Issue by liub1934** [ustbhuangyi/better-scroll#754]
### Version
1.14.0

### Reproduction link
[https://github.liub37.com/cnodejs](https://github.liub37.com/cnodejs)

### Steps to reproduce
鼠标滚动到底部后没有触发scrollEnd事件，往上拉的话可以正常触发。
![gif](https://user-images.githubusercontent.com/29849550/53939632-a7049400-40ee-11e9-9e85-9ccedfee729b.gif)

### What is expected?
鼠标滚动到底部也触发scrollEnd

### What is actually happening?
实际没有触发

**Comment by wuxiuran** [comment]
触发时机：滚动结束。

**Comment by theniceangel** [comment]
我们用滚轮测试了一下，会触发 scrollEnd。
