### ISSUE TITLE
移动端 报Ignored attempt to cancel a touchstart event with cancelable=false, 的错误

### ISSUE THREAD

**Issue by rujptw** [ustbhuangyi/better-scroll#755]
1. 使用better-scroll时，第一次触发上拉事件，触发了ajax请求，没有报错，
2. 第二次直接报bscroll.esm.js?9012:1013 [Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

3.代码如下：initScroll() {
			const options = {
				pullDownRefresh: {
					threshold: 50, // 当下拉到超过顶部 50px 时，触发 pullingDown 事件
					stop: 20 // 刷新
				},
				pullUpLoad: {
					threshold: -20 // 在上拉到超过底部 20px 时，触发 pullingUp 事件
				}
			};
			if (!this.scroll) {
				this.scroll = new BScroll(this.$refs["list-main"], options);
				this.scroll.on("pullingDown", () => {
					if (this.pageNum < 1) {
						this.pageNum = 1;
					}
					if (this.pageNum > 1) {
						this.pageNum--;
					}
					this.getProposalList();
					if (this.totalCount) {
						this.scroll.finishPullDown();
					}
				});
				this.scroll.on("pullingUp", () => {
					this.pageNum++;
					this.getProposalList();
					if (this.totalCount) {
						this.scroll.finishPullDown();
					}
				});
			} else {
				this.scroll.refresh();
			}
		},

**Comment by theniceangel** [comment]
代码逻辑有问题，首先你要确保获取收据之后再调finishPullDown或者finishPullUp。而且你pullingUp里面的finish函数写错了

**Comment by rujptw** [comment]
是this.scroll.finishPullDown()调用错误了吗？

**Comment by rujptw** [comment]
解决了，thx

**Comment by 60late** [comment]
> 解决了，thx

求问怎么解决的啊

**Comment by rujptw** [comment]
你看一一下Riemann66l对我的回复




------------------ 原始邮件 ------------------
发件人: "60late"<notifications@github.com>; 
发送时间: 2019年8月5日(星期一) 下午4:16
收件人: "ustbhuangyi/better-scroll"<better-scroll@noreply.github.com>; 
抄送: "random"<2609274343@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ustbhuangyi/better-scroll] 移动端 报Ignored attempt to cancel a touchstart event with cancelable=false, 的错误 (#755)



 
解决了，thx
  
求问怎么解决的啊

**Comment by zmlc-f** [comment]
请问怎么解决的啊

**Comment by suzhenghui-sky** [comment]
> 你看一一下Riemann66l对我的回复
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "60late"<notifications@github.com>; 发送时间: 2019年8月5日(星期一) 下午4:16 收件人: "ustbhuangyi/better-scroll"<better-scroll@noreply.github.com>; 抄送: "random"<2609274343@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [ustbhuangyi/better-scroll] 移动端 报Ignored attempt to cancel a touchstart event with cancelable=false, 的错误 (#755) 解决了，thx 求问怎么解决的啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

看什么？有说什么嘛？
