### ISSUE TITLE
ie11 使用scrollTo到超出部分不回弹

### ISSUE THREAD

**Issue by Forthere** [ustbhuangyi/better-scroll#756]
Version
1.14.0

Reproduction link
https://ustbhuangyi.github.io/better-scroll/#/examples/vertical-scroll/zh

Steps to reproduce
在ie11打开[demo](https://ustbhuangyi.github.io/better-scroll/#/examples/vertical-scroll/zh), 在Methods列表中x输入200, 点击scrollTo按钮。 不能实现回弹。

What is expected?
期望能够跟chremo一样能够回弹。

What is actually happening?
点击之后到对应的地方。

**Comment by theniceangel** [comment]
是y输入200吧？

**Comment by Forthere** [comment]
Version 1.15.0 已经修复这个问题了。 谢谢
