### ISSUE TITLE
scrollToElement not working as expected.

### ISSUE THREAD

**Issue by CrashyBang** [ustbhuangyi/better-scroll#758]
### Version
1.15.0

### Reproduction link
[https://codepen.io/chopfitzroy/pen/BbJOVX?editors=0010#0](https://codepen.io/chopfitzroy/pen/BbJOVX?editors=0010#0)

### Steps to reproduce
1) Click on one of the images, no scrolling occurs.

2) Open dev tools and check correct element that is clicked on is logged to the console.

### What is expected?
The the element clicked on will be scrolled to the center (or as close as possible) of the horizontal scroller.

### What is actually happening?
No scrolling occurs.

---
I am developing the actual site in Vue, I just wrote the Pen to be as minimal as possible so that the problem is more easily identifiable.

I am using https://ustbhuangyi.github.io/better-scroll/doc/en/api.html#scrolltoelementel-time-offsetx-offsety-easing as a reference.

**Comment by theniceangel** [comment]
I have seen the demo, your HTML Layout has some questions. `wrapper` DOM must has fixed width / height, `content` DOM's width / height must exceed `wrapper`, [see the doc](https://ustbhuangyi.github.io/better-scroll/doc/en/#the-implementation-of-better-scroll-in-mvvm-frameworks)

**Comment by CrashyBang** [comment]
Hey @theniceangel, I see what you mean, after taking another look at the documentation I believe I have made the required updates and the [demo](https://codepen.io/chopfitzroy/pen/BbJOVX?editors=0010#0) should now work.

Unfortunately I am still not able to get it to scroll.

**Comment by theniceangel** [comment]
sorry for replying to you so much later.

The key point is that the content's width must exceed the wrapper's, but they are keep the same in your demo, I modified the css. As follows:
```diff
.time-line-gallery {
    position: fixed;
-   overflow-x: auto;
+   overflow: hidden;
    z-index: 102;
    left: 0;
    bottom: 0;
    width: 100vw;
    height: 150px;
    background-color: deeppink;
}

.time-line-thumbnails {
-    display: flex;
-    flex-wrap: nowrap;
+    display: inline-block;
+    white-space: nowrap;
}

img {
-     max-width: 100%;
      max-height: 100px;
}
```

With these css rules,  the content' width are equal to the summary of his children's width.

At last, if you want to a horizontal scrolling, please set `scrollX: true` in your options when you init better-scroll instance.

```js
scroller = new BScroll('.time-line-gallery', {
    scrollX: true
  });
```

Now, it works!

**Comment by CrashyBang** [comment]
Hey @theniceangel,

I think I may have done something wrong, I have made the updates as you suggested [here](https://codepen.io/chopfitzroy/pen/BbJOVX?editors=0010#0), while the click to scroll is now working, the list is vertical, ideally I want the list horizontal and to 'side scroll'.

Cheers for all the help!

**Comment by theniceangel** [comment]
sorry, I forgot one change in css
```diff
.time-line-thumbnail {
-       flex: 0 0 auto;
+       display:inline-block;
        position: relative;
        margin: 0 10px;
        background-color: deepskyblue;
}
```

**Comment by CrashyBang** [comment]
Awesome! Thank you.

For anyone who stumbles across this thread working demo is here: https://codepen.io/chopfitzroy/pen/BbJOVX?editors=0010#0

Cheers.
