### ISSUE TITLE
About wheel's disabled option

### ISSUE THREAD

**Issue by hezhongfeng** [ustbhuangyi/better-scroll#760]
### Version
1.15.0

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll/commit/27e227e8857335c7b337924019f35a48b0aa4172](https://github.com/ustbhuangyi/better-scroll/commit/27e227e8857335c7b337924019f35a48b0aa4172)

### Steps to reproduce
我感觉现在的wheel disabled的滚动是有问题的
首先看我最初提PR的效果

![最初](https://i.loli.net/2019/03/15/5c8b5646bd041.gif)

然后是现在的：

![现在的](https://i.loli.net/2019/03/15/5c8b57e75d0ef.gif)

### What is expected?
无论是靠惯性滑动还是停留在disabled区，都要根据滚动方向滚动，除非disabled区在边界

### What is actually happening?
现在的逻辑有点奇怪，无论从哪边进入disabled区或者离哪边近都会向前滚动（向index小的也就是主宰滚动）

---
如果是bug的话我可以提PR进行优化

**Comment by theniceangel** [comment]
之前我给你的意见是按照滚动方向来计算最近的非 disable 的item。后面我们内部商量了一下，打算按照 IOS Web Select 的禁止选中的逻辑去做。

**Comment by hezhongfeng** [comment]
好的，就是说无论从哪里滚动和停留都会滚向上面的（主宰）吗？
没问题的话就可以关掉了，谢谢解答
