### ISSUE TITLE
better-scroll 在移动端浏览器中的表现明显卡顿

### ISSUE THREAD

**Issue by nirvana72** [ustbhuangyi/better-scroll#761]
我已最小化了重现demo, 两个界面分别是bs 和 div的原生滚动条
pc上几乎没有区别， 但是在ios 移动端浏览器中， bs 的滚动条明显卡顿

页面分别加载图文内容， 每个内容有文字级图片3~9张不等， 加载的都是压缩图
按说内容也不能说多， 但是两种滚动条的表现却相差很大

当页面内容少的时候，5篇以内文章内容时，卡顿几乎可以呼略， 
10篇的时候，明显可以感觉到卡顿， 
30篇时， 有种想关掉app的冲动
100篇时，几乎没法用了

而div的原生滚动条， 100篇的时候始终很流畅

主要表现在上下划动变向延迟， 快速划动滚动慢， 慢速划动手指跟随闪烁掉帧

相反， div 出现的原生滚动条， 以上三个问题表现完美

测试机  iphone6s plus ios 12.1.4

**Comment by ustbhuangyi** [comment]
还请提供一下最小化复现 demo 的 repo 或者在线演示地址

**Comment by nirvana72** [comment]
演示地址
http://www.mu78.com/scroll-demo/index.html

代码地址
https://gitlab.com/ni5802372/vue-better-scroll-demo.git

说明一下，我用的是一个叫vue-slim-better-scroll的包， 是把BS 二次封装的产品， 也许是封装的不好吧， 我在尝试着直接用BS 实现一下滚动

**Comment by XdyGoGo** [comment]
http://119.23.255.181/dist/index.html#/index
