### ISSUE TITLE
Where are the plain javascript examples?

### ISSUE THREAD

**Issue by JurgenJocubeit** [ustbhuangyi/better-scroll#763]
I'm disappointed to see all the examples are in vue, when this excellent code is written in plain javascript.

I want to implement better-scroll with vanilla web components written using TypeScript... but the only examples I can find are in vuejs.

**Comment by JurgenJocubeit** [comment]
"Considering that one of the most suitable JavaScript MVVM framework for mobile development currently is Vue, and better-scroll can be applied in conjunction with Vue very well, so I rewrote the demo with Vue."

This is your opinion. I agree Vue is awesome. But I'm not using Vue in my latest project, and don't want to. The examples would be much easier to understand if there was a plain javascript version.

**Comment by theniceangel** [comment]
We made a discussion last day. We are planning to write examples with Vue and React in better-scroll 2.0. Plain javascript examples will in our consideration if we have enough time.
