### ISSUE TITLE
1.15.0版本，scrollEnd会触发多次

### ISSUE THREAD

**Issue by xu302763630** [ustbhuangyi/better-scroll#765]
旧版本没这个问题，1.15.0版本 scrollEnd事件会多次执行回调函数。
![1553519300(1)](https://user-images.githubusercontent.com/39487412/54922000-28a74f00-4f42-11e9-89bb-a6e32e2c5a47.jpg)
例如此处次数会打印多个123

**Comment by LiuJinYang9527** [comment]
这个问题解决了吗 ？

**Comment by ixyx** [comment]
> 这个问题解决了吗？

应该是解决了，你试试看
