### ISSUE TITLE
加了BSCroll之后，文本无法选中了，user-select: text!important;均不管用，new BSScroll实例的时候同时添加click: true, taps: true, disableTouch:false,属性也不可以，请问如何解决；

### ISSUE THREAD

**Issue by aNewLearnerHere** [ustbhuangyi/better-scroll#769]

**Comment by theniceangel** [comment]
preventDefault: false

**Comment by ustbhuangyi** [comment]
[preventDefaultException](https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#preventdefaultexception)

**Comment by 86driver** [comment]
楼主现在解决了吗   我设置了preventDefaultException还是无效

**Comment by 86driver** [comment]
> [preventDefaultException](https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#preventdefaultexception)

 我设置了preventDefaultException也不生效     在PC上使用

**Comment by towry** [comment]
现在依然无效，[preventDefaultException](https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#preventdefaultexception)
