### ISSUE TITLE
1.15.1 Picker 多级联动 wheelTo重复递归调用

### ISSUE THREAD

**Issue by virgoheRomAn** [ustbhuangyi/better-scroll#771]
### Version
1.15.0

### Reproduction link
[https://ustbhuangyi.github.io/better-scroll/#/examples/picker/en](https://ustbhuangyi.github.io/better-scroll/#/examples/picker/en)

### Steps to reproduce
example实例中city-picker，
原因：BS wheelTo方法滑动到了顶部，重新触发了change方法，造成了递归的出现，导致计算临时坐标位置tempIndex错误

### What is expected?
修复这个问题，wheelTo不要触发change方法

### What is actually happening?
wheelTo造成多次触发change方法

---
选择省市区

**Comment by theniceangel** [comment]
根据你描述的信息，看不出哪里有问题，能更具体一点或者贴代码么

**Comment by virgoheRomAn** [comment]
> 根据你描述的信息，看不出哪里有问题，能更具体一点或者贴代码么
举个具体的例子吧：
城市联动：选择“河北省”=>“秦皇岛市”=>“山海关区”，然后选择北京省，这时就会报错。

**Comment by virgoheRomAn** [comment]
问题出至（代码）：

**Comment by virgoheRomAn** [comment]
`handleChange(i, newIndex) {
    console.log(i, newIndex)
    if (newIndex !== this.tempIndex[i]) {
         for (let j = 2; j > i; j--) {
            this.tempIndex.splice(j, 1, 0)
            this.$refs.picker.scrollTo(j, 0)
          }
          this.tempIndex.splice(i, 1, newIndex)
     }
 }`

**Comment by theniceangel** [comment]
@virgoheRomAn 嗯，我修复下demo。

**Comment by virgoheRomAn** [comment]
> @virgoheRomAn 嗯，我修复下demo。

谢谢。
