### ISSUE TITLE
IOS进度条没法拖动

### ISSUE THREAD

**Issue by linzi12138** [ustbhuangyi/better-scroll#774]
最近使用在项目中,需要在滚动的盒子里面使用video标签,但是IOS上的小窗进度条没法拖动,而且一触碰进度条视频就会暂停

**Comment by theniceangel** [comment]
```js
{
  preventDefaultException:  {tagName: /^(INPUT|TEXTAREA|BUTTON|SELECT|VIDEO)$/} 
}

```

加这个配置项试试

**Comment by tony-bryant** [comment]
> ```js
> {
>   preventDefaultException:  {tagName: /^(INPUT|TEXTAREA|BUTTON|SELECT|VIDEO)$/} 
> }
> ```
> 
> 加这个配置项试试

加上后还是没有解决问题

**Comment by tvxqljw** [comment]
这个设置目前没有效果
