### ISSUE TITLE
Android UC浏览器（v12.3.8.1018）不兼容反馈

### ISSUE THREAD

**Issue by xieyihao** [ustbhuangyi/better-scroll#776]
### Version
1.15.0

### Reproduction link
[https://ustbhuangyi.github.io/better-scroll/#/examples/goods-list/en](https://ustbhuangyi.github.io/better-scroll/#/examples/goods-list/en)

### Steps to reproduce
1. 环境：Android 7，
   手机：华为、小米、vivo
2.打开官网DEMO例子：https://ustbhuangyi.github.io/better-scroll/#/examples/goods-list/en
3.无法滚动。

### What is expected?
可以正常滚动

### What is actually happening?
不能滚动

---
发现UC浏览器还是很多问题的

**Comment by huijieshi** [comment]
同发现UC浏览器这个问题

**Comment by dolymood** [comment]
oppo android 7.1 UC 最新版 实验无问题

**Comment by huijieshi** [comment]
> ### Version
> 1.15.0
> 
> ### Reproduction link
> https://ustbhuangyi.github.io/better-scroll/#/examples/goods-list/en
> 
> ### Steps to reproduce
> 1. 环境：Android 7，
>    手机：华为、小米、vivo
>    2.打开官网DEMO例子：https://ustbhuangyi.github.io/better-scroll/#/examples/goods-list/en
>    3.无法滚动。
> 
> ### What is expected?
> 可以正常滚动
> 
> ### What is actually happening?
> 不能滚动
> 
> 发现UC浏览器还是很多问题的

1.15.1实测华为没有问题

**Comment by huijieshi** [comment]
华为 1.15.1    UC  实验无问题

**Comment by AnneYanDong** [comment]
我也遇到安卓UC浏览器失效

**Comment by AnneYanDong** [comment]
observeDOM: false加上这个配置就可以了，亲测（可以看看效果https:m.youxiake.com/search/results?keyword=杭州&spm=#/mSearchResult）

**Comment by ustbhuangyi** [comment]
@AnneYanDong 能否帮忙从源码方面调试一下，在有问题的手机下，如果设置为 true，是触发了 JS 报错么？

**Comment by rome888** [comment]
同遇到此问题，测试没有捕获到错误

**Comment by loewe0202** [comment]
同遇到此问题

**Comment by minikey** [comment]
是不是跟UC浏览器的默认手势冲突上了，我刚解决这个问题， `touch-action:pan-y;` css属性配置调试一下

**Comment by theniceangel** [comment]
请参考 #1067
