### ISSUE TITLE
在 Vue 中使用 scroll 插件遇到难题

### ISSUE THREAD

**Issue by patchBig** [ustbhuangyi/better-scroll#777]
### Version
1.15.0

### Reproduction link
[https://jsfiddle.net/st4kdo6w/](https://jsfiddle.net/st4kdo6w/)

### Steps to reproduce
在 Vue 中使用 scroll 组件，使页面能够纵向滚动，
然后页面里面有一个可以横向滚动的列表，是通过 css 设置横向滚动的

### What is expected?
期望横向滚动列表的时候，能够正常横向滚动

### What is actually happening?
横向滚动列表的时候，不能够滚动

---
需要设置一些什么可以达到这种效果；
需要引入 scroll 组件，jsfiddle 不知道怎么引入 ==

**Comment by tank0317** [comment]
http://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#eventpassthrough

**Comment by patchBig** [comment]
![image](https://user-images.githubusercontent.com/25219300/55928759-87600e80-5c4c-11e9-8351-4532cd60a8e2.png)
![image](https://user-images.githubusercontent.com/25219300/55928777-92b33a00-5c4c-11e9-99ed-e898707e7df9.png)
已经配置了 但是不好使

**Comment by patchBig** [comment]
发现横向可以滚动了，纵向不能滚动了 ==
![image](https://user-images.githubusercontent.com/25219300/55929089-bf1b8600-5c4d-11e9-8403-db399247928e.png)

**Comment by patchBig** [comment]
解决了 感谢 大佬

**Comment by gdoudeng** [comment]
> 发现横向可以滚动了，纵向不能滚动了==
> ![图片](https://user-images.githubusercontent.com/25219300/55929089-bf1b8600-5c4d-11e9-8403-db399247928e.png)

我也是横向可以滚，纵向就不能滚了啊，求救啊
