### ISSUE TITLE
vue 里面使用better-scroll 滑动后 需要点击两次才会触发点击事件

### ISSUE THREAD

**Issue by CheRat** [ustbhuangyi/better-scroll#781]

**Comment by ustbhuangyi** [comment]
滑动过程中点击无效，这个是库本身的设计，参考 iOS 列表滚动的交互。

**Comment by lingsang2** [comment]
> 滑动过程中点击无效，这个是库本身的设计，参考 iOS 列表滚动的交互。

执行下拉动作的时候，因为回弹的原因，需要很长时间才能触发点击事件。
以正常的速度点击，原生的滚动在点击第一次最多第二次就可以触发事件，bs需要在第三甚至第四下才能触发点击事件。

**Comment by hufuhao** [comment]
使用scrollTo方法后到达了指定位置，点击第一下事件不触发，是如何解决的呢

**Comment by fanfanjiang** [comment]
我也有相同的问题，必须等动画完全停止后才能触发click，感觉应该在滑动比较慢的情况下就可以派发click了

**Comment by webylb** [comment]
遇到这样的需求了 希望有解决办法

**Comment by trtrtr6** [comment]
看了源码，如下处理后可解决相应的问题，你们可以尝试下
`scroll.on('scrollEnd', () => {
         scroll.isInTransition = false
  })`

**Comment by chenxianqi** [comment]
全局监听touch事件在里面判断class为触发类型target

**Comment by houyajie** [comment]
我也遇到同样的问题，滑动之后点击两次才能触发点击事件
