### ISSUE TITLE
滑动区域内包含input输入框时，会导致无法选择和全选复制输入框内的内容

### ISSUE THREAD

**Issue by StarFishing** [ustbhuangyi/better-scroll#783]
### Version
1.15.0

### Reproduction link
[https://github.com/StarFishing/SearchVideo](https://github.com/StarFishing/SearchVideo)

### Steps to reproduce
无法复制全选输入框的内容

### What is expected?
在包含输入框的滑动范围内，可以鼠标全选输入框框内的内容

### What is actually happening?
无法复制全选输入框的内容

**Comment by theniceangel** [comment]
preventDefault 设置为 false

**Comment by callMeXD** [comment]
遇到类似的问题，textarea中内容无法被选中，进行相关的设置之后textarea文本仍然不能被选中，但是对input输入框有作用
最后通过focus与blur事件，配合disable与enable使用达到了textarea中的文本能够选中，但是在enable后会出现滚动距离偏差的问题
