### ISSUE TITLE
useTransform 為 false 時造成的重大問題 

### ISSUE THREAD

**Issue by aron19951209** [ustbhuangyi/better-scroll#788]
![螢幕錄製 2019-04-20 下午4 09 35](https://user-images.githubusercontent.com/33840671/56454990-a6b51500-638b-11e9-8c8b-8fb1d551943e.gif)

### Version
1.15.0

### Reproduction link
[https://codepen.io/Aoyue/pen/PgaYBb](https://codepen.io/Aoyue/pen/PgaYBb)

### Steps to reproduce
- 分別觀察對 `.wrapper-1` 及 `.wrapper-2` 捲動 ( 使用滑鼠滾輪 ) 
- 分別觀察對 `.wrapper-1` 及 `.wrapper-2` 捲動 ( 使用拖拉滾動 ) 

`.wrapper-2` 於 Mobile 及 PC 都造成嚴重的亂滾、亂彈，而 `.wrapper-1` 是採用預設的設置 `transform` 去滾動沒什麼異常。

### What is expected?
雖然 `useTransform: false` 有一定的效能極限，但功能方面希望皆

能與 `useTransform: true` 一樣正常

### What is actually happening?
當 `useTransform` 為 `false` 採用 `top, left` 來驅動將導致滾動行為有嚴重錯誤，似乎在加減速及反彈上沒有處理好。

---

需要針對下面組合做測試：
- `useTransform: false` && `useTransition: false` 
- `useTransform: false` && `useTransition: true`

這對某些想依賴原生 `position: sticky` 的開發者非常重要，因為眾所皆知 `transform` 將導致內部元素 `position: sticky` 及 `position: fixed` 失效，但又不想像 cube ui 那樣透過 clone dom 的方式來實現這個標題黏貼的功能。

**Comment by wenbo1** [comment]
这个问题我也发现了，加上observeDOM: false似乎可行，但是DOM刷新后top位置又会出现以上问题

**Comment by theniceangel** [comment]
不建议用 top / left 模式了。我们在 2.0 会移除这个模式。如果你需要做吸附的功能，可以参照下 example 下面 index-list 标题吸附的效果。

**Comment by aron19951209** [comment]
@theniceangel 

是想讓整個包變得更小所以移除 `top`, `left` 模式嗎？我完全理解 index-list 的實作，但我認為目前 `position: sticky` 在各家瀏覽器兼容性已經非常高，因為採用 `transform` 而無法使用原生的 `sticky` 很可惜，且透過「 滾動偵測並在 wrapper append cloned element 」會導致一些比較麻煩的問題：

劣勢：採用 `transform` 而非 `top`, `left`
---

1. 無法再 sticky title 上做一些動態雙向綁定 ( 當然如果實作成各家 framework 的 component 可以解決此問題，但無法依賴原生的行為就是比較次級的做法 )
2. 常常會因為 `transform` 的關係，導致內部 `position: fixed`, `position: sticky` 的元素失效，開發者體驗不佳

優勢：採用 `top`, `left` 而非 `transform`
---

1. 可使用原生的 `position: sticky` ,`position: fixed`
2. 不用 clone element 也意味著可以直接對 sticky title 做一些 data, event binding，更好維護

雖然採用 `top`, `left` 沒有 `transform` 來的流暢 ( 但不是很明顯 )，我嘗試用一些比較老舊的設備測試過 `requestAnimationFrame` + `top`, `left` 互動上也是蠻流暢的。我認為未來原生的屬性支援度會越來越高且容易上手及開發，除非 `transform` 突然支援 `fixed` 及 `sticky` 了，不然我認為還是保留 `top`, `left` 為上。還是你們團隊有什麼比較細節的考量嗎？我也可以為你們盡一份力！
