### ISSUE TITLE
无法通过！event._constructed来判断原生点击事件？

### ISSUE THREAD

**Issue by gaoshijun1993** [ustbhuangyi/better-scroll#79]

**Comment by gaoshijun1993** [comment]
已经把better-scroll更新到了最新版，问题依旧

**Comment by gaoshijun1993** [comment]
`
test(event) {
        console.log('click event was triggered');
        console.log(event)
      }
`
log出两次event，并且完全一样，_constructed属性都是true，所以推断BScroll会派发两次click事件

**Comment by tangyang8942** [comment]
if(!event._constructed){
     //原生点击事件
}
