### ISSUE TITLE
嵌套问题

### ISSUE THREAD

**Issue by yyx1111** [ustbhuangyi/better-scroll#792]
### Version
1.15.0

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll/issues](https://github.com/ustbhuangyi/better-scroll/issues)

### Steps to reproduce
我在1.15.2版本嵌套使用中发现问题,上下滚动时(左右滚动没有测试),当内层滚动惯性或者说动画没有停止时,再次拖动内层,此时内层无响应,外层发生响应,是否使用stopPropagation:true选项都是一样结果,我改用1.12.6版本后无此问题

### What is expected?
内层动画停止前也能滚动

### What is actually happening?
内层动画停止前也能滚动

**Comment by theniceangel** [comment]
Reproduction link 有点问题

**Comment by yyx1111** [comment]
那个是提问的时候必须填,文本说的很清楚

**Comment by theniceangel** [comment]
> 那个是提问的时候必须填,文本说的很清楚

我的意思是提供一个可以复现你问题的链接

**Comment by LaoCheng-cjs** [comment]
这个插件最大问题在于嵌套了。在外面有一层滚动，如果里面也有横着滚动的话，是无法在横着滚动元素上面，进行往下滚动，尝试各种设置，都无法解决，如果你有好的方法或者建议，在下面留言，非常感激。
例如：

> 在下面栗子中，我不能再 88... 区域内进行往下滚动，只能靠旁边的粉红色区域往下滚动

https://codesandbox.io/s/2158v0okjn?fontsize=14

**Comment by dolymood** [comment]
内层的配置 改成这样就OK 了

![image](https://user-images.githubusercontent.com/2121554/59353764-4a9cba80-8d56-11e9-8df3-466956c20a62.png)
