### ISSUE TITLE
桌面版滚动条无法显示

### ISSUE THREAD

**Issue by Lstoryc** [ustbhuangyi/better-scroll#793]
### Version
1.15.0

### Reproduction link
[https://codepen.io/lstoryc/pen/xNEVZP](https://codepen.io/lstoryc/pen/xNEVZP)

### Steps to reproduce
打开测试地址即可

### What is expected?
期待正常显示滚动条

### What is actually happening?
滚动条无法显示

**Comment by theniceangel** [comment]
wrapper 样式问题

**Comment by Lstoryc** [comment]
已解决PC端问题，wrapper需要设置固定高度，不要使用vh vw，会导致异常，并且需要设置 position： relative；处理滚动条高度异常；
demo: https://codepen.io/lstoryc/pen/zQKBgO
