### ISSUE TITLE
滚动时点击会触发click事件

### ISSUE THREAD

**Issue by a62527776a** [ustbhuangyi/better-scroll#798]
### Version
1.15.0

### Reproduction link
[https://dscsdoj.top/public/unsplash/index.html#/demo2](https://dscsdoj.top/public/unsplash/index.html#/demo2)

### Steps to reproduce
在scroll滑动的过程中点击其中的元素

### What is expected?
只有在滚动停止时才触发滚动事件

### What is actually happening?
在滚动的过程中就会触发click事件

---
用户滑动的过程中看见了感兴趣的内容
然后用手指点上去 预期停止滚动
但滚动是停止了 click事件也触发了 导致直接跳转到了另一个页面

**Comment by theniceangel** [comment]
这个链接好像没写跳转的行为把

**Comment by guoenyue** [comment]
？？？基于什么把这个issue给关了呢，好像并没有解决问题呢，真是个调皮的管理员小家伙
