### ISSUE TITLE
关于slider.vue示例样式错误

### ISSUE THREAD

**Issue by junglehunter96** [ustbhuangyi/better-scroll#799]
`.slide
    min-height: 1px`
应为
`.slide
    position:relative
    min-height: 1px`
否则 dots会发生定位错误

**Comment by junglehunter96** [comment]
> `.slide position: min-height: 1px`
> 应为
> `.slide position:relative min-height: 1px`
> 否则 dots会发生定位错误

**Comment by theniceangel** [comment]
我们示例的表现是正常的，如果你的项目布局跟示例不一样，你自己用样式控制就好了
