### ISSUE TITLE
滚动区域含有input元素，点击之后无法失焦

### ISSUE THREAD

**Issue by webman158** [ustbhuangyi/better-scroll#8]
我的better-scroll滚动区域中有input元素，在点击input输入之后就无法失焦了

（用的最新版本的better-scroll -- v 0.1.10  ,,  测试机：只有安卓上有这个问题，ios没问题的）

请问这个能如何解决呢？

**Comment by ustbhuangyi** [comment]
你的问题是不是点击 input 后获取了焦点，然后再滚动外层的列表，input 的焦点仍然存在呢？如果是这样的话，可以监听 scroll 的 beforeScrollStart 事件，在事件的回调函数里让 input blur 即可。

**Comment by webman158** [comment]
恩恩，是这样的，主要还是表单元素失焦不了，根据你的指导我这样处理就ok了
BScroll.on('beforeScrollStart',function(){
    if(!!document.activeElement){
        document.activeElement.blur();
    }
});

问下哈 ，之后这个问题的修复是打算写在源码里面还是直接使用类似上面的做法来解决呢？

谢谢你抽出时间帮忙解决！

**Comment by ustbhuangyi** [comment]
这个问题不应该在 better-scroll 源码里解决喔，属于业务场景的问题，应该由使用方解决~
