### ISSUE TITLE
如何禁止鼠标中键的滚动? 就是滚轮滚动

### ISSUE THREAD

**Issue by caihuattkl** [ustbhuangyi/better-scroll#801]
如何禁止鼠标中键的滚动? 就是滚轮滚动。
我是h5端使用，在谷歌浏览器模拟下鼠标中间可以滚动，但是我看官网的demo就无法滚动。我也想禁止鼠标中键滚动。。请问如何处理！实在不知道，才发帖。请谅解！

**Comment by theniceangel** [comment]
实例化 bs 的时候，第二个参数 `options` 不要有 `mouseWheel ` 属性。

**Comment by caihuattkl** [comment]
@theniceangel 不行吧? 我看了.没有这个属性啊
