### ISSUE TITLE
npm安装了 import BScroll from '@better-scroll/core' 找不到包哦

### ISSUE THREAD

**Issue by fanbingkun** [ustbhuangyi/better-scroll#803]
安装了 找不到 应该是没有打包吧

**Comment by ustbhuangyi** [comment]
你的 @ 有没有配置 webpack alias？

**Comment by fanbingkun** [comment]
有的，  但是引用相对路径 ./node_modules/@better-scroll/core   也找不到，还是这个问题吗

**Comment by ustbhuangyi** [comment]
把 @ 这个 alias 去了应该就没问题，和相对路径没啥关系。

**Comment by fanbingkun** [comment]
刚试了下  好像还是不行呀 大佬

**Comment by fanbingkun** [comment]
![image](https://user-images.githubusercontent.com/36094539/58524401-aca7dc80-81fa-11e9-8c12-d8fac23575a7.png)
我看你这包里面就 都还是ts文件

**Comment by fanbingkun** [comment]
也没有dist打包好的

**Comment by fanbingkun** [comment]
![image](https://user-images.githubusercontent.com/36094539/58524466-dcef7b00-81fa-11e9-8818-b9d05d3a1064.png)
入口找不到 是吗

**Comment by ustbhuangyi** [comment]
多谢反馈，我们这边查一下

**Comment by theniceangel** [comment]
> 也没有dist打包好的

现在可以了，但是必须指定 npm-tag，试试。
```shell
npm install @better-scroll/core@next
```

**Comment by fanbingkun** [comment]
xiexie

**Comment by fanbingkun** [comment]
好像还是不行  没有这个版本哦
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @better-scroll/shared-utils@^2.0.0-alpha.7
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@better-scroll/core'
npm ERR! notarget

**Comment by theniceangel** [comment]
> 好像还是不行 没有这个版本哦
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for @better-scroll/shared-utils@^2.0.0-alpha.7
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget
> npm ERR! notarget It was specified as a dependency of '@better-scroll/core'
> npm ERR! notarget

我们这边试了一下是ok的，你可以删掉 `lock` 文件或者 `node_modules`。
