### ISSUE TITLE
npm install @better-scroll/core@next --save 还是不行哦

### ISSUE THREAD

**Issue by fanbingkun** [ustbhuangyi/better-scroll#804]
![image](https://user-images.githubusercontent.com/36094539/58601646-5307e680-82bc-11e9-90d7-b60ad364c830.png)
还是不行啊
你们可以嘛

**Comment by theniceangel** [comment]
我用 npm 和 yarn 都可以

**Comment by ustbhuangyi** [comment]
@fanbingkun 我这边亲测可以
