### ISSUE TITLE
pullingUp的兼容问题

### ISSUE THREAD

**Issue by richardsmogodb** [ustbhuangyi/better-scroll#805]
Version
1.12.6

Steps to reproduce
**Edge**下设置`mouseWheel`和`pullUpLoad`为true，监听`pullingUp`事件，鼠标滑轮滑到scroll底部并没有触发`pullingUp`事件，在**firefox**和**chrome**下均可以触发。

What is expected?
Edge下能够触发`pullingUp`事件。

What is actually happening?
Edge下不能够触发`pullingUp`事件。

**Comment by shijunti19** [comment]
我也是，这个必须支持啊，不然滚轮支持就毫无用处，作者估计没做过一个完整的，不然不可能漏了这个

**Comment by shijunti19** [comment]
就是PC端我只有滚轮的时候
我PC滚轮的时候也不会触发pullUpLoad
![image](https://user-images.githubusercontent.com/5392211/64931217-a43ae680-d869-11e9-9a19-a9796dba430e.png)
this.bscroll.movingDirectionY是undefined，是个bug希望修复

**Comment by luciy** [comment]
今天同样遇到这个问题，在拖动 scrollbar 时候不触发 pullUpLoad。 临时解决方法  this.BScroll.movingDirectionY = 1; 。

**Comment by theniceangel** [comment]
fixed in v2.0.0
