### ISSUE TITLE
如何禁止鼠标中键的滚动? 就是滚轮滚动

### ISSUE THREAD

**Issue by caihuattkl** [ustbhuangyi/better-scroll#806]
实例化 bs 的时候，第二个参数 `options` 不要有 `mouseWheel ` 属性。

_Originally posted by @theniceangel in https://github.com/ustbhuangyi/better-scroll/issues/801#issuecomment-496062195_

**Comment by caihuattkl** [comment]
https://github.com/ustbhuangyi/better-scroll/issues/801

**Comment by caihuattkl** [comment]
@theniceangel 不行吧? 我看了.没有这个属性啊

**Comment by theniceangel** [comment]
贴下你实例化bs的代码吧
