### ISSUE TITLE
官方picker两联联动大bug

### ISSUE THREAD

**Issue by dydoit** [ustbhuangyi/better-scroll#807]
在做移动端日期组件的时候使用了picker组件，选择2018年12月份后，再点击弹出picker组件，此时滚动年份到2019年时，月份不是滚动到1月，而是滚动到最后一栏（本人例子是5月），但是点击确认时选中的依然是2019年1月！亲测了几次都这样

**Comment by theniceangel** [comment]
能提供线上链接么

**Comment by dydoit** [comment]
https://ordertest.beautyyan.cn/

**Comment by dydoit** [comment]
执行wheelTo(0)后月份滑动到1月，然后迅速被源码里的resetPosition方法重新把位置滑动到最尾部

**Comment by dydoit** [comment]
https://ordertest.beautyyan.cn/




| |
邓寅
|
|
邮箱：18565125218@163.com
|

签名由 网易邮箱大师 定制

在2019年05月30日 19:22，JiZhi 写道：

能提供线上链接么

**Comment by theniceangel** [comment]
@dydoit 看代码你好像用的是之前 `example` 下的 `picker.vue` 和 `city-picker.vue` 的代码。你可以看下最新的代码 `picker.vue` 的 `scrollTo` 和 `city-picker.vue` 的 `handlechange` 逻辑都发生了相映的变化。
