### ISSUE TITLE
直接能支持ts吗？还是配置啥就可以支持？

### ISSUE THREAD

**Issue by kezhongfa** [ustbhuangyi/better-scroll#808]
版本： "@better-scroll/core": "^2.0.0-alpha.9","typescript": "^3.4.3",

![image](https://user-images.githubusercontent.com/6939549/58695479-19240680-83c8-11e9-8e5c-95cc2ac4affb.png)

**Comment by Sakura-1997** [comment]
a

**Comment by theniceangel** [comment]
请安装下最新的版本`npm install @better-scroll/core@next`。
