### ISSUE TITLE
轮播图在切换到其它组件后切回来的BUG！

### ISSUE THREAD

**Issue by yanpengxiang** [ustbhuangyi/better-scroll#81]
1.课程进度第四章第六节，按照老师的代码完成之后，我发现切换到其它组件你等个几秒切回来轮播图就不动了。
2.destroyed这个钩子里面清除定时器的代码貌似木有执行。
3.我以为是我哪里写错了但是我看了下http://vuemusic.t.imooc.io/里面的demo也有这个问题。

**Comment by ustbhuangyi** [comment]
课程的问题不要在这里开 issue，课程项目的代码已经有 issue 修复了这个问题，去那里看吧
