### ISSUE TITLE
定位失效，怎么解决

### ISSUE THREAD

**Issue by leewayjean** [ustbhuangyi/better-scroll#814]
### Version
1.15.0

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll](https://github.com/ustbhuangyi/better-scroll)

### Steps to reproduce
使用better-scroll，固定定位失效

### What is expected?
我希望实现一个滚动吸顶效果

### What is actually happening?
页面滚动，某个元素到达指定位置时，我希望它是固定住的，动态添加样式。使用position：fixed固定在屏幕某个位置。没有预期的效果，定位失效

**Comment by theniceangel** [comment]
可以参考下 demo 的 index-list
