### ISSUE TITLE
[New Feature] infinity 外部如何添加数据

### ISSUE THREAD

**Issue by cherishstand** [ustbhuangyi/better-scroll#815]
### What problem does this feature solve?
infinity 无限滚动时，现有的是用fetch请求数据，Vue环境下， 如果需求是聊天室中初始化30条历史数据，其他数据用websocket不定时添加，请问，我该怎么做啊???

### What does the proposed API look like?
No, Im sorry

**Comment by theniceangel** [comment]
考虑自己保存一个 data pool。每次 fetch 触发之后，就去这个池子里面拉新数据。
