### ISSUE TITLE
[New Feature] 能否在PC端禁用touch事件

### ISSUE THREAD

**Issue by qmhc** [ustbhuangyi/better-scroll#818]
### What problem does this feature solve?
在PC端上系统能只是用wheel滚动

### What does the proposed API look like?
就像IScroll那样 options.disableTouch = true

**Comment by theniceangel** [comment]
你说的是鼠标事件吧

**Comment by qmhc** [comment]
> 你说的是鼠标事件吧

我已经发现，`options.disableMouse` 就是我想要的配置项，配置 `options.disableMouse = false ` 并且开启 `mouse-wheel` 插件就是我描述的效果了
