### ISSUE TITLE
官网 示例的源码有下载地址吗？

### ISSUE THREAD

**Issue by pretty8816** [ustbhuangyi/better-scroll#822]
比如 官网示例的这个链接的案例，https://ustbhuangyi.github.io/better-scroll/#/examples/nav-list/1/zh

请问大家，有没有下载源码的地址

**Comment by theniceangel** [comment]
better-scroll 1.0 的代码都放在 `v1` 分支下了，切换到这个分支下，代码都在 `examples` 目录下。

**Comment by pretty8816** [comment]
谢谢，找到了
