### ISSUE TITLE
2.0的中scrollToElement方法出错

### ISSUE THREAD

**Issue by Jonny0601** [ustbhuangyi/better-scroll#824]
2.0的中scrollToElement方法 没有被代理到 BScroll 的实例对像上，需要使用this.scroll.scroller.scrollToElement访问，但是调用this.scroll.scroller.scrollToElemen后该方法抛出"TypeError: Cannot read property 'left' of undefined"，scrollToElemen方法中this.wrapperOffset不存在导致抛出left不存在错误

**Comment by linkwanggo** [comment]
今天遇到scrollToElement not a function问题，看了你的回答之后豁然开朗 感谢~

**Comment by theniceangel** [comment]
@Jonny0601 @linkwanggo fix at `2.0.0-alpha.14`

**Comment by Jonny0601** [comment]
@theniceangel 👍

**Comment by Jonny0601** [comment]
@linkwanggo 可以暂时用scrollTo代替，因为scrollToElement其实也是用scrollTo实现的
