### ISSUE TITLE
禁用touch功能描述错误。

### ISSUE THREAD

**Issue by Yxjhasadream** [ustbhuangyi/better-scroll#825]
### Version
1.15.0

### Reproduction link
[https://codepen.io/anon/pen/wLaEzp](https://codepen.io/anon/pen/wLaEzp)

### Steps to reproduce
创建一个滚动条对象，并给配置中的参数传入
var wrapper = document.querySelector('.wrapper');
    var scroll = new BScroll(wrapper, {
        scrollbar: {
            fade: false,
            interactive: true // 1.8.0 新增
        },
        mouseWheel: {
            speed: 20,
            invert: false,
            easeTime: 300
        },
        disableTouch: true,
        // 感觉better-scroll的文档描述有问题，应该是源码弄错了，把禁用touch和禁用鼠标搞反了。 禁用了鼠标反而把touch功能给禁了。
        //disableMouse:true 
    });

### What is expected?
此时将不再能够通过拖动元素来使页面滚动

### What is actually happening?
然而仍然能够拖动页面元素让页面滚动，反而将参数改为disableMouse:true  即禁用鼠标后，将无法直接拖动，效果上与禁用touch一致。应该是源码在获取参数时将两个才参数弄反了。

**Comment by Yxjhasadream** [comment]
![image](https://user-images.githubusercontent.com/35222088/59417584-1da1e380-8dfa-11e9-9b3c-a0fa8b43ee6c.png)
我只在源码中找到了这一段，具体是不是它产生的作用，无法确定，这个hasTouch是从另外一个文件env.js中通过判断window对象和创建div元素来得到的。 


    if (!this.options.disableMouse) {
      eventOperation(this.wrapper, 'mousedown', this)
      eventOperation(target, 'mousemove', this)
      eventOperation(target, 'mousecancel', this)
      eventOperation(target, 'mouseup', this)
    }

    if (hasTouch && !this.options.disableTouch) {
      eventOperation(this.wrapper, 'touchstart', this)
      eventOperation(target, 'touchmove', this)
      eventOperation(target, 'touchcancel', this)
      eventOperation(target, 'touchend', this)
    }

如果确实就是上面的代码产生了最终鼠标是加你的效果，那么当配置了disableMouse 为true的时候，理论上不应该会添加上鼠标的相关事件。。。所以应该还有别的地方有做处理？   我是在chrome和火狐下都会有这个问题。
chrome 版本 69.0.3497.100（正式版本） （64 位）
firefox 版本 67.0.2 (64 位)
这份demo也能很好的复现这个问题。
https://codepen.io/anon/pen/wLaEzp

**Comment by theniceangel** [comment]
@Yxjhasadream disableMouse 为 true 的时候，的确不会添加鼠标的相关事件，这块源码也没有错误。

**Comment by Yxjhasadream** [comment]
@theniceangel  所以如果我想禁用掉touch事件的正确方式应该是什么呢？我现在是把鼠标给禁用了（disableMouse=true），反而导致了touch失效，正是我想要的效果。。而文档中很明显的描述了。disableTouch 如果是true，将会不再监听touch的相关事件，但是我设置了之后，仍然监听了touch事件，，反而是我把disableMouse设置为true后，touch事件不再被监听了。
![image](https://user-images.githubusercontent.com/35222088/59506078-e99def80-8ed9-11e9-9200-ad7b84d9275e.png)

**Comment by theniceangel** [comment]
@Yxjhasadream 我就是根据你给的 codepen 的代码，实例化 bs，并不会监听 touch 事件。
![image](https://user-images.githubusercontent.com/25956811/59552965-c863fe80-8fc0-11e9-92b4-2e6fece22517.png)

**Comment by Yxjhasadream** [comment]
@theniceangel 抱歉。我属于前端新手，应该是我对于touch事件的理解和认知有问题。。默认把touch和 “鼠标直接拖动元素进行滚动” 给直接关联了。。。。我的需求应该是要 “禁用鼠标能直接通过拖动元素来进行滚动的功能”  而不是“禁用touch”。。因为在我看来，touch事件是导致鼠标拖动页面元素就能让页面滚动起来的原因。。。。。所以，有办法    禁用“鼠标直接通过拖动元素来进行滚动”这个功能  吗？

**Comment by theniceangel** [comment]
disableMouse 就是不注册 click 事件， disableTouch 就是不注册 touch 事件，如果你是在 PC 场景并且只想通过鼠标滚轮交互，那就把这两个都设置为 true。如果是在手机的场景，这两个保持默认就行了

**Comment by Yxjhasadream** [comment]
看你话的意思，原来这两个属性都是针对手机场景的设置嘛？好吧。。感谢你的回答。我知道要怎么弄了。
