### ISSUE TITLE
老哥，BS2.0，用滚轮控制时候没有出现滚动条，touch的时候会有

### ISSUE THREAD

**Issue by MmmMMMmmmyang** [ustbhuangyi/better-scroll#826]

**Comment by theniceangel** [comment]
麻烦贴一下使用时候的代码

**Comment by MmmMMMmmmyang** [comment]
因为现在用的是我自己封装好的BS1.0，想迁移至2.0，而且项目需求是移动PC都能滚动，而且都要有滚动条，下面这个是我自己拿官方DEMO测试的代码，就发现滚轮滚动时候没有滚动条。

`<script type="text/ecmascript-6">
import BScroll from "@better-scroll/core";
import ScrollBar from "@better-scroll/scroll-bar";
import MouseWheel from "@better-scroll/mouse-wheel";
import PullDown from '@better-scroll/pull-down'

BScroll.use(ScrollBar);
BScroll.use(MouseWheel);
BScroll.use(PullDown)

export default {
  data() {
    return {
      emojis: [
        "😀 😁 😂 🤣 😃",
        "😄 😅 😆 😉 😊",
        "😫 😴 😌 😛 😜",
        "👆🏻 😒 😓 😔 👇🏻",
        "😑 😶 🙄 😏 😣",
         "😀 😁 😂 🤣 😃",
        "😄 😅 😆 😉 😊",
        "😫 😴 😌 😛 😜",
        "👆🏻 😒 😓 😔 👇🏻",
        "😑 😶 🙄 😏 😣",
         "😀 😁 😂 🤣 😃",
        "😄 😅 😆 😉 😊",
        "😫 😴 😌 😛 😜",
        "👆🏻 😒 😓 😔 👇🏻",
        "😑 😶 🙄 😏 😣",
      ]
    };
  },
  mounted() {
    this.init();
  },
  beforeDestroy() {
    this.bs.destroy();
  },
  methods: {
    init() {
      this.bs = new BScroll(this.$refs.scroll, {
        scrollY: true,
        scrollY: true,
        click: true,
        probeType: 3,
        mouseWheel: {
          speed: 20,
          invert: false,
          easeTime: 300
        },
        scrollY: true,
        scrollbar: true,
        pullDownRefresh: true
      });
      this.bs.on('pullingDown', this.pullingDownHandler)
    },
    clickHandler(item) {
      // alert(item);
    },
    pullingDownHandler(){
      console.log(111111)
    },
    _registerHooks(hookNames, handler) {
      hookNames.forEach(name => {
        this.bs.on(name, handler);
      });
    }
  }
};
</script>`
