### ISSUE TITLE
在360极速浏览器上无法滚动

### ISSUE THREAD

**Issue by xwpongithub** [ustbhuangyi/better-scroll#827]
Version
1.15.2(换成1.13.0版本实验也有问题)

Reproduction link
https://codepen.io/xwpongithub/pen/zVvQgz

Steps to reproduce
用PC的360极速浏览器打开后滚动区不会滚动（webkit内核），滚动区wrapper也设置了固定高度，另外还试过chrome和firefox且能正常滚动

What is expected?
希望能解决下这个不会滚动的问题

**Comment by theniceangel** [comment]
360貌似有极速模式和兼容模式，是切到极速模式也报错么
