### ISSUE TITLE
slide插件loop为false时失效

### ISSUE THREAD

**Issue by Jonny0601** [ustbhuangyi/better-scroll#828]
2.0的silde插件，如果silde.loop设置为flase，就无法滚动，手动执行this.slide.next()或者this.slide.prev()也无效，只有设置loop为true才能正常使用

**Comment by theniceangel** [comment]
请提供下代码。

**Comment by Jonny0601** [comment]
我跑的是v2.0.0-alpha.14的，就修改了slide下面banner.vue的列子，
![image](https://user-images.githubusercontent.com/18041735/59558156-7d78d400-901e-11e9-8b16-84418ac716dd.png)，把silde的loop改为false，确实拖不动了，难道是我浏览器的问题？chrome 74

**Comment by Jonny0601** [comment]
@theniceangel 还是下载的依赖有问题么
