### ISSUE TITLE
移动端使用better-scroll做横向滚动，手指上下滑动该区域不能使页面上下滚动问题

### ISSUE THREAD

**Issue by zhentonglee** [ustbhuangyi/better-scroll#829]
移动端使用better-scroll做横向滚动，希望手指上下滑动该区域时，能使页面正常上下滚动。

**Comment by theniceangel** [comment]
文档给出了：[常见问题](https://better-scroll.github.io/docs/zh-CN/FAQ/diagnosis.html#%E3%80%90%E9%97%AE%E9%A2%98%E4%BA%8C%E3%80%91%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E7%94%A8-betterscroll-%E5%81%9A%E4%BA%86%E6%A8%AA%E5%90%91%E6%BB%9A%E5%8A%A8%E4%B9%8B%E5%90%8E%EF%BC%8C%E7%BA%B5%E5%90%91%E6%BB%9A%E5%8A%A8%E5%A4%B1%E6%95%88%EF%BC%9F)
