### ISSUE TITLE
请问这个项目支持ssr么？

### ISSUE THREAD

**Issue by laojunpeng** [ustbhuangyi/better-scroll#83]
报错Cannot call a class as a function
at BScroll (bscroll.js:448)

如果支持ssr，请大神指教
import是这样写的
if (process.BROWSER_BUILD) {
  Vue.use(require('better-scroll'))
}

**Comment by ustbhuangyi** [comment]
better-scroll 的初始化时机需要 DOM 已经渲染了，而且它是原生 JS 写的，并不是 Vue 的插件。
