### ISSUE TITLE
click事件在disableMouse为true时设置eventPassthrough时会出现派发两次点击事件的情况

### ISSUE THREAD

**Issue by zhixinpeng** [ustbhuangyi/better-scroll#830]
先贴我的示例代码吧：https://codesandbox.io/s/vue-template-2ygxy?fontsize=14

首先产生的原因是：同时设置 eventPassthrough: "vertical", click: true, disableMouse: false。

产生的现象是：在移动端或移动端预览模式下打开 https://2ygxy.codesandbox.io/ 点击元素会派发两次_constructed: true的事件，而在PC端不会。

![image](https://user-images.githubusercontent.com/24643457/59736431-2bd58100-928c-11e9-8ac7-2bc35684de3d.png)

这里我为什么要设置disableMouse为false呢，因为不设置这个，在Thinkpad下的某些微信或企业微信PC端无法在滚动区域内派发点击事件，即便设置了 click: true 也不行。

以上，为何设置eventPassthrough之后会出现这种情况呢，如何避免？

**Comment by theniceangel** [comment]
出现这个问题是因为按照你如上的 `disableMouse` 的配置。在移动端既监听了 touch 也监听了 mouse 事件。BS 内部是会根据环境来计算应该监听 touch 还是 监听 mouse 事件。因为在某些微信，或者企业微信的 PC 的场景，探测到了 touch 事件（这个是微信的 BUG），所以那样的话，监听了 touch 和 mouse 事件，导致你的困扰。

解决的办法如下：

1. 当前是企业微信PC场景

```js
{
 disableMouse: false,
 disableTouch: true
}
```

具体的逻辑可以参考源码 [_handleDOMEvents](https://github.com/ustbhuangyi/better-scroll/blob/v1/src/scroll/init.js) 部分的逻辑。思路就是保证只监听一种类型的事件。

**Comment by zhixinpeng** [comment]
谢谢解答。按照这个方法可以解决我的问题。
