### ISSUE TITLE
slider轮播图bug

### ISSUE THREAD

**Issue by aikugui** [ustbhuangyi/better-scroll#831]
slider轮播图滚动从第一张滑动到第2张的时候有bug，之后就正常了

**Comment by theniceangel** [comment]
能否贴出具体的使用代码？

**Comment by Jonny0601** [comment]
@theniceangel 应该是用手指迅速来回切换的时候，getCurrentPage方法获得pageX会不准

**Comment by theniceangel** [comment]
因为目前维护了 1.x 与 2.x，所以需要告诉下我你正在使用的 version

**Comment by Jonny0601** [comment]
@theniceangel 目前据我所知的 2.x版本中的会有此问题，1.x版本没用过 slider功能
