### ISSUE TITLE
Typo in description of project

### ISSUE THREAD

**Issue by piotrgredowski** [ustbhuangyi/better-scroll#833]
### Version
1.15.0

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll](https://github.com/ustbhuangyi/better-scroll)

### Steps to reproduce
Open GH page of project.

### What is expected?
"(...) performance (...)" in description of project.

### What is actually happening?
"(...) perfErmance (...)" in description of project.

**Comment by theniceangel** [comment]
Sorry, can you list a detail link to reproduce the issue?
