### ISSUE TITLE
[New Feature] 是否有计划做一个 vue-virtual-scroll-list 的 plugin？

### ISSUE THREAD

**Issue by falstack** [ustbhuangyi/better-scroll#834]
### What problem does this feature solve?
better-scroll 已经为移动端的列表滚动做了极好的支持，但对于数据巨大的列表，因为 better-scroll 代理了滚动事件，所以无法与 vue-virtual-scroll-list 配合使用，是否有计划支持出一个 plugin？

### What does the proposed API look like?
https://github.com/tangbc/vue-virtual-scroll-list

**Comment by falstack** [comment]
发现最简单的方法就是把设置容器高度的 API 暴露出来，让使用者可以不调用 refresh，而是 setHeight（setWidth）

**Comment by ustbhuangyi** [comment]
可以使用 cube-ui 的 https://didi.github.io/cube-ui/#/zh-CN/docs/recycle-list
基于 bs 写的无限滚动在 1.x 版本上有，由于是用 transition 模拟的滚动，目前这些小瑕疵还无法解决。
https://github.com/ustbhuangyi/better-scroll/issues/580
而 cube-ui 这块是基于原生滚动去写的，不会有上述问题。
