### ISSUE TITLE
2.x中文文档缺失

### ISSUE THREAD

**Issue by yuzhengbo** [ustbhuangyi/better-scroll#835]
### Version
1.15.0

### Reproduction link
[https://better-scroll.github.io/docs/zh-CN/plugins/pullup.html#%E4%BB%8B%E7%BB%8D](https://better-scroll.github.io/docs/zh-CN/plugins/pullup.html#%E4%BB%8B%E7%BB%8D)

### Steps to reproduce
BetterScroll 2.x 插件文档：
https://better-scroll.github.io/docs/zh-CN/plugins/pullup.html#%E4%BB%8B%E7%BB%8D

### What is expected?
查看pullup插件教程

### What is actually happening?
只有使用教程，没有安装教程

---
pullup插件中文文档缺少安装教程

**Comment by theniceangel** [comment]
补充了。
