### ISSUE TITLE
[New Feature] 在 better-scroll 区域中希望可以阻止某一块区域的滑动

### ISSUE THREAD

**Issue by zboboan** [ustbhuangyi/better-scroll#837]
### What problem does this feature solve?
在移动端上 滑动中，有须求希望某一块区域不要滑动，但不阻止原生的拖动和手势，比如地图上有缩放，手势，但希望不要滑动，现在解决方案是用  disable 和 enable 方法切换，能不能有更简便的方法呢  

### What does the proposed API look like?
#可以阻止某一块区域的滑动

**Comment by theniceangel** [comment]
我们在 2.x 的版本会提供配置项，如果你现在用的是 1.x，目前你现在的做法是可取的

**Comment by zboboan** [comment]
> 我们在2.x的版本会提供配置项，如果你现在用的是1.x，目前你现在的做法是可取的

请问一下在 2.x中是怎么配置的呢？

**Comment by theniceangel** [comment]
@zboboan [BetterScroll 文档](https://better-scroll.github.io/docs/zh-CN/guide/base-scroll-options.html#tagexception)

**Comment by zboboan** [comment]
> 
> 
> @zboboan [BetterScroll 文档](https://better-scroll.github.io/docs/zh-CN/guide/base-scroll-options.html#tagexception)
万分感谢
