### ISSUE TITLE
[New Feature] 官方可以出个vue、react版的better-scroll吗？

### ISSUE THREAD

**Issue by 941477276** [ustbhuangyi/better-scroll#838]
### What problem does this feature solve?
目前在vue项目中使用better-scroll，自己封装的组件，但感觉很麻烦，better-scroll更新后又要去维护自己封装的组件

### What does the proposed API look like?
目前在vue项目中使用better-scroll，自己封装的组件，但感觉很麻烦，better-scroll更新后又要去维护自己封装的组件

**Comment by theniceangel** [comment]
react 版本考虑在后期加入，目前文档是 vue 的
