### ISSUE TITLE
使用React.lazy动态加载组件失败

### ISSUE THREAD

**Issue by solayao** [ustbhuangyi/better-scroll#839]
目的： 想抽象一个公用的Scroll组件，通过懒加载动态加载组件

官方建议组件加载方式： import ScrollBar from '@better-scroll/scroll-bar';
调用React.lazy懒加载: const ScrollBar = React.lazy(() => import('@better-scroll/scroll-bar'));

注册：BScroll.use(ScrollBar); 并设置相关属性

启动后，控制台报: [BScroll warn]: Plugin Class must specify plugin's name in static property by 'pluginName' field.

并且ScrollBar相关样式没有正确渲染出来。

问题：是否支持懒加载组件？

**Comment by theniceangel** [comment]
这个方法应该是用来动态引入 react 组件的，而 ScrollBar 并不是一个组件

**Comment by solayao** [comment]
那对于插件是否有动态引入的概念呢？毕竟用import导入插件后，组件文件大小就会稍微增大。或者是想抽象出一个组件的话只能用具备所有插件能力的 BetterScroll？但是有很多情况下所有插件的功能并不是都能使用上

**Comment by solayao** [comment]
> 这个方法应该是用来动态引入 react 组件的，而 ScrollBar 并不是一个组件

那对于插件是否有动态引入的概念呢？毕竟用import导入插件后，组件文件大小就会稍微增大。或者是想抽象出一个组件的话只能用具备所有插件能力的 BetterScroll？但是有很多情况下所有插件的功能并不是都能使用上

**Comment by theniceangel** [comment]
@solayao 按照react的lazy用法，你只需要抽象一个组件，组件里面用了 BetterScroll，然后动态加载这个组件即可。
