### ISSUE TITLE
[New Feature] 嵌套scroll问题

### ISSUE THREAD

**Issue by Feng-Bu-Jue** [ustbhuangyi/better-scroll#840]
### What problem does this feature solve?
是否支持 prevent子元素滑动，让父元素滑动到底后 在不touchend的情况下 继续滑动子元素

### What does the proposed API look like?
可以改变touchmove作用的目标？

**Comment by Feng-Bu-Jue** [comment]
![2019-07-02_17_10_27](https://user-images.githubusercontent.com/31085556/60502070-a4f2c080-9cef-11e9-8f9e-b38d861bb5ab.gif)
类似于这样的效果

**Comment by dolymood** [comment]
https://didi.github.io/cube-ui/example/#/scroll/h-scrolls

https://didi.github.io/cube-ui/example/#/scroll/v-scrolls

供参考，这个在2.x的即将新来的beta中会增加这个的原生支持
