### ISSUE TITLE
window.performance.timing.navigationStart failed on iOS 8

### ISSUE THREAD

**Issue by codingfishman** [ustbhuangyi/better-scroll#841]
### Version
1.15.2

### Reproduction link
[https://codesandbox.io/embed/vue-template-lxxqv](https://codesandbox.io/embed/vue-template-lxxqv)

### Steps to reproduce
1. try initiate a BScroll 
2. run on iOS 8
3. failed to scroll 

### What is expected?
scroll normally 

### What is actually happening?
cannot scroll

---
the code is right here: https://github.com/ustbhuangyi/better-scroll/blob/v1.15.0/src/util/lang.js#L2

while iOS 8 has the `window.performance.now, it doesn't have the `window.performance.timing`.

**Comment by zw888** [comment]
你解决了么？我也出现了

**Comment by dolymood** [comment]
建议先 hack 下 timing

```js
if (!performance.timing) {
  performance.timing = {}
  Object.defineProperty(performance.timing, 'navigationStart', {
    get: function () {
      return Date.now() - performance.now()
    }
  })
}
```
