### ISSUE TITLE
better-scroll在vant popup组件中，移动端无法向上滚动

### ISSUE THREAD

**Issue by qianbimomo** [ustbhuangyi/better-scroll#843]
### Version
1.8.1

### Reproduction link
[https://codesandbox.io/embed/vue-template-o7m14](https://codesandbox.io/embed/vue-template-o7m14)

### Steps to reproduce
1.pc端浏览滚动条正常

2.chrome远程调试移动端浏览，向下可以滚动，向上无效

### What is expected?
如何处理vant,popup组件和滚动条冲突

### What is actually happening?
移动端滚动条和vant，popup组件冲突

---
把vant组件popup替换为div，移动端滚动条正常

**Comment by theniceangel** [comment]
延迟实例化 bs 试试

**Comment by vok123** [comment]
new BetterScroll(wrapper, {
      bindToWrapper: true
});
bindToWrapper设置为true

**Comment by qianbimomo** [comment]
设置bindToWrapper属性后，移动端滚动条正常，谢谢！

**Comment by nongzhenli** [comment]
赞！解决了我的苦恼、

**Comment by wyh-skr** [comment]
> 设置bindToWrapper属性后，移动端滚动条正常，谢谢！

赞赞赞

**Comment by a798032825** [comment]
必须点赞，今天用vant popup组件遇到这个问题。亲测有效，感谢！

**Comment by wwdDongDong** [comment]
> 设置bindToWrapper属性后，移动端滚动条正常，谢谢！

good for you
