### ISSUE TITLE
2.0版本使用slide插件动态渲染banner问题

### ISSUE THREAD

**Issue by Juice4213** [ustbhuangyi/better-scroll#844]
![image](https://user-images.githubusercontent.com/19168944/60727271-1771d380-9f70-11e9-908d-d6624a3103c8.png)
动态渲染image时无法计算内容的宽度，报错
![image](https://user-images.githubusercontent.com/19168944/60727360-4be58f80-9f70-11e9-8b8a-0f97c6147aa3.png)

**Comment by mingtail** [comment]
![Image_1](https://user-images.githubusercontent.com/23714225/60753620-ef35b380-a007-11e9-8e83-ea40cee767d8.png)
看报错位置 children[0] 元素找不到. 在初始化时候 'bannerImgs' 异步获取造成的. 
应该获取数据后初始化, 或者在 '.slide-banner-scroll' 元素上添加 v-if="bannerImgs.length"

**Comment by theniceangel** [comment]
请提供代码

**Comment by theniceangel** [comment]
@Juice4213 插件内部断言你的子元素依据存在，请确保所有 DOM 元素渲染之后，再初始化 bs。

**Comment by Juice4213** [comment]
> ![Image_1](https://user-images.githubusercontent.com/23714225/60753620-ef35b380-a007-11e9-8e83-ea40cee767d8.png)
> 看报错位置 children[0] 元素找不到. 在初始化时候 'bannerImgs' 异步获取造成的.
> 应该获取数据后初始化, 或者在 '.slide-banner-scroll' 元素上添加 v-if="bannerImgs.length"

嗯，是异步的问题，已解决
