### ISSUE TITLE
BS2.0中disableMouse配置为false，出现触屏无法滚动的问题（目的是兼容平板可触屏亦可鼠标控制）

### ISSUE THREAD

**Issue by MmmMMMmmmyang** [ustbhuangyi/better-scroll#847]
在1.0中，因为要兼容平板电脑使用鼠标点击，所以将disableMouse设置为false（如果不设置false，平板将无法用鼠标进行点击），移动端PC端平板端均可正常使用。

但是在迁移2.0的时候将disableMouse设置为false，无论真机、浏览器或平板，触屏均无法滚动！（touch可点击无法滚动，滚轮可点击可滚动）

**Comment by theniceangel** [comment]
@MmmMMMmmmyang 在 1.0 当中，这样配置的话，会监听 mouse 以及 touch 事件，这样会导致 https://github.com/ustbhuangyi/better-scroll/issues/830 的问题。所以在 2.0 里面，监听事件只能是一种，要么是 touch，要么是 mouse。

**Comment by MmmMMMmmmyang** [comment]
@theniceangel 那是不是意味着BS2.0中平板电脑只能使用触摸，而不能使用触摸和外接鼠标同时控制滚动？或者有没有办法在平板电脑中可以同时使用触摸和鼠标，但不会影响纯移动端和纯PC端？

**Comment by MmmMMMmmmyang** [comment]
@theniceangel 老哥，我写了demo测试了一下你说的问题
1.在1.0中设置disableMouse:false时，只要避免设置eventPassthrough，点击事件依旧是只派发一次（无论PC还是移动端或者微信开发者工具），那对我这种不设置eventPassthrough的开发者来说，是不是等于无bug？
2.有个小建议，因为现在平板电脑外接鼠标键盘，或者可拆卸电脑越来越多，BS2.0只能监听一种会不会不太妥。派发两种并在文档写清楚注释会不会更好点。

**Comment by theniceangel** [comment]
@MmmMMMmmmyang 嗯，我们内部讨论下吧，如果考虑到你这种场景，可能就得放开了。

**Comment by theniceangel** [comment]
@MmmMMMmmmyang 我们会在下一个 alpha 版本加入，发版之后，会让你测一下。

**Comment by MmmMMMmmmyang** [comment]
@theniceangel 好的我的哥😀😀

**Comment by Yxjhasadream** [comment]
借楼。 @theniceangel   老哥。我想请问一下。我如果想在PC端使用，如何模拟我们通常的滚动条行为？即:
1.鼠标滚动，滚动条跟着动（这个目前没问题）
2.直接拖拽滚动条进行滚动（这个目前进行一些设置，滚动条设置为可交互即可）
3.不能直接按住鼠标左键来拖动（这个目前单独设置也可以，但是和2一起的时候似乎就不管用了）
目前碰到的情况是。2和3不知道要怎么设置才能兼容到一起。
目前观测到的情况是

disableTouch: true,disableMouse:false  可以拖动滚动条，滚轮也能生效，但是也可以直接拖动页面元素（类似触屏直接手势滚动那种效果，希望禁用这种效果，但是似乎和touch没关系。虽然我按我的理解，touch应该就是用来监听处理我直接拖动元素的配置项）

disableTouch: true,disableMouse:true   滚轮生效，但是无法拖动滚动条了。页面元素也达到预期，无法拖动了。（希望在这种情况下能拖动滚动条。）


不知道上述的预期应该怎么配置。如果方便的话。希望能帮我看看。。。感谢。

**Comment by theniceangel** [comment]
@MmmMMMmmmyang 试一下最新的版本 `v2.0.0-alpha.20`。

**Comment by Yxjhasadream** [comment]
@theniceangel 2.0可以支持我上面说的那样吗？我试试看先，谢谢哦。

**Comment by theniceangel** [comment]
@Yxjhasadream 你这个交互也忒复杂了吧，能尽量简单化么，先贴代码吧

**Comment by Yxjhasadream** [comment]
@theniceangel  复杂还好吧。。就是类似于想要一个带有能指定滚动到哪儿的API的滚动条。不要有其他的侵入性。。https://codepen.io/anon/pen/wLaEzp   我希望这个demo里面，能够无法拖动那一排的1。就是预期效果。

**Comment by theniceangel** [comment]
@Yxjhasadream 按你的需求，应该不行的

**Comment by Yxjhasadream** [comment]
@theniceangel  好吧。。那方便大致和我说说。直接拖动那一排的1（页面dom元素），是什么事件决定的吗？还是说是由什么机制决定的？

**Comment by MmmMMMmmmyang** [comment]
@theniceangel 老哥，我用同事的平板电脑外接鼠标测试鼠标控制和触屏控制，当disableMouse设置为false时，可以滚动和点击，不设置disableMouse时，平板电脑外接鼠标不能点击，这和预想的一样。以后如果有什么问题我再及时反馈。

**Comment by qmhc** [comment]
@Yxjhasadream 我在vue项目中使用2.0.0-alpha.12版本时遇到了和你一样的需求和问题，最后我是自己实现滚动条，结合bs的api完成需求的

**Comment by Yxjhasadream** [comment]
> @qmhc  好吧。。意思是，你用默认的浏览器滚动条？然后结合API来实现滚动到指定位置？

**Comment by qmhc** [comment]
@Yxjhasadream 自己实现一个滚动条组件，一些滚动的信息通过bs的api获取，相互的关联也是通过api交互

**Comment by linzhenzhen** [comment]
> @Yxjhasadream 自己实现一个滚动条组件，一些滚动的信息通过bs的api获取，相互的关联也是通过api交互

这个能请教一下，稍微具体的事件和处理思路吗？比如怎么实现的滚动条组件。
我目前的场景是横向滚动，只能 touch 拖拽浏览，不能使用 touch scroll 或者鼠标的 scroll。
感谢～

**Comment by qmhc** [comment]
@linzhenzhen 其实滚动条组件需要知道几个属性即可，首先是可视区的宽度和内容总宽度，这两个用于计算滚动条长度，最好画画图理解一下可视区宽度、内容总宽度、滚动条长度、滚动条容器总长度这4个值之间的关系，之后相互间的交互就是通过props和事件了，我是分别计算位置的百分比来传递的，理论上可以做双向绑定（虽然我没弄）

**Comment by theniceangel** [comment]
由于在某些特殊的设备上，用户可能希望既监听 mouse 又监听 touch 事件，所以可以通过以下的配置来达到效果。

```js
{
    disableMouse: false,
    disableTouch: false
}
```

**Comment by lunzilunzi** [comment]
> 借楼。 @theniceangel 老哥。我想请问一下。我如果想在PC端使用，如何模拟我们通常的滚动条行为？即:
> 1.鼠标滚轮滚动，滚动条跟着动（这个目前没问题）
> 2.直接拖拽滚动条进行滚动（这个目前进行一些设置，滚动条设置为可交互即可）
> 3.不能直接按住鼠标左键来拖动（这个目前单独设置也可以，但是和2一起的时候似乎就不管用了）
> 目前碰到的情况是。2和3不知道要怎么设置才能兼容到一起。
> 目前观测到的情况是
> 
> disableTouch: true,disableMouse:false 可以拖动滚动条，滚轮也能生效，但是也可以直接拖动页面元素（类似触屏直接手势滚动那种效果，希望禁用这种效果，但是似乎和touch没关系。虽然我按我的理解，touch应该就是用来监听处理我直接拖动元素的配置项）
> 
> disableTouch: true,disableMouse:true 滚轮生效，但是无法拖动滚动条了。页面元素也达到预期，无法拖动了。（希望在这种情况下能拖动滚动条。）
> 
> 不知道上述的预期应该怎么配置。如果方便的话。希望能帮我看看。。。感谢。

@theniceangel 他可能说得太复杂了, 其实他想要就是正常的PC端滑动逻辑而已...
1. 可以鼠标滚轮滑动
2. 可以拖动滚动条滑动
3. 不可以鼠标拖拽滑动

奈何自己是个做java的, 对js的工程化完全不了解, 短时间内不太看得懂源码, 不然可以试着修改一下

**Comment by lunzilunzi** [comment]
@theniceangel 而且我想了想, scrollbar 既然是个插件, 提供了 interactive 这个配置项(滚动条是否可以交互), 然而又得取决于 core 的 disableMouse!=true, 感觉这个设计挺矛盾的. 理论上来说, 他应该是 mouse touch 之外的第三种交互方式, 不该受它们两个的影响
