### ISSUE TITLE
组件在调用卸载函数时，后台报了一堆warning信息

### ISSUE THREAD

**Issue by solayao** [ustbhuangyi/better-scroll#848]
操作：在注销组件，调用destory()时，在控制台显示一堆warning
![image](https://user-images.githubusercontent.com/14294893/60799274-71a7aa00-a1a5-11e9-984f-541bff9ed797.png)
![image](https://user-images.githubusercontent.com/14294893/60799294-7bc9a880-a1a5-11e9-996e-a761a154a600.png)

虽然不影响操作，但是一堆warning信息提醒很碍眼，求帮忙解决。

**Comment by theniceangel** [comment]
请提供下你的代码。

**Comment by solayao** [comment]
@theniceangel 
项目链接: https://github.com/solayao/dizzyl-f-base/tree/master/src/components/Dizzy/Scroll
拉了项目后，在demo页已经有调用事例了， 打开控制台，然后点击 Test to jump 链接就可以重现了

**Comment by cuijing1031** [comment]
fixed in 2.0.0-alpha.19 version

**Comment by solayao** [comment]
@cuijing1031 thanks.
