### ISSUE TITLE
上拉长列表性能瓶颈

### ISSUE THREAD

**Issue by carrollcai** [ustbhuangyi/better-scroll#849]
项目中能对一些导致重排的操作，做一些节流处理吗

比如
`document.documentElement.scrollLeft || window.pageXOffset || document.body.scrollLeft`

`let matrix = window.getComputedStyle(this.scroller, null)`

在长列表里，是性能瓶颈，有一半的时间都在Rerendering。

![image](https://user-images.githubusercontent.com/17819303/60855398-1e316c80-a236-11e9-96d2-064bdf0edf76.png)

**Comment by theniceangel** [comment]
如果是长列表，建议使用虚拟滚动列表

**Comment by carrollcai** [comment]
> 如果是长列表，建议使用虚拟滚动列表

我们尝试用了react-virtualized虚拟滚动列表，但是它无法控制滚动的粒度，下拉比较快时，会长时间白屏。因为数据的渲染在滚动之后。还有一个问题，我们可以增大虚拟滚动的高度，但是这样会在首屏的时间，加载过多的数据。

**Comment by carrollcai** [comment]
我大概读了一下better-scroll的代码，_startProbe方法中，如果用requestAnimationFrame帧渲染，会不断触发getComputedPosition，导致一直重排，这是性能瓶颈，请问有什么magic方法，可以减少_startProbe的probe调用吗

**Comment by theniceangel** [comment]
这个问题在于如果使用 css transition 去滚动的话，bs 需要实时派发当前滚动的位置，所以 _startProbe 是必须的。如果你设置 useTransition 为 false，那么就会用 requestAnimationFrame，不会导致 getComputedStyle 的 reflow。

**Comment by carrollcai** [comment]
这是个死循环，如果useTransition设置为true，那么列表滑动时，像放ppt一样卡，这更无法接受。请问滴滴有成熟滚动列表的产品或者市面上有使用bs完成长列表的吗？我调研了头条、拼多多、饿了么都是采用传统的scroll滚动。是否现在的移动浏览器就无法使用transform做长列表滚动？

**Comment by theniceangel** [comment]
@carrollcai cube-ui 有个 recycle-list 是我写的，你可以参考下。

**Comment by carrollcai** [comment]
在长列表，transform的稳定性（fps）不如scroll滑动，尤其是划得快的情况。我们会继续关注bs的，其他方面比如轮播，tab切换，bs还是很给力的。谢谢解答。

**Comment by weituotian** [comment]
better-scroll不能加入虚拟列表功能吗？，如果用户一直在那翻页，数据越来越多，最后爆满了怎么办？

**Comment by fantasy525** [comment]
@weituotian 虚拟滚动应该不是滚动插件做的事情，可以结合这个滚动插件自己做虚拟列表。不过2022年可以尝试用css的content-visibility试试
