### ISSUE TITLE
异步返回数据，无法滚动

### ISSUE THREAD

**Issue by 1309954466** [ustbhuangyi/better-scroll#85]
jquery 异步返回数据后，强制刷新，无法滚动了

var _self = this;

        this.oScroll = new BScroll(_self.$refs.orderWrapper, {
          click: true
        });

$.ajax({
          url:_self.$store.state.ipAddress + 'OrderComment',
          type:'Get',
          dataType:  "json",
          data:{id:'12'},
          contentType: "application/json",
          success:function(msg) {
            console.log("s:" + msg.Count);
            _self.rowcount = parseInt(msg.Count);
            for (var i = 0; i < _self.rowcount; i++) {
              _self.viewModel.goodorder.push({name: "a1", shopname: "123", zl: "", jg: "", scount: 0});
            }
            _self.oScroll.refresh();
          }

**Comment by helei112g** [comment]
vue2, better-scroll0.3.2遇到同样的问题。首次进入加载正常。

拉到底部加载更多，this.scroll && this.scroll.refresh() 刷新后，
```
refresh===this.scroll.y 0
refresh===this.scroll.maxScrollY 0
```
距离都变成0了。
是按照 [当 better-scroll 遇见 Vue ](https://github.com/DDFE/DDFE-blog/issues/15)文档封装的组件

**Comment by ustbhuangyi** [comment]
数据更新后，需要延时刷新 scroll
