### ISSUE TITLE
picker 组件渲染不同数据多次调起样式显示有问题

### ISSUE THREAD

**Issue by gzh4213** [ustbhuangyi/better-scroll#850]
多次调起渲染不同数据会出现如图所示问题，滑动一下屏幕数据又正常了
![image](https://user-images.githubusercontent.com/19168944/60888605-c45a9200-a289-11e9-87cd-d2ae161d6c51.png)
第一次调起
![image](https://user-images.githubusercontent.com/19168944/60888671-f53ac700-a289-11e9-9677-7b7dfcf63f3d.png)
第二次调起
![image](https://user-images.githubusercontent.com/19168944/60888715-0be11e00-a28a-11e9-9042-2006c805c4af.png)
第三次调起就出现问题了

![image](https://user-images.githubusercontent.com/19168944/60889663-1f8d8400-a28c-11e9-8454-662b974a505e.png)
![image](https://user-images.githubusercontent.com/19168944/60889685-2d430980-a28c-11e9-859f-cf0a1f278fff.png)

![image](https://user-images.githubusercontent.com/19168944/60889223-28ca2100-a28b-11e9-9ddc-a43162cd0d3f.png)

看源码里rotateX方法中第二次渲染数据时，this.items.length的还是第一次数据的长度

**Comment by theniceangel** [comment]
提供下代码吧

**Comment by Juice4213** [comment]
> 提供下代码吧
![image](https://user-images.githubusercontent.com/19168944/60938911-628d3d00-a308-11e9-95e6-0fb8ef0d0d7f.png)

代码就是在demo基础上修改的样式，代码只做了以上改动，数据作为组件属性传入

**Comment by theniceangel** [comment]
@Juice4213 有线上复现的demo么？
