### ISSUE TITLE
如何在滚动的时候改变指示点，而不是滚动结束后改变指示点

### ISSUE THREAD

**Issue by mentoorliubin** [ustbhuangyi/better-scroll#851]
如何在滚动的时候改变指示点，而不是滚动结束后改变指示点?现在用的是scrollEnd时间来获取指示点下标，可是我想做到滚动的同时指示点跟着变样式，这样如何解决呢

**Comment by theniceangel** [comment]
@mentoorliubin 目前我们是在滚动完成之后，计算 index。你这个需求，我们考虑下

**Comment by theniceangel** [comment]
@mentoorliubin 试一下 `v2.0.0-alpha.20` 这个版本，代码实例参考:
![image](https://user-images.githubusercontent.com/25956811/61210574-7a612880-a72f-11e9-8e9e-e104bd5ab8f5.png)
