### ISSUE TITLE
webview中使用 scrollTo  方法兼容问题

### ISSUE THREAD

**Issue by wumiangithub** [ustbhuangyi/better-scroll#852]

**Comment by wumiangithub** [comment]
在部分华为，或者小米8/小米mix2s  等等一些机型中。。
在android的webview中使用scrollTo  会出现回弹问题，并且滚动不到指定位置。横向tag滚动。
 this.scroll = new BScroll(this.$refs.tagScroll, {
                            click: true,
                            scrollX: true,
                            bounce: false,
                            // freeScroll:true,
                            eventPassthrough: 'vertical'
});

**Comment by theniceangel** [comment]
提供下线上demo

**Comment by wumiangithub** [comment]
内嵌在淘集集app中   赚赚tab
链接
https://growth.taojiji.com/zzmoney/view/v1_0_0/index/user_id/67756463322356057/g/Api2_18_1/os/android/token/14ce0bc6637e73d_/uuid/d33818f5-f30b-4aa6-a478-22eca080c139/imei/864106030694277/channel/vivo/scope_code/1555308252/res/720*1280/version/2.18.1/timestamp/1555308380/system_version/6.0.1/system_model/vivoY66/app_type/4

**Comment by theniceangel** [comment]
@wumiangithub 你那边可以调试一下么

**Comment by wumiangithub** [comment]
调试下来，我换成了scrollBy()目前看来可以解决
