### ISSUE TITLE
移动端真机调试报错Ignored attempt to cancel a touchstart event with cancelable=false

### ISSUE THREAD

**Issue by haishengXie0712** [ustbhuangyi/better-scroll#853]
### Version
1.15.0

### Reproduction link
[https://codesandbox.io/s/vue-template-zndzj](https://codesandbox.io/s/vue-template-zndzj)

### Steps to reproduce
就是一个普通的使用demo,在谷歌模拟器内正常.在安卓SdkView里面会拖拽不动,并报错Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

### What is expected?
希望可以解决相应的问题

### What is actually happening?
希望可以解决相应的问题

**Comment by 60late** [comment]
我也遇到这个问题了，求解决

**Comment by haishengXie0712** [comment]
@60late 我后面启用了,自己手写的加载更多.

**Comment by 60late** [comment]
> @60late 我后面启用了,自己手写的加载更多.
能解释清楚一些吗大佬，我主要是报Ignored attempt 这个错

**Comment by haishengXie0712** [comment]
弃用了才对.我没有使用 better-scroll 了.
