### ISSUE TITLE
华为安卓4.4版本下拉加载更多，会引起每次加载的内容，上面一部分像是被卡住了。dom还在，但就是看不见。re

### ISSUE THREAD

**Issue by zw888** [ustbhuangyi/better-scroll#855]
![image](https://user-images.githubusercontent.com/33955555/61268931-a502be00-a7cf-11e9-930d-987ca2c0fe38.png)
卡屏图片如下
![Screenshot_2019-07-16-13-41-37](https://user-images.githubusercontent.com/33955555/61268969-bf3c9c00-a7cf-11e9-8633-b3937a0902e8.jpeg)
每次卡屏的高度大小好像跟下拉的距离有关，
scroll配置如下
  probeType: 3,
      click: true,
      scrollX: false,
      scrollY: true,
      // eventPassthrough: 'horizontal',
      pullDownRefresh: {
        threshold: 60,
        stop: 50
      },
      pullUpLoad: {
        threshold: -20
      }

**Comment by zw888** [comment]
上面“教育部“记录上面的白色部分就是卡屏的部分，我看了，dom元素是在的。样式也没什么变化，像是被什么东西挡住了一样。希望大佬帮忙看看。

**Comment by theniceangel** [comment]
@zw888 提供线上链接吧
