### ISSUE TITLE
页面强制横屏效果下，滑动跟手势方向是反的。。

### ISSUE THREAD

**Issue by yong16** [ustbhuangyi/better-scroll#857]
### Version
2.0

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll/issues](https://github.com/ustbhuangyi/better-scroll/issues)

### Steps to reproduce
以横向滚动为例，demo 中的 例子，加上下面css:

@media only screen and (orientation: portrait) {
  .demo {
    -webkit-transform: translate3d(-50%, -50%, 0) rotate(90deg);
    transform: translate3d(-50%, -50%, 0) rotate(90deg);
  }
},
竖屏情况下，让页面横向展示。。强制横屏后，不管横竖屏，手势上下滑动才会触发组件左右滑动，手势左右滑动会触发组件上下滑动

### What is actually happening?
2.0版本，强制页面横屏展示后，不管横竖屏，手势上下滑动才会触发组件左右滑动，手势左右滑动会触发组件上下滑动

**Comment by Clare29** [comment]
请问问题解决了吗，我也碰到了这个问题

**Comment by SummerJoan3** [comment]
我也碰到了这个问题

**Comment by JangYB** [comment]
> ### Version
> 2.0
> 
> ### Reproduction link
> https://github.com/ustbhuangyi/better-scroll/issues
> 
> ### Steps to reproduce
> 以横向滚动为例，demo 中的 例子，加上下面css:
> 
> @media only screen and (orientation: portrait) {
> .demo {
> -webkit-transform: translate3d(-50%, -50%, 0) rotate(90deg);
> transform: translate3d(-50%, -50%, 0) rotate(90deg);
> }
> },
> 竖屏情况下，让页面横向展示。。强制横屏后，不管横竖屏，手势上下滑动才会触发组件左右滑动，手势左右滑动会触发组件上下滑动
> 
> ### What is expected?
> ### What is actually happening?
> 2.0版本，强制页面横屏展示后，不管横竖屏，手势上下滑动才会触发组件左右滑动，手势左右滑动会触发组件上下滑动

请问问题是否解决呢，碰到同样问题噢

**Comment by theniceangel** [comment]
bs 探测到横屏的时候，会自动刷新的呀

**Comment by steady-join** [comment]
我也遇到了这个问题，请问能否解决呀

**Comment by theniceangel** [comment]
fixed at v2.3.0, see [here](https://better-scroll.github.io/examples/#/core/horizontal-rotated) for details

**Comment by ych335** [comment]
给文档看漏了的小伙伴们,设置quadrant可以解决这个问题，详情看：https://better-scroll.github.io/docs/zh-CN/guide/base-scroll.html#quadrant
ps：bs真是我用到过的最好的滚动库
