### ISSUE TITLE
Why did I have a rebound effect when I was using better-scroll, but it didn't come down?

### ISSUE THREAD

**Issue by cwc845982120** [ustbhuangyi/better-scroll#86]
Why did I have a rebound effect when I was using better-scroll, but it didn't come down?
为什么我在使用better-scroll的时候，下拉有回弹效果，上拉却没有？

**Comment by ustbhuangyi** [comment]
回弹效果上下都有的，提供一下你的 demo 地址

**Comment by cwc845982120** [comment]
这个是不是dom节点多了的话就不是很好用啊，高度感觉老是计算不正确，我看了下就是这个原因，还有就是如果list数据不够多，能不能也有这种回弹效果，不然数据少不能回弹，数据多才能回弹，用户会有反差。

**Comment by ustbhuangyi** [comment]
当子元素高度没有父元素高度高的时候，不会滚动，也不会有回弹效果

**Comment by gaoshijun1993** [comment]
> 当子元素高度没有父元素高度高的时候，不会滚动，也不会有回弹效果

@ustbhuangyi 希望这种情况下也能够加上回弹效果, 因为操作会有反差
