### ISSUE TITLE
eventPassthrough: 'horizontal' 会触发pc端垂直方向的默认行为

### ISSUE THREAD

**Issue by JohnApache** [ustbhuangyi/better-scroll#863]
### Version
1.15.0

### Reproduction link
[https://codesandbox.io/embed/elated-wiles-ngqyr](https://codesandbox.io/embed/elated-wiles-ngqyr)

### Steps to reproduce
打开codesankbox 地址  默认是注释eventPassthrough: 'horizontal' 属性的，页面滚动效果展示正常， 当取消 eventPassthrough: 'horizontal' 注释的时候 ，鼠标上下滚动 就会触发垂直方向浏览器的默认行为，整个页面会被拖动，浏览器原生的拖拽触顶触底回弹效果的默认行为，我用的是mac chorme浏览器，代码https://codesandbox.io/embed/elated-wiles-ngqyr

### What is expected?
eventPassthrough: 'horizontal' 期望只是开启水平方向的浏览器默认行为，垂直方向的滚动效果不会触发浏览器默认行为

### What is actually happening?
在水平方向上是正常的 但是 垂直方向会触发 chorme 浏览器原生的拖动整个页面触顶触底回弹效果的默认行为

**Comment by miaohu** [comment]
请问这个问题解决了吗? 我现在遇到了同样的问题.

**Comment by JohnApache** [comment]
@miaohu  没有具体回归看过哪个版本修复的，现在看 sandbox 示例展示效果最新next 版本是已经修复了的
