### ISSUE TITLE
Vue使用，移动端滚动重影问题

### ISSUE THREAD

**Issue by LvJianfeng** [ustbhuangyi/better-scroll#865]
### Version
"@better-scroll/core": "^2.0.0-alpha.16"

### Reproduction link
[http://localhost:8080/](http://localhost:8080/)

### Steps to reproduce
横向滑动的时候

### What is expected?
滚动不重影

### What is actually happening?
在手机上滚动发生，价格参数发生重复;
电脑上没有此类问题

### Code
```
<div class="hot_wrapper" ref="hot_wrapper">
      <ul class="content" ref="wrapperUl">
        <li v-for="(good, index) in hotList" :key="index">
          <hot-li :good="good"></hot-li>
        </li>
      </ul>
</div>

Vue[created()]
this.$refs.wrapperUl.style.width = `${width}px`;
this.$nextTick(() => {
  if (!this.scroll) {
       this.scroll = new BScroll(this.$refs.hot_wrapper, {
              scrollX: true,
              click: true,
              freeScroll: true,
              eventPassthrough: "vertical"
            });
        } else {
            this.scroll.refresh();
        }
});
```

![向左滑动](https://user-images.githubusercontent.com/9586013/62278507-ca9ff080-b47a-11e9-8ae7-aa10d08f93c2.png)

**Comment by dolymood** [comment]
repo 需要完整提供 这个图片看不出来啥

**Comment by demonskp** [comment]
我也遇到了相同的问题，但是这个问题在高版本的手机当中不会有重影，在Android低版本（5.1.1）就会出现重影。

**Comment by LvJianfeng** [comment]
我的有由于外面的css导致的； @demonskp

**Comment by demonskp** [comment]
> 我的有由于外面的css导致的； @demonskp

我修改了css，修复了这个问题。但是还是很奇怪为什么在不同版本的webview里面表现不一致。

**Comment by overlord1126** [comment]
> > 我的有由于外面的css导致的； @demonskp
> 
> 我修改了css，修复了这个问题。但是还是很奇怪为什么在不同版本的webview里面表现不一致。

朋友 你修改了什么css 修复了重影的问题? 我也遇到了

**Comment by demonskp** [comment]
> > > 我的有由于外面的css导致的； @demonskp
> > 
> > 
> > 我修改了css，修复了这个问题。但是还是很奇怪为什么在不同版本的webview里面表现不一致。
> 
> 朋友 你修改了什么css 修复了重影的问题? 我也遇到了

我是通过在外面再套一层div来隔离解决的  你可以看看BFC相关的东西

**Comment by webylb** [comment]
尴尬 加了个overflow: hidden;
