### ISSUE TITLE
商品列表左右联动时，分组下的商品较少，点击某个分组不高亮，高亮停留在上一个分组

### ISSUE THREAD

**Issue by myyida1git** [ustbhuangyi/better-scroll#867]
![image](https://user-images.githubusercontent.com/29189295/62410045-ee963a00-b612-11e9-9626-de6a34b5d7bf.png)

**Comment by dolymood** [comment]
这个问题是属于计算问题，可以参考cube-ui的 scrollnav 的效果 https://didi.github.io/cube-ui/#/zh-CN/docs/scroll-nav
