### ISSUE TITLE
slide 一次滚动多页

### ISSUE THREAD

**Issue by lif3ng** [ustbhuangyi/better-scroll#868]
### Version
2.0.0-alpha.20

### Reproduction link
[https://codesandbox.io/embed/bs-pages-demo-7gm7q](https://codesandbox.io/embed/bs-pages-demo-7gm7q)

### Steps to reproduce
在page区域左滑，滑过多个页面。

### What is expected?
只划过一个页面（pre/next）

### What is actually happening?
划过多个页面

---
scroll content 区域使用flex布局，flex item 宽度为100vw不收缩，感觉 slideItemWidth * threshold 的计算不符合预期。

**Comment by cuijing1031** [comment]
需要关闭惯性动画效果，设置如下：
 momentum: false

**Comment by lif3ng** [comment]
> 需要关闭惯性动画效果，设置如下：
> momentum: false

管用 多谢
