### ISSUE TITLE
ios12.3.1，微信（7.0.5）打开h5页面，键盘收起后有灰色遮罩，导致无法点击遮罩洗下面的按钮

### ISSUE THREAD

**Issue by Luolei1992** [ustbhuangyi/better-scroll#869]
![微信图片_20190812150831](https://user-images.githubusercontent.com/23149226/62849790-8bdc2700-bd13-11e9-86ae-80a53a8678a6.jpg)

**Comment by dolymood** [comment]
不明白，看起来和BS貌似没啥关系
