### ISSUE TITLE
点击 scroll 容器，安卓机无法失焦

### ISSUE THREAD

**Issue by wengcd** [ustbhuangyi/better-scroll#87]
网页的底部是个 textarea，上面是个scroll 聊天区域，安卓机当点击 textarea focus了以后，点scroll区域无法让textarea失焦

**Comment by ustbhuangyi** [comment]
因为 better-scroll 默认会 preventDefault 阻止默认行为，有一种解决方案，你可以监听 beforeScrollStart 事件，在事件的回调函数里去手动 blur textarea
