### ISSUE TITLE
BS2.0 鼠标右键点击后的bug

### ISSUE THREAD

**Issue by Eflet** [ustbhuangyi/better-scroll#872]
### Version
1.15.0

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll](https://github.com/ustbhuangyi/better-scroll)

### Steps to reproduce
初始化BScroll以后，
1.如果直接在scroll元素上点击鼠标右键，那之后就不能再触发滑动了
2.如果先正常滑动，然后再鼠标右键，元素会瞬间滑动

之前使用1.x的时候没有这个问题，使用2.0以后出现，在官网在线文档里面的例子里面也能重现
cube-ui里的scroll控件貌似不会出现这种情况

### What is expected?
不响应右键事件

### What is actually happening?
响应右键事件

**Comment by theniceangel** [comment]
v2.0.3 没复现
