### ISSUE TITLE
给父级添加fixed定位。滚动无效。

### ISSUE THREAD

**Issue by wumiangithub** [ustbhuangyi/better-scroll#874]
一个商品分类栏的横向滚动需求。
分类栏的父级本来是sticky定位，但是部分机型不支持。只能当分类栏滚动到顶部，替换为fixed定位。但是
给父级添加fixed定位。滚动无效。

**Comment by dolymood** [comment]
那是因为高度发生了变化，此时需要手工refresh下重新计算高度
