### ISSUE TITLE
横向滚动 在iphone6上存在兼容

### ISSUE THREAD

**Issue by ajl512** [ustbhuangyi/better-scroll#876]
一个有40关的游戏关卡数字横向滚动，类似40个方块一排摆放，每过一关，就将盒子往左移动一个固定宽度this.scroll.scrollBy(-this.scrollWidth,0,1000)，目前测试发现iphone上向左滚动后又会回弹回去

**Comment by dolymood** [comment]
如果有回弹，说明宽度计算的不对，即可能需要刷新
