### ISSUE TITLE
安卓真机上不能滑动，ios可以

### ISSUE THREAD

**Issue by chaoyang-Rex** [ustbhuangyi/better-scroll#877]
安卓上报错Ignored attempt to cancel a touchcancel event with cancelable=false, for example because scrolling is in progress and cannot be interrupted. at core.esm.js : 679

**Comment by theniceangel** [comment]
这个报错应该是浏览器自带的，你可以 google 一下相关的资料，至于无法在安卓上滚动，你可以提供一个线上链接给我们
