### ISSUE TITLE
使用scrollTo方法后到达了指定位置，点击第一下按钮后事件不触发，第二次才触发，是如何解决的呢

### ISSUE THREAD

**Issue by linxiaodong0538** [ustbhuangyi/better-scroll#878]
使用scrollTo方法后到达了指定位置，点击第一下按钮后事件不触发，第二次才触发，是如何解决的呢

_Originally posted by @hufuhao in https://github.com/ustbhuangyi/better-scroll/issues/781#issuecomment-491270057_

**Comment by theniceangel** [comment]
有线上链接么

**Comment by yuelinghunyu** [comment]
我也是
