### ISSUE TITLE
持续触发scroll

### ISSUE THREAD

**Issue by alekoshen712** [ustbhuangyi/better-scroll#88]
![image](https://user-images.githubusercontent.com/19506220/27778373-ede856e8-5fec-11e7-8087-a7f14b584766.png)

当在商家页滑动商品,在未完成滑动动画时,点击评论后,页面切换了,但会持续触发scroll事件.
如果滑动动画完成,则不会持续触发scroll
![gaa](https://user-images.githubusercontent.com/19506220/27778655-41d53314-5fef-11e7-9e9b-4b6afc1c8302.gif)

vue中开始我猜是keepalive的缘故,但在react中也有类似的问题,在react的组件中我尝试在componentWillUnmount中将这个betterScroll实例销毁,但依然不起效果.

整个DOM树已经消失,但还是不断的触发scroll事件.猜测是better-scroll中触发scroll回调事件的判断逻辑不精准导致.

**Comment by ustbhuangyi** [comment]
如果存在这个问题，也不是应该 better-scroll 应该处理的，而是在你的路由切换的时候停止滚动，0.3.0 版本提供了一个 stop 接口，可以停止 scroll 的滚动

**Comment by alekoshen712** [comment]
谢谢🙏

**Comment by alekoshen712** [comment]
升级0.3.0版本后.报错找不到vconsole模块
装了该模块后出现了调试用的vconsole.
