### ISSUE TITLE
有没有遇到这种情况的，在某台电脑的微信上不可以滚动，官网的demo在这台电脑的微信上也滚动不了，但是在浏览器上可以，有知道这是怎么回事的吗

### ISSUE THREAD

**Issue by pp344** [ustbhuangyi/better-scroll#880]

**Comment by pp344** [comment]
知道了，那台电脑的微信 'ontouchstart' in window 返回的是true

**Comment by theniceangel** [comment]
对于微信 `'ontouchstart' in window 返回的是true` 这样的场景，需要手动管理 `disableTouch` 与 `disableMouse` 这两个配置项

**Comment by pp344** [comment]
嗯嗯，可以了

**Comment by pp344** [comment]
手动配置后，在可以 触摸的 PC 上不能滑动，又回到 判断微信浏览器是否可以触摸，然后 'ontouchstart' in window 为true 这个问题 , 手动添加去监听 是触发了 mouse事件，还是touch事件的话，然后又要重新初始化，有什么好的解决方案吗
