### ISSUE TITLE
2版本pullup组件在使用mouseWheel时存在触发问题

### ISSUE THREAD

**Issue by qmhc** [ustbhuangyi/better-scroll#881]
### Version
2.0.0-beta.2

### Reproduction link
[https://codesandbox.io/s/vue-template-4rs0u?fontsize=14](https://codesandbox.io/s/vue-template-4rs0u?fontsize=14)

### Steps to reproduce
情况1）仅用鼠标滚轮将列表滚动至最底部，pullup并不会触发
情况2）先用mouse向下滑动一下段距离（不要到底部），随后用鼠标滚轮滚动到底部，pullup正常触发
情况3）直接用mouse滑动到底部，pullup正常触发

### What is expected?
在不使用mouse进行滚动时，直接使用滚轮也可以触发pullup

### What is actually happening?
一定要使用mouse进行滚动后，才可以触发pullup

**Comment by theniceangel** [comment]
fixed in v2.0.0
