### ISSUE TITLE
scrollToElement

### ISSUE THREAD

**Issue by DJAlejandro** [ustbhuangyi/better-scroll#886]
scrollToElement添加第二个参数后会触发原生的滚动事件，如果我做的是像慕课饿了么项目中那样带有联动效果的两个互相关联的组件，那么点击左边的菜单栏，右侧跟着会以动画过渡的方式定位到指定位置，但同时会触发右侧的滚动事件，就好像在用手滑动右侧滚动。其结果是左侧又在之前点选的位置上滑动了相应的index，导致左侧index指向错了

**Comment by DJAlejandro** [comment]
> scrollToElement添加第二个参数后会触发原生的滚动事件，如果我做的是像慕课饿了么项目中那样带有联动效果的两个互相关联的组件，那么点击左边的菜单栏，右侧跟着会以动画过渡的方式定位到指定位置，但同时会触发右侧的滚动事件，就好像在用手滑动右侧滚动。其结果是左侧又在之前点选的位置上滑动了相应的index，导致左侧index指向错了

目前的解决方式就是不传第二个参数，放弃过渡效果。这样最后的定位是对的。但是有其他的解决方法吗

**Comment by anzaigo** [comment]
问题解决了吗

**Comment by anzaigo** [comment]
我也遇到了
