### ISSUE TITLE
pc端竖向使用better-scroll滚动，横向使用原生滚动，横向没法用鼠标滑动

### ISSUE THREAD

**Issue by zcw2313** [ustbhuangyi/better-scroll#888]

**Comment by theniceangel** [comment]
可以[参照配置](https://better-scroll.github.io/docs/zh-CN/guide/base-scroll-options.html#preventdefaultexception)看看

**Comment by happy-windman** [comment]
你好 如何解决的呢，我也遇到了 T T

**Comment by happy-windman** [comment]
> 你好 如何解决的呢，我也遇到了 T T

已解决了。是因为better-scroll把原生的默认事件禁用了，在配置中把preventDefault设为true，或者preventDefaultException进行筛选
