### ISSUE TITLE
zoomTo on监听不到 zoomEnd和zoomStart

### ISSUE THREAD

**Issue by zhuweilong** [ustbhuangyi/better-scroll#889]
zoomTo on监听不到 zoomEnd和zoomStart  还有 zoomTo 放大n倍后，再缩1 时，滚动的位置又回到了起点

**Comment by theniceangel** [comment]
能否提供线上 demo

**Comment by zhuweilong** [comment]
不用demo吧  你就cdn引入到index.html里  new一个实例 你zoomTo() 就有问题
