### ISSUE TITLE
[New Feature] 减少picker组件滚动后子列刷新改变的间隔时间

### ISSUE THREAD

**Issue by trtrtr6** [ustbhuangyi/better-scroll#892]
#### **picker** 列滚动后面子列改变刷新这中间间隔时候有点长，可以参考mint-ui的picker效果。

自己有尝试在 **touchEnd** 的时候去处理后续子列的刷新，但是这时获取到的 **selectedIndex** 还是改变之前的 **index**。**scrollEnd** 之后获取index再刷新子列，间隔时间有点太长了，感觉要等好久才会看到子列的刷新。

是否可以在 **touchEnd** 抛出正确的 **selectedIndex**，减少子列刷新间隔

### What does the proposed API look like?
在 **touchEnd** 抛出正确的 **selectedIndex**，或者针对picker这类滚动加一个 **pickerChange** 事件抛出正确的 **selectedIndex**（在 **touchEnd** 事件之前）

**Comment by dolymood** [comment]
可以考虑，这个我们在思考下，之前的间隔主要是由动画决定的 所以会显得有点”长“

**Comment by trtrtr6** [comment]
经同事提醒，在做vue项目时使用vue的watch监听了wheel.selectedIndex的值，在selectedIndex变化的第一时间拿到了值，速度快多了，整体也流畅很多
