### ISSUE TITLE
关于example无法访问的问题

### ISSUE THREAD

**Issue by Yweimao** [ustbhuangyi/better-scroll#893]
hello,黄老师您好, 就是我下载v1分支下面的代码,想看一下example, 然后安装了依赖, 然后跑起来了, 编译成功了, 但是提示 http://0.0.0.0:8932/ 这个网址无法访问, 不知道是什么问题 ???

**Comment by theniceangel** [comment]
你这应该不是v1分支的代码，切到v1，重新安装依赖
