### ISSUE TITLE
2版本移动端label内的checkbox无法触发

### ISSUE THREAD

**Issue by qmhc** [ustbhuangyi/better-scroll#894]
### Version
2.0.0-beta.2

### Reproduction link
[https://codesandbox.io/s/vue-template-til1r?fontsize=14](https://codesandbox.io/s/vue-template-til1r?fontsize=14)

### Steps to reproduce
在PC端，点击（click）`复选框`可以正常的切换该 `<label>` 内的 `<input>` 复选框的状态
在移动端，点击（touch）`复选框`不能触发 `<label>` 内的 `<input>` 复选框的状态切换

业务场景是，使用 `<label>` 来实现自定义的复选框效果时，在移动端无法正常的触发状态的改变，需要单独给 `<label>` 添加 `touchstart` 事件并阻止冒泡才可以正常工作，但是这样就无法从复选框的触点去进行滚动

**Comment by theniceangel** [comment]
preventDefault 配置位 false 即可。
