### ISSUE TITLE
ios xs 添加动画导致滑动卡顿

### ISSUE THREAD

**Issue by MinMr** [ustbhuangyi/better-scroll#899]
滑动的每一项添加了一个动画，造成滑动卡顿
![image](https://user-images.githubusercontent.com/32814481/64954171-58169300-d8b7-11e9-975f-c743c13f6e80.png)

**Comment by MinMr** [comment]
黄大大  希望帮忙看下是怎么回事

**Comment by theniceangel** [comment]
请提供线上demo

**Comment by Eflet** [comment]
我最近碰到类似的问题，在滑动的过程中动态改变每个对象的样式，发现卡顿严重
stackoverflow上找到的解决方案你可以试试：
v-for里面的东西统统包装在一个单独控件里面
就是你这里的li，用一个单独的控件包装起来，参数统统用prop传进去，滑动就很流畅了
好像是应为scope不同，dom的更新方式不同

**Comment by MinMr** [comment]
> 我最近碰到类似的问题，在滑动的过程中动态改变每个对象的样式，发现卡顿严重
> stackoverflow上找到的解决方案你可以试试：
> v-for里面的东西统统包装在一个单独控件里面
> 就是你这里的li，用一个单独的控件包装起来，参数统统用prop传进去，滑动就很流畅了
> 好像是应为scope不同，dom的更新方式不同

**Comment by MinMr** [comment]
> 我最近碰到类似的问题，在滑动的过程中动态改变每个对象的样式，发现卡顿严重
> stackoverflow上找到的解决方案你可以试试：
> v-for里面的东西统统包装在一个单独控件里面
> 就是你这里的li，用一个单独的控件包装起来，参数统统用prop传进去，滑动就很流畅了
> 好像是应为scope不同，dom的更新方式不同

**Comment by MinMr** [comment]
按照 @Eflet 同学提供的思路我将整个ul滚动的内容提出来当成了一个组件
![image](https://user-images.githubusercontent.com/32814481/65242169-f012b780-db17-11e9-916d-71ce8ebf9a9d.png)  如上图  这样滑动起来确实好多了 感谢
