### ISSUE TITLE
Better-scoll in the sliding process the following error that Browser is Google

### ISSUE THREAD

**Issue by baocode** [ustbhuangyi/better-scroll#9]
Better-scoll in the sliding process the following error:
。Browser： Google
。Version：56
。Desc：“Unable to preventDefault inside passive event listener due to target being treated as passive.”

**Comment by Becavalier** [comment]
Add a check of "e.cancelable" before doing e.preventDefault() in function "_move(e)".

**Comment by ustbhuangyi** [comment]
fixed

**Comment by neurotoxinvx** [comment]
@RByers Thanks for your advice
