### ISSUE TITLE
scroll滚动位置无法在vue keep-alive中被保存，并且scrollTo也无效

### ISSUE THREAD

**Issue by WQone** [ustbhuangyi/better-scroll#901]
### Version
1.15.0

### Reproduction link
[https://wqone.github.io/vue-h5/](https://wqone.github.io/vue-h5/)

### Steps to reproduce
【每一次执行不一定会触发】
1. 刷新页面初始化scroll
2.快速往下滑动 刷新数据
3.点击某一个div进入详情页
4.快速返回
这时候会看到要么滚动条已经在顶部了，要么因为scrollTo的原因页面从设置的滚动条位置自动滚动到顶部

### What is expected?
滚动条应该在返回当前页时与离开页面时的位置保持一致

### What is actually happening?
这个问题我试了很多次，尽管使用scrollTo依然没有解决这个问题所以特地建立了一个例子，希望能够尽快解答我的疑问

**Comment by WQone** [comment]
![dfcdsf2](https://user-images.githubusercontent.com/25738656/65136274-def37900-da39-11e9-8471-680e21d3b17c.gif)

**Comment by dolymood** [comment]
可以试试把observeDOM 关掉，然后自己维护 在active的时候 刷新下

**Comment by WQone** [comment]
@dolymood  不是特别明白你所表达的含义

**Comment by bouncing** [comment]
回滚到老版本，别用新的版本。

**Comment by WQone** [comment]
@bouncing 请问是指哪个版本号

**Comment by paint-JionYu** [comment]
@WQone 1.13.2这个版本没问题

**Comment by paint-JionYu** [comment]
@WQone 这个问题我也遇到

**Comment by wchmei** [comment]
记录离开后的位置，然后再切回来时，将    this.$refs.scroll.scrollTo(0,this.saveY, 1) 的时间设置为1就好了
activated() {
    this.$refs.scroll.scrollTo(0,this.saveY, 1)
    // console.log('home activated');
    this.$refs.scroll.refresh()
  },
  deactivated() {
    this.saveY = this.$refs.scroll.getScrollY()
    // console.log('home deactivated');
    // console.log(this.saveY);
    // 在离开的时候取消事件的全局监听
    this.$bus.$off("itemImageLoad", this.imgListener);
    // console.log(this.$refs.scroll);

  },

**Comment by wchmei** [comment]
记录离开后的位置，然后再切回来时，将 this.$refs.scroll.scrollTo(0,this.saveY, 1) 的时间设置为1就好了
`activated() {
this.$refs.scroll.scrollTo(0,this.saveY, 1)
// console.log('home activated');
this.$refs.scroll.refresh()
},
deactivated() {
this.saveY = this.$refs.scroll.getScrollY()
// console.log('home deactivated');
// console.log(this.saveY);
// 在离开的时候取消事件的全局监听
this.$bus.$off("itemImageLoad", this.imgListener);
// console.log(this.$refs.scroll);

},`

**Comment by wchmei** [comment]
记录离开时的位置，切换回来时将 this.$refs.scroll.scrollTo(0,this.saveY, 1) ，之前这里时间设置为0，经常跳转到顶部，设置为1后就好了
`activated() {
this.$refs.scroll.scrollTo(0,this.saveY, 1)
this.$refs.scroll.refresh()
},
deactivated() {
this.saveY = this.$refs.scroll.getScrollY()
this.$bus.$off("itemImageLoad", this.imgListener);
},`

**Comment by unomisa** [comment]
### 我的场景
BScroll对象设置为:
```
observeDOM: true,
observeImage: true
```
**在图片加载时切换页面**，再回到页面出现自动滚动到顶部BUG。
### BUG原因
在**非当前路由**时，`img`加载完成之后的回调`refresh()`，导致自动回滚顶部。可以通过滚动监听观察到这一行为。
### 解决方案
1. 关闭上述两个设置，转而手动监听`img`的加载完成并回调`refresh()`来保证滚动区域高度正常。
2. 添加一个变量来确定`img`触发回调时是否在当前路由，如果是，则正常回调，如果不是则取消回调。这样便可以保证在**非当前路由**不会`refresh()`导致回滚。
