### ISSUE TITLE
vue  cli3 引入这个插件的时候，一直报错"ReferenceError: BScroll is not defined"。我想知道大家都有这个问题吗？还是我哪写的不对

### ISSUE THREAD

**Issue by huihui11239** [ustbhuangyi/better-scroll#902]
1、在main.js中引入
import BScroll from '@better-scroll/core'
2、vue中也是这个结构
<div class="wrapper">
  <ul class="content">
    <li>...</li>
    <li>...</li>
    ...
  </ul>
  
</div>
3、运用
let wrapper = document.querySelector('.wrapper')
 let scroll = new BScroll(wrapper)

**Comment by dolymood** [comment]
提供的更完整一些
