### ISSUE TITLE
[New Feature] 支持触摸屏的大屏电脑无法滚动

### ISSUE THREAD

**Issue by nangongxiaomo** [ustbhuangyi/better-scroll#913]
### What problem does this feature solve?
商场大屏 用户体验机

### What does the proposed API look like?
支持触摸的大屏电脑上支持触摸

**Comment by FJHou** [comment]
https://better-scroll.github.io/docs/zh-CN/guide/base-scroll-options.html#bindtowrapper

看看是否对你有帮助

**Comment by JanYiAn** [comment]
同求，最近也是这个问题。在PC中的浏览器中似乎无法响应手势滑动

**Comment by theniceangel** [comment]
> 同求，最近也是这个问题。在PC中的浏览器中似乎无法响应手势滑动

因为我们这里没有对应的设备测试，可以打下断点，看下 touch 或者 mouse 事件是否监听上
