### ISSUE TITLE
无限滚动infinity插件在计算滚动项高度会有问题

### ISSUE THREAD

**Issue by zsdxwzy** [ustbhuangyi/better-scroll#914]
### Reproduction link
[https://github.com/ustbhuangyi/better-scroll](https://github.com/ustbhuangyi/better-scroll)

### Steps to reproduce
chrome打开infinity的demo就能看见，带有图片的消息的排版可能会出现问题

### What is expected?
应该是根据item的height自适应去改变transform

### What is actually happening?
可能是图片的加载导致item的高度计算不准确而导致tranform数值不对

**Comment by dolymood** [comment]
infinity 的图片 不确定高度的是 需要缓存计算才可以的
参考对应的示例效果就是这样做的
