### ISSUE TITLE
安卓微信客户端2.0beta2版本上拉刷新时没重新计算滚动条高度

### ISSUE THREAD

**Issue by xaviertung** [ustbhuangyi/better-scroll#916]
2.0beta2版本上拉刷新时没有重新计算滚动条高度：
1、ios微信客户端正常；
2、安卓（我用的是华为p20测的）系统浏览器正常；
3、安卓微信客户端上拉刷新时未正常计算滚动条高度。

**Comment by cangyu1993** [comment]
有些 东西必须异步我很纳闷！init初始化和refresh我都挂了一个定时器才能正常进行下去！你加个定时器试一下
