### ISSUE TITLE
你好，如果要实现瀑布流宽高根据内容，图片来定义吗，每次都是固定宽高很有局限性

### ISSUE THREAD

**Issue by chen1142399899** [ustbhuangyi/better-scroll#919]

**Comment by wenxuli** [comment]
我也想知道如何解决这个问题，请问你解决了吗？

**Comment by chen1142399899** [comment]
解决了





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wenxuli <notifications@github.com&gt;
发送时间: 2019年11月8日 17:18
收件人: ustbhuangyi/better-scroll <better-scroll@noreply.github.com&gt;
抄送: chen1142399899 <1142399899@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ustbhuangyi/better-scroll] 你好，如果要实现瀑布流宽高根据内容，图片来定义吗，每次都是固定宽高很有局限性 (#919)




我也想知道如何解决这个问题，请问你解决了吗？

**Comment by wenxuli** [comment]
请问你是怎么解决的呢？我现在也正在做瀑布流效果




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chen1142399899"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 下午5:57
收件人:&nbsp;"ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;;
抄送:&nbsp;"詠逺、侑茤逺"<1206304983@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ustbhuangyi/better-scroll] 你好，如果要实现瀑布流宽高根据内容，图片来定义吗，每次都是固定宽高很有局限性 (#919)



解决了 
 
 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: wenxuli <notifications@github.com&amp;gt; 
 发送时间: 2019年11月8日 17:18 
 收件人: ustbhuangyi/better-scroll <better-scroll@noreply.github.com&amp;gt; 
 抄送: chen1142399899 <1142399899@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 
 主题: 回复：[ustbhuangyi/better-scroll] 你好，如果要实现瀑布流宽高根据内容，图片来定义吗，每次都是固定宽高很有局限性 (#919) 
 
 
 
 
 我也想知道如何解决这个问题，请问你解决了吗？

**Comment by chen1142399899** [comment]
要不就换插件，要不就用css布局 也可以实现瀑布流



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wenxuli <notifications@github.com&gt;
发送时间: 2019年11月8日 18:00
收件人: ustbhuangyi/better-scroll <better-scroll@noreply.github.com&gt;
抄送: chen1142399899 <1142399899@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ustbhuangyi/better-scroll] 你好，如果要实现瀑布流宽高根据内容，图片来定义吗，每次都是固定宽高很有局限性 (#919)



请问你是怎么解决的呢？我现在也正在做瀑布流效果 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"chen1142399899"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2019年11月8日(星期五) 下午5:57 
 收件人:&amp;nbsp;"ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"詠逺、侑茤逺"<1206304983@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [ustbhuangyi/better-scroll] 你好，如果要实现瀑布流宽高根据内容，图片来定义吗，每次都是固定宽高很有局限性 (#919) 
 
 
 
 解决了  
   
   
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: wenxuli <notifications@github.com&amp;amp;gt;  
  发送时间: 2019年11月8日 17:18  
  收件人: ustbhuangyi/better-scroll <better-scroll@noreply.github.com&amp;amp;gt;  
  抄送: chen1142399899 <1142399899@qq.com&amp;amp;gt;, Author <author@noreply.github.com&amp;amp;gt;  
  主题: 回复：[ustbhuangyi/better-scroll] 你好，如果要实现瀑布流宽高根据内容，图片来定义吗，每次都是固定宽高很有局限性 (#919)  
   
   
   
   
  我也想知道如何解决这个问题，请问你解决了吗？
