### ISSUE TITLE
关于移动端点击事件触发两次的问题

### ISSUE THREAD

**Issue by tangyang8942** [ustbhuangyi/better-scroll#92]
移动端点击时会触发两次click事件，PC端点击时会触发三次click事件

**Comment by tangyang8942** [comment]
clearTimeout(this.timer);
this.timer=setTimeout(() => {
	if(!e._constructed){
		return;
	}
	console.log(666);
	this.$store.dispatch('toggle');
},0);

this can resolve the problem！

**Comment by ustbhuangyi** [comment]
试试 click 为 false 呢？

**Comment by tangyang8942** [comment]
@ustbhuangyi 不行，将click设置为true时完全不会触发click事件，不是原生事件导致的，已经做了event._constructed判断。 经过多次尝试（也更换了不同的环境），发现这个问题（移动端点击时会触发两次click事件）并不是在所有环境中都会出现，我的Mac上昨天还是可以的，今天就出现这问题，也发现部分windows上也会出现，具体出现原因不知

**Comment by ustbhuangyi** [comment]
哪些移动端会触发 2次 click，这两次 click 的 event 中有没有 _constructed 属性？

**Comment by tangyang8942** [comment]
@ustbhuangyi PC端chrome的模拟环境和移动端的UC都有这个问题，两次click的事件对象中都有_constructed属性

**Comment by BusyHe** [comment]
我也出现同样的问题

**Comment by cccRaim** [comment]
+1

**Comment by xiaohaifengke** [comment]
我刚开始用的时候也出现过，后来发现是我自己的问题。下面详细说一下我遇到的问题。
    滚动的原理是一个小盒子里面有个大盒子，我把某个事件A的弹框放在大盒子里了，然后触发事件A的时候，弹框悬浮在大盒子上面，弹框中有个取消按钮对应事件B使弹框消失，取消按钮下面的大盒子中某个元素上绑定了事件C(事件B的元素和事件C的元素是重叠的)，此刻点击事件B的话，事件C也会被点击执行对应的点击操作。在控制台好像会打印三次事件B的console.log。(我记不清这三次全是事件B的还是B+C的了，但是响应了三次事件是肯定的)。后来我把弹框放在小盒子外面就一切都正常了。（说的有点乱，希望能给大家点帮助）。

**Comment by BusyHe** [comment]
@xiaohaifengke 那情况就差不多了，我的是父容器可点击，子组件里面有div是可点击的，但是子组件是隐藏的，这样的话也算是个bug吧

**Comment by xiaohaifengke** [comment]
还是遇到了新问题，如下：
    我上面说的解决办法是在preventDefault: true这个情况下没问题。但是我后来在点击的时候需要加button:active效果，而preventDefault: true情况下会阻止掉该效果。如果preventDefault: false的话，就有button:active效果了，但是会触发两次事件，第一个事件是为了弹出对话框，第二个事件是触发在弹框上的（该事件多余，会让弹框关掉，因为弹框上绑定关闭弹框的事件），所以效果就是点击button，弹框闪一下就关掉了。应该是插件的bug吧，希望作者能fix下。

**Comment by ustbhuangyi** [comment]
最新版已经修复

**Comment by yaonote** [comment]
还是有这个问题...

**Comment by bangquanwu** [comment]
问题依旧存在

**Comment by AikenZhang** [comment]
问题 依旧存在

**Comment by ximing** [comment]
问题 依旧存在 2.0.0-beta.2

**Comment by Anne223** [comment]
问题依旧存在，点击click，会产生2次e._constructed:true

**Comment by BUPTlhuanyu** [comment]
点击事件触发两次可以通过stopPropagation:true来解决，但是会导致滚动不正常的现象，滚动到底部的时候无法再滚动以及点击

**Comment by BUPTlhuanyu** [comment]
这个bug可以看看这个，非常常用的一些场景：https://github.com/ustbhuangyi/better-scroll/issues/630

**Comment by BUPTlhuanyu** [comment]
@ustbhuangyi 嵌套的bs还是有问题，当外层bs无法滚动的时候，内层都无法点击

**Comment by dqm07** [comment]
onTouchStart可以解决

**Comment by addlistener** [comment]
v2.5.1

单个 BScroll instance

同一个 timestamp 的 touchend 触发了四次 checkClick，收获两个 click event

<img width="511" alt="image" src="https://github.com/user-attachments/assets/b53277e1-2736-4cde-b4ed-4296a7a3622c" />

<img width="580" alt="image" src="https://github.com/user-attachments/assets/51845b12-554b-4eb9-89c4-cc77a1de47e0" />

--------

> stopPropagation:true
> onTouchStart可以解决

2.5.1 试了上面两个都没有用。

Nested scroll 里面处理了这个问题。但是当你不是 nested 的时候，你去加这个插件，他会让你的 scroll 搞的像nested一样，有多层滑动，显得一卡一卡的。
https://better-scroll.github.io/docs/zh-CN/plugins/nested-scroll.html
