### ISSUE TITLE
当手指快速移动突然停止不动后，期望不用再滚动了

### ISSUE THREAD

**Issue by fantasy525** [ustbhuangyi/better-scroll#920]
`"better-scroll": "^1.15.2"`
## 步骤：
在我手指拖动快速滑动一段距离后，此时我突然停止不动，这时bs仍然后继续惯性滚动一段距离，这个我在原生app里面测试原生的list-view他们是如果此时列表速度为0，我松开后就不会继续滚动，我觉得这个更符合用户的习惯，能否更改下？
![2019-10-25 18-43-17 2019-10-25 18_43_44](https://user-images.githubusercontent.com/22516157/67565495-26b3a180-f758-11e9-8880-3c02e0aca0a1.gif)

## 期望
期望我手指离开时如果此时速度为0，就别继续惯性滚动了

**Comment by dolymood** [comment]
手机上就不是这样的，因为是用鼠标模拟的行为，类似于做了swipe的操作，而不是正常移动 你可以实际手机体验下就知道了
