### ISSUE TITLE
Swipe momentum scrolling broken after zoom

### ISSUE THREAD

**Issue by Alexxkrehmen** [ustbhuangyi/better-scroll#921]
Hi,

Sorry, I can't read chinese, so impossible for to know is this issue is already listed.
I've made a very basic test, with a wrapper displaying a vertical stack of divs and initialized like this :
`let scroll = new BScroll('.wrapper',{
    scrollY: true,
    scrollbar: {
      fade: true,
      interactive: true
    },
    zoom: {
      start: 1,
      min: 1,
      max: 4
     }
  });`

Testing on an iPad, the scroller is working properly at first, when I swipe up or down, everything is scrolling smoothly.
But after a pinch zoom, the swipe momentum scroll isn't working anymore, most of the time... Sometimes it still works, but not very often.

**Comment by ckools** [comment]
I have the same problem. I just set `useTransition: false` to  make it works
