### ISSUE TITLE
关于cube-scroll的两个bug

### ISSUE THREAD

**Issue by he429134733** [ustbhuangyi/better-scroll#922]
### Version
1.15.0

### Reproduction link
[https://github.com/didi/cube-ui](https://github.com/didi/cube-ui)

### Steps to reproduce
当我使用cube-scroll 作为整个页面的滚动时，碰到了两个bug， 一个是 当cube-scroll有img标签的时候，如果不指定img的height 在加载完成之后，cube-scroll不能滚动、但是元素显示的很正常 只是不能滚动，当我用纯文字的时候 很正常。  第二个  当我使用require（img）的时候 也是发生了一样的bug

### What is expected?
能够正常滚动

### What is actually happening?
不能滚动

**Comment by he429134733** [comment]
官方的demo 也有这个bug 当我把官方的img 的height 取消 也出现同样的bug 貌似丢失了图片的高度

**Comment by theniceangel** [comment]
img 图片的加载跟 js 的执行不是一个线程，确保 img 加载完成之后，再调用 `scroll.refresh` 计算正确的高度
