### ISSUE TITLE
bs2.0同时使用slide插件和observe-dom插件，observe-dom会失效

### ISSUE THREAD

**Issue by psychokiller666** [ustbhuangyi/better-scroll#926]
### Version
1.15.0

### Reproduction link
[https://better-scroll.github.io/docs/zh-CN/plugins/slide.html#%E7%A4%BA%E4%BE%8B](https://better-scroll.github.io/docs/zh-CN/plugins/slide.html#%E7%A4%BA%E4%BE%8B)

### Steps to reproduce
```
            this.slide = new this.$BScroll(this.$refs.banner_wrapper, {
                scrollX: true,
                scrollY: false,
                observeDom: true,
                // nestedScroll: true,
                click: true,
                slide: {
                    loop: true,
                    threshold: 100
                },
                // useTransition: true,
                momentum: false,
                bounce: false,
                probeType: 3
            })
```

### What is expected?
在pc端，改变了浏览器窗口宽度以及高度，bs会自动refresh()

### What is actually happening?
实际上并没有触发refresh()

**Comment by theniceangel** [comment]
safe as https://github.com/ustbhuangyi/better-scroll/issues/942
