### ISSUE TITLE
设置pull-up插件的threshold值无效

### ISSUE THREAD

**Issue by liang0612** [ustbhuangyi/better-scroll#927]
this.scroll = new BScroll(this.scrollEl.nativeElement, {
            scrollY: true,
            pullDownRefresh: this.pullDownRefresh,
            pullUpLoad: { threshold: 90 }
        });
threshold设置时无效，每次到底就会触发事件,没有计算当滚动到底部时在网上拉一断距离然后在触发事件

**Comment by theniceangel** [comment]
如果是想要触底，`threshold` 为负值
