### ISSUE TITLE
better-scroll 调用refresh() 可滚动的宽度还是上一次的呢？

### ISSUE THREAD

**Issue by tgydarren** [ustbhuangyi/better-scroll#932]
比如：我第一次的数据是两条，宽度200px，我更新数据为8条时，宽度是800px，我调用了refresh()。但是可滚动的距离还是那200px。如何解决呢？

**Comment by paint-JionYu** [comment]
你有监听数据加载完成，再调用的 refresh() 吗

**Comment by tgydarren** [comment]
是的，vue框架，我在$nextTick后调用refresh()





--
_______________________________________
Name:田广宇
Tel:15101022527

在 2019-11-22 14:30:22，"paint-JionYu" <notifications@github.com> 写道：


你有监听数据加载完成，再调用的 refresh() 吗

**Comment by tgydarren** [comment]
哦对了，我有试过setTimeout(refresh(), 2000)也不行呢




--
_______________________________________
Name:田广宇
Tel:15101022527

在 2019-11-22 14:30:22，"paint-JionYu" <notifications@github.com> 写道：


你有监听数据加载完成，再调用的 refresh() 吗

**Comment by paint-JionYu** [comment]
@load 监听数据加载完

**Comment by theniceangel** [comment]
横向滚动对样式的要求有点高，可以参考横向滚动的 demo
