### ISSUE TITLE
PC 不支持触发上拉功能？

### ISSUE THREAD

**Issue by EmiyaYang** [ustbhuangyi/better-scroll#933]
### Version
1.15.0

### Reproduction link
[https://codepen.io/Emiya1996/pen/XWWGxrZ](https://codepen.io/Emiya1996/pen/XWWGxrZ)

### Steps to reproduce
将列表拉至底部

### What is expected?
拉至底部触发 pullingUp 事件，打印”上拉“。

### What is actually happening?
nothing happens

**Comment by codevstrong** [comment]
支持的，你可能配置没有设置好，还有`pullUpLoad`要设置为`true`

**Comment by theniceangel** [comment]
@EmiyaYang PC端滚轮不支持触底反弹，所以配置错了，应该是

```js
pullUpLoad: {
   threshold: 0 // 不小于 0
}
```
