### ISSUE TITLE
[New Feature] 如何动态设置eventPassthrough

### ISSUE THREAD

**Issue by goodchao01** [ustbhuangyi/better-scroll#934]
### What problem does this feature solve?
当在bscroll容器内嵌套一个react-virtualized组件时，需要设置eventPassthrough:vertical来实现列表滚动，但滚动到顶部时希望可以调用组件的下拉刷新功能

### What does the proposed API look like?
this.scroll.options.eventPassthrough = '';

**Comment by theniceangel** [comment]
1.x 版本么
