### ISSUE TITLE
为什么scroll调用scrollTo()是undefined

### ISSUE THREAD

**Issue by JaneChelle** [ustbhuangyi/better-scroll#935]
为什么scroll调用scrollTo()是undefined
![(`{RN8~B5{B7N`Q3_ SELES](https://user-images.githubusercontent.com/38367355/69477024-4522c080-0e1c-11ea-8452-6f9764c5fc46.png)

**Comment by theniceangel** [comment]
先打印出 `this.$refs.suggest` 出来看看是啥
