### ISSUE TITLE
滚动到底部时，使用scrollTo方法会触发pullingUp事件

### ISSUE THREAD

**Issue by codevstrong** [ustbhuangyi/better-scroll#936]
### Version
1.15.0

### Reproduction link
[https://github.com/codevstrong/BugReportForBScroll.git](https://github.com/codevstrong/BugReportForBScroll.git)

### Steps to reproduce
在滚动区域上滑触底，当其停止后，（等待此上拉事件finish），点击利用scrollTo实现的返回顶部按钮，会再次触发pullingUp

### What is expected?
滚动区触底时，触发一次pullingUp事件，
点击返回顶部时，仅回到顶部，没有其它附加事件

### What is actually happening?
点击回到顶部时，如果上一次的上拉加载事件已经完成（滚动区域触底，并自然恢复，2s后），那么会触发一次pullingUp。
在PC端Firefox和真实手机端均测试过，结果是每次使用按钮返回顶部时，都会触发一次pullingUp事件。
后续使用scrollTo(x, 0, 500)，当滚动区域触底并自然恢复后，不同的x值，也会触发一次pullingUp事件

**Comment by theniceangel** [comment]
Thanks ~

**Comment by codevstrong** [comment]
@theniceangel 
我受到前面的话题您的建议的启发
>  PC 不支持触发上拉功能？
>  #933 opened 6 days ago by EmiyaYang

将`pullUpLoad`设置为
```javascript
{
    threshold: -1    // 只要是负的都行
}
```
可以暂时解决一部分场景下的bug问题，但是`scrollTo`方法还是跟`pullingUp`事件耦合性太高了，
如果需要`threshold`大于0就不行了。
