### ISSUE TITLE
[New Feature] 请问横向滚动与竖向滚动结合的demo有没有代码参考呢？

### ISSUE THREAD

**Issue by coffeeDanny** [ustbhuangyi/better-scroll#937]
### What problem does this feature solve?
以下为demo链接
https://ustbhuangyi.github.io/better-scroll/#/examples/nav-list/4/en
但在GitHub上未找到demo的代码参考，希望可以查到参考代码。

### What does the proposed API look like?
希望可以学到精髓

**Comment by theniceangel** [comment]
切到 v1 分支即可

**Comment by coffeeDanny** [comment]
感谢感谢，找到了，非常感谢 @theniceangel

**Comment by coffeeDanny** [comment]
已解决。
