### ISSUE TITLE
你好，请问一个问题。

### ISSUE THREAD

**Issue by mangoyi** [ustbhuangyi/better-scroll#94]
运用了better-scroll在网页中，对应的元素已经添加了width: 100%; transition-timing-function: cubic-bezier(0.165, 0.84, 0.44, 1); transition-duration: 0ms; transform: translate(0px, 0px) translateZ(0px);

这些scroll要用到的属性，但是依然不能滚动。ps： 要滚动的内容，存在点击事件。

谢谢。

**Comment by ustbhuangyi** [comment]
不符合提 issue 规范
