### ISSUE TITLE
slide嵌套scroll后内外层滚动相互影响 

### ISSUE THREAD

**Issue by comDotCyx** [ustbhuangyi/better-scroll#940]
**步骤**
1 最外层是slide进行tab切换
2 每个slide里面使用纵向的scroll做下拉刷新和加载更多
3 某个slide里纵向的scroll又嵌套了一个横向的scroll（或者slide）

**期望**
最里层横向的scroll横向滚动不会带动最外层slide滚动，但是纵向可以带动中间的scroll滚动

**实际效果**
1 最里面的scroll使用stopPropagation：true导致纵向不能带动中间的scroll滚动，添加eventpassthrough:'vertical'也不行。
2 最里面的scroll使用stopPropagation：false(默认)，则里面不能滚动，滑动的时候会拖动最外面的slide

能否达到最里面的scroll只阻止横向冒泡的效果呢

**Comment by theniceangel** [comment]
请提供版本以及线上 demo

**Comment by comDotCyx** [comment]
@theniceangel 您好，大致是这么个情况，vue: 2.6.9 /cube-ui 1.12.34 / better-scroll: 1.15.0  
demo: https://codesandbox.io/s/vue-template-9btuy
