### ISSUE TITLE
BetterScroll Slide插件能否支持resize，或者能够通过什么方式实现

### ISSUE THREAD

**Issue by lxyc** [ustbhuangyi/better-scroll#942]
目前官方的案例，在resize后也会出现问题
![image](https://user-images.githubusercontent.com/23122397/69895160-c7077200-1365-11ea-8b5a-0d3c7a02a5df.png)

**Comment by theniceangel** [comment]
目前的解决方案只能是重新初始化，接下来优化

**Comment by theniceangel** [comment]
@lxyc 2.0.0-beta6 版本支持 resize
