### ISSUE TITLE
当content高度小于wrapper高度时下拉刷新和上啦不触发

### ISSUE THREAD

**Issue by cangyu1993** [ustbhuangyi/better-scroll#944]
这个issues是讨论用的，不是bug，当content高度大于wrapper高度时才能滚动，是不是只有在滚动的情况下才能出发上拉加载和下拉刷新？有什么好的优化方案吗？必有，当我的列表只有一条数据是我无法触发下拉刷新（因为页面不能触发滚动）

**Comment by yeso** [comment]
碰到同样问题，提了一个PR等审核。

**Comment by hllive** [comment]
根据[https://www.jianshu.com/p/1ee7b760fca1](url)的提示，可以通过将wrapper的高度和content的高度着对比，如果content高度小于等于wrapper的高度，就直接强制修改 this.scroll.hasVerticalScroll = true
添加以下函数：
`//判断当content高度小于wrapper高度时设置可以下拉`
    `_verticalScroll(){`
      `if (`
        `this.scroll.scrollerHeight >=`
        `this.scroll.wrapper.firstChild.clientHeight`
     ` ) {`
       ` this.scroll.hasVerticalScroll = true;`
     ` }`
   ` }`
在初始化和refresh()之后执行一下这个函数

**Comment by kingshuaishuai** [comment]
`我的解决方案直接给content高度高于父容器1px，`calc(100% + 1px)`

**Comment by toastsgithub** [comment]
同样遇到问题; 目前已经用强制内容区高度略高于容器高度来触发滚动，但感觉有点tricky; 还是期待一个配置项来允许数据少的时候触发下拉刷新

**Comment by theniceangel** [comment]
fixed in v2.0.0
