### ISSUE TITLE
在惯性滚动的过程中 ，获取滚动实例的y属性值为NaN

### ISSUE THREAD

**Issue by freeany** [ustbhuangyi/better-scroll#946]
### Version
1.15.0

### Reproduction link
[https://github.com/freeany/mgjie](https://github.com/freeany/mgjie)

### Steps to reproduce
我将滚动区域的组件使用vue中的keep-alive包裹起来，当切换组件的时候， 执行的deactived钩子函数获取滚动实例的y属性值， 如果惯性滚动没有结束，则获取到的数据是NaN
this.$refs.bscroll.bscroll.y

### What is expected?
希望给个回复?

### What is actually happening?
必须等滚动动画结束之后才可以正确的获取到滚动实例的y属性值

**Comment by dolymood** [comment]
之前好像遇到过类似的场景，需要在 deactived 的时候 stop 掉 bs 实例
