### ISSUE TITLE
在传统html页面中使用这个插件会报错

### ISSUE THREAD

**Issue by manpenghui** [ustbhuangyi/better-scroll#95]
引入dist文件夹下的bscroll.js
`
 <script src="./bscroll.js"></script>
`
初始化后，chrome会报错
`
Uncaught TypeError: Cannot read property 'style' of undefined
    at new BScroll (bscroll.js:455)
    at scroll2.html:42`
`

**Comment by jermyn626** [comment]
我也出现同样的问题😥

**Comment by Taffyw** [comment]
我看里面都是es6代码 肯定会报错  估计没编译成正常版本 这个只能vuecli里用




发自网易邮箱大师
在2017年08月08日 10:58，woojm 写道：

我也出现同样的问题😥

**Comment by jermyn626** [comment]
谢谢大兄弟 @Taffyw，我用 `webpack` + `babel-loader` 编译打包过，也是出现了同样的问题。

#### 然而我是这样解决的：

以下是我一开始时写的 DOM 结构与相关的 JavaScript 代码

```HTML
<div id="message__items">
  <div class="message__item"></div>
  <div class="message__item"></div>
  <div class="message__item"></div>
  ...
</div>
```

```JavaScript
import BScroll from 'better-scroll'
new BScroll(document.getElementById('message__items'));
```

但其实这样的 DOM 结构不符合官方的 demo 的，于是我把 DOM 结构改成这样：

```HTML
<div id="message__items">
  <ul>
    <div class="message__item"></div>
    <div class="message__item"></div>
    <div class="message__item"></div>
    ...
  </ul>
</div>
```

改完以后不再出现 `Cannot read property 'style' of undefined` 这个问题了。

**Comment by ustbhuangyi** [comment]
参考：http://ustbhuangyi.github.io/better-scroll/doc/installation.html#script-加载
