### ISSUE TITLE
监听scroll事件不生效

### ISSUE THREAD

**Issue by fe-linjin** [ustbhuangyi/better-scroll#951]
let wrapper = document.querySelector('.picker-view-list') 
        let scrollContainer = new BScroll(wrapper, {
            scrollY: true,
            click: true
        })

        scrollContainer.on('scroll', (obj) => {
            console.log('scroll', obj)
        })

        scrollContainer.on('scrollStart', () => {
            console.log('scrollStart')
        })

        scrollContainer.on('scrollEnd', (obj) => {
            console.log('scrollEnd', obj)
        })

**Comment by fe-linjin** [comment]
"better-scroll": "^1.15.2",

**Comment by fe-linjin** [comment]
已经解决，使用不但问题

**Comment by owen800q** [comment]
@fe-linjin 怎么解决的，我这边也是这样

**Comment by fe-linjin** [comment]
> @fe-linjin 怎么解决的，我这边也是这样

我当时没有设置propType值，


```
const scrollContainer = new BScroll(wrapper, {
            scrollY: true,
            click: true,
            preventDefault: true,
            probeType: 2 // 2 实时触发 1延迟触发 
        })
```

**Comment by songjie55** [comment]
没加probeType
