### ISSUE TITLE
拖动横向滚动条导致纵向滚动条回到顶部

### ISSUE THREAD

**Issue by yangdan8** [ustbhuangyi/better-scroll#955]
### Version
1.15.0

### Reproduction link
[https://ustbhuangyi.github.io/better-scroll/#/examples/free-scroll/en](https://ustbhuangyi.github.io/better-scroll/#/examples/free-scroll/en)

### Steps to reproduce
1.先拖动纵向滚动条到中间或者底部
2.再拖动横向滚动条

### What is expected?
已经滚动的纵向滚动条位置不变

### What is actually happening?
纵向滚动条被scroll to 0

**Comment by dolymood** [comment]
多谢反馈

**Comment by theniceangel** [comment]
2.x 版本不存在此问题
