### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by Volcanione** [ustbhuangyi/better-scroll#957]
[This package](https://www.jsdelivr.com/package/npm/@better-scroll/core) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by dolymood** [comment]
https://www.jsdelivr.com/package/npm/@better-scroll/core?version=2.0.0-beta.4

之前最早的 alpha 版本有问题 使用最新相关版本就可以了
