### ISSUE TITLE
在iOS上快速滑动的时候，偶尔会出现白屏。不关闭动画有什么解决方法吗？

### ISSUE THREAD

**Issue by zb48602** [ustbhuangyi/better-scroll#960]
1在iOS上快速滑动的时候，偶尔会出现白屏。不关闭动画有什么解决方法吗？
2这种情况在第一次页面渲染，特别是图片没有懒加载完成时特别明显
3bscroll的版本是1.15.2

**Comment by theniceangel** [comment]
使用 css transition 会出现这种问题，除了关闭 transition，使用 js 外，目前没有解决方案
