### ISSUE TITLE
官网示例在firefox73.0b7的手机模式下无法滚动或拉动

### ISSUE THREAD

**Issue by aloha66** [ustbhuangyi/better-scroll#962]
### Version
1.15.0

### Reproduction link
[https://better-scroll.github.io/examples/#/scrollbar/](https://better-scroll.github.io/examples/#/scrollbar/)

### Steps to reproduce
1. 打开Firefox，按f12,选中手机模式
2. 滚动或拖动列表

### What is expected?
和chrome一样的滚动效果

### What is actually happening?
不滚动

**Comment by dolymood** [comment]
模拟完 刷新试试呢

**Comment by aloha66** [comment]
> 模拟完 刷新试试呢

![image](https://user-images.githubusercontent.com/20942781/74308325-dd3ca000-4da2-11ea-91e0-65b391010d59.png)
我再试了一下，都是建立于刷新完再操作的结果。如果禁用触摸模拟，那肯定滚动不了。
