### ISSUE TITLE
在nuxt里 2.0版本的引入就报错

### ISSUE THREAD

**Issue by wbyc816** [ustbhuangyi/better-scroll#963]
![image](https://user-images.githubusercontent.com/21327368/72786125-c30e1700-3c67-11ea-986b-3061f3d11099.png)
已经正常安装了，还是报下面一直找不到依赖
![image](https://user-images.githubusercontent.com/21327368/72786068-a671df00-3c67-11ea-8bcc-9c697e286447.png)
![image](https://user-images.githubusercontent.com/21327368/72786164-de792200-3c67-11ea-81e8-62670f03e34c.png)
 换回1.0+版本 就没问题，是nuxt哪里没配置对吗？

**Comment by theniceangel** [comment]
```bash
npm install @better-scroll/core@next --save
```
