### ISSUE TITLE
bs2.0使用observe-dom插件导致下拉刷新插件显示更新成功文案时机错误

### ISSUE THREAD

**Issue by aloha66** [ustbhuangyi/better-scroll#966]
### Version
1.15.0

### Reproduction link
[https://better-scroll.github.io/examples/#/pulldown/](https://better-scroll.github.io/examples/#/pulldown/)

### Steps to reproduce
1. 打开网页后，手机模式；
2. 限速fast3g;
3. 下拉刷新

### What is expected?
异步数据加载完后才显示更新成功

### What is actually happening?
在pending的时候就提示更新成功了

---
我这边没有一个对外的api地址可以访问，官网的下拉demo是随机数实际上是不能复现。初步推测原因是observe-dom。我把observe-dom插件移除一切正常。按道理bs1也存在这个问题，但是这里最新版只能选1.15

**Comment by theniceangel** [comment]
@aloha66 你贴下你的具体代码
