### ISSUE TITLE
vue keep-alive deactivated,deactivated之后不会调用BScroll的scrollEnd钩子，并且A路由的scroll函数扔在执行

### ISSUE THREAD

**Issue by daixiongsheng** [ustbhuangyi/better-scroll#967]
### Version
1.15.0

### Reproduction link
[https://www.lanzous.com/i9fyjfc](https://www.lanzous.com/i9fyjfc)

### Steps to reproduce
相关页面已经打包,只有一个html和vue,vue-router,bscroll和js文件和一个gif效果图。
只需要打开html，在滚动A路由页面的时候快速切换到B路由

### What is expected?
在deactivated之后scrollEnd钩子执行，且BScroll的scroll钩子不会再执行

### What is actually happening?
在deactivated之后scrollEnd钩子不执行，且BScroll的scroll钩子会一直执行

---
BScroll版本是1.15.2，在2.0版本也有这个bug
在1.8.1中bug显示的是切换后页面中存在的是上一个页面的BScroll实例
初步推断是与vue的keep-alive机制有关

**Comment by dolymood** [comment]
这个需要自己手工stop掉 在生病周期里

**Comment by cody1991** [comment]
deactivated() {
    if (this.slide) this.slide.disable();
  },

好像有时候不能触发

@daixiongsheng 最后是怎么解决的？
