### ISSUE TITLE
性能优化

### ISSUE THREAD

**Issue by shangxinbo** [ustbhuangyi/better-scroll#975]
### What problem does this feature solve?
我发现在部分安卓webview中better-scroll的性能表现一般，如果我想要优化滚动的交互体验，请问应该从哪方面入手，我看了我们很多api和配置参数，很少说这个配置会引起什么性能问题，如果配了会增加性能消耗如果不配会减少性能消耗等等的建议，请问better-scroll的性能消耗主要会消耗在哪方面，这样我可以尽量躲避性能消耗，来提升性能表现

**Comment by L-Chris** [comment]
Translater频繁调用到getComputedStyle，会导致重排重绘，这个是可以优化的
