### ISSUE TITLE
在可触摸的PC电脑上，无法进行手势拖拉滚动

### ISSUE THREAD

**Issue by TaiEri** [ustbhuangyi/better-scroll#979]
### Version
1.15.0

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll/issues/new](https://github.com/ustbhuangyi/better-scroll/issues/new)

### Steps to reproduce
搭建完成

### What is expected?
可以通过手势和鼠标拖动

### What is actually happening?
手势无法拖动

**Comment by Richard-Choooou** [comment]
同

**Comment by dolymood** [comment]
我们这边没有相关设备测试，建议大家可以调试下
猜测的原因是：
在初始化的时候，存在 ontouchstart 判断事件是否支持 以及 mouse-wheel 相关支持，看实际走的是touch 还是 mouse-wheel 相关能力
