### ISSUE TITLE
efficiency problem with both x and y axis animation combined

### ISSUE THREAD

**Issue by lfjs** [ustbhuangyi/better-scroll#980]
hey my dear developer！
![2020-03-25_21-08-58 mp4_20200325_213038 578](https://user-images.githubusercontent.com/16173591/77541716-0000bf00-6ee0-11ea-9469-10739ce133ed.jpg)
if you can see that jepg above，you probably can understand my situation
i have a mp4 video recorded about this
the problem is that in a sudden chance i noticed when scrolling horizontally along x axis
all of `div` slotted in `better scroll` like `<div class="theme">{{formatItem(itemX)}}</div>`
`
    formatItem(item){
      console.log('formatItem',item);
    },`
this `formatItem()` will be executted every pixel moved
only happen in horizontal animation
`this.top = new BScroll(this.$refs.top, {scrollX: true,scrollY: false,probeType: 3,bounce: false,click: true});`
im such a noob that i can‘t do much further than this
may the force be with u

**Comment by theniceangel** [comment]
your vue component is rerendered？

**Comment by lfjs** [comment]
> your vue component is rerendered？

yes thats exactly what i mean
