### ISSUE TITLE
better scroll 派发的click事件 shiftKey 未更新

### ISSUE THREAD

**Issue by TanChungui** [ustbhuangyi/better-scroll#981]
JavaScript | MouseEvent shiftKey属性
所述的MouseEvent Shift键，属性用于限定换档键是否被按下。它是一个布尔值。如果按下Shift键，然后单击鼠标左键，则返回true；如果未按下Shift键，则返回false。
句法：
event.shiftKey
返回值：返回一个布尔值，指示是否按下Shift键。

true：表示按下Shift键。
false：表示未按下shift键。

**Comment by theniceangel** [comment]
fixed at v2.0.3
