### ISSUE TITLE
ios13.4，滑动太快，会回弹

### ISSUE THREAD

**Issue by json1224** [ustbhuangyi/better-scroll#982]

**Comment by KDJack** [comment]
+1

**Comment by AU-Pro** [comment]
+1，当translate(${x}px,${y}px) 的距离越远，getComputedPosition()获取到的值再传递给_translate(x, y)去暂停时，真实的滑动距离和暂停滑动的滑动距离，会相差很大，造成了快速滑动一定距离之后，触发stop()时，视觉上回弹一小段距离。和不同端的性能有关系，也和项目内部其他逻辑的性能消耗也有关系。

**Comment by tanlucheng** [comment]
我这边也遇到了，iOS系统更新到13.4 就遇到这个问题了，请问解决方案吗？

**Comment by tanlucheng** [comment]
> +1，当translate(${x}px,${y}px) 的距离越远，getComputedPosition()获取到的值再传递给_translate(x, y)去暂停时，真实的滑动距离和暂停滑动的滑动距离，会相差很大，造成了快速滑动一定距离之后，触发stop()时，视觉上回弹一小段距离。和不同端的性能有关系，也和项目内部其他逻辑的性能消耗也有关系。

请问解决方案吗？

**Comment by xiaoxiaodemeng** [comment]
我这也是，你们有啥解决方案吗

**Comment by theniceangel** [comment]
@xiaoxiaodemeng 遇到这个问题的，请参考https://github.com/ustbhuangyi/better-scroll/issues/978

**Comment by zxflslzyx** [comment]
+1

**Comment by theniceangel** [comment]
v2.0.0-beta.9 已修复此问题

**Comment by haidaxian** [comment]
bs 2.0.3 在 IOS 13.7 下 useTransition = true 次问题依旧出现

**Comment by haidaxian** [comment]
@theniceangel bs 2.0.3 在 IOS 13.7 下 useTransition = true 此问题依旧出现

**Comment by 894046832** [comment]
滑动太快，会回弹，此问题未修复，用了 useTransition = false，也没用

**Comment by 894046832** [comment]
测试：2.0.4解决了

**Comment by theniceangel** [comment]
iOS 14 系统内部自己已修复了该问题

**Comment by fallenleavesguy** [comment]
关了回弹，滑太快依旧还是会回弹，目前用的2.5.0版本，而且用scroll-bar插件就无法滑动了
