### ISSUE TITLE
在vue中使用，无法触发scroll事件？？

### ISSUE THREAD

**Issue by MrsZf** [ustbhuangyi/better-scroll#983]
mounted() {
   this.$nextTick(()=>{
    //  console.log(this.$refs.wrapper)
      this.scroll = new BScroll(this.$refs.wrapper,{
          probeType:3,
          pullUpLoad:true
      })
      this.scroll.on('scroll',(pos)=>{
        console.log(pos)
      })
      this.scroll.on('pullingUp',()=>{
        console.log("上拉加载更多")
      })
   })
 }

**Comment by theniceangel** [comment]
参考文档的示例

**Comment by WHUT-XGP** [comment]
我也遇到了这个问题，我绑定了相关元素且确实有回弹效果，但是监听不到scroll事件

**Comment by WHUT-XGP** [comment]
我检查发现probeType里的T我小写了，尴尬
