### ISSUE TITLE
ios端滑动过程中手指点击屏幕某个位置，滚动停止的位置会上下小幅度晃动

### ISSUE THREAD

**Issue by wangxiaoqier** [ustbhuangyi/better-scroll#984]
### Reproduction link
[https://better-scroll.github.io/examples/#/](https://better-scroll.github.io/examples/#/)

### Steps to reproduce
首先让页面滚动，在动画停下来之前，手指触摸滑动区域。滚动动画会出现先往上滚动一小端距离，然后又滚回到刚刚触摸的那个位置。

### What is expected?
当手指触摸时，页面直接停止在当前滑动的地方

### What is actually happening?
出现页面的跳动

---
官方所有demo都存在这个问题。

**Comment by theniceangel** [comment]
https://github.com/ustbhuangyi/better-scroll/issues/580，可以参考这个

**Comment by theniceangel** [comment]
https://github.com/ustbhuangyi/better-scroll/issues/580
参考以上
