### ISSUE TITLE
使用better-scroll导致position sticky吸顶失效 怎么解决

### ISSUE THREAD

**Issue by Brolly0204** [ustbhuangyi/better-scroll#985]
### Version
"better-scroll": "^1.15.2"
"vue": "^2.5.2"

### Reproduction link
[https://www](https://www)

### Steps to reproduce
滚动列表中使用better-scroll，列表中标题元素position sticky

### What is expected?
不会影响sticky 可以完美结合better-scroll实现index list

### What is actually happening?
使用better-scroll滚动列表 sticky无效，不使用则可以

---

**Comment by dolymood** [comment]
这个本质上是浏览器的 外层 transform 影响 position fixed 所导致的
所以不能嵌套
