### ISSUE TITLE
1x 和 2x 的初始化问题

### ISSUE THREAD

**Issue by wentiangang** [ustbhuangyi/better-scroll#986]
使用1x初始化完成之后，可以进行滑动  ，但是使用2x初始化之后，不能滑动。很坑

**Comment by dolymood** [comment]
麻烦按照issue规范提供复现case

**Comment by somychfudewe** [comment]
这个问题应该是在 Chrome 的手机模式初始化后不能滑动.
手机上操作是可以滑动的, 在 PC 重新切换一下手机调试模式就可以滑动了.

#993 This is a bug.

**Comment by ChihoSy** [comment]
这个问题我也遇到了，1.x可以正常滑动，2.x不能滑动，我发现是加载的数据变化导致的，2.x需要手动refresh，可能1.x和2.x在这方面的处理不同吧。
