### ISSUE TITLE
better-scroll  slider XiaoMi bug

### ISSUE THREAD

**Issue by 5ibinbin** [ustbhuangyi/better-scroll#987]
轮播组件在小米手机上会出现这个问题，其他的手机是正常的，麻烦看一下
[https://user-gold-cdn.xitu.io/2020/4/14/1717821a77a0e16a?imageView2/2/w/480/h/480/q/85/interlace/1](url)

**Comment by theniceangel** [comment]
@5ibinbin 有线上 demo 地址么
