### ISSUE TITLE
better scroll默认会加pointer-events 属性，如何不加该属性？

### ISSUE THREAD

**Issue by wuyi123321** [ustbhuangyi/better-scroll#989]
黄老师：

better-scroll 默认会给滑动组件加pointer-events属性，我看cube-ui 的滑动就不会加该属性
加上该属性会在高频率滑动后 有时添加的属性还为pointer-events:none 导致内部无法点击

我用的是better-scroll2 的slider组件 来做滑动答题页面，快速滑动后有时会出现点击不了。 最终发现是pointer-events:none 这个属性导致的无法点击。

希望能手动控制pointer-events 这个属性

**Comment by dolymood** [comment]
最好有视频 或者 复现case 这里的是为了防止其他操作加入的

**Comment by wuyi123321** [comment]
[https://wuyi123321.github.io/betterscroll-silder-bug.gif](url)
该图片链接是我录屏的gif  在silder组件滑动过程中 触摸一下屏幕 就会使pointer-events 变为none ，导致页面点击不动但是还可以正常滑动

**Comment by wuyi123321** [comment]
[https://wuyi123321.github.io/silder-bug.gif](url)
我用sildder的文档demo也可以测试出pointer-events 变为none， 这种情况下点击就会失效，上面链接就是测试录屏（复制链接在浏览器打开）

**Comment by dolymood** [comment]
看起来像是兼容性问题

**Comment by wuyi123321** [comment]
手机上也是这样的 ios 安卓都会出现这样问题 最后用 pointer-events:auto !import 暂时屏蔽无法点击问题

**Comment by m1328224904** [comment]
兄弟，你这个问题是怎么解决？在哪里加上属性？

**Comment by wuyi123321** [comment]
就在滑动的每一项的css上加  用!import 优先级让style属性失效

**Comment by m1328224904** [comment]
能否加个微信或者qq好友，我们深入讨论一下，我这个还是不行

**Comment by wuyi123321** [comment]
1107225119




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "飞翔的猪"<notifications@github.com&gt;; 
发送时间: 2020年5月21日(星期四) 中午1:35
收件人: "ustbhuangyi/better-scroll"<better-scroll@noreply.github.com&gt;; 
抄送: "无疑"<1107225119@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ustbhuangyi/better-scroll] better scroll默认会加pointer-events 属性，如何不加该属性？ (#989)





 
能否加个微信或者qq好友，我们深入讨论一下，我这个还是不行

**Comment by theniceangel** [comment]
@wuyi123321 能否提供一下线上的测试 demo

**Comment by wuyi123321** [comment]
[http://wuyi12.gitee.io/mypersonpage/output/hgquestion/index.html#/dati](url)  
链接打开 开发者模式  滑动时快速双击 基本必现点击不了问题

**Comment by theniceangel** [comment]
> [http://wuyi12.gitee.io/mypersonpage/output/hgquestion/index.html#/dati](url)
> 链接打开 开发者模式 滑动时快速双击 基本必现点击不了问题

页面报错了

**Comment by wuyi123321** [comment]
> > [http://wuyi12.gitee.io/mypersonpage/output/hgquestion/index.html#/dati](url)
> > 链接打开 开发者模式 滑动时快速双击 基本必现点击不了问题
> 
> 页面报错了

复制链接到浏览器地址栏打开

**Comment by theniceangel** [comment]
> > > [http://wuyi12.gitee.io/mypersonpage/output/hgquestion/index.html#/dati](url)
> > > 链接打开 开发者模式 滑动时快速双击 基本必现点击不了问题
> > 
> > 
> > 页面报错了
> 
> 复制链接到浏览器地址栏打开

![image](https://user-images.githubusercontent.com/25956811/84099279-d0237b00-aa3b-11ea-9696-e7529f7c4d0b.png)

**Comment by wuyi123321** [comment]
> http://wuyi12.gitee.io/mypersonpage/output/hgquestion/index.html#/dati

[http://wuyi12.gitee.io/mypersonpage/output/hgquestion/index.html](url) 用这个地址登录一下 验证码随便填

**Comment by theniceangel** [comment]
fixed it v2.0.0

**Comment by kugeliu** [comment]
> fixed it v2.0.0

我也碰到这个问题了，可是我的版本是2.0.1的😂

**Comment by xiehui999** [comment]
+1

**Comment by Mobbbb** [comment]
我更想知道加这个属性是出于什么目的，或者说去掉会有影响吗？目前遇到的问题是selenium自动化测试过程中，click_and_hold的拖拽模拟不起作用了

**Comment by wuyi123321** [comment]
> 我更想知道加这个属性是出于什么目的，或者说去掉会有影响吗？目前遇到的问题是selenium自动化测试过程中，click_and_hold的拖拽模拟不起作用了

拖拽不起作用应该是没有refresh的 和这个关系不大

**Comment by theniceangel** [comment]
> 我更想知道加这个属性是出于什么目的，或者说去掉会有影响吗？目前遇到的问题是selenium自动化测试过程中，click_and_hold的拖拽模拟不起作用了

因为在滚动过程中，如果点击了滚动区域。是不应该派发 click 事件的，而是先让他停下来

**Comment by sumshare** [comment]
在translate事件中设置为none，没有仔细看有什么作用，当滚动结或选择恰当的时机调用实例scroller的方法比如this.outerScroll.scroller.togglePointerEvents(true);

**Comment by 1927344728** [comment]
我在使用中发现一个问题：
@1.12.6、@1.15.2版中，加了 bounce = false 关闭回弹效果 ，滚动区域滑动到顶或到底时，内容区域样式属性 pointer-events:none，导致区域内第一次click事件无效，后面的正常。调试发现是，点击或者滑动区域，pointer-events 又更新为 auto 了。 
这是否是关闭回弹后，少一个translate事件来将 pointer-events 的 none 改回 auto 呢？

另外，尝试升级到版本 @2.0.0、@2.4.2，发现 bounce = false 无法关闭回弹效果。
