### ISSUE TITLE
在ios上用手轻轻的滑动，页面会有比较明显的抖动

### ISSUE THREAD

**Issue by 953950350** [ustbhuangyi/better-scroll#991]
### Version
1.12.0

### Reproduction link
[https://ustbhuangyi.github.io/better-scroll](https://ustbhuangyi.github.io/better-scroll)

### Steps to reproduce
使用iphone设备，用手轻轻的滑动，页面会有比较明显的抖动
测试的设备有iphone7、iphonex，系统是ios13

### What is expected?
不应该出现抖动现象

### What is actually happening?
用手轻轻的滑动，页面会有比较明显的抖动

**Comment by dolymood** [comment]
ios13 应该会存在类似 https://github.com/ustbhuangyi/better-scroll/issues/978 这样问题
