### ISSUE TITLE
在Vue项目中使用better-scroll，每次初始化项目不能滑动，刷新后就可以滑动

### ISSUE THREAD

**Issue by fengshuqiang1** [ustbhuangyi/better-scroll#993]
我是按照作者推荐的方式来封装的scroll组件，但是每一次重启Vue项目后。移动端调式页面，scroll组件区域不能进行任何操作（除了点击）。刷新后就可以滑动是怎么回事啊？

**Comment by George-kiki** [comment]
应该是你的数据在scroll初始化完成后才拿到得，导致scroll已经完成了初始化，这个时候你的数据才来撑开scroll的高度导致滑动不了，你可以在接口调用完成后使用 refresh这个api来刷新scroll的高度

**Comment by fengshuqiang1** [comment]
我是在图片加载完成后使用refresh更新滚动条的，还是不行。但是我已经找到问题了。因给是better-scroll和谷歌浏览器之间的问题。我在手机端测试是没有问题的！

**Comment by ak-monster** [comment]
我也遇到这样的问题，而且我查看scroll属性发现，hasVerticalScroll:true 并且scrollHeight也成功获取了高度的，但是就是初始化不能滑动。有大神知道怎么回事吗？

**Comment by dolymood** [comment]
浏览器 PC模式和mobile模式切换 是需要重新刷新才可以的
