### ISSUE TITLE
can't scroll because findNearestValidWheel return NaN when itemHeight is zero

### ISSUE THREAD

**Issue by pianfeng240** [ustbhuangyi/better-scroll#999]
### Version
2.0.0-beta.6

### Reproduction link
[https://github.com/ustbhuangyi/better-scroll/blob/dev/packages/wheel/src/index.ts](https://github.com/ustbhuangyi/better-scroll/blob/dev/packages/wheel/src/index.ts)

### Steps to reproduce
version: 2.0.0-beta.6

package: wheel

file: src/index.ts.

line: 229
let currentIndex = Math.abs(Math.round(-y / this.itemHeight))

currentIndex is NaN when y and itemHeight are all zero

### What is expected?
can scroll

### What is actually happening?
can't scroll
print the scroll, y is NaN

---

**Comment by theniceangel** [comment]
提供复现 demo
